- inc/poche/Poche.class.php
- inc/poche/Routing.class.php
As asked in issue #553 I introduced a 'limit' query parameter to control how many items should be displayed in the feed at most. It should also address a part of issue #1000.
So far the limit should be set manually, by default all items are displayed.
> [RSS] introducing query param 'limit' for max items in RSS feed

- inc/poche/Poche.class.php
This patch add an error message in case of login failure attempt.
The purpose of this message is to enable the usage of fail2ban to block any brute force attack on the login page.
The fail2ban filter definition to take advantage of this log message (named apache-auth-wallabag.conf):
```ini
[INCLUDES]
before = apache-common.conf
[Definition]
failregex = ^%(_apache_error_client)s user .* (authentication failure|not found|password mismatch).*$
ignoreregex =
```
Anf the jail definition:
```ini
[apache-auth-custo]
enabled = true
port = http,https
filter = apache-auth-wallabag
logpath = /var/log/apache2/*error.log
maxretry = 1
```
Those examples are tested on Ubuntu.
**remark**: the change on line 1068 and after is only the automatic removal of ^M at the end of the line by my text editor.
This …
> Add message in web server log in case of authentication failure

- .gitignore
- .travis.yml
- build.xml
- phpunit.xml.dist
Instead of launching the tests suite using:
```
ant -f app/build.xml prepare && phpunit -c app
```
It will be more simple:
```
ant prepare && phpunit
```
> Simplify build system

- .scrutinizer.yml
- .travis.yml
- app/config/parameters.yml.dist
- app/config/security.yml
- src/Wallabag/CoreBundle/Command/InstallCommand.php
- src/Wallabag/CoreBundle/Controller/ConfigController.php
- src/Wallabag/CoreBundle/Controller/RssController.php
- src/Wallabag/CoreBundle/DataFixtures/ORM/LoadEntryData.php
- src/Wallabag/CoreBundle/Entity/Config.php
- src/Wallabag/CoreBundle/Entity/User.php
- src/Wallabag/CoreBundle/Form/Type/ConfigType.php
- src/Wallabag/CoreBundle/Form/Type/RssType.php
- src/Wallabag/CoreBundle/ParamConverter/UsernameRssTokenConverter.php
- src/Wallabag/CoreBundle/Repository/EntryRepository.php
- src/Wallabag/CoreBundle/Repository/UserRepository.php
- src/Wallabag/CoreBundle/Resources/config/services.yml
- src/Wallabag/CoreBundle/Resources/views/Config/index.html.twig
- src/Wallabag/CoreBundle/Resources/views/Entry/entries.xml.twig
- src/Wallabag/CoreBundle/Resources/views/themes/baggy/public/css/main.css
- src/Wallabag/CoreBundle/Tests/Command/InstallCommandTest.php
- src/Wallabag/CoreBundle/Tests/Controller/ConfigControllerTest.php
- src/Wallabag/CoreBundle/Tests/Controller/EntryControllerTest.php
- src/Wallabag/CoreBundle/Tests/Controller/RssControllerTest.php
- src/Wallabag/CoreBundle/Tests/Controller/WallabagRestControllerTest.php
- src/Wallabag/CoreBundle/Tests/Mock/InstallCommandMock.php
- src/Wallabag/CoreBundle/Tests/ParamConverter/UsernameRssTokenConverterTest.php
- src/Wallabag/CoreBundle/Tools/Utils.php
By default, items in each feeds are limited to 50. User can change this value in the config page. This will fix #1000.
I've re-added the token system (I put it in a `Tools/Utils` class), which can also be regenerated (todo: make an ajax call).
Url are like that: `http://wallabag.io/j0k3r/0jlmUxAVZqmc26P/unread.xml`
I've added a ParamConverter to check if the username and the token in the url are good.
I've also added an `@Assert\Range` on `itemPerPage` & `rssLimit` to be sure it's a number. So the validation works on the form too. I've put a kind of random number as max value: 100.000.
Regarding the `InstallCommand` tests, they are god damn too long to execute because it launch external commands (mostly related to doctrine).
So I've added a PHPUnit @group (`command-doctrine`) so that we …
> Add RSS feeds

- src/Wallabag/CoreBundle/Controller/ConfigController.php
- src/Wallabag/CoreBundle/Entity/User.php
- src/Wallabag/CoreBundle/Form/Type/UserInformationType.php
- src/Wallabag/CoreBundle/Resources/views/Config/index.html.twig
- src/Wallabag/CoreBundle/Tests/Controller/ConfigControllerTest.php
Since password are linked to username it was hard to change username while checking that the password is the good one.
Instead of doing crazy things to achieve that, I act that user won't be able to update username.
Also, username (and email) must be unique, since people logged in using username and can request a new password using email.
This should fix #1149
> Remove ability to change username

- inc/poche/Routing.class.php
The import returns some variables needed in the template (I know, it's not logical). 
But when we refactor routing, we forgot to set these values into `$this->vars`: the import only ran once, whereas it should restart automatically (every `IMPORT_DELAY` seconds).
> fix restart of import

- themes/default/config.twig
fix link to Save your first article (no capital letters in documentation pages)
> fix link to save your first article

- app/config/routing.yml
- src/Wallabag/ApiBundle/Controller/WallabagRestController.php
- src/Wallabag/CoreBundle/Controller/EntryController.php
- src/Wallabag/CoreBundle/Controller/RssController.php
- src/Wallabag/CoreBundle/Repository/EntryRepository.php
- src/Wallabag/CoreBundle/Resources/views/Entry/entries.html.twig
- src/Wallabag/CoreBundle/Resources/views/themes/baggy/public/css/main.css
- src/Wallabag/CoreBundle/Tests/Controller/EntryControllerTest.php
Adds pagerfanta paginator everywhere, and modifies article routing. 
Change API for is_starred and is_archived. (Reflects the output of the API 'getEntries')
> Adds pagerfanta paginator everywhere, modifies article routing.

- inc/poche/Poche.class.php
- inc/poche/Routing.class.php
> fix security bug with PHP_AUTH_USER

- app/AppKernel.php
- app/SymfonyRequirements.php
- app/check.php
- app/config/config.yml
- composer.json
- composer.lock
- src/Wallabag/CoreBundle/Controller/EntryController.php
- src/Wallabag/CoreBundle/Controller/RssController.php
- src/Wallabag/CoreBundle/Entity/Entry.php
- src/Wallabag/CoreBundle/Filter/EntryFilterType.php
- src/Wallabag/CoreBundle/Helper/Tools.php
- src/Wallabag/CoreBundle/Repository/EntryRepository.php
- src/Wallabag/CoreBundle/Resources/views/Entry/entries.html.twig
- src/Wallabag/CoreBundle/Resources/views/Entry/entries.xml.twig
- src/Wallabag/CoreBundle/Resources/views/themes/_global/public/css/style.css
- src/Wallabag/CoreBundle/Resources/views/themes/baggy/public/css/main.css
- src/Wallabag/CoreBundle/Resources/views/themes/material/Entry/entries.html.twig
- src/Wallabag/CoreBundle/Resources/views/themes/material/public/css/print.css
- src/Wallabag/CoreBundle/Tests/Controller/EntryControllerTest.php
- src/Wallabag/CoreBundle/Twig/Extension/WallabagExtension.php
> store estimated reading time in database (#393)

- inc/poche/Tools.class.php
I recently tried to save a link from exploit-db.com who use Sucuri.net Cloud Firewall.
As part of their IDS they block all unknown/old useragents.
> Update Useragent to Win8.1 and FF36

- src/Wallabag/CoreBundle/Controller/EntryController.php
- src/Wallabag/CoreBundle/Resources/views/Entry/new.html.twig
- src/Wallabag/CoreBundle/Resources/views/Entry/new_form.html.twig
- src/Wallabag/CoreBundle/Resources/views/Static/howto.html.twig
- src/Wallabag/CoreBundle/Resources/views/base.html.twig
- src/Wallabag/CoreBundle/Resources/views/themes/material/Entry/new.html.twig
- src/Wallabag/CoreBundle/Resources/views/themes/material/Entry/new_form.html.twig
- src/Wallabag/CoreBundle/Resources/views/themes/material/Static/howto.html.twig
- src/Wallabag/CoreBundle/Resources/views/themes/material/layout.html.twig
- src/Wallabag/CoreBundle/Resources/views/themes/material/public/js/init.js
replaces #1307 (I had problems with merge, some files were deleted, I made so many mistakes I think)
> add new post form in material header

- src/Wallabag/CoreBundle/Resources/views/themes/material/Entry/entry.html.twig
only because export is still not yet implemented.
> disable download links on entry view

- .scrutinizer.yml
see https://scrutinizer-ci.com/g/wallabag/wallabag/inspections/1ba56fc0-e1d6-4d6a-863d-9b18927b011d/log
> change timeout because scrutinizer failed

- .gitignore
- Capfile
- Gemfile
- Gemfile.lock
- config/deploy.rb
- config/deploy/production.rb
- config/deploy/staging.rb
> capistrano config

- src/Wallabag/CoreBundle/Filter/EntryFilterType.php
- src/Wallabag/CoreBundle/Resources/views/themes/material/Entry/entries.html.twig
- src/Wallabag/CoreBundle/Tests/Controller/EntryControllerTest.php
I put a field text which looks for the domain names who contain the term (%term% in fact). I disabled the availibity to have a select list with these options: starts with, ends with, contains, is exactly. 
@j0k3r, @tcitworld Tell me if it's good for you.
After this PR is merged, @modos189 needs to enhance it with some JS and CSS :-)
> fix #981: add filter on domain name

- src/Wallabag/CoreBundle/Resources/views/themes/material/Config/index.html.twig
It fixes the problem. 
But the anchor is between the tabs and the form. So the page scrolls down when we validate the form. But it fixes the problem.
(I know, the branch name is wrong)
> fix #1368 config: redirect on correct tab in material theme

- app/config/config.yml
- app/config/parameters.yml.dist
- src/Wallabag/CoreBundle/Resources/views/base.html.twig
- src/Wallabag/CoreBundle/Resources/views/themes/material/public/css/main.css
Just a first version, no need to have a beautiful bar.
> fix #1332: bottom bar to display message

- composer.lock
- src/Wallabag/CoreBundle/Controller/EntryController.php
- src/Wallabag/CoreBundle/Filter/EntryFilterType.php
- src/Wallabag/CoreBundle/Repository/EntryRepository.php
- src/Wallabag/CoreBundle/Resources/views/Entry/entries.html.twig
- src/Wallabag/CoreBundle/Resources/views/base.html.twig
- src/Wallabag/CoreBundle/Resources/views/themes/material/Entry/entries.html.twig
- src/Wallabag/CoreBundle/Resources/views/themes/material/layout.html.twig
- src/Wallabag/CoreBundle/Resources/views/themes/material/public/js/init.js
- src/Wallabag/CoreBundle/Tests/Controller/EntryControllerTest.php
> filters: implement status filter and a new view (to display all entries)

- app/config/services.yml
- src/Wallabag/CoreBundle/Event/Subscriber/CustomDoctrineORMSubscriber.php
- src/Wallabag/CoreBundle/Filter/EntryFilterType.php
- src/Wallabag/CoreBundle/Tests/Controller/EntryControllerTest.php
I override the default behavior of the filter_date_range to add time and allow filter for a single day
Fix #1379
> Fix date filter on same day

- src/Wallabag/CoreBundle/Resources/views/themes/material/Entry/entries.html.twig
For longer domains, use all the space.
> Use full size of the panel for domain-filtering

- src/Wallabag/CoreBundle/Controller/ConfigController.php
- src/Wallabag/CoreBundle/Tests/Controller/ConfigControllerTest.php
By default, creating user with FOSUser are disabled by default.
Fix #1423
> Enabled created user from Config

- .travis.yml
- app/config/config_test.yml
- app/config/tests/parameters.yml.dist.mysql
- app/config/tests/parameters.yml.dist.pgsql
- app/config/tests/parameters.yml.dist.sqlite
- build.xml
- composer.json
- composer.lock
- src/Wallabag/CoreBundle/DataFixtures/ORM/LoadEntryData.php
- src/Wallabag/CoreBundle/Entity/Entry.php
- src/Wallabag/CoreBundle/Helper/ContentProxy.php
- src/Wallabag/CoreBundle/Repository/EntryRepository.php
- src/Wallabag/CoreBundle/Tests/Controller/EntryControllerTest.php
- src/Wallabag/CoreBundle/Tests/Controller/TagControllerTest.php
- src/Wallabag/CoreBundle/Tests/Helper/ContentProxyTest.php
Support:
- MySQL
- SQLite
- PostgreSQL
To avoid bad behavior when testing archived, starred, deleted, etc .. I try to use the same content every time:
- I create the content (using a custom `$url`)
- I re-use this `$url` to retrieve the content on every test
I also moved setup of readingTime & domainName in ContentProxy to centralize all the work performed when saving a new content.
> Add multiple database tests on Travis

- src/Wallabag/CoreBundle/Controller/EntryController.php
- src/Wallabag/CoreBundle/Resources/views/_bookmarklet.html.twig
- src/Wallabag/CoreBundle/Resources/views/themes/baggy/Static/howto.html.twig
- src/Wallabag/CoreBundle/Resources/views/themes/baggy/layout.html.twig
- src/Wallabag/CoreBundle/Resources/views/themes/material/Static/howto.html.twig
- src/Wallabag/CoreBundle/Tests/Controller/EntryControllerTest.php
Do we need a test for this PR?
> implement bookmarklet

- composer.json
Configuring SMTP parameters required to be written in files which is not convenient when using docker containers as the credentials need to be in the filesystem. Created environment parameters override for those parameters. A new build script created in order to generate those parameters right before launching the application.
This allows to build containers without [specifying credentials in the container itself](https://github.com/mathbruyen/home/blob/424542ae568b8c23af8d9585d4390db421cf9ca3/wallabag/Dockerfile) and [use them in kubernetes](https://github.com/mathbruyen/home/blob/424542ae568b8c23af8d9585d4390db421cf9ca3/wallabag-controller.yaml) (I'm also looking at [this PR on kubernetes](https://github.com/kubernetes/kubernetes/issues/4710) for storing the password in a secret out of …
> SMTP from environment variables

- app/AppKernel.php
- app/config/config.yml
- composer.json
- composer.lock
- src/Wallabag/CoreBundle/Command/TagAllCommand.php
- src/Wallabag/CoreBundle/Controller/ConfigController.php
- src/Wallabag/CoreBundle/DataFixtures/ORM/LoadConfigData.php
- src/Wallabag/CoreBundle/Entity/Config.php
- src/Wallabag/CoreBundle/Entity/Entry.php
- src/Wallabag/CoreBundle/Entity/TaggingRule.php
- src/Wallabag/CoreBundle/Form/DataTransformer/StringToListTransformer.php
- src/Wallabag/CoreBundle/Form/Type/TaggingRuleType.php
- src/Wallabag/CoreBundle/Helper/ContentProxy.php
- src/Wallabag/CoreBundle/Helper/RuleBasedTagger.php
- src/Wallabag/CoreBundle/Operator/Doctrine/Matches.php
- src/Wallabag/CoreBundle/Operator/PHP/Matches.php
- src/Wallabag/CoreBundle/Repository/TaggingRuleRepository.php
- src/Wallabag/CoreBundle/Resources/config/services.yml
- src/Wallabag/CoreBundle/Resources/views/themes/baggy/Config/index.html.twig
- src/Wallabag/CoreBundle/Resources/views/themes/material/Config/index.html.twig
- src/Wallabag/CoreBundle/Tests/Controller/ConfigControllerTest.php
- src/Wallabag/CoreBundle/Tests/Controller/EntryControllerTest.php
- src/Wallabag/CoreBundle/Tests/Form/DataTransformer/StringToListTransformerTest.php
- src/Wallabag/CoreBundle/Tests/Helper/ContentProxyTest.php
- src/Wallabag/CoreBundle/Tests/Helper/RuleBasedTaggerTest.php
- src/Wallabag/UserBundle/Repository/UserRepository.php
As described in #1477, here is my PoC for a rule-based automatic tagging.
It rules engine is [RulerZ](https://github.com/K-Phoen/rulerz) and I created a new tab in the configuration panel to manage the tagging rules. It's a quick draft but at least it allows us to create rules and test them:
It's really a WIP so there are no tests, validation for the rules or help about the DSL used for the rules.
If you like the overall direction of this feature, I'll finish my PR :)
Note: there are a lot of *additions* but it's mainly the `composer.lock file`. Also, reading the PR commit-by-commit should be easier.
**Updated screenshot**:
> Rule based tags

- src/Wallabag/CoreBundle/DataFixtures/ORM/LoadTaggingRuleData.php
- src/Wallabag/CoreBundle/Entity/Entry.php
- src/Wallabag/CoreBundle/Helper/RuleBasedTagger.php
- src/Wallabag/CoreBundle/Tests/Helper/RuleBasedTaggerTest.php
When a new tag is created but not yet persisted, it can be duplicated.
It could happen when multiple rules match the content and at least 2 of them should attach same new tag.
Fix #1528
> v2 – 	Avoid multiple tag creation

- src/Wallabag/CoreBundle/Controller/EntryController.php
- src/Wallabag/CoreBundle/DataFixtures/ORM/LoadEntryData.php
- src/Wallabag/CoreBundle/Tests/Controller/EntryControllerTest.php
Fix #1512
We generate the url of the removed content and compare it to the referer url. If they matche, we redirect user to the homepage otherwise to the referer url.
> v2 – 	Don't redirect to the content page after deletion

- .travis.yml
- app/config/config.yml
- app/config/parameters.yml.dist
- app/config/tests/parameters.yml.dist.mysql
- app/config/tests/parameters.yml.dist.pgsql
- app/config/tests/parameters.yml.dist.sqlite
- src/Wallabag/CoreBundle/DataFixtures/ORM/LoadConfigData.php
- src/Wallabag/CoreBundle/Resources/views/themes/baggy/Config/index.html.twig
- src/Wallabag/CoreBundle/Resources/views/themes/material/Config/index.html.twig
- src/Wallabag/CoreBundle/Tests/Controller/ConfigControllerTest.php
- src/Wallabag/UserBundle/DependencyInjection/Configuration.php
- src/Wallabag/UserBundle/DependencyInjection/WallabagUserExtension.php
- src/Wallabag/UserBundle/Mailer/AuthCodeMailer.php
- src/Wallabag/UserBundle/Resources/config/services.yml
- src/Wallabag/UserBundle/Resources/translations/wallabag_user.en.yml
- src/Wallabag/UserBundle/Resources/translations/wallabag_user.fr.yml
- src/Wallabag/UserBundle/Tests/Mailer/AuthCodeMailerTest.php
Related #1490 
Here is the email template:
> Hi Jeremy,
>
> Since you enable two factor authentication on your wallabag account and you just logged in from a new device (computer, phone, etc.), we send you a code to validate your connection.
>Here is the code: 412585
>
>Please don't hesitate to contact us if you have any problems: https://www.wallabag.org/pages/support.html
>The wallabag team
> v2 – Add custom email for 2FA

- src/Wallabag/CoreBundle/Controller/EntryController.php
Bad condition when deleting an entry returned `true` instead of the referer url.
Following #1540
> v2 – Fix wrong if when deleting an entry

- src/Wallabag/ApiBundle/Controller/WallabagRestController.php
- src/Wallabag/ApiBundle/Tests/Controller/WallabagRestControllerTest.php
- src/Wallabag/ApiBundle/Tests/WallabagApiTestCase.php
- src/Wallabag/CoreBundle/Controller/TagController.php
- src/Wallabag/CoreBundle/DataFixtures/ORM/LoadEntryData.php
- src/Wallabag/CoreBundle/DataFixtures/ORM/LoadTagData.php
- src/Wallabag/CoreBundle/Entity/Entry.php
- src/Wallabag/CoreBundle/Entity/Tag.php
- src/Wallabag/CoreBundle/Helper/RuleBasedTagger.php
- src/Wallabag/CoreBundle/Repository/EntryRepository.php
- src/Wallabag/CoreBundle/Repository/TagRepository.php
- src/Wallabag/CoreBundle/Tests/Controller/ConfigControllerTest.php
- src/Wallabag/CoreBundle/Tests/Helper/RuleBasedTaggerTest.php
- src/Wallabag/UserBundle/Entity/User.php
> v2 – Remove user reference in tag

- src/Wallabag/CoreBundle/Repository/EntryRepository.php
- src/Wallabag/UserBundle/Mailer/AuthCodeMailer.php
- src/Wallabag/UserBundle/Tests/Mailer/AuthCodeMailerTest.php
Symfony use a different class when in dev mode and prod mode.
Prod loads `Symfony\Bundle\FrameworkBundle\Translation\Translator`.
Dev loads `Symfony\Component\Translation\DataCollectorTranslator` to gather information for the debug bar.
Fix #1585
> Use translator interface instead of final class

- .gitignore
- build.xml
Having a big composer.lock on a final project can have side effect on incoming PR that add a new vendor.
Mostly because conflict are too frequent.
By ignoring composer.lock we ease the PR submission and rebase.
BUT we need to be careful when we release a new version of wallabag. We should manually `git add -f composer.lock` to update it.
Since composer.lock will no longer be commited I switch the `composer install` to a `composer up` in the travis configuration.
/ping @bdunogier what do you think?
> Ignore composer.lock

- src/Wallabag/CoreBundle/Entity/Entry.php
Fix #1453
When removing an entry, it'll also remove all associated tag and avoid crazy stuff like defined in the previous issue.
> Remove tag relation when removing an entry

- src/Wallabag/CoreBundle/Tests/Controller/SettingsControllerTest.php
- src/Wallabag/UserBundle/Mailer/AuthCodeMailer.php
- src/Wallabag/UserBundle/Tests/Mailer/AuthCodeMailerTest.php
Fix #1643 due to https://github.com/symfony/symfony/pull/15272
> Fix #1643: fix the way to load the HTML template in 2factor auth

- app/Resources/CraueConfigBundle/translations/CraueConfigBundle.en.yml
- app/config/config.yml
- app/config/parameters.yml.dist
- app/config/tests/parameters.yml.dist.mysql
- app/config/tests/parameters.yml.dist.pgsql
- app/config/tests/parameters.yml.dist.sqlite
- src/Wallabag/CoreBundle/Tests/Controller/SettingsControllerTest.php
- src/Wallabag/UserBundle/Mailer/AuthCodeMailer.php
Fix #1622. 
It's now possible to enable/disable email confirmation for user registration via the parameters.
> Fix #1622: parameter for FosUser confirmation

- src/Wallabag/CoreBundle/Resources/views/themes/material/Entry/entries.html.twig
Using slice & striptags, the content is automatically escaped.
If some html character need to be displayed, they'll be escape too, sth like `&amp;`.
Using |raw, the content isn't escape twice and is well displayed.
Fix #1426
I've also refactored a little the estimated time html to avoid to much duplicate code.
> Unescape content for Material card

- README.md
So the only solution I found so far is to force the `prod` env when create the project with composer.
There is other solution.
Since the `cache:clear` task is using `dev` env by default, so it tries to load dev bundle, which aren't there since we specify `--no-dev`.
----
Fix #1617 
/ping @bdunogier 
/see https://github.com/sensiolabs/SensioDistributionBundle/pull/140
> Force prod env on project creation

- src/Wallabag/CoreBundle/Resources/public/themes/material/css/main.css
So that pictures don't go too far on the right.
> display pictures properly

- app/config/config.yml
- src/Wallabag/CoreBundle/Resources/translations/messages.fa.yml
Translation file for the 'Persian' language. Also recognized by fa_IR. Also known (in the Persian language) as Farsi. Also written like فارسی in Persian. All said, please call the language just 'Persian'.
> Translation for Persian

- src/Wallabag/CoreBundle/Controller/EntryController.php
- src/Wallabag/CoreBundle/Tests/Controller/EntryControllerTest.php
> Fix #1551 - Redirect to the last page when current page is out of range

- docs/fr/user/create_account.rst
- docs/fr/user/installation.rst
>  Fix #1708: typos in french documentation

- src/Wallabag/CoreBundle/Command/InstallCommand.php
Since https://github.com/wallabag/wallabag/pull/1652 user created while installing wallabag is now admin. I think it's better to say that information to the user.
Also, I've switched the default answer to `true` so, hitting <kbd>enter</kbd> all the way will create an admin.
> Change wording for create a new user

- src/Wallabag/CoreBundle/Resources/views/themes/material/Entry/entry.html.twig
| Fixed tickets | #1717
We now have a trash icon instead of a cross. 
The cross is already used to close some div (new link form, etc.) and has some js behaviors.
> Fix #1717: Change remove tag icon in entry view with material theme

- .travis.yml
- src/Wallabag/CoreBundle/Command/InstallCommand.php
- src/Wallabag/CoreBundle/Tests/Command/InstallCommandTest.php
- src/Wallabag/UserBundle/Resources/config/services.yml
Since Symfony 3.0.3 has been released, we can remove this hardcoded alias.
> Remove extra definition

- docs/en/user/installation.rst
Hi,
There was a typo in the installation part of the documentation: a php extension was `pĥp-hash` instead of `php-hash`. This PR fixes that.
Didn't know what to put for "translation": 
- Yes there already is a translation for that part, and the french version is correct
- No, this PR doesn't change anything in the translation
> Doc: fix typo in php-hash ext name

- docker-compose.yml
- docker/php/Dockerfile
| New feature?|  no
| BC breaks?   | no
| Fixed tickets | #1726
Docker-compose should be upgraded to v1.6 to use the argument of the docker-compose.yml file.
In this sample, the argument is different from the default to show that it's the one from compose which is taken.
Following #1749
Kudos to @DjayDev
> Docker timezone

- README.md
- app/config/config.yml
- docs/en/user/installation.rst
- docs/fr/user/installation.rst
Because we have problems for those who install wallabag via `composer create-project` (no way to upgrade their installation), we considered to use `git clone`.
> Prepare files for 2.0.0-beta.2

- src/Wallabag/CoreBundle/Controller/DeveloperController.php
> add refresh-token grant-type

- src/Wallabag/ApiBundle/Controller/WallabagRestController.php
- src/Wallabag/ApiBundle/Tests/Controller/WallabagRestControllerTest.php
If an entry was with the same URL was re-sent a second time, a second article was created in DB. This fixes it.
Note that all metadata (archived, starred, tags, ...) associated with the second call to API will be applied to the original entry.
Also, checkout #1796
> Don't add entry through API if it already exists

- src/Wallabag/ApiBundle/Controller/WallabagRestController.php
- src/Wallabag/ApiBundle/Tests/Controller/WallabagRestControllerTest.php
- src/Wallabag/CoreBundle/Controller/DeveloperController.php
- src/Wallabag/CoreBundle/Entity/Entry.php
| Fixed tickets | #1780, #1784
Yeah, because a (bool) string is always true... 
Also, cs.
> fix api properties and typo

- src/Wallabag/ApiBundle/Tests/Controller/WallabagRestControllerTest.php
- src/Wallabag/CoreBundle/Controller/TagController.php
- src/Wallabag/CoreBundle/Tests/Controller/TagControllerTest.php
> Fix #1768 Split tags with commas from UI

- src/Wallabag/CoreBundle/Command/InstallCommand.php
- src/Wallabag/CoreBundle/Helper/EntriesExport.php
- src/Wallabag/ImportBundle/Controller/WallabagController.php
- src/Wallabag/ImportBundle/Controller/WallabagV1Controller.php
- src/Wallabag/ImportBundle/Controller/WallabagV2Controller.php
- src/Wallabag/ImportBundle/Import/WallabagImport.php
- src/Wallabag/ImportBundle/Import/WallabagV1Import.php
- src/Wallabag/ImportBundle/Import/WallabagV2Import.php
Use an abstract class to store all common actions from wallabag vX import.
Move specificity in v1 & v2 import.
> Refacto wallabag import

- src/Wallabag/CoreBundle/Command/InstallCommand.php
| Fixed tickets | https://github.com/wallabag/wallabag/issues/1830
Instead of checking that one of the DB driver is installed we retrieve the selected driver (in parameters) and see if the extension exists.
> Check selected PDO driver on install

- README.md
- app/config/config.yml
- docs/en/user/installation.rst
- docs/fr/user/installation.rst
- src/Wallabag/CoreBundle/Resources/public/themes/material/css/main.css
- src/Wallabag/CoreBundle/Resources/views/base.html.twig
- src/Wallabag/CoreBundle/Resources/views/themes/baggy/Static/about.html.twig
- src/Wallabag/CoreBundle/Resources/views/themes/baggy/Static/howto.html.twig
- src/Wallabag/CoreBundle/Resources/views/themes/material/Static/about.html.twig
- src/Wallabag/CoreBundle/Resources/views/themes/material/Static/howto.html.twig
:birthday: :birthday: :birthday:
> :rocket: Prepare v2.0.0 :birthday:

- composer.json
| Fixed tickets | #1843
To avoid problem with PHP < 7.0
> Lock ocramius/proxy-manager

- src/Wallabag/CoreBundle/Resources/public/themes/baggy/js/saveLink.js
- src/Wallabag/CoreBundle/Resources/views/themes/baggy/Config/index.html.twig
- src/Wallabag/CoreBundle/Resources/views/themes/material/Config/index.html.twig
| Fixed tickets | #1673
Fix #1673 
I don't think that we have to work many hours on baggy theme. Baggy is still here and must be readable for articles, but for config screens, we only have to do the minimum.
> Remove keyboard shortcut and add tagging rule panel in baggy

- src/Wallabag/CoreBundle/Resources/config/services.yml
| Fixed tickets | #1801
When using the default User Agent, the website returns a 403. By forcing the User Agent for this domain, we got the proper behavior: a 200
Since we can't _append_ new user agent to the default graby configuration, we need to rewrite all the default config + the new one.
> Force user-agent for iansommerville.com

- composer.json
- docs/en/user/installation.rst
- docs/fr/user/installation.rst
Previously, here #1725 (by @mathbruyen) ... 
| BC breaks?    | yes (previous overrides no longer work)
SMTP configuration has been added in #1518 to use ParameterHandle's `env-map`. But Symfony actually has a native way of allowing parameters to be overriden from environment so rather than having to define a mapping for each possible parameter, users can define any override in `parameters.yml`:
> parameters:
>     database_host: %WALLABAG_DB_HOST%
and define an environment variable `SYMFONY__WALLABAG_DB_HOST`.
Links:
* [env-map](https://github.com/Incenteev/ParameterHandler#using-environment-variables- …
> Remove SMTP configuration environment overrides

- src/Wallabag/ApiBundle/Controller/WallabagRestController.php
| Fixed tickets | #1863 
Fix #1863: only the unread entries were fetched with GET /api/entries entrypoint. Now, all the entries are fetched
> All the entries are fetched via GET /api/entries

- app/config/config.yml
- src/Wallabag/CoreBundle/Command/InstallCommand.php
| Fixed tickets | #1769 
When installing a new project with MySQL, if the database doesn't exist before installation will fail because DBAL will try to get the server version by querying it.
And since this query is done using the default database connexion and since the database doesn't exist, DBAL can't connect to the server.
Following #1773
See http://blog.insight.sensiolabs.com/2014/12/22/making-symfony-bootable-with-dbal-2-5.html
> Force server version to avoid connexion error

- src/Wallabag/CoreBundle/Command/InstallCommand.php
- src/Wallabag/CoreBundle/Tests/Command/InstallCommandTest.php
| Fixed tickets | #1881
If user doesn't want to create a new admin (even if it's recommended) the internal config weren't created resulting in error when using the interface.
> Move setup config outside setupAdmin

- app/AppKernel.php
- app/config/services.yml
- composer.json
- src/Wallabag/CoreBundle/Controller/EntryController.php
- src/Wallabag/CoreBundle/Resources/config/services.yml
- src/Wallabag/CoreBundle/Resources/public/themes/baggy/css/main.css
- src/Wallabag/CoreBundle/Resources/public/themes/material/css/main.css
- src/Wallabag/CoreBundle/Resources/views/themes/baggy/Entry/entries.html.twig
- src/Wallabag/CoreBundle/Resources/views/themes/material/Entry/entries.html.twig
- src/Wallabag/CoreBundle/Tests/Controller/EntryControllerTest.php
| Fixed tickets | #1905
Fix #1905
Usage of https://github.com/whiteoctober/WhiteOctoberPagerfantaBundle
> Improve pagination when user has lot of entries

- docs/en/user/migration.rst
- docs/fr/user/migration.rst
- src/Wallabag/ImportBundle/Command/ImportCommand.php
* Add CLI import for wallabag v2 with the ``--importer=v2`` option
* Add *mark all as read** support with the ``--markAsRead=yes`` option
* BC breaks with old importer because I change the command name
* No tests on this command because we only use v1/v2 importers which are already tested.
> Add CLI import for wallabag v2 files

- src/Wallabag/CoreBundle/Controller/ConfigController.php
- src/Wallabag/CoreBundle/Tests/Controller/ConfigControllerTest.php
| Fixed tickets | #2004 
Fix #2004
About tests, I need your opinion.
> Fix reading speed not defined when user was created via config page

- src/Wallabag/CoreBundle/Resources/views/themes/material/layout.html.twig
This PR fixes the link to the Firefox addon page displayed in the footer. I chose to remove the language from the link so that we let Mozilla Addons site handle it.
| Fixed tickets | #2037
> Do not specify language in Firefox addon link

- src/Wallabag/CoreBundle/Form/Type/EntryFilterType.php
- src/Wallabag/CoreBundle/Resources/translations/messages.da.yml
- src/Wallabag/CoreBundle/Resources/translations/messages.de.yml
- src/Wallabag/CoreBundle/Resources/translations/messages.en.yml
- src/Wallabag/CoreBundle/Resources/translations/messages.es.yml
- src/Wallabag/CoreBundle/Resources/translations/messages.fa.yml
- src/Wallabag/CoreBundle/Resources/translations/messages.fr.yml
- src/Wallabag/CoreBundle/Resources/translations/messages.oc.yml
- src/Wallabag/CoreBundle/Resources/translations/messages.pl.yml
- src/Wallabag/CoreBundle/Resources/translations/messages.ro.yml
- src/Wallabag/CoreBundle/Resources/translations/messages.tr.yml
- src/Wallabag/CoreBundle/Resources/views/themes/baggy/Entry/entries.html.twig
- src/Wallabag/CoreBundle/Resources/views/themes/material/Entry/entries.html.twig
- src/Wallabag/CoreBundle/Tests/Controller/EntryControllerTest.php
This PR allows users to filter their entries and requiring items to be "unread".
| Tests pass?   | yes*
| Fixed tickets | #2031
_* I'm getting a couple of PHPUnit test errors/failures, but they also exist on versions without this change._
----
There is some coupling caused by the SQL query that might cause future issues if the schema/Doctrine design changes.
Currently in [EntryFilterType.php](https://github.com/wallabag/wallabag/blob/6be103cd39e90849ab614d65bc8ad09f3507a206/src/Wallabag/CoreBundle/Form/Type/EntryFilterType.php#L83) the column for finding the read/unread status is also the archived …
> Add unread filter to entries pages

- docs/en/user/installation.rst
I am using Wallabag with lighttpd and noticed that the regex for the rewrite doesn't work as it's missing quantifier. I've added them.
I tested it using https://regex101.com/
> Corrected Regex for lighttpd rewrite

- src/Wallabag/CoreBundle/Controller/EntryController.php
| Fixed tickets | https://github.com/wallabag/wallabag/issues/1964
Instead of checking for the whole absolute url, we just check with the relative url.
If the referer ends with the relative url of the deleted entry, don't redirect to the referer.
Should fix https://github.com/wallabag/wallabag/issues/1964
> Try to find bad redirection after delete

- composer.json
| Fixed tickets | https://github.com/wallabag/wallabag/issues/2141
The fabpot's one is now depreacted
Fix https://github.com/wallabag/wallabag/issues/2141
> Use friendsofphp instead of fabpot

- src/Wallabag/CoreBundle/Form/Type/EntryFilterType.php
- tests/Wallabag/CoreBundle/Controller/EntryControllerTest.php
| Fixed tickets | https://github.com/wallabag/wallabag/issues/2077
When we select only one value in the reading time filter, we need to perform a query with only one value (greater than OR lower than).
Should fix https://github.com/wallabag/wallabag/issues/2077
> Handle only upper or only lower reading filter

- .gitignore
- README.md
- bin/doctrine
- bin/doctrine-dbal
- bin/doctrine-migrations
- bin/doctrine.php
- bin/php-cs-fixer
- bin/security-checker
- docs/en/user/installation.rst
- docs/fr/user/installation.rst
Since Composer 1.2, binaries are re-installed from vendors if there aren't found.
This avoid us to commit binaries vendors into the repo.
:warning: You have to update your Composer to the 1.2 (`composer selfupdate`)
> Remove binary from repo

- src/Wallabag/CoreBundle/Resources/public/themes/baggy/css/ratatouille.css
- src/Wallabag/CoreBundle/Resources/public/themes/material/css/main.css
Hi,
This is fixing the issue with images inside a figure element that are bigger than expected.
> FIX image inside a figure element max-width

- src/Wallabag/CoreBundle/Controller/FooterController.php
- src/Wallabag/CoreBundle/Controller/StaticController.php
- src/Wallabag/CoreBundle/DependencyInjection/WallabagCoreExtension.php
- src/Wallabag/CoreBundle/Resources/config/parameters.yml
- src/Wallabag/CoreBundle/Resources/views/themes/baggy/Static/howto.html.twig
- src/Wallabag/CoreBundle/Resources/views/themes/material/Static/howto.html.twig
- src/Wallabag/CoreBundle/Resources/views/themes/material/footer.html.twig
- src/Wallabag/CoreBundle/Resources/views/themes/material/layout.html.twig
Hi there,
I'm not sure would merge this but at the time I did these changes, social links URLs were wrong and I thought it might be a good idea to mutualize these informations.
> Handling socials links into a config file

- src/Wallabag/CoreBundle/Resources/translations/messages.de.yml
> Fixed typo in entry:notice:entry_saved

- .travis.yml
- src/Wallabag/CoreBundle/Form/DataTransformer/StringToListTransformer.php
- src/Wallabag/CoreBundle/Form/Type/ConfigType.php
- src/Wallabag/CoreBundle/Helper/RuleBasedTagger.php
- src/Wallabag/CoreBundle/Resources/views/themes/baggy/Config/index.html.twig
- src/Wallabag/CoreBundle/Resources/views/themes/material/Config/index.html.twig
- tests/Wallabag/CoreBundle/Command/InstallCommandTest.php
When Two factor authentication is disabled, the `form_rest` displayed the label of the 2FA field, see below
> Fix form user display when 2FA is disabled

- src/Wallabag/ImportBundle/Import/AbstractImport.php
- src/Wallabag/ImportBundle/Import/PocketImport.php
- src/Wallabag/ImportBundle/Import/WallabagImport.php
- tests/Wallabag/ImportBundle/Import/PocketImportTest.php
- tests/Wallabag/ImportBundle/Import/WallabagV2ImportTest.php
| Fixed tickets | fix https://github.com/wallabag/wallabag/issues/2223
graby will throw an Exception in some case (like a bad url, a restricted url or a secured pdf).
Import doesn't handle that case and break the whole import.
With that commit the import isn't stopped but the entry is just skipped.
Also, as a  bonus, I've added extra test on WallabagImportV2 when the json is empty.
> Avoid breaking import when fetching fail

- src/Wallabag/CoreBundle/Resources/translations/messages.da.yml
- src/Wallabag/CoreBundle/Resources/translations/messages.de.yml
- src/Wallabag/CoreBundle/Resources/translations/messages.en.yml
- src/Wallabag/CoreBundle/Resources/translations/messages.es.yml
- src/Wallabag/CoreBundle/Resources/translations/messages.fa.yml
- src/Wallabag/CoreBundle/Resources/translations/messages.fr.yml
- src/Wallabag/CoreBundle/Resources/translations/messages.it.yml
- src/Wallabag/CoreBundle/Resources/translations/messages.oc.yml
- src/Wallabag/CoreBundle/Resources/translations/messages.pl.yml
- src/Wallabag/CoreBundle/Resources/translations/messages.ro.yml
- src/Wallabag/CoreBundle/Resources/translations/messages.tr.yml
- src/Wallabag/CoreBundle/Resources/views/themes/baggy/Entry/entry.html.twig
- src/Wallabag/CoreBundle/Resources/views/themes/material/Entry/entry.html.twig
> Added creation date and reading time on article view

- src/Wallabag/ApiBundle/Controller/WallabagRestController.php
- src/Wallabag/ApiBundle/Entity/Client.php
- src/Wallabag/CoreBundle/Controller/EntryController.php
- src/Wallabag/CoreBundle/Controller/ExportController.php
- src/Wallabag/CoreBundle/Controller/TagController.php
- src/Wallabag/CoreBundle/DataFixtures/ORM/LoadTagData.php
- src/Wallabag/CoreBundle/Helper/PreparePagerForEntries.php
- src/Wallabag/CoreBundle/Repository/EntryRepository.php
- src/Wallabag/CoreBundle/Resources/config/services.yml
- src/Wallabag/CoreBundle/Resources/translations/messages.da.yml
- src/Wallabag/CoreBundle/Resources/translations/messages.de.yml
- src/Wallabag/CoreBundle/Resources/translations/messages.en.yml
- src/Wallabag/CoreBundle/Resources/translations/messages.es.yml
- src/Wallabag/CoreBundle/Resources/translations/messages.fa.yml
- src/Wallabag/CoreBundle/Resources/translations/messages.fr.yml
- src/Wallabag/CoreBundle/Resources/translations/messages.oc.yml
- src/Wallabag/CoreBundle/Resources/translations/messages.pl.yml
- src/Wallabag/CoreBundle/Resources/translations/messages.ro.yml
- src/Wallabag/CoreBundle/Resources/translations/messages.tr.yml
- src/Wallabag/CoreBundle/Resources/views/themes/baggy/Entry/entries.html.twig
- src/Wallabag/CoreBundle/Resources/views/themes/baggy/Tag/tags.html.twig
- src/Wallabag/CoreBundle/Resources/views/themes/material/Entry/entries.html.twig
- src/Wallabag/CoreBundle/Resources/views/themes/material/Tag/tags.html.twig
- tests/Wallabag/ApiBundle/Controller/WallabagRestControllerTest.php
- tests/Wallabag/CoreBundle/Controller/TagControllerTest.php
| Fixed tickets | #1982
Replaces #2175.
> Delete tag or tags by label

- docs/de/conf.py
- docs/de/requirements.txt
Configuration for ReadTheDocs website.
> Add configuration for german documentation

- .travis.yml
Got tired of `EE/home/travis/build.sh: line 45:  4445 Segmentation fault      (core dumped) phpunit -v` using PHP 7.1.0beta3
> Allow failure for PHP 7.1

- src/Wallabag/CoreBundle/Command/InstallCommand.php
- tests/Wallabag/CoreBundle/Command/InstallCommandTest.php
| Fixed tickets | fix #2251
Checking for the driver isn't enough.
We are now checking if we can etablish a connection to the database before trying to do anything.
By displaying the error from the Exception (in case of error) we hope to reduce issues overload about people getting error with the database
> Add a check for the database connection

- src/Wallabag/CoreBundle/Controller/DeveloperController.php
- src/Wallabag/CoreBundle/Resources/views/themes/material/layout.html.twig
- src/Wallabag/CoreBundle/Twig/WallabagExtension.php
Instead of performing a complex select (to retrieve all data for entry, etc...) just select the counter and retrieve it.
Down from ~50ms to ~30ms on the unread page (with 500 items)
> Instead of selecting the whole data, just count it

- src/Wallabag/CoreBundle/Resources/translations/messages.oc.yml
Line 347, I'm not sure about what I wrote to avoid and end of string started with "
I had to use the simple ' in the sentence.
Let me know if it was okay like so.
> Occitan  updated

- src/Wallabag/ApiBundle/Controller/WallabagRestController.php
Since Symfony 3.1 we can define the json of a JsonResonse using `->setJson()`
> Re-use JsonResponse

- .travis.yml
- bin/symfony_requirements
- install.sh
- src/Wallabag/ImportBundle/Import/PocketImport.php
- src/Wallabag/ImportBundle/Import/ReadabilityImport.php
- src/Wallabag/ImportBundle/Import/WallabagImport.php
- var/SymfonyRequirements.php
> Check if asset is enable instead of opposite

- src/Wallabag/CoreBundle/Helper/EntriesExport.php
| Fixed tickets | #2296 
I removed all special chars from the filename of an epub chapter, in case other characters break the file (not only `+`).
> Fix issue #2296: epub export with special chars in the title.

- src/Wallabag/CoreBundle/Resources/views/themes/baggy/Entry/entries.xml.twig
- src/Wallabag/CoreBundle/Resources/views/themes/material/Entry/entries.xml.twig
For some reason I can't get to connect to v2 servers with the latest versions of the android app. CDATA fragments are not properly enclosed. This seems to fix it.
See https://github.com/wallabag/android-app/pull/282#issuecomment-230105731
> fix feeds not syncing on android app

- phpunit.xml.dist
- src/Wallabag/CoreBundle/Resources/translations/messages.da.yml
- src/Wallabag/CoreBundle/Resources/translations/messages.de.yml
- src/Wallabag/CoreBundle/Resources/translations/messages.en.yml
- src/Wallabag/CoreBundle/Resources/translations/messages.es.yml
- src/Wallabag/CoreBundle/Resources/translations/messages.fa.yml
- src/Wallabag/CoreBundle/Resources/translations/messages.fr.yml
- src/Wallabag/CoreBundle/Resources/translations/messages.it.yml
- src/Wallabag/CoreBundle/Resources/translations/messages.oc.yml
- src/Wallabag/CoreBundle/Resources/translations/messages.pl.yml
- src/Wallabag/CoreBundle/Resources/translations/messages.ro.yml
- src/Wallabag/CoreBundle/Resources/translations/messages.tr.yml
- src/Wallabag/ImportBundle/Controller/ImportController.php
- src/Wallabag/ImportBundle/Resources/views/Import/check_queue.html.twig
- tests/Wallabag/CoreBundle/WallabagCoreTestCase.php
- tests/Wallabag/ImportBundle/Controller/PocketControllerTest.php
- tests/Wallabag/ImportBundle/Controller/ReadabilityControllerTest.php
- tests/Wallabag/ImportBundle/Controller/WallabagV1ControllerTest.php
- tests/Wallabag/ImportBundle/Controller/WallabagV2ControllerTest.php
- Disable PHPUnit deprecation that fail tests since Twig 1.25.0 (it didn't seems the error come from something we've done)
- Display a message when async import won’t work
Preview of the error message:
- Avoid failing tests for user who didn’t install Redis (test will be marked as skip)
> Some checks about Redis & RabbitMQ

- src/Wallabag/ApiBundle/Controller/WallabagRestController.php
- src/Wallabag/CoreBundle/Controller/TagController.php
- src/Wallabag/CoreBundle/Helper/ContentProxy.php
- src/Wallabag/CoreBundle/Repository/TagRepository.php
- src/Wallabag/CoreBundle/Twig/WallabagExtension.php
- src/Wallabag/ImportBundle/Import/PocketImport.php
- src/Wallabag/ImportBundle/Import/WallabagImport.php
- tests/Wallabag/CoreBundle/Helper/ContentProxyTest.php
- tests/Wallabag/ImportBundle/Import/PocketImportTest.php
- tests/Wallabag/ImportBundle/Import/WallabagV1ImportTest.php
- tests/Wallabag/ImportBundle/Import/WallabagV2ImportTest.php
| Fixed tickets | #1981, #2298
This should fix https://github.com/wallabag/wallabag/issues/1981, the duplicated tag on import (when not using async import).
Also, I pushed a fix https://github.com/wallabag/wallabag/issues/2298 for bad count in the menu
> Fix duplicate tags on import

- docker/php/Dockerfile
- docs/de/developer/docker.rst
- docs/en/developer/docker.rst
- docs/fr/developer/docker.rst
To be able to export an entry as an EPUB file, we need the `gd` extension.
=> Add it to docker
I also fixed a small error in the docs: `console` is in `bin/` and not in `app/.`
> Docker : install PHP 'gd' extension

- app/config/config.yml
- src/Wallabag/CoreBundle/Controller/ExceptionController.php
- src/Wallabag/CoreBundle/ParamConverter/UsernameRssTokenConverter.php
- src/Wallabag/CoreBundle/Resources/config/services.yml
- src/Wallabag/CoreBundle/Resources/views/themes/baggy/Exception/error.html.twig
- src/Wallabag/CoreBundle/Resources/views/themes/material/Exception/error.html.twig
- tests/Wallabag/CoreBundle/ParamConverter/UsernameRssTokenConverterTest.php
| Fixed tickets | https://github.com/wallabag/wallabag/issues/1570
All error goes to the same template which only display the error message and the status code.
Should (finally) fix https://github.com/wallabag/wallabag/issues/1570
On material:
On baggy:
> Customize errors templates

- app/config/services.yml
- src/Wallabag/CoreBundle/Resources/translations/messages.da.yml
- src/Wallabag/CoreBundle/Resources/translations/messages.de.yml
- src/Wallabag/CoreBundle/Resources/translations/messages.en.yml
- src/Wallabag/CoreBundle/Resources/translations/messages.es.yml
- src/Wallabag/CoreBundle/Resources/translations/messages.fa.yml
- src/Wallabag/CoreBundle/Resources/translations/messages.fr.yml
- src/Wallabag/CoreBundle/Resources/translations/messages.it.yml
- src/Wallabag/CoreBundle/Resources/translations/messages.oc.yml
- src/Wallabag/CoreBundle/Resources/translations/messages.pl.yml
- src/Wallabag/CoreBundle/Resources/translations/messages.ro.yml
- src/Wallabag/CoreBundle/Resources/translations/messages.tr.yml
- src/Wallabag/CoreBundle/Resources/views/themes/material/layout.html.twig
- src/Wallabag/CoreBundle/Twig/WallabagExtension.php
- tests/Wallabag/CoreBundle/Twig/WallabagExtensionTest.php
Related to https://github.com/wallabag/wallabag/issues/1638
It display a single line in the footer with some stats.
> Add simple stats in footer

- src/Wallabag/CoreBundle/Repository/EntryRepository.php
- tests/Wallabag/CoreBundle/Controller/EntryControllerTest.php
| Fixed tickets | https://github.com/wallabag/wallabag/issues/2126
Should fix https://github.com/wallabag/wallabag/issues/2126
When comparing the saved url and the new one, we should ensure the url is well decoded to avoid difference with accented characters in url.
> Avoid duplicate url with accents

- src/Wallabag/ApiBundle/Controller/WallabagRestController.php
- tests/Wallabag/ApiBundle/Controller/WallabagRestControllerTest.php
| Fixed tickets | https://github.com/wallabag/wallabag/issues/1796
Should fix https://github.com/wallabag/wallabag/issues/1796
It should allow third party to check if an url was already saved by a user
> Add an exists endpoint in API

- src/Wallabag/CoreBundle/Helper/EntriesExport.php
Trying to create a ePub version, the first page shows a message of a
“missing >”. This change solve this problem (and, for sure, in any
download version that’s use HTML).
> Remove error message when creating ePub versions

- .travis.yml
- docs/de/user/installation.rst
- docs/de/user/upgrade-2.0.x-2.0.y.rst
- docs/de/user/upgrade-2.0.x-2.1.y.rst
- docs/en/user/installation.rst
- docs/en/user/upgrade-2.0.x-2.0.y.rst
- docs/en/user/upgrade-2.0.x-2.1.y.rst
- docs/fr/user/installation.rst
- docs/fr/user/upgrade-2.0.x-2.0.y.rst
- docs/fr/user/upgrade-2.0.x-2.1.y.rst
- install.sh
- install_dev.sh
We removed too much stuff in the installation part. Re-add `wallabag:install`
Also use `install_dev.sh` for Travis and `install.sh` for final user.
Add `--no-dev` to `composer install` for prod env
Also, the translations build won't run PHPUnit now (so it'll be faster)
> Fix for 2.1 installation

- .travis.yml
- src/Wallabag/UserBundle/EventListener/CreateConfigListener.php
- tests/Wallabag/UserBundle/EventListener/CreateConfigListenerTest.php
| Fixed tickets | https://github.com/wallabag/wallabag/issues/2357
Should fix https://github.com/wallabag/wallabag/issues/2357
When a user register itself AND the wallabag instance is configured to send a confirmation email, the user is disabled when the listener (which create the config) receive the event.
There were a check (don't know why) if the user is enabled we create the config. But the user is disabled when confirmation email is actived.
> Create config even if user is disabled

- composer.json
As requested from Gitter, `mouf/nodejs-installer` isn't required anymore.
`pagerfanta/pagerfanta` comes with pagerfanta bundle and `prepareDeploymentTarget` is only required for Heroku.
> Remove mouf/nodejs-installer from composer

- src/Wallabag/UserBundle/Resources/views/Manage/edit.html.twig
- tests/Wallabag/UserBundle/Controller/ManageControllerTest.php
| Fixed tickets | #2380
Fix #2380
When 2FA is enabled: 
When it's disabled:
> Fixed two-factor checkbox display in user admin panel

- CHANGELOG.md
- RELEASE_PROCESS.md
To replace our old (and manual) CHANGELOG generation, I will use `github-changelog-generator` by @skywinder. 
The command I use for that: `github_changelog_generator --no-compare-link --future-release "2.1.2"` (don't forget to replace the future release).
> Changed Changelog by using github-changelog-generator from @skywinder

- app/config/config.yml
- app/config/parameters.yml.dist
- src/Wallabag/CoreBundle/Resources/config/services.yml
| New feature?  | yes (new parameters)
| Fixed tickets | #2143 & #2391
Should fix #2143 #2391
Add ability to use socket for Redis & MySQL.
Should we wait for 2.2.0 or can this be added to 2.1.2? Because we added information in `parameters.yml` that must be set to run wallabag (even if defined at null).
> Add ability to use socket

- docs/de/developer/maintenance.rst
- docs/de/developer/rabbitmq.rst
- docs/de/developer/redis.rst
- docs/en/developer/maintenance.rst
- docs/en/developer/rabbitmq.rst
- docs/en/developer/redis.rst
- docs/fr/developer/maintenance.rst
- docs/fr/developer/rabbitmq.rst
- docs/fr/developer/redis.rst
| Bug fix?      | *kind of*
| Fixed tickets | https://github.com/wallabag/wallabag/issues/2398
Should fix https://github.com/wallabag/wallabag/issues/2398
All `bin/console` command in the documentation should define the environment to prod to avoid error on the end user.
> Set env to prod in documentation

- app/config/config.yml
| Fixed tickets | https://github.com/wallabag/wallabag/issues/2379
Should fix https://github.com/wallabag/wallabag/issues/2379
When creating a user, we set the language config “en” by default. We should use the defined locale (from `parameters.yml`) instead
> Use default locale for user config

- src/Wallabag/ApiBundle/Controller/WallabagRestController.php
- src/Wallabag/CoreBundle/Controller/TagController.php
- src/Wallabag/CoreBundle/Resources/config/services.yml
- tests/Wallabag/ApiBundle/Controller/WallabagRestControllerTest.php
- tests/Wallabag/CoreBundle/Controller/EntryControllerTest.php
- tests/Wallabag/CoreBundle/Controller/TagControllerTest.php
| Fixed tickets | fix https://github.com/wallabag/wallabag/issues/2270
When the association between a tag and an entry is removed, if the tag doesn’t have other entries, we can remove it.
Also add more tests for that part and ensure TagControllerTest is isolated from the rest of the test suite (finally!)
> Ensure orphan tag are remove in API

- src/Wallabag/ApiBundle/Controller/WallabagRestController.php
- tests/Wallabag/ApiBundle/Controller/WallabagRestControllerTest.php
| New feature?  | yes (little one)
| Fixed tickets | https://github.com/wallabag/wallabag/issues/1796
This is the end of https://github.com/wallabag/wallabag/pull/2325
We can now check multiple urls at once using: 
```
/api/entries/exists?urls[]=http://...&urls[]=http://...
```
I don't know if we should put a limitation to avoid receiving hundred of urls at once ?
> Ability to check multiple urls in API

- src/Wallabag/CoreBundle/Resources/translations/messages.da.yml
- src/Wallabag/CoreBundle/Resources/translations/messages.de.yml
- src/Wallabag/CoreBundle/Resources/translations/messages.en.yml
- src/Wallabag/CoreBundle/Resources/translations/messages.es.yml
- src/Wallabag/CoreBundle/Resources/translations/messages.fr.yml
- src/Wallabag/CoreBundle/Resources/translations/messages.it.yml
- src/Wallabag/CoreBundle/Resources/translations/messages.oc.yml
- src/Wallabag/CoreBundle/Resources/translations/messages.pl.yml
- src/Wallabag/CoreBundle/Resources/translations/messages.ro.yml
- src/Wallabag/CoreBundle/Resources/translations/messages.tr.yml
- src/Wallabag/CoreBundle/Resources/views/themes/baggy/Entry/entry.html.twig
| Fixed tickets | n/a
When there was more than one annotation, the `%nbAnnotations%` placeholder was displayed in both themes, instead of actual number.
> Show number of annotations instead of nbAnnotations placeholder

- src/Wallabag/CoreBundle/Resources/views/themes/common/Static/_bookmarklet.html.twig
| Fixed tickets | #2130, #2210, #1960
Current bookmarklet is broken, because it opens new Wallabag window, and closes it immediately, before Wallabag has a chance to add the link to the database.
Ideal solution would be to have the bookmarklet act _within_ the article page (like Pocket does), but that's significant amount of work. This PR prevents new window from being automatically closed. I realize it's not ideal, but at least it makes the bookmarklet work.
Additionally, I surrounded the JavaScript code with anonymous function, to avoid polluting page's scope by bookmarklet's …
> Remove automatic closing of the window from bookmarklet

- src/Wallabag/ApiBundle/Entity/AccessToken.php
- src/Wallabag/ApiBundle/Entity/RefreshToken.php
As per Doctrine said in the debug tool bar:
- The field Wallabag\ApiBundle\Entity\Client#refreshTokens is on the inverse side of a bi-directional relationship, but the specified mappedBy association on the target-entity Wallabag\ApiBundle\Entity\RefreshToken#client does not contain the required 'inversedBy="refreshTokens"' attribute.
- The field Wallabag\ApiBundle\Entity\Client#accessTokens is on the inverse side of a bi-directional relationship, but the specified mappedBy association on the target-entity Wallabag\ApiBundle\Entity\AccessToken#client does not …
> Fix entities definition

- app/config/config.yml
This is to be sure that user testing wallabag from the master will have the version defined as dev.
What do you think?
> Define a dev version for the master

- src/Wallabag/CoreBundle/Resources/views/themes/common/Entry/share.html.twig
I put the article title in the description field, to avoid wrong content (I tried locally with an article from lemonde and it starts with a video).
> Fixed Twitter Cards by adding a description tag

- tests/Wallabag/ImportBundle/Controller/ChromeControllerTest.php
- tests/Wallabag/ImportBundle/Controller/FirefoxControllerTest.php
Add missing check about Redis for tests.
Running test without Redis won't fail now and @tcitworld'll be happy again :frog:
> Avoid error when Redis isn't here in tests

- docs/de/user/installation.rst
- docs/en/user/installation.rst
- docs/fr/user/installation.rst
I have an other problem on the english homepage. 
`user-docs` is not converted into a link, see http://doc.wallabag.org/en/master/index.html, contrary to french and german documentations. Need help for this bug.
> Fixed display for note in installation page

- app/config/config.yml
- src/Wallabag/ApiBundle/Controller/WallabagRestController.php
- src/Wallabag/ApiBundle/Resources/config/routing_rest.yml
- tests/Wallabag/ApiBundle/Controller/WallabagRestControllerTest.php
Following discussions on Twitter - see https://twitter.com/wallabagapp/status/783608582323462144 - here's kind of a *draft* PR.
There is an endpoint in the API to get an entry as a JSON string: `/api/entries/123.json`
The returned JSON string contains an HTML version of the entry's content, but this is not well suited for offline reading, especially as it doesn't contain the images of the entry.
Instead of this HTML version of the entry's content, I'd rather use an EPUB version: one file to download, embeds the images, and many reading engines exist (like on ereader devices ;-) ), as it's a well-known format.
Great thing is: wallabag already has a "download as EPUB" feature, which is currently not exposed by the API.
So: this PR is a draft (no test included for now -- seems to work on my …
> API: ability to export entry in all available format (epub, pdf, etc...)

- docs/de/index.rst
- docs/de/user/parameters.rst
- docs/en/index.rst
- docs/en/user/parameters.rst
- docs/fr/index.rst
- docs/fr/user/parameters.rst
| New feature?  |  no
In #2392, we forgot french documentation and links for the menu. 
@Strubbl @jlnostr Can you help us for the german translation please? :)
> Added french documentation for parameters.yml

- docs/en/developer/api.rst
| Fixed tickets | #2443
Namely http://v2.wallabag.org/api/doc, so api methods can be looked up without installing wallabag first.
> Mention example instance in docs

- app/config/config.yml
- src/Wallabag/CoreBundle/Controller/EntryController.php
- src/Wallabag/CoreBundle/DependencyInjection/Configuration.php
- src/Wallabag/CoreBundle/DependencyInjection/WallabagCoreExtension.php
- src/Wallabag/CoreBundle/Resources/config/services.yml
- tests/Wallabag/CoreBundle/Controller/EntryControllerTest.php
| Bug fix?      | yes (kind of)
| Fixed tickets | fix https://github.com/wallabag/wallabag/issues/2440
In case user wants a fresh version of the current one and the website isn’t available, don’t erase it with a boring message saying wallabag wasn’t able to refresh the content.
> If reload content failed, don’t update it

- app/Resources/CraueConfigBundle/translations/CraueConfigBundle.da.yml
- app/Resources/CraueConfigBundle/translations/CraueConfigBundle.de.yml
- app/Resources/CraueConfigBundle/translations/CraueConfigBundle.en.yml
- app/Resources/CraueConfigBundle/translations/CraueConfigBundle.es.yml
- app/Resources/CraueConfigBundle/translations/CraueConfigBundle.fa.yml
- app/Resources/CraueConfigBundle/translations/CraueConfigBundle.fr.yml
- app/Resources/CraueConfigBundle/translations/CraueConfigBundle.it.yml
- app/Resources/CraueConfigBundle/translations/CraueConfigBundle.oc.yml
- app/Resources/CraueConfigBundle/translations/CraueConfigBundle.pl.yml
- app/Resources/CraueConfigBundle/translations/CraueConfigBundle.ro.yml
- app/Resources/CraueConfigBundle/translations/CraueConfigBundle.tr.yml
- src/Wallabag/CoreBundle/Command/InstallCommand.php
- src/Wallabag/CoreBundle/DataFixtures/ORM/LoadSettingData.php
- src/Wallabag/CoreBundle/Resources/translations/messages.da.yml
- src/Wallabag/CoreBundle/Resources/translations/messages.de.yml
- src/Wallabag/CoreBundle/Resources/translations/messages.en.yml
- src/Wallabag/CoreBundle/Resources/translations/messages.es.yml
- src/Wallabag/CoreBundle/Resources/translations/messages.fa.yml
- src/Wallabag/CoreBundle/Resources/translations/messages.fr.yml
- src/Wallabag/CoreBundle/Resources/translations/messages.it.yml
- src/Wallabag/CoreBundle/Resources/translations/messages.oc.yml
- src/Wallabag/CoreBundle/Resources/translations/messages.pl.yml
- src/Wallabag/CoreBundle/Resources/translations/messages.ro.yml
- src/Wallabag/CoreBundle/Resources/translations/messages.tr.yml
- src/Wallabag/CoreBundle/Resources/views/themes/common/Entry/share.html.twig
- src/Wallabag/CoreBundle/Twig/WallabagExtension.php
- src/Wallabag/ImportBundle/Consumer/AbstractConsumer.php
- src/Wallabag/ImportBundle/Import/BrowserImport.php
- tests/Wallabag/ImportBundle/Consumer/RedisEntryConsumerTest.php
| Fixed tickets | fix #2476, fix #2474, fix #2469, fix #2441
I use a kind of hacky way to convert the user locale (defined with 2 letters, like `fr`) into a local with 5 letters (like `fr_FR`). I guess it should work on most of the case..
When the `parseEntry` returns null it means the entry already exists in the database. Sending `false` as return, will requeue the message which will then loop forever.
Browser import can requeue message from `parseEntry` but we should take care of the way import are handled (depending on the producer)
#2474 `error.page_title` was missing
#2469 …
> Some fixes

- scripts/dev.sh
- scripts/install.sh
- scripts/require.sh
- scripts/update.sh
As discussed in #2500, we need to check if composer is installed locally (with a `composer.phar` file). 
I added a `require.sh` file to check it.
> Added require.sh to check if composer is installed

- docs/de/developer/api.rst
- docs/en/developer/api.rst
- docs/fr/developer/api.rst
| Bug fix?      | yes|
| New feature?  | |no
| BC breaks?    | |no
| Deprecations? | |no
| Tests pass?   | |no
| Documentation | yes|
sorry, i failed to link correctly. a space needs to be between link name and url. :crying_cat_face:
> docs: fix link to wallabag-stats project

- src/Wallabag/CoreBundle/Helper/EntriesExport.php
- src/Wallabag/CoreBundle/Resources/config/services.yml
- src/Wallabag/ImportBundle/Resources/config/services.yml
- src/Wallabag/UserBundle/Mailer/AuthCodeMailer.php
- src/Wallabag/UserBundle/Resources/config/services.yml
- tests/Wallabag/UserBundle/Mailer/AuthCodeMailerTest.php
| Q | A |
| --- | --- |
| Bug fix? | no |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Documentation | no |
| Translation | no |
| Fixed tickets |  |
| License | MIT |
We are injecting CraueConfig service when we only need to retrieve one or two values from it.
Instead I discovered we can directly inject a value from a service in the service definition!
> Inject parameter instead of service

- scripts/dev.sh
- scripts/install.sh
- scripts/update.sh
| Q | A |
| --- | --- |
| Bug fix? | yes |
| New feature? | no |
| BC breaks? | i dont know |
| Deprecations? | no |
| Tests pass? | no |
| Documentation | no |
| Translation | no |
| Fixed tickets | #2517 |
| License | MIT |
this fix issue when installing , like : 
```
scripts/install.sh: 8: scripts/install.sh: [[: not found
scripts/install.sh: 9: .: Can't open /require.sh
Makefile:15: recipe for target 'install' failed
make: *** [install] Error 2
```
> fix path for  the install scripts

- src/Wallabag/ImportBundle/Command/ImportCommand.php
Hi!
I've waited way too long and finally, my Instapaper subscription ended last week. 
As I had a lot of articles, my web server was dying of timeout. 
So I've added Instapaper to the command line. Hope it's ok with you :) I can find some time to try to explain that somewhere in the doc if needed.
Magic:
```
php bin/console wallabag:import 1 instapaper-export.csv --importer=instapaper
Start : 01-11-2016 10:04:01 ---
1206 imported
0 already saved
End : 01-11-2016 10:28:20 ---
```
> Add Instapaper to CLI import

- src/Wallabag/CoreBundle/Resources/config/services.yml
Slashdot replaces actual content with a form regarding cookies when
requests originate from France. By forcing the user-agent, the warning
seems to go away.
> Force user-agent for .slashdot.org

- src/Wallabag/CoreBundle/Repository/EntryRepository.php
| Fixed tickets | fix #2531 
Imported content use the real creation date. If we sort by id, it'll
display contents in reverse order.
> Use created_at as default sort

- src/Wallabag/CoreBundle/Resources/views/themes/material/Entry/entries.html.twig
| Fixed tickets | fix #2544
Like `8.666666666667 min`.
This bug was already fixed in the 2.2 branch (see https://github.com/wallabag/wallabag/blob/2.2/src/Wallabag/CoreBundle/Resources/views/themes/material/Entry/entries.html.twig#L42)
> Round readingtime to avoid crazy number

- src/Wallabag/CoreBundle/Resources/translations/messages.da.yml
- src/Wallabag/CoreBundle/Resources/translations/messages.de.yml
- src/Wallabag/CoreBundle/Resources/translations/messages.en.yml
- src/Wallabag/CoreBundle/Resources/translations/messages.es.yml
- src/Wallabag/CoreBundle/Resources/translations/messages.fa.yml
- src/Wallabag/CoreBundle/Resources/translations/messages.fr.yml
- src/Wallabag/CoreBundle/Resources/translations/messages.it.yml
- src/Wallabag/CoreBundle/Resources/translations/messages.oc.yml
- src/Wallabag/CoreBundle/Resources/translations/messages.pl.yml
- src/Wallabag/CoreBundle/Resources/translations/messages.pt.yml
- src/Wallabag/CoreBundle/Resources/translations/messages.ro.yml
- src/Wallabag/CoreBundle/Resources/translations/messages.tr.yml
| Fixed tickets | ...
support.wallabag.org website is now closed.
> Removed support website on about page

- src/Wallabag/CoreBundle/Resources/views/themes/material/layout.html.twig
We used `title` but it takes time to be displayed. With these tooltips, we have the information in 50ms 👍 
I use tooltips from materializecss http://materializecss.com/dialogs.html#tooltip 
Screenshot:
> Added tooltips in header bar

- docs/de/user/installation.rst
- docs/en/user/installation.rst
- docs/fr/user/installation.rst
Documentation: Regarding
https://www.nginx.com/resources/wiki/start/topics/recipes/symfony/ we
need to limit access to config.php and make_dev.php files from Nginx.
That's why we return 404 error page for these files.
> fix #2582 - Documentation, Nginx config: disable all other PHP file from symphony

- src/Wallabag/CoreBundle/Resources/config/services.yml
| Bug fix?      | kind of
Since [graby@1.5.0](https://github.com/j0k3r/graby/releases/tag/1.5.0), user-agents can be defined in site-config, which is now the recommended way
> User-agents have moved to site-config

- app/DoctrineMigrations/Version20161118134328.php
- docs/de/user/filters.rst
- docs/en/user/filters.rst
- docs/fr/user/filters.rst
- src/Wallabag/CoreBundle/Entity/Entry.php
- src/Wallabag/CoreBundle/Form/Type/EntryFilterType.php
- src/Wallabag/CoreBundle/Helper/ContentProxy.php
- src/Wallabag/CoreBundle/Resources/translations/messages.da.yml
- src/Wallabag/CoreBundle/Resources/translations/messages.de.yml
- src/Wallabag/CoreBundle/Resources/translations/messages.en.yml
- src/Wallabag/CoreBundle/Resources/translations/messages.es.yml
- src/Wallabag/CoreBundle/Resources/translations/messages.fa.yml
- src/Wallabag/CoreBundle/Resources/translations/messages.fr.yml
- src/Wallabag/CoreBundle/Resources/translations/messages.it.yml
- src/Wallabag/CoreBundle/Resources/translations/messages.oc.yml
- src/Wallabag/CoreBundle/Resources/translations/messages.pl.yml
- src/Wallabag/CoreBundle/Resources/translations/messages.pt.yml
- src/Wallabag/CoreBundle/Resources/translations/messages.ro.yml
- src/Wallabag/CoreBundle/Resources/translations/messages.tr.yml
- src/Wallabag/CoreBundle/Resources/views/themes/baggy/Entry/entries.html.twig
- src/Wallabag/CoreBundle/Resources/views/themes/material/Entry/entries.html.twig
- tests/Wallabag/CoreBundle/Controller/EntryControllerTest.php
- tests/Wallabag/CoreBundle/Helper/ContentProxyTest.php
| Fixed tickets | #2589
Fix #2589
We now store the HTTP status code. 
We can filter entries thanks to the new filter, see screenshot (I added the filter in baggy theme too).
In an other PR, it's possible to improve the field (by replacing the text field with a list for example).
> Added http_status in Entry entity

- composer.json
Following https://github.com/wallabag/wallabag/pull/2495 assets needs to be installed now.
This was missing from post command script in `composer.json`
Also, should we create absolute or relative symlink? Currently it's absolute.
> Install assets for shortcuts

- app/Resources/CraueConfigBundle/translations/CraueConfigBundle.da.yml
- app/Resources/CraueConfigBundle/translations/CraueConfigBundle.de.yml
- app/Resources/CraueConfigBundle/translations/CraueConfigBundle.en.yml
- app/Resources/CraueConfigBundle/translations/CraueConfigBundle.es.yml
- app/Resources/CraueConfigBundle/translations/CraueConfigBundle.fa.yml
- app/Resources/CraueConfigBundle/translations/CraueConfigBundle.fr.yml
- app/Resources/CraueConfigBundle/translations/CraueConfigBundle.it.yml
- app/Resources/CraueConfigBundle/translations/CraueConfigBundle.oc.yml
- app/Resources/CraueConfigBundle/translations/CraueConfigBundle.pl.yml
- app/Resources/CraueConfigBundle/translations/CraueConfigBundle.pt.yml
- app/Resources/CraueConfigBundle/translations/CraueConfigBundle.ro.yml
- app/Resources/CraueConfigBundle/translations/CraueConfigBundle.tr.yml
- docs/de/user/configuration.rst
- docs/en/user/configuration.rst
- docs/fr/user/configuration.rst
- src/Wallabag/CoreBundle/Controller/RssController.php
- src/Wallabag/CoreBundle/Resources/views/themes/common/Entry/entries.xml.twig
- tests/Wallabag/CoreBundle/Controller/RssControllerTest.php
| Fixed tickets | fix #1831
RSS now support pagination.
Following https://tools.ietf.org/html/rfc5005#page-4
I also added some missing translation related to internal config page.
> RSS paging

- app/config/parameters.yml.dist
- docs/de/user/parameters.rst
- docs/en/user/parameters.rst
- docs/fr/user/parameters.rst
- src/Wallabag/CoreBundle/Resources/config/services.yml
| Bug fix?      | kinf of
| Fixed tickets | fix #2579
We can now use a password for the Redis connection.
If you want to define one, [use that answer](http://stackoverflow.com/a/7548743/569101).
> Add ability to use Redis with password

- composer.json
| Fixed tickets | fix #2617
This should be removed for the 2.3.0 since we'll drop PHP 5.5.
Should we create a 2.1.5 for that?
> Force composer to run as PHP 5.5.9

- src/Wallabag/CoreBundle/Resources/views/themes/common/Static/quickstart.html.twig
In the QuickStart page, the cards' titles were black. With the colored background it seems weird…
> Add white-text class to card-title too

- src/Wallabag/ApiBundle/Controller/EntryRestController.php
- tests/Wallabag/ApiBundle/Controller/EntryRestControllerTest.php
| Documentation | yes (api doc)
| Fixed tickets | fix #2489
Entry can be reloaded using the API.
Note that if we can't reload the entry (because we can't retrieve content OR the retrieved content failed), an empty 304 will be returned.
Otherwise, the full new entry will be return.
> Add ability to reload entry from API

- src/Wallabag/ApiBundle/Controller/EntryRestController.php
- tests/Wallabag/ApiBundle/Controller/EntryRestControllerTest.php
| Fixed tickets | Related #2614
Previously it was a 400 but this is more related to a real error.
Using the API user should only know the content got reloaded or not.
If reloaded: 200 otherwise: 304.
> Return 304 when content isn't reloaded using the API

- .travis.yml
- app/DoctrineMigrations/Version20161122203647.php
- app/Resources/FOSUserBundle/translations/FOSUserBundle.da.yml
- app/Resources/FOSUserBundle/translations/FOSUserBundle.de.yml
- app/Resources/FOSUserBundle/translations/FOSUserBundle.es.yml
- app/Resources/FOSUserBundle/translations/FOSUserBundle.fr.yml
- app/Resources/FOSUserBundle/translations/FOSUserBundle.oc.yml
- app/Resources/FOSUserBundle/translations/FOSUserBundle.pl.yml
- app/Resources/FOSUserBundle/translations/FOSUserBundle.pt.yml
- app/config/config.yml
- composer.json
- docs/de/developer/translate.rst
- docs/en/developer/translate.rst
- docs/fr/developer/translate.rst
- src/Wallabag/UserBundle/Repository/UserRepository.php
- src/Wallabag/UserBundle/Resources/views/Resetting/check_email.html.twig
- tests/Wallabag/CoreBundle/Controller/ConfigControllerTest.php
| Fixed tickets | fix #2580
When resetting the password, the overridden template we used wasn’t well spelled.
And since we are using a locked version of FOSUser (on a custom commit, because they breaks change in [that next commit](https://github.com/FriendsOfSymfony/FOSUserBundle/commit/f7a1f513753517601e94a0c208fdf8d24d1b85ce)), the translation of `resetting.check_email` is wrong in any language but english.
Because of that missing translations, I didn't set the milestone to 2.2. Should we wait for FOSUser to FINALLY RELEASE A FUCKING NEW VERSION and then got that translation …
> Fix password layout

- app/DoctrineMigrations/Version20160410190541.php
- app/DoctrineMigrations/Version20160812120952.php
- app/DoctrineMigrations/Version20160911214952.php
- app/DoctrineMigrations/Version20160916201049.php
- app/DoctrineMigrations/Version20161001072726.php
- app/DoctrineMigrations/Version20161022134138.php
- app/DoctrineMigrations/Version20161024212538.php
- app/DoctrineMigrations/Version20161031132655.php
- app/DoctrineMigrations/Version20161104073720.php
- app/DoctrineMigrations/Version20161106113822.php
- app/DoctrineMigrations/Version20161117071626.php
- app/DoctrineMigrations/Version20161118134328.php
- app/DoctrineMigrations/Version20161122144743.php
- app/DoctrineMigrations/Version20161122203647.php
I want to discuss with @wallabag/core team about this improvement. 
I know that we'll have problems with migrations when we'll release wallabag 2.2. 
We need to add as many checks as possible.
~~In this PR, I added `hasColumn()` (inspired by phinx from @robmorgan: [MySQL](https://github.com/robmorgan/phinx/blob/0.6.x-dev/src/Phinx/Db/Adapter/MysqlAdapter.php#L362), [SQLite](https://github.com/robmorgan/phinx/blob/0.6.x-dev/src/Phinx/Db/Adapter/SQLiteAdapter.php#L293), [Postgres](https://github.com/robmorgan/phinx/blob/0.6.x-dev/src/Phinx/Db/Adapter/PostgresAdapter.php#L346)).~~
~~I want to know if we need to have this feature in wallabag. And where we can store it.~~
I also replaced `abortIf` by `skipIf`. Like that, other migrations will be played.
abortIf: 
skipIf:
> Added hasColumn() in migration to check column existence

- src/Wallabag/CoreBundle/Resources/views/themes/material/Entry/entry.html.twig
| Fixed tickets | #2647 
Fix #2647 
This floating button is only visible on tablet or smartphone.
> Added floating button on entry view for mobile

- src/Wallabag/CoreBundle/Entity/TaggingRule.php
- tests/Wallabag/CoreBundle/Controller/ConfigControllerTest.php
| Fixed tickets | fix #2678
Limiting tagging rule to 255 to avoid database error when saving
> Limit rule to 255

- src/Wallabag/ImportBundle/Command/RedisWorkerCommand.php
Because Simpleue wants an integer (see https://github.com/javibravo/simpleue/blob/master/src/Simpleue/Worker/QueueWorker.php#L88), we need to cast the parameter. 
The problem is in the library I think, but it's faster to fix on our side.
> Casted maxIterations for Redis import

- src/Wallabag/ImportBundle/Import/ChromeImport.php
- src/Wallabag/ImportBundle/Import/FirefoxImport.php
- src/Wallabag/ImportBundle/Import/WallabagV2Import.php
During imports on wallabag.it, I found errors. 
`is_archived` and `is_starred` aren't nullable. So we need to set values. 
I don't know if I can improve tests. If necessary, I'll have on them a look later.
> Fixed imports with is_starred and is_archived

- src/Wallabag/CoreBundle/Resources/views/themes/material/layout.html.twig
- src/Wallabag/ImportBundle/Resources/views/Import/index.html.twig
Because this notification is annoying for a wallabag admin, and because it takes some resources to be run, I think it's better to display it only on the Import page.
> Moved total messages from import

- src/Wallabag/CoreBundle/Repository/EntryRepository.php
I removed join on user table. We only need user id.
I think we can have performance gain. 
I saw very looong queries on app.wallabag.it with this QueryBuilder.
> Removed user join in query builder

- src/Wallabag/CoreBundle/Controller/EntryController.php
- src/Wallabag/CoreBundle/Controller/RssController.php
- src/Wallabag/CoreBundle/Repository/EntryRepository.php
Due to overload on app.wallabag.it, we disabled output walkers (see https://github.com/whiteoctober/Pagerfanta/issues/115)
The query to fetch all entries before:
The query to fetch all entries after:
> Removed outputWalkers for pagination

- app/DoctrineMigrations/Version20160911214952.php
- app/DoctrineMigrations/Version20161031132655.php
- app/DoctrineMigrations/Version20161117071626.php
- app/DoctrineMigrations/Version20161122144743.php
| Bug fix?      | could be
We now can run the migration every time, new line from `craue_config_setting` are properly checked.
> Ensure craue_config_setting migration are ok

- docs/de/user/installation.rst
- docs/de/user/upgrade.rst
- docs/en/user/installation.rst
- docs/en/user/upgrade.rst
- docs/fr/user/installation.rst
- docs/fr/user/upgrade.rst
| Documentation | yes (install/upgrade doc)
Even though all the websites used in the commands redirect http to
https, a man in the middle can happen with the initial request,
leading to arbitrary code execution.
> Change documentation links to HTTPS

- src/Wallabag/CoreBundle/Controller/TagController.php
- src/Wallabag/CoreBundle/DataFixtures/ORM/LoadTagData.php
- tests/Wallabag/CoreBundle/Controller/ExportControllerTest.php
- tests/Wallabag/CoreBundle/Controller/TagControllerTest.php
When an article had a tag with space inside (eg: "Intelligence artificielle"), the export failed.
```
Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Call to a member function getId() on null in /var/www/wallabag/src/Wallabag/CoreBundle/Controller/ExportController.php:66 Stack trace: #0 [internal function]: Wallabag\CoreBundle\Controller\ExportController->downloadEntriesAction(Object(Symfony\Component\HttpFoundation\Request), 'pdf', 'tag_entries')
```
> Fixed export by tags with a tag which contains space

- src/Wallabag/CoreBundle/Resources/views/themes/material/Entry/_card_actions.html.twig
- src/Wallabag/CoreBundle/Resources/views/themes/material/Entry/_reading_time.html.twig
- src/Wallabag/CoreBundle/Resources/views/themes/material/Entry/entry.html.twig
Before:
Reading time of entries on the main view was broken because of a wrong rounded value.
After:
The reading time code is now shared between both views.
> Fix entry reading time

- composer.json
- src/Wallabag/CoreBundle/Helper/ContentProxy.php
- tests/Wallabag/CoreBundle/Controller/SecurityControllerTest.php
- tests/Wallabag/CoreBundle/Helper/ContentProxyTest.php
| Fixed tickets | https://github.com/wallabag/ios-app/issues/62
If the website doesn't provide an og_image, the value will be false and so it'll be saved like that in the database.
We prefer to leave it as null instead of false.
> Avoid false preview image

- src/Wallabag/CoreBundle/Repository/TagRepository.php
This adds an orderBy clause to the listing of tags for a user. This makes the list at `/tag/list` more useable as the order of the tags seems not to be that random.
> Sort list of available tags

- app/DoctrineMigrations/Version20161214094402.php
I forgot a migration to rename `uuid` field in entry table. I was sure that this field was added in 2.2. 
Doctrine migrations removed renameColumn(). I need to write this migration in SQL. 
But SQLite 🤢 ...
> Added migration to rename uuid to uid

- app/DoctrineMigrations/Version20160410190541.php
- docs/de/user/query-upgrade-21-22.rst
- docs/en/user/query-upgrade-21-22.rst
- docs/fr/user/query-upgrade-21-22.rst
> Fixed duplicate entry for share_public in craue_setting_table

- scripts/require.sh
when composer.phar is not globally installed, we should add "./" in front of "composer.phar" to run it from the current folder.
| Fixed tickets | none yet
> scripts/update.sh: 18: scripts/update.sh: composer.phar: not found

- src/Wallabag/CoreBundle/Resources/views/themes/material/layout.html.twig
| BC breaks?    | -
| Documentation |  no
This PR adds `active` class to the list used for the current search. The active list is retrieved from the `currentRoute` query parameter.
> Show active list in the left menu during search

- docs/en/user/installation.rst
The documentation is missing information about the correct directives to use with apache 2.4. Without the "Require All granted" apache throw a 403 error.
> Add informations about Apache 2.4

- src/Wallabag/CoreBundle/Resources/views/themes/material/Entry/_card_full_image.html.twig
- src/Wallabag/CoreBundle/Resources/views/themes/material/Entry/_card_list.html.twig
- src/Wallabag/CoreBundle/Resources/views/themes/material/Entry/_card_no_preview.html.twig
- src/Wallabag/CoreBundle/Resources/views/themes/material/Entry/_card_preview.html.twig
- src/Wallabag/CoreBundle/Resources/views/themes/material/Entry/entry.html.twig
| BC breaks?    | -
| Deprecations? | -
| Fixed tickets | #2802 
This commit provides some improvements on the rendering of entry title
on entries list and entry views and refactors filter calls:
- Remove escape filter from apparent title, striptags is enough
- Move raw filter to the end of apparent title as it's ignored if not
placed as the last filter
- Replace raw filter with e('html_attr') for title used in attributes,
fixing possible issue and/or glitch
- Add striptags to entry.title used for link sharing to respect the
apparent title
**Note: this PR changes the behavior of Wallabag on link sharing, please test to …
> Fix rendering of entry title in Twig views

- src/Wallabag/CoreBundle/Repository/EntryRepository.php
- tests/Wallabag/CoreBundle/Controller/EntryControllerTest.php
| Tests pass?   | idk
This PR extends search to entries url to provide an alternative way to domain filtering.
> Search by term: extend to entries url

- src/Wallabag/ImportBundle/Consumer/AbstractConsumer.php
- tests/Wallabag/ImportBundle/Consumer/AMQPEntryConsumerTest.php
- tests/Wallabag/ImportBundle/Consumer/RedisEntryConsumerTest.php
On wallabag.it, I have sometimes imports which still run because user deleted its account after launching import. 
So RabbitMQ tries perpetually to read these messages, because they stay in queue. 
Now, when a user is deleted, we read the messages.
> Import: we now skip messages when user is null

- .travis.yml
- composer.json
| Fixed tickets | fix https://github.com/wallabag/wallabag/issues/2930
It should restore the PHP 7.1 compatibility
> Use wallabag/tcpdf

- src/Wallabag/ApiBundle/Controller/EntryRestController.php
- tests/Wallabag/ApiBundle/Controller/EntryRestControllerTest.php
| Fixed tickets | #2896
If the entry exists, `/api/exists` will now return it's id, otherwise still `false`.
> Api exists returns

- src/Wallabag/CoreBundle/Resources/views/base.html.twig
I use Chrome on an English/German Ubuntu. The language of my user is also configured to be English. Annoyingly the translation integrated in Chrome detects that Wallabag is French (which is not the case, it's English) and translates it then from English to German. To fix it, i removed the language from the html tag. 
I'm not aware of a potential side effect. I think another way to fix it would be to take the language of the current user and set it in the tag.
> remove language on html tag

- src/Wallabag/CoreBundle/Helper/DownloadImages.php
| Fixed tickets | #2805 
Save alpha channel when downloading PNG images
Fixes #2805
> Save alpha channel when downloading PNG images

- src/Wallabag/CoreBundle/Helper/EntriesExport.php
| Tests pass?   | maybe
The text "Produced by wallabag with PHPePub" is the first page of any epub.
On ebooks reader, it is common (e.g. kobo) to use the first page as the cover of
unread books, which makes it more difficult to differentiate the books.
Move the Notices chapter at the end of the book.
[Example of EPUB produced with the patch](https://framadrop.org/r/weF9UJ92_0#XPyno0a1/K6ehw+h/2l9+TXzwv444MGFqwxo5MXML4M=)
PS: unsure why the TOC is at the last page...
> Add export notice at the end of the epub

- composer.json
| Fixed tickets | https://github.com/wallabag/wallabag/issues/3043
FOSUserBundle is now stable (finally).
> Remove dev FOSUserBundle

- composer.json
This facilitates packaging, when installing in a different work PREFIX
than the final install location.
Signed-off-by: Olivier Mehani <shtrom@ssji.net>
| BC breaks?    | ?
| Deprecations? | ?
A small change to `composer.json` so the symlinks it creates when installing assets are relative. 
Maybe linked to #2950
> Make symfony-assets-install use `relative` symlinks

- docs/de/user/articles.rst
- docs/en/user/articles.rst
- docs/fr/user/articles.rst
- docs/it/user/articles.rst
- Update URL for Firefox extension to Wallabager instead of deprecated extension
- Add F-Droid link for Android app
- Fux a typo
> Use up-to-date Firefox extension and add F-Droid link for Android app.

- src/Wallabag/CoreBundle/Resources/translations/messages.en.yml
Correct one typo in CoreBundle messages.en.yml.
I didn't manage to run tests yet.
> Correct create_application en string

- src/Wallabag/ApiBundle/Form/Type/ClientType.php
- src/Wallabag/CoreBundle/Form/Type/ConfigType.php
- src/Wallabag/CoreBundle/Form/Type/EditEntryType.php
- src/Wallabag/CoreBundle/Form/Type/RssType.php
Use `property_path` form option to map underscored form fields
to object properties
@see https://github.com/symfony/symfony/issues/9162#issuecomment-25431148
Fix #3067
| Fixed tickets | #3067 
> Fix display the form errors correctly

- src/Wallabag/ApiBundle/Controller/EntryRestController.php
- tests/Wallabag/ApiBundle/Controller/EntryRestControllerTest.php
> Fix API pagination is broken if perPage is custom value

- src/Wallabag/CoreBundle/GuzzleSiteAuthenticator/GrabySiteConfigBuilder.php
- src/Wallabag/CoreBundle/Helper/HttpClientFactory.php
- src/Wallabag/CoreBundle/Resources/config/services.yml
- tests/Wallabag/CoreBundle/GuzzleSiteAuthenticator/GrabySiteConfigBuilderTest.php
Allows 3rd parties to register new guzzle subscribers by adding extra calls to the http_client_factory service. Used in https://github.com/bdunogier/guzzle-site-authenticator/pull/14 to fix a wrong URI during a login process.
| Fixed tickets | n/a
Allows 3rd parties to register new guzzle subscribers by adding extra calls to `addSubscribers` on the `http_client_factory` service.
Needed to fix a bug with a particular site's response. I think it improves wallabag's extensibility, and better decouples features such as paywalls.
> Improved Guzzle subscribers extensibility

- src/Wallabag/ApiBundle/Controller/TagRestController.php
- tests/Wallabag/ApiBundle/Controller/TagRestControllerTest.php
| Fixed tickets | https://github.com/wallabag/wallabag/issues/2709
It allows to request to delete a tag using query string instead of body parameter (which seems to be the standard).
Instead of breaking the previous behavior, I used a generic way to retrieve parameter (which looks into request attributes, query parameters and request parameters)
> Retrieve tag / tags value from query or request

- src/Wallabag/ApiBundle/Controller/EntryRestController.php
- tests/Wallabag/ApiBundle/Controller/EntryRestControllerTest.php
> Create a new entry via API even when its content can't be retrieved

- composer.json
- src/Wallabag/CoreBundle/GuzzleSiteAuthenticator/GrabySiteConfigBuilder.php
- src/Wallabag/CoreBundle/Helper/HttpClientFactory.php
- src/Wallabag/CoreBundle/Resources/config/services.yml
- tests/Wallabag/CoreBundle/GuzzleSiteAuthenticator/GrabySiteConfigBuilderTest.php
| Fixed tickets | https://github.com/wallabag/guzzle-site-authenticator/pull/15
If we can’t find a credential for the current host, even if it required login, we won’t add them and website will be fetched without any login.
Also, add logger.
Tested using NextINpact content and it worked well :call_me_hand:
> Skip auth when no credentials are found

- app/DoctrineMigrations/Version20170510082609.php
| Fixed tickets | #2810
What about usernames with more than 180 characters in existing instances (:scream:) ?
> Added migration to change length for user fields

- src/Wallabag/CoreBundle/Resources/views/themes/common/Static/about.html.twig
| Fixed tickets | #2891 
The two contribute strings were mixed up
> reorder contrib strings in about page

- composer.json
- var/SymfonyRequirements.php
Lock guzzle-site-authenticator to avoid error when new version (which is in 2.3 branch)
> Lock guzzle-site-authenticator to avoid errors

- src/Wallabag/CoreBundle/Resources/translations/messages.da.yml
- src/Wallabag/CoreBundle/Resources/translations/messages.de.yml
- src/Wallabag/CoreBundle/Resources/translations/messages.en.yml
- src/Wallabag/CoreBundle/Resources/translations/messages.es.yml
- src/Wallabag/CoreBundle/Resources/translations/messages.fa.yml
- src/Wallabag/CoreBundle/Resources/translations/messages.fr.yml
- src/Wallabag/CoreBundle/Resources/translations/messages.it.yml
- src/Wallabag/CoreBundle/Resources/translations/messages.oc.yml
- src/Wallabag/CoreBundle/Resources/translations/messages.pl.yml
- src/Wallabag/CoreBundle/Resources/translations/messages.pt.yml
- src/Wallabag/CoreBundle/Resources/translations/messages.ro.yml
- src/Wallabag/CoreBundle/Resources/translations/messages.tr.yml
- src/Wallabag/CoreBundle/Resources/views/themes/material/Entry/entry.html.twig
| Fixed tickets | #2967 
Use export in article view as well.
The translation has been taken from entry.list.export_title when available.
> unify Download/Export wording.

- app/config/config.yml
- tests/Wallabag/CoreBundle/Helper/ContentProxyTest.php
| BC breaks?    | ?
The URL to help fix a content retrieval problem is wrong.
> Fix documentation URL for "How can I help to fix that?"

- src/Wallabag/ApiBundle/Controller/EntryRestController.php
- src/Wallabag/CoreBundle/Controller/TagController.php
- src/Wallabag/CoreBundle/Helper/ContentProxy.php
- src/Wallabag/CoreBundle/Helper/TagsAssigner.php
- src/Wallabag/CoreBundle/Resources/config/services.yml
- src/Wallabag/ImportBundle/Import/AbstractImport.php
- src/Wallabag/ImportBundle/Import/BrowserImport.php
- src/Wallabag/ImportBundle/Import/PinboardImport.php
- src/Wallabag/ImportBundle/Import/PocketImport.php
- src/Wallabag/ImportBundle/Import/WallabagImport.php
- src/Wallabag/ImportBundle/Resources/config/services.yml
- tests/Wallabag/CoreBundle/Helper/ContentProxyTest.php
- tests/Wallabag/CoreBundle/Helper/TagsAssignerTest.php
- tests/Wallabag/ImportBundle/Import/ChromeImportTest.php
- tests/Wallabag/ImportBundle/Import/FirefoxImportTest.php
- tests/Wallabag/ImportBundle/Import/InstapaperImportTest.php
- tests/Wallabag/ImportBundle/Import/PocketImportTest.php
- tests/Wallabag/ImportBundle/Import/ReadabilityImportTest.php
- tests/Wallabag/ImportBundle/Import/WallabagV1ImportTest.php
- tests/Wallabag/ImportBundle/Import/WallabagV2ImportTest.php
| Bug fix?      | not really, but related https://github.com/wallabag/wallabag/issues/2864
Move Tags assigner to a dedicated file. This will for instance allow sending the « Create tag » event from this file, and maybe refactoring it
> Move Tags assigner to a separate file

- src/Wallabag/CoreBundle/Controller/TagController.php
- src/Wallabag/CoreBundle/Helper/Redirect.php
- tests/Wallabag/CoreBundle/Controller/TagControllerTest.php
- tests/Wallabag/CoreBundle/Helper/RedirectTest.php
| BC breaks?    | somewhat?
| Fixed tickets | #2835 
Ignore ActionMarkAsRead to stay on entry when removing a tag.
> Ignore ActionMarkAsRead when removing tag from entry

- src/Wallabag/ImportBundle/Import/InstapaperImport.php
- tests/Wallabag/CoreBundle/Command/ExportCommandTest.php
- tests/Wallabag/CoreBundle/Command/TagAllCommandTest.php
- tests/Wallabag/CoreBundle/Helper/ContentProxyTest.php
- tests/Wallabag/CoreBundle/ParamConverter/UsernameRssTokenConverterTest.php
- tests/Wallabag/ImportBundle/Command/RedisWorkerCommandTest.php
- tests/Wallabag/ImportBundle/Controller/InstapaperControllerTest.php
- tests/Wallabag/ImportBundle/Controller/PinboardControllerTest.php
- tests/Wallabag/ImportBundle/Controller/ReadabilityControllerTest.php
- tests/Wallabag/ImportBundle/Controller/WallabagV1ControllerTest.php
- tests/Wallabag/ImportBundle/Controller/WallabagV2ControllerTest.php
- tests/Wallabag/ImportBundle/Import/InstapaperImportTest.php
- tests/Wallabag/ImportBundle/fixtures/instapaper-export.csv
| Fixed tickets | https://github.com/wallabag/wallabag/pull/2897
Add support for tag in Instapaper import.
Instapaper doesn't support _tags_ but folder. Folders are also used for archive, unread & starred. One article can only be in one folder. So if the folder is not Archive, Unread & Starred, it means it's a tag (for us).
Also, I've improved tags assertions in import tests.
So instead of just checking the number of tags, we also check which tag is assigned to an entry.
> Add support for tag in Instapaper import

- src/Wallabag/CoreBundle/Controller/EntryController.php
- src/Wallabag/CoreBundle/Controller/TagController.php
- src/Wallabag/CoreBundle/Helper/PreparePagerForEntries.php
- src/Wallabag/UserBundle/Entity/User.php
- src/Wallabag/UserBundle/EventListener/CreateConfigListener.php
| Fixed tickets | https://github.com/wallabag/wallabag/issues/1360
- Page parameter was never used in `PreparePagerForEntries`
It could have been used if we set the current page inside function.
But we did that in each controller because we can have an `OutOfRangeCurrentPageException`
- Set the right variable type for date in User entity
- Two parameters weren't used in the `CreateConfigListener` we can remove them
> More Scrutinizer issues fixed

- src/Wallabag/CoreBundle/Helper/DownloadImages.php
- tests/Wallabag/CoreBundle/Helper/DownloadImagesTest.php
| Fixed tickets | https://github.com/wallabag/wallabag/issues/2964
Images with `&` in the path weren’t well replaced because they might be with `&amp;` in the html instead.
Replacing `&` with `&amp;` fix the problem.
It might not fix all problem related to images download so we shouldn't close the related issue yet.
> Replace images with & in url

- src/Wallabag/ApiBundle/Controller/EntryRestController.php
- src/Wallabag/CoreBundle/Helper/ContentProxy.php
- tests/Wallabag/ApiBundle/Controller/EntryRestControllerTest.php
| Fixed tickets | https://github.com/wallabag/wallabag/issues/3169
Like when we create an entry, we can now patch an entry with new fields:
- content
- language
- preview_picture
- published_at
- authors
> Add ability to patch an entry with more fields

- src/Wallabag/ApiBundle/Controller/UserRestController.php
- src/Wallabag/ApiBundle/Entity/Client.php
- src/Wallabag/CoreBundle/Resources/views/themes/common/Developer/index.html.twig
- src/Wallabag/UserBundle/Entity/User.php
- tests/Wallabag/AnnotationBundle/Controller/AnnotationControllerTest.php
- tests/Wallabag/ApiBundle/Controller/UserRestControllerTest.php
- tests/Wallabag/CoreBundle/Command/ShowUserCommandTest.php
| Fixed tickets | https://github.com/wallabag/wallabag/issues/3056
While creating a new user using the API, we also create a new client for the current user.
So the app which just create the user can use its newly created client to configure the app.
That new client is only return after creating the user.
When calling the endpoint /api/user to get user information, the new client information won’t be return.
Here is a response when creating a user:
```json
{
"id": 5,
"username": "username",
"email": "email@google.io",
"created_at": "2017-06-07T23:23:19+0200",
"updated_at": …
```
> Create (and return) a client after creating a new user using the API

- src/Wallabag/CoreBundle/Helper/ContentProxy.php
- src/Wallabag/CoreBundle/Resources/config/services.yml
- tests/Wallabag/ApiBundle/Controller/EntryRestControllerTest.php
- tests/Wallabag/CoreBundle/Controller/EntryControllerTest.php
- tests/Wallabag/CoreBundle/Helper/ContentProxyTest.php
- tests/Wallabag/ImportBundle/Controller/ReadabilityControllerTest.php
| Fixed tickets | https://github.com/wallabag/wallabag/issues/3186
_This is a proposal.
Any suggestions on which fields might be a good to validate is welcome._
Instead of saving the value of each field right into the content without any validation, it seems better to validate them **before**.
This might sounds obvious now we say that but we didn't do it before that PR.
> Validate language & preview picture fields

- src/Wallabag/ApiBundle/Controller/EntryRestController.php
- src/Wallabag/CoreBundle/Entity/Entry.php
- src/Wallabag/CoreBundle/Form/Type/EntryFilterType.php
- src/Wallabag/CoreBundle/Repository/EntryRepository.php
- src/Wallabag/CoreBundle/Resources/translations/messages.da.yml
- src/Wallabag/CoreBundle/Resources/translations/messages.de.yml
- src/Wallabag/CoreBundle/Resources/translations/messages.en.yml
- src/Wallabag/CoreBundle/Resources/translations/messages.es.yml
- src/Wallabag/CoreBundle/Resources/translations/messages.fa.yml
- src/Wallabag/CoreBundle/Resources/translations/messages.fr.yml
- src/Wallabag/CoreBundle/Resources/translations/messages.it.yml
- src/Wallabag/CoreBundle/Resources/translations/messages.oc.yml
- src/Wallabag/CoreBundle/Resources/translations/messages.pl.yml
- src/Wallabag/CoreBundle/Resources/translations/messages.pt.yml
- src/Wallabag/CoreBundle/Resources/translations/messages.ro.yml
- src/Wallabag/CoreBundle/Resources/views/themes/baggy/Entry/entries.html.twig
- src/Wallabag/CoreBundle/Resources/views/themes/material/Entry/entries.html.twig
- tests/Wallabag/ApiBundle/Controller/EntryRestControllerTest.php
- tests/Wallabag/CoreBundle/Controller/EntryControllerTest.php
| Translation   | needed
| Fixed tickets | https://github.com/wallabag/wallabag/issues/3004
From the interface:
- entries can now be filtered by `is_public`
From the API:
- entries can be filtered by `public`
- entry response contains the `is_public` boolean field
- posting or patching an entry can received the `public` field (to make the entry public or not)
> Add ability to filter public entries & use it in the API

- app/Resources/CraueConfigBundle/views/Settings/modify.html.twig
> Fixed internal settings form

- src/Wallabag/CoreBundle/Helper/ContentProxy.php
- tests/Wallabag/CoreBundle/Helper/ContentProxyTest.php
> Empty preview pictures and language return null

- src/Wallabag/ApiBundle/Controller/DeveloperController.php
- tests/Wallabag/ApiBundle/Controller/DeveloperControllerTest.php
| Documentation | https://github.com/wallabag/doc/pull/20
| Fixed tickets | https://github.com/wallabag/wallabag/issues/2800
While https://github.com/wallabag/wallabag/pull/3068 needs more changes to be ready, we can allow apps to use the `client_credentials` auth method instead of the `password` one (which sends the user's credentials every time, and requires apps to save them).
Now apps can simply request an `access_token` with the `client ID` and `secret ID`. There's no `refresh_token`.
The `password` auth method is still available but we can depreciate it.
cc @wallabag/contributors
> Add client_credentials oAuth2 auth method

- src/Wallabag/CoreBundle/Entity/SiteCredential.php
- src/Wallabag/UserBundle/Entity/User.php
There were this error in the console:
> The association Wallabag\CoreBundle\Entity\SiteCredential#user refers to the inverse side field Wallabag\UserBundle\Entity\User#site_credentials which does not exist.
> Fixed mapping entities

- app/config/config.yml
| Fixed tickets | https://github.com/wallabag/wallabag/issues/3268
Using html template format will then put the html format in the allowed list for the api doc which we don’t want since the api doesn’t response for html format.
> Disallow html for API templating formats

- src/Wallabag/ApiBundle/Controller/EntryRestController.php
- src/Wallabag/CoreBundle/Command/ExportCommand.php
- src/Wallabag/CoreBundle/Controller/ExportController.php
- src/Wallabag/CoreBundle/Helper/EntriesExport.php
| Tests pass?   | maybe
As mentioned in #2821, the author of an epub file is always "wallabag".
This PR introduces another author:
- When exporting a single article to epub, mobi, and pdf, use the article domain for the "author" metadata
- When exporting multiple articles in one file (all or category), the author is set to "_All authors_" or "_&lt;category> authors_", similar to the title ("_All articles_" or "_&lt;category> articles_"). Please tell me if you would rather display a list of all the authors of the exported articles; I can do that instead.
N.B.: I changed the author from array to string, …
> Use the article publisher as author for exported files

- src/Wallabag/ImportBundle/Controller/BrowserController.php
- tests/Wallabag/CoreBundle/Controller/EntryControllerTest.php
The previous url was redirected.
So while looking for that initial url in the database we couln't find it because it got and ending `/` at the end. Updating the initial url fix the problem.
> Put the final URL in data test

- Makefile
Make build command was still using grunt.
> Fix make build by replacing grunt with webpack

- src/Wallabag/CoreBundle/Controller/TagController.php
- src/Wallabag/CoreBundle/Repository/EntryRepository.php
- src/Wallabag/CoreBundle/Repository/TagRepository.php
| Fixed tickets | #3313 
Previously, two queries were executed by tag.
Now there is only one query executed for the complete tag list.
> Reduce number of queries on tag list

- src/Wallabag/CoreBundle/Resources/views/themes/baggy/Entry/entry.html.twig
| Tests pass?   | maybe
When using the Baggy theme, the links on each article to export to epub, mobi or pdf are wrong (like "?epub&method=id&value=1" instead of "export/1.epub").
This PR replaces the link with the same link as in the Material theme.
> Fix export links in baggy theme

- src/Wallabag/CoreBundle/Command/CleanDuplicatesCommand.php
- src/Wallabag/CoreBundle/Command/ReloadEntryCommand.php
- src/Wallabag/CoreBundle/Repository/EntryRepository.php
- tests/Wallabag/CoreBundle/Command/ReloadEntryCommandTest.php
| Fixed tickets | #3247 
I did not implement the `article` option described in the original issue because it seems easier to use the UI for this use case. Let me know if you want me to add it.
I have some ideas of relevant options for later like : 
* `wallabag:entry:reload --unread`
* `wallabag:entry:reload --starred`
* `wallabag:entry:reload --filter="insert rule here"`
* ...
> Add reload entry command

- src/Wallabag/CoreBundle/Resources/views/themes/baggy/Entry/entries.html.twig
- src/Wallabag/CoreBundle/Resources/views/themes/material/Entry/entries.html.twig
| Fixed tickets | #3019 (second part)
And when a parameter is null, it won't appear in the url like `?tag=`.
> Empty currentTag should be null

- app/DoctrineMigrations/Version20170824113337.php
- src/Wallabag/ApiBundle/Controller/EntryRestController.php
- src/Wallabag/CoreBundle/Controller/EntryController.php
- src/Wallabag/CoreBundle/Entity/Entry.php
- src/Wallabag/CoreBundle/Repository/EntryRepository.php
- tests/Wallabag/ApiBundle/Controller/EntryRestControllerTest.php
| Fixed tickets | #2381
This field is used to sort starred entries by starred_at field instead of createdAt field which is often not relevant (i.e. RSS exposed by wallabag).
TODO
===
> Add starred_at field which is set when an entry is starred

- app/Resources/CraueConfigBundle/translations/CraueConfigBundle.de.yml
Translate commented out strings and add missing quotation marks.
This time for wallabag branch 2.3 instead of master.
(Avoiding same merge conflict like with #3336 )
> Translate missing strings, add quotation marks

- app/DoctrineMigrations/Version20170719231144.php
- src/Wallabag/CoreBundle/Entity/Tag.php
- src/Wallabag/CoreBundle/Helper/TagsAssigner.php
- tests/Wallabag/CoreBundle/Controller/TagControllerTest.php
- tests/Wallabag/ImportBundle/Controller/PinboardControllerTest.php
- tests/Wallabag/ImportBundle/Controller/WallabagV1ControllerTest.php
| BC breaks?    | somewhat?
| Fixed tickets | #2502 
Store tag labels in lowercase in order to prevent case-sensitive duplicates.
Non-lowercase tags already existing before this PR should still work as usual but any new tag will be saved in lowercase.
> Ignore tag's case

- composer.json
- src/Wallabag/CoreBundle/Helper/EntriesExport.php
| Related tickets | #2591 
* adds a dependencie on https://github.com/mtibben/html2text
* Links are not displayed in order to not have a rendering too close to markdown
* wrap content text to 100 chars max per line (like the title)
Preview from the article given in the original issue : 
<details>
<summary>Before</summary>
```
====================================================================================================
Asynchronous Scraping with Python
====================================================================================================
Previously, I've …
```
> Better entry txt export using html2text

- src/Wallabag/CoreBundle/DataFixtures/ORM/LoadTagData.php
- src/Wallabag/CoreBundle/Repository/EntryRepository.php
- tests/Wallabag/ApiBundle/Controller/EntryRestControllerTest.php
- tests/Wallabag/CoreBundle/Controller/ExportControllerTest.php
- tests/Wallabag/CoreBundle/Controller/RssControllerTest.php
First, the `setParameter()` were done on the same parameter which in fact just duplicated the condition in the SQL query (like `where t.label = 'test' and t.label = 'test'`).
Changed the parameter doesn't help because the query was then wrong.
Changing the way to match associated tags for an entry and it worked.
poke @Zlitus
> Multiple tag search, which was broken from API

- app/Resources/static/themes/material/css/article.scss
Decreasing margin of .stats, increasing vertical margin of .stats li,
increasing right margin of material icons and reducing contrast of
material icons.
Here is a screenshot of current style:
And the updated style:
Can someone push the updated compiled assets please?
> Entry view: update .stats margins and color

- app/AppKernel.php
Since #3376, the web server console commands were not available.
> Enable WebServerBundle in dev environment

- app/AppKernel.php
- app/config/config.yml
- app/config/config_dev.yml
- app/config/config_prod.yml
- app/config/parameters.yml.dist
- app/config/parameters_test.yml
- app/config/tests/parameters_test.sqlite.yml
- app/config/wallabag.yml
- src/Wallabag/CoreBundle/Command/ExportCommand.php
- src/Wallabag/CoreBundle/Resources/config/services.yml
- tests/Wallabag/ImportBundle/Command/ImportCommandTest.php
Replace `kernel.root_dir` by `kernel.project_dir` and `Kernel::getRootDir()` by `Kernel::getProjectDir()`.
`kernel.root_dir` and `Kernel::getProjectDir()` are deprecated since Symfony 3.3.
See https://symfony.com/blog/new-in-symfony-3-3-a-simpler-way-to-get-the-project-root-directory and https://github.com/symfony/symfony/blob/3.3/UPGRADE-3.3.md#httpkernel for more information.
>  Replace kernel.root_dir by kernel.project_dir

- src/Wallabag/ApiBundle/Controller/EntryRestController.php
- src/Wallabag/CoreBundle/Repository/EntryRepository.php
- tests/Wallabag/ApiBundle/Controller/EntryRestControllerTest.php
Check is $tags is a string before explode
| Fixed tickets | #3361 
> Fix #3361 check type for tags in entry repository

- src/Wallabag/CoreBundle/Helper/EntriesExport.php
Add the title of the article in an `h1` tag at the beginning of the exported epub.
_Wondering: is it possible to add it on a separated page, to use it as the cover page?_
> add the title of article on the epub export

- src/Wallabag/UserBundle/Resources/translations/wallabag_user.en.yml
| Documentation | /no
| Translation   | yes/
> Spelling: Two-factor for wallabag connection

- app/DoctrineMigrations/Version20171105202000.php
- src/Wallabag/ApiBundle/Controller/EntryRestController.php
- src/Wallabag/CoreBundle/DataFixtures/ORM/LoadEntryData.php
- src/Wallabag/CoreBundle/Entity/Entry.php
- src/Wallabag/CoreBundle/Form/Type/EditEntryType.php
- src/Wallabag/CoreBundle/Resources/translations/messages.da.yml
- src/Wallabag/CoreBundle/Resources/translations/messages.de.yml
- src/Wallabag/CoreBundle/Resources/translations/messages.en.yml
- src/Wallabag/CoreBundle/Resources/translations/messages.es.yml
- src/Wallabag/CoreBundle/Resources/translations/messages.fa.yml
- src/Wallabag/CoreBundle/Resources/translations/messages.fr.yml
- src/Wallabag/CoreBundle/Resources/translations/messages.it.yml
- src/Wallabag/CoreBundle/Resources/translations/messages.oc.yml
- src/Wallabag/CoreBundle/Resources/translations/messages.pl.yml
- src/Wallabag/CoreBundle/Resources/translations/messages.pt.yml
- src/Wallabag/CoreBundle/Resources/translations/messages.ro.yml
- src/Wallabag/CoreBundle/Resources/translations/messages.ru.yml
- src/Wallabag/CoreBundle/Resources/translations/messages.tr.yml
- src/Wallabag/CoreBundle/Resources/views/themes/baggy/Entry/entry.html.twig
- src/Wallabag/CoreBundle/Resources/views/themes/material/Entry/edit.html.twig
- src/Wallabag/CoreBundle/Resources/views/themes/material/Entry/entry.html.twig
- src/Wallabag/CoreBundle/Twig/WallabagExtension.php
- tests/Wallabag/ApiBundle/Controller/EntryRestControllerTest.php
- tests/Wallabag/CoreBundle/Controller/EntryControllerTest.php
- tests/Wallabag/CoreBundle/Twig/WallabagExtensionTest.php
| Fixed tickets | #2106
Fixes #2106
This PR adds a new property (`originUrl`) to Entry. It lets the user to specify an origin url from which she retrieved/found an entry.
> Add originUrl property to Entry

- app/DoctrineMigrations/Version20171008195606.php
- tests/Wallabag/ApiBundle/Controller/EntryRestControllerTest.php
- tests/Wallabag/CoreBundle/GuzzleSiteAuthenticator/GrabySiteConfigBuilderTest.php
- tests/Wallabag/CoreBundle/Helper/ContentProxyTest.php
This PR fixes migration from PR #3373 for MySQL databases.
> Fix MySQL issue on mig from #3373

- src/Wallabag/CoreBundle/Controller/SiteCredentialController.php
- tests/Wallabag/CoreBundle/Controller/SiteCredentialControllerTest.php
| Fixed tickets | fixes #3429
If `restricted_access` is disabled, accessing `/site-credentials/` must be disabled.
> Disable controller access if feature disabled

- src/Wallabag/CoreBundle/Resources/views/themes/common/Entry/entries.xml.twig
| Fixed tickets | #3448 
Fixed `pubDate` format to be compliant with Date & Time specifications designed by RFC822.
It uses the PHP constant `DATE_RSS`.
> Fix #3448 - pubDate now conformant to DateTime RFC822 specifications

- Makefile
The symfony server:run command can only be used in dev environment
| Bug fix?      | yes, kind of
The symfony `server:run` command can only be used in dev environment.
> Replaced env by dev for make run

- app/DoctrineMigrations/Version20160401000000.php
| CHANGELOG.md  | :confused: 
| Fixed tickets | #3480
Instead of checking if some migrations were run we just check if the main table exist.
- if it exists, we can skip the initial migration
- if not, run the initial migration
Poke @aaa2000
> Change the way to check for initial migration

- src/Wallabag/CoreBundle/Resources/views/themes/material/Entry/entry.html.twig
| Tests pass?   | aye
| Fixed tickets | #3484
Hides the "Share" toolbar entry completely if all the share services are disabled.
I'm not really happy with the big "if" block, but I'd say it'd be overdoing it to change it without having a more modulare sharing system (e.g. be able to add/remove supported services). The list is hardcoded in the template, it can be hardcoded in the condition for it.
> Fix 3484: hide the share toggle button if no service is enabled

- README.md
Because `make run` is only for dev environment.
> Removed "make run" in the README

- app/config/config.yml
- app/config/config_test.yml
- app/config/parameters.yml.dist
- app/config/tests/parameters_test.mysql.yml
- app/config/tests/parameters_test.pgsql.yml
- app/config/tests/parameters_test.sqlite.yml
- src/Wallabag/CoreBundle/Doctrine/DBAL/Driver/CustomPostgreSQLDriver.php
- src/Wallabag/CoreBundle/Doctrine/DBAL/Schema/CustomPostgreSqlSchemaManager.php
| Documentation | https://github.com/wallabag/doc/pull/54
| Fixed tickets | #3479
Since DBAL guys are waiting for Travis to support PostgreSQL 10 ([which seems to be waited for months now](https://github.com/travis-ci/travis-ci/issues/8537)) we need to take action to fix migration for our PostgreSQL 10 users.
Introduce a custom driver & schema manager with the fix from the [DBAL issue](https://github.com/doctrine/dbal/issues/2868).
User using PostgreSQL 10 will need to add an extra line in the `parameters.yml`:
```diff
database_driver: pdo_pgsql
+    database_driver_class: …
```
> Add custom driver & schema manager for PostgreSQL 10

- CHANGELOG.md
- src/Wallabag/ApiBundle/Controller/EntryRestController.php
- src/Wallabag/CoreBundle/Controller/EntryController.php
- src/Wallabag/CoreBundle/Helper/ContentProxy.php
- tests/Wallabag/ApiBundle/Controller/EntryRestControllerTest.php
- tests/Wallabag/CoreBundle/Controller/EntryControllerTest.php
- tests/Wallabag/CoreBundle/WallabagCoreTestCase.php
| Fixed tickets | #2053 
Entries will now have a default title when it's empty (*because of an exception during the fetch*):
- basename part of entry's path, if any
- or domain name
This default title does not replace the "No title found" of Graby when it fails to extract a title.
This PR still needs a test on `EntryControllerTest` using a mock.
> Fix empty title and domain_name when exception is thrown during fetch

- src/Wallabag/CoreBundle/Command/InstallCommand.php
| BC breaks?    | -
| Deprecations? | -
server:run --env=prod does not exist anymore
> command: replace note regarding server:run --env=prod

- CHANGELOG.md
- src/Wallabag/CoreBundle/Resources/views/themes/material/Entry/_card_actions.html.twig
- src/Wallabag/CoreBundle/Resources/views/themes/material/Entry/_card_list.html.twig
- src/Wallabag/CoreBundle/Resources/views/themes/material/Entry/entry.html.twig
| CHANGELOG.md  | yes
| Fixed tickets | #3437 
Fixes #3437 
Here are some screens with updated icons:
I also fixed the icons (_unarchive, star_) of bottom menu on mobile view:
> material: replace exit_to_app, redo and autorenew icons

- CHANGELOG.md
- src/Wallabag/ApiBundle/Controller/EntryRestController.php
- tests/Wallabag/ApiBundle/Controller/EntryRestControllerTest.php
| Bug fix?      | _sort of_
| CHANGELOG.md  | yes
Workaround for https://github.com/wallabag/android-app/issues/646
> api: copy entry object before sending, to keep id

- src/Wallabag/CoreBundle/Resources/views/themes/common/Developer/index.html.twig
| Fixed tickets | #3432
Fix #3432
I didn't replace the words, because I don't have an opinion on that. 
But @gnppn is right about consistency on buttons/links.
> Replaced Create new client link with a button

- src/Wallabag/CoreBundle/Resources/views/themes/material/Entry/Card/_content.html.twig
- src/Wallabag/CoreBundle/Resources/views/themes/material/Entry/_tags.html.twig
- src/Wallabag/CoreBundle/Resources/views/themes/material/Entry/entry.html.twig
- tests/Wallabag/CoreBundle/Controller/EntryControllerTest.php
| Fixed tickets | #3534 
Fixes #3534
> Fix broken link to remove tags from entries

- src/Wallabag/CoreBundle/Resources/views/themes/material/Entry/_tags.html.twig
Since the `withRemove` variable is a template flag, it can be undefined.
In the `Entry\Card\_content.html.twig` template for example, the `withRemove` variable is not defined and I got an `Exception` when changing the `view-mode` :
```
Twig_Error_Runtime: Variable "withRemove" does not exist.
```
> Fix error when withRemove variable is not defined.

- src/Wallabag/CoreBundle/Resources/views/themes/baggy/Entry/entries.html.twig
- src/Wallabag/CoreBundle/Resources/views/themes/baggy/Entry/entry.html.twig
- src/Wallabag/CoreBundle/Resources/views/themes/material/Entry/Card/_content.html.twig
- src/Wallabag/CoreBundle/Resources/views/themes/material/Entry/entry.html.twig
This is a bug fix for the entry title. Adding a default value ends with this issue.
Before:
After:
> Fix title card HTML parsing

- src/Wallabag/CoreBundle/Resources/views/themes/common/Static/_bookmarklet.html.twig
| Fixed tickets | #3405
fix #3405
The bookmarklet use the current url as query string so the function encodeURIComponent must be used instead of encodeURI.
> Better encoding of the URI for the bookmarklet

- app/config/security.yml
- tests/Wallabag/CoreBundle/Controller/SecurityControllerTest.php
| Fixed tickets | #3612 
fix #3612
Allow user to use email to login.
> Allow login by email

- src/Wallabag/CoreBundle/Resources/views/themes/material/Entry/entry.html.twig
Hello,
Fixing some encoding issues. cc #3663 
Before:
After:
Have a nice day.
> Fix authors and preview alt encoding display

- src/Wallabag/CoreBundle/Helper/DownloadImages.php
- tests/Wallabag/CoreBundle/Helper/DownloadImagesTest.php
Hi,
Image path could be null resulting in this error `PHP Warning:  imagecreatefromstring(): Data is not in a recognized format in /wallabag/src/Wallabag/CoreBundle/Helper/DownloadImages.php on line 121`.
Encountered with https://framablog.org/2018/06/30/engagement-atypique/ .
Have a nice day.
> Fix image downloading on null image path

- tests/Wallabag/ImportBundle/Controller/FirefoxControllerTest.php
- tests/Wallabag/ImportBundle/fixtures/firefox-bookmarks.json
Looks like we got a lot of random failing while grabing SO content, replacing it might fix the problem.
See https://travis-ci.org/wallabag/wallabag/builds/400333598
> Replace SO url by lemonde.fr to avoid random failing test

- app/config/config.yml
```
Remaining deprecation notices (2)
2x: The "framework.trusted_proxies" configuration key has been deprecated in Symfony 3.3. Use the Request::setTrustedProxies() method in your front controller instead.
1x in InstallCommandTest::testRunInstallCommandChooseNothing from Tests\Wallabag\CoreBundle\Command
1x in AnnotationControllerTest::setUp from Tests\AnnotationBundle\Controller
```
> Remove remaining deprecation notices

- tests/Wallabag/CoreBundle/Controller/EntryControllerTest.php
- var/SymfonyRequirements.php
Looks like a test is always failing on Travis and can't reproduce locally.
Removing it since it affect language detection which is already covered by the ru_RU test.
> Removing failing test from Travis

- .travis.yml
PHP 7.2 is now published since a while. So it shouldn't fail on Travis.
> PHP 7.2 shouldn't fail

- src/Wallabag/AnnotationBundle/Repository/AnnotationRepository.php
- src/Wallabag/CoreBundle/Repository/EntryRepository.php
This PR renames methods which return a `QueryBuilder` with an `orderBy()` and improves the performance of the query for `getBuilderForUntaggedByUser()`.
The improvement may not be seen on this PR, but for an upcoming PR it definitely improves things:
A `count()` with the current `size(e.tags) = 0` for retrieving untagged entries:
```
wallabag=# EXPLAIN ANALYZE SELECT count(w0_.id) AS sclr_0 FROM "wallabag_entry" w0_ WHERE w0_.user_id = 1 AND (SELECT COUNT(*) FROM wallabag_entry_tag w1_ WHERE w1_.entry_id = w0_.id) = 0;
QUERY PLAN …
```
> Rename getBuilderByUser and refactor query for untagged entries

- app/DoctrineMigrations/Version20180405182455.php
- src/Wallabag/ApiBundle/Controller/EntryRestController.php
- src/Wallabag/CoreBundle/Controller/EntryController.php
- src/Wallabag/CoreBundle/DataFixtures/ORM/LoadEntryData.php
- src/Wallabag/CoreBundle/Entity/Entry.php
- src/Wallabag/CoreBundle/Repository/EntryRepository.php
- src/Wallabag/ImportBundle/Import/BrowserImport.php
- src/Wallabag/ImportBundle/Import/InstapaperImport.php
- src/Wallabag/ImportBundle/Import/PinboardImport.php
- src/Wallabag/ImportBundle/Import/PocketImport.php
- src/Wallabag/ImportBundle/Import/ReadabilityImport.php
- src/Wallabag/ImportBundle/Import/WallabagImport.php
- tests/Wallabag/ApiBundle/Controller/EntryRestControllerTest.php
- tests/Wallabag/CoreBundle/Controller/ConfigControllerTest.php
- tests/Wallabag/CoreBundle/Controller/EntryControllerTest.php
| Fixed tickets | #2716 #3556 
Add archived_at date this changes will allow:
* order entries by date of reading
* consistency => tagging or updating some metadata on an entry does'nt change date of reading (third app can rely on this date for stats ex : list all entries read for each week)
> Entry: add archived_at property and updateArchived method

- src/Wallabag/CoreBundle/Helper/ContentProxy.php
- tests/Wallabag/CoreBundle/Helper/ContentProxyTest.php
| Tests pass?   | yes (my changes doesn't cause any new failures, 8013f35d96c42b15c1da28cdff40e97289ad4e25 already cause 2 Errors)
| Fixed tickets | #3633
The issue described in https://github.com/wallabag/wallabag/issues/3633 was caused by <code>e('html_attr')</code> in [_content.html.twig](https://github.com/wallabag/wallabag/blob/e586d65b64089fc1cc230a18c470aae3f45f91a6/src/Wallabag/CoreBundle/Resources/views/themes/material/Entry/Card/_content.html.twig#L5). By replacing it with <code>e('html')</code> is a quick but not secure solution.
The real issue was caused by the library …
> Bugfix: Sanitize the title of a saved webpage from invalid UTF-8 characters.

- app/config/config.yml
- app/config/parameters.yml.dist
| Fixed tickets | #2046
Added secure email to the swiftmailer configuration incl. port, encryption and authentication mode. 
Notes:
* Changes made also to the wallabag/docker repository (https://github.com/wallabag/docker/pull/106)
* Changes required in the Wallabag parameter documentation https://doc.wallabag.org/en/admin/parameters.html
> Add secure email

- src/Wallabag/CoreBundle/Resources/views/themes/material/Entry/_card_no_preview.html.twig
Tags and images aren't coupled, so they shouldn't be coupled in
the UI, either. This also makes the titles and source domains show
up consistently for image and non-image entry cards.
I'm not sure what all of the questions are actually asking, so
I can't answer them very well.
> Show tags on non-image gallery preview card

- app/config/security.yml
- src/Wallabag/CoreBundle/Controller/ConfigController.php
- src/Wallabag/CoreBundle/Event/Listener/UserLocaleListener.php
- src/Wallabag/UserBundle/EventListener/CreateConfigListener.php
- src/Wallabag/UserBundle/Resources/config/services.yml
- src/Wallabag/UserBundle/Resources/views/Registration/register_content.html.twig
- src/Wallabag/UserBundle/Resources/views/layout.html.twig
- tests/Wallabag/CoreBundle/Controller/ConfigControllerTest.php
- tests/Wallabag/CoreBundle/Event/Listener/UserLocaleListenerTest.php
- tests/Wallabag/UserBundle/EventListener/CreateConfigListenerTest.php
> Added possibility to change locale from login/register pages

- src/Wallabag/CoreBundle/Helper/ContentProxy.php
- tests/Wallabag/CoreBundle/Helper/ContentProxyTest.php
| Bug fix?      | _sort of_
| New feature?  | _sort of_
| Fixed tickets | #3529 
Fixes #3529 
This PR is a partial fix for #3529: it still set the final url as the actual entry url, but now it sets origin_url field to the former url.
Ex:
Current behavior:
- User saves a reddit.com to Wallabag
- Graby fetchs the page and finds a new link to follow (llvm.org)
- Entry is saved with llvm.org as the entry url
| Given url | Fetched url | Stored url | Stored origin url |
| - | - | - | - |
| `https://www.reddit.com/r/li[…]` | `http://lists.llvm.org/pip[…]` | `http://lists.llvm.org/pip[…]` | - |
New behavior: …
> Swap entry url with origin url if graby provides an updated one

- .github/PULL_REQUEST_TEMPLATE.md
This PR is a little one to move 'Fixed tickets' off of the template's table and use GitHub special keywords to auto-close issues on merge.
> Add note on GitHub PR template to auto-close issues

- src/Wallabag/CoreBundle/Resources/translations/messages.da.yml
- src/Wallabag/CoreBundle/Resources/translations/messages.en.yml
- src/Wallabag/CoreBundle/Resources/translations/messages.es.yml
- src/Wallabag/CoreBundle/Resources/translations/messages.fa.yml
- src/Wallabag/CoreBundle/Resources/translations/messages.it.yml
- src/Wallabag/CoreBundle/Resources/translations/messages.pt.yml
- src/Wallabag/CoreBundle/Resources/translations/messages.ro.yml
- src/Wallabag/CoreBundle/Resources/translations/messages.tr.yml
Signed-off-by: Olivier Mehani <shtrom@ssji.net>
| Tests pass?   | didn't try
This is a minor fix that correct some English language in the documentation for tagging rules. It also updates the string in the translations.
> Fix documentation wording for matches/notmatches tagging rules

- README.md
Fix link to Wallabag requirements in documentation
> Fix link to wallabag requirements in documentation

- src/Wallabag/CoreBundle/Resources/views/themes/baggy/Entry/entries.html.twig
- src/Wallabag/CoreBundle/Resources/views/themes/baggy/Entry/entry.html.twig
- src/Wallabag/CoreBundle/Resources/views/themes/common/Entry/share.html.twig
- src/Wallabag/CoreBundle/Resources/views/themes/common/Static/howto.html.twig
- src/Wallabag/CoreBundle/Resources/views/themes/material/Entry/entry.html.twig
- src/Wallabag/CoreBundle/Resources/views/themes/material/layout.html.twig
From https://developers.google.com/web/tools/lighthouse/audits/noopener:
- new pages will run in separate processes, avoiding any performance
intermingling impacts
- new pages won't have access to current page's window object via JavaScript
> Add rel=noopener to target=_blank links

- src/Wallabag/CoreBundle/Resources/translations/messages.en.yml
- src/Wallabag/CoreBundle/Resources/translations/messages.fr.yml
| CHANGELOG.md  | yes
This very slight modification is to ensure that the option is well understood.
Indeed, it indicated the destination (go to home page or stay on the current page) when one article was mark as read. However, this option is actually also controlling where you go when you mark something as favorite, or when you delete one.
I think this modification will allow one to better understand what this option is doing (I personally couldn't understand why I was taken back to the home page when marking an article as favorite).
> Update translation when marking as read

- src/Wallabag/CoreBundle/Resources/views/themes/baggy/Entry/entry.html.twig
- src/Wallabag/CoreBundle/Resources/views/themes/material/Entry/entry.html.twig
Showing the preview picture usually leads to showing a duplicate
image, and frequently leads to showing duplicate images directly
adjacent to each other.
before
Before:
After:
Fixes #1875
> Remove preview picture from single entry view page for #1875

- src/Wallabag/UserBundle/Resources/views/layout.html.twig
class and alt tags must be in the correct order for the android app to recognize the wallabag server
as per @msebald finding. 
installed it today and got the same login error. 
Fixes https://github.com/wallabag/android-app/issues/744
> Fix Android app login issue

- app/Resources/static/themes/material/css/cards.scss
- src/Wallabag/CoreBundle/Resources/views/themes/material/Entry/_card_list.html.twig
Fixes #3779 
This PR fixes missing placeholder and normalizes the size of thumbnails in the list view.
I'll push compiled prod assets after review.
> material: fix missing thumbnail on list view

- app/Resources/static/themes/material/css/cards.scss
Fixes #3780 
This PR changes the size of tag chips on the list view:
I'll push compiled prod assets after review.
> material: decrease size of tags on list view

- composer.json
I just released the 1.0.0
https://github.com/wallabag/guzzle-site-authenticator/releases/tag/1.0.0
We don't need the `@dev` anymore.
> No more dev for guzzle-site-authenticator

- src/Wallabag/ImportBundle/Consumer/AbstractConsumer.php
- src/Wallabag/ImportBundle/Import/AbstractImport.php
- src/Wallabag/ImportBundle/Import/BrowserImport.php
- src/Wallabag/ImportBundle/Import/ChromeImport.php
- src/Wallabag/ImportBundle/Import/FirefoxImport.php
- src/Wallabag/ImportBundle/Import/InstapaperImport.php
- src/Wallabag/ImportBundle/Import/PinboardImport.php
- src/Wallabag/ImportBundle/Import/PocketImport.php
- src/Wallabag/ImportBundle/Import/ReadabilityImport.php
- src/Wallabag/ImportBundle/Import/WallabagImport.php
We got some imports with a missing `url` field generating some errors while trying to retrieve an existing entry with that url (hello @Rurik19 :grimacing:).
Introducing the `validateEntry` allow us to dismiss a message when it doesn't have an url (or other missing stuff in the future)
> Validate imported entry to avoid error on import

- src/Wallabag/CoreBundle/Helper/EntriesExport.php
We replace the title used as the unique identifier of the epub file with a urn following the format:
```
urn:wallabag:{sha1("wallabagUrl:listOfEntryIdsSeparatedByComma")}
```
This format is repeatable: it always gives the same uid for the same list of entries.
Fixes #3811
> EntriesExport/epub: replace epub identifier with unique urn

- src/Wallabag/CoreBundle/Resources/views/themes/baggy/Entry/entries.html.twig
- src/Wallabag/CoreBundle/Resources/views/themes/material/Entry/entries.html.twig
Fixes #3832 #3790 
The conditions in which the JSON or CSV export button were displayed were inverted in the templates.
> Fix settings field inverted

- src/Wallabag/ApiBundle/Entity/Client.php
- src/Wallabag/ApiBundle/Repository/ClientRepository.php
- tests/Wallabag/ApiBundle/Controller/DeveloperControllerTest.php
If someone send a malformated client_id when trying to authenticate using the API we got a 500 if wallabag use postgres because the request send a string instead of an integer.
Fixes #3817
> Cast client id to avoid PG error

- src/Wallabag/CoreBundle/Controller/ExportController.php
- src/Wallabag/CoreBundle/Helper/EntriesExport.php
- src/Wallabag/CoreBundle/Resources/translations/messages.da.yml
- src/Wallabag/CoreBundle/Resources/translations/messages.de.yml
- src/Wallabag/CoreBundle/Resources/translations/messages.en.yml
- src/Wallabag/CoreBundle/Resources/translations/messages.es.yml
- src/Wallabag/CoreBundle/Resources/translations/messages.fa.yml
- src/Wallabag/CoreBundle/Resources/translations/messages.fr.yml
- src/Wallabag/CoreBundle/Resources/translations/messages.it.yml
- src/Wallabag/CoreBundle/Resources/translations/messages.oc.yml
- src/Wallabag/CoreBundle/Resources/translations/messages.pl.yml
- src/Wallabag/CoreBundle/Resources/translations/messages.pt.yml
- src/Wallabag/CoreBundle/Resources/translations/messages.ro.yml
- src/Wallabag/CoreBundle/Resources/translations/messages.ru.yml
- src/Wallabag/CoreBundle/Resources/translations/messages.th.yml
- src/Wallabag/CoreBundle/Resources/translations/messages.tr.yml
- tests/Wallabag/CoreBundle/Controller/ExportControllerTest.php
Fixes #3603 
Related to #2821 
Completes fix for #3811 
This PR:
- removes the TOC page inserted at the end of an epub export (#3603)
- fixes issue with filenames (_Title.html duplicates_)
- reverts c779373 and moves back phpepub and wallabag notes to the end of the book
- changes title and filename when the export is of type `tag_entries`, appending the related tag (_e.g. `Tag hello-world articles.epub`)
- replaces the "{method} authors" with "Various authors"
- adds metadata on the cover of each entry: reading time, publishers, date of creation and a link to the original article …
> Rework of EPUB/PDF exports

- app/config/security.yml
- src/Wallabag/ApiBundle/Controller/WallabagRestController.php
- tests/Wallabag/ApiBundle/Controller/WallabagRestControllerTest.php
Useful for api client which required some information.
We might add more inside them in the future.
The endpoint /api/version should be avoided now as it contains not so much information rather the version.
Fixes #3808
> Add a new endpoint to retrieve information from the wallabag instance

- composer.json
Fixes #3844 for wallabag 2.3.7.
Easiest. PR. Ever. 😉
> Update composer.json to add php-tidy (ext-tidy)

- src/Wallabag/CoreBundle/Resources/views/themes/baggy/Entry/entry.html.twig
- src/Wallabag/CoreBundle/Resources/views/themes/material/Entry/entry.html.twig
Instead of sending an email to the devs, it now creates an issue on GitHub using a zap from zapier.
> Add dedicated email for site config issue

- .travis.yml
- app/DoctrineMigrations/Version20190117131816.php
- composer.json
- phpstan.neon
- src/Wallabag/CoreBundle/Command/InstallCommand.php
- src/Wallabag/CoreBundle/Entity/SiteCredential.php
- src/Wallabag/CoreBundle/Helper/RuleBasedTagger.php
- tests/Wallabag/AnnotationBundle/Controller/AnnotationControllerTest.php
- tests/Wallabag/ApiBundle/Controller/EntryRestControllerTest.php
- tests/Wallabag/CoreBundle/Controller/ConfigControllerTest.php
- tests/Wallabag/CoreBundle/Controller/EntryControllerTest.php
- tests/Wallabag/CoreBundle/Controller/ExportControllerTest.php
- tests/Wallabag/CoreBundle/Controller/RssControllerTest.php
- tests/Wallabag/CoreBundle/Helper/RedirectTest.php
- tests/Wallabag/CoreBundle/ParamConverter/UsernameRssTokenConverterTest.php
- tests/Wallabag/ImportBundle/Consumer/AMQPEntryConsumerTest.php
- tests/Wallabag/ImportBundle/Consumer/RedisEntryConsumerTest.php
- tests/Wallabag/ImportBundle/Controller/ChromeControllerTest.php
- tests/Wallabag/ImportBundle/Controller/FirefoxControllerTest.php
- tests/Wallabag/ImportBundle/Controller/InstapaperControllerTest.php
- tests/Wallabag/ImportBundle/Controller/PinboardControllerTest.php
- tests/Wallabag/ImportBundle/Controller/ReadabilityControllerTest.php
- tests/Wallabag/ImportBundle/Controller/WallabagV1ControllerTest.php
- tests/Wallabag/ImportBundle/Controller/WallabagV2ControllerTest.php
- tests/Wallabag/UserBundle/Controller/ManageControllerTest.php
- tests/Wallabag/UserBundle/Mailer/AuthCodeMailerTest.php
- tests/Wallabag/UserBundle/Mailer/CountableMemorySpool.php
| Bug fix?      | kind of
The idea is to use it more and more and reach the higher level we could.
I fixed most of from the lowest level.
phpstan will run on travis on the same build as cs-fixer
- Fix error for level 0 & 1 (level 7 has 699 errors...)
- Add `updated_at` to site_credential (so the `timestamps()` method applies correctly)
> Enable PHPStan

- .travis.yml
- app/config/config.yml
Since https://github.com/doctrine/dbal/pull/2671 the bug with the database server version can be closed.
I've tried to install wallabag on PG 11.1 & MySQL 5.7 and it worked great.
Fixes #3739
> Removed hardcoded database version

- src/Wallabag/ApiBundle/Controller/EntryRestController.php
- src/Wallabag/ApiBundle/Controller/SearchRestController.php
- src/Wallabag/ApiBundle/Controller/WallabagRestController.php
- src/Wallabag/ApiBundle/Resources/config/routing_rest.yml
- tests/Wallabag/ApiBundle/Controller/SearchRestControllerTest.php
| Fixed tickets | #2611
I was hoping to find a search API for a separate project to add search support to the Firefox omnibox, but it turns out Wallabag doesn't have one - I'm not too familiar with Symfony, but I've taken a crack at it:
- Adds a new `search` key to `src/Wallabag/ApiBundle/Resources/config/routing_rest.yml`
- Reuses the `getBuilderForSearchByUser` method from the EntryRepository
- Supports, `term`, `page`, and `perPage` query parameters
- Some very basic tests
The test are a little limited, since it's basically a proxy for the existing search …
> Add a basic Search REST endpoint

- src/Wallabag/ImportBundle/Import/PocketImport.php
- tests/Wallabag/ImportBundle/Import/PocketImportTest.php
Would be nice to do a test for this given that a lot of it is already there, just need more assertions but haven't found the time yet so thought it would be good to at least get a fix out.
> Fix read & starred status in Pocket import

- src/Wallabag/UserBundle/Resources/views/TwoFactor/email_auth_code.html.twig
In 2 factor auth emails, the log image is broken:
This is because the img points to the non-existing `logo-other_themes.png`. Here is swapped for `logo-square.png`, but there are other options at https://github.com/wallabag/wallabag/tree/master/web/wallassets/themes/_global/img, including https://github.com/wallabag/wallabag/blob/master/web/wallassets/themes/_global/img/logo-w.png
> Fix broken 2 factor auth logo image

- src/Wallabag/ApiBundle/Form/Type/ClientType.php
- src/Wallabag/CoreBundle/Form/Type/EditEntryType.php
- src/Wallabag/CoreBundle/Form/Type/NewEntryType.php
Related to https://github.com/symfony/symfony/issues/29690
For an `UrlType` the `default_protocol` value is `http` which now result in converting the url input into a text input.
Forcing `default_protocol` to null will let the input type as url.
> Force default_protocol to generate an url input

- src/Wallabag/ApiBundle/Controller/EntryRestController.php
- tests/Wallabag/ApiBundle/Controller/EntryRestControllerTest.php
Fixes #3711
This PR fixes a test, the clone and add a new `expect` parameter to the `delete entry` call. When specifying `?expect=id` the API will return the id of the removed entry instead of returning the whole object.
By default, `expect` is set to `entry` which is the current behavior.
Fixes https://github.com/wallabag/android-app/issues/646
> Add support of expect parameter to change return object when deleting entry

- scripts/install.sh
- scripts/update.sh
Now both
```
./install prod --ignore-root-warning
./install --ignore-root-warning prod
```
will work
$1 was both used for the environment and the root flag
Fixes wallabag/wallabag#3884
> Allow optional --ignore-root-warning

- app/DoctrineMigrations/Version20190129120000.php
During `wallabag:install`, the `craue_config_setting` table is populated (see https://github.com/wallabag/wallabag/blob/master/src/Wallabag/CoreBundle/Command/InstallCommand.php#L280-L285) with some default entries that are needed for wallabag to function. On a shared hosting however, this command cannot be run so wallabag crashes because of the missing entries (with this error: https://github.com/wallabag/wallabag/issues/3662).
Only some of these entries were created by the migration scripts. This adds the missing entries as part of a migration, to allow shared hosting users to have a complete database. I took the entries from https://github.com/wallabag/wallabag/blob/master/app/config/wallabag.yml#L32-L164, except those that were already added by a previous migration.
I ran the tests …
> Add missing entries in craue_config_setting.

- src/Wallabag/CoreBundle/Helper/EntriesExport.php
This commit fixes an exception occurring when exporting as epub several
articles with the same title. The chapter filename is now derived from
title and url.
Fixes #3642
> epub: fix exception when articles have the same title

- src/Wallabag/CoreBundle/Helper/ContentProxy.php
Looks like sometimes (usually from import) the `html` key isn’t available.
> Fix PHP warning

- src/Wallabag/CoreBundle/DataFixtures/ORM/LoadSiteCredentialData.php
- src/Wallabag/CoreBundle/GuzzleSiteAuthenticator/GrabySiteConfigBuilder.php
- src/Wallabag/CoreBundle/Repository/SiteCredentialRepository.php
- src/Wallabag/CoreBundle/Resources/translations/messages.da.yml
- src/Wallabag/CoreBundle/Resources/translations/messages.de.yml
- src/Wallabag/CoreBundle/Resources/translations/messages.en.yml
- src/Wallabag/CoreBundle/Resources/translations/messages.es.yml
- src/Wallabag/CoreBundle/Resources/translations/messages.fa.yml
- src/Wallabag/CoreBundle/Resources/translations/messages.fr.yml
- src/Wallabag/CoreBundle/Resources/translations/messages.it.yml
- src/Wallabag/CoreBundle/Resources/translations/messages.oc.yml
- src/Wallabag/CoreBundle/Resources/translations/messages.pl.yml
- src/Wallabag/CoreBundle/Resources/translations/messages.pt.yml
- src/Wallabag/CoreBundle/Resources/translations/messages.ro.yml
- src/Wallabag/CoreBundle/Resources/translations/messages.th.yml
- tests/Wallabag/CoreBundle/Controller/EntryControllerTest.php
- tests/Wallabag/CoreBundle/GuzzleSiteAuthenticator/GrabySiteConfigBuilderTest.php
| New feature?  | kind of
| Documentation | maybe?
Fixes #3936
Add ability to match many domains for credentials  …
Instead of fetching one domain, we use the same method as in site config (to retrieve the matching file) and handle api.example.org, example.org, .org (yes the last one isn’t useful).
If one of these match, we got it and use it.
>  Add ability to match many domains for credentials

- app/Resources/static/themes/material/css/cards.scss
- app/Resources/static/themes/material/css/media_queries.scss
- src/Wallabag/CoreBundle/Resources/views/themes/material/Entry/Card/_content.html.twig
- src/Wallabag/CoreBundle/Resources/views/themes/material/Entry/_card_list.html.twig
Add reading time and creation date to rows of list view.
Refactor styles using a sass mixin.
New behavior in list view:
Fixes #3838
*Note:* updated compiled assets will be added after review.
> material: add metadata to list view

- .travis.yml
- composer.json
- src/Wallabag/CoreBundle/Helper/DownloadImages.php
- tests/Wallabag/CoreBundle/GuzzleSiteAuthenticator/GrabySiteConfigBuilderTest.php
- tests/Wallabag/CoreBundle/ParamConverter/UsernameFeedTokenConverterTest.php
- tests/Wallabag/UserBundle/EventListener/CreateConfigListenerTest.php
| New feature?  | kind of
| Documentation | not yet
If Imagick is available, GIF will be saved using it to keep animation.
Otherwise the previous method will be used and the animation won't be kept.
Fix https://github.com/wallabag/wallabag/issues/3505
- Installing Imagick on Travis to avoid phpstan to fail because it can't find the class
- Fixing CS from php-cs-fixer update
> Use Imagick to keep GIF animation

- src/Wallabag/CoreBundle/Resources/views/themes/common/Entry/share.html.twig
Essentially, same as commit 038fccd for single entry views. From that commit:
> Showing the preview picture usually leads to showing a duplicate
> image, and frequently leads to showing duplicate images directly
> adjacent to each other.
> Remove preview picture from share view page for #1875

- composer.json
Some issue appeared after the release of PHP 7.2.17 about Intl Memory Leak / infinite loop.
To fix it we should upgrade to Symfony 3.4 (which is done in wallabag 2.4) but for the 2.3 branch, we'll use a temporary fix for the Locale issue.
Fix #3926
> Fix Intl Locale issue

- src/Wallabag/ApiBundle/Controller/EntryRestController.php
- src/Wallabag/CoreBundle/Repository/EntryRepository.php
- tests/Wallabag/ApiBundle/Controller/EntryRestControllerTest.php
| New feature?  | _sort of_
| Deprecations? | _maybe?_
`detail=metadata` will nullify the `content` field of entries in order to
make smaller responses.
`detail=full` keeps the former behavior, it sends the content of entries.
It's the default, for backward compatibility.
Fixes #2817
With this change, calls to `/api/entries?detail=metadata` will return `Entry` objects with `content: null`. Are you ok with that @wallabag/core?
> api/entries: add parameter detail to exclude or include content in response

- src/Wallabag/ImportBundle/Import/InstapaperImport.php
Instapaper doesn't export the creation date of the article.
When exporting them, the newest is the first in the list.
So if we want to keep the order we need to import the first item at the end, which means, reverse the entries array.
> Fix Instapaper import date order

- src/Wallabag/CoreBundle/Helper/ContentProxy.php
- src/Wallabag/CoreBundle/Helper/DownloadImages.php
- tests/Wallabag/CoreBundle/Helper/ContentProxyTest.php
- tests/Wallabag/ImportBundle/Controller/WallabagV1ControllerTest.php
I'd like to have a preview picture for every link I add to my wallabag. Currently only pictures set as `og:image` are used for the preview picture (unless the link is an image).
This MR parses the content to find the first picture in the content and use it as a preview (unless there already is a preview picture).
I'd like that to be added to the core but maybe you'd prefer if it required an activation from the user (a new boolean)? That's why I did not edit the tests that check there are no preview pictures for some links: I am waiting for your feedback.
> Preview picture: use the 1st pic retrieved if no og:image set

- src/Wallabag/ApiBundle/Controller/EntryRestController.php
- src/Wallabag/CoreBundle/Command/GenerateUrlHashesCommand.php
- src/Wallabag/CoreBundle/Entity/Entry.php
- src/Wallabag/CoreBundle/Helper/UrlHasher.php
- src/Wallabag/CoreBundle/Repository/EntryRepository.php
Fixed tickets |#3919
Simplify the logic from #3158 by hashing all the urls from the request,
and only doing a search by hash. This allows to get performance benefits
from the new indexed hash column even when using older clients that do
not hash the URL in the request.
> Always hash exists url

- .gitignore
- RELEASE_PROCESS.md
- app/config/wallabag.yml
- composer.lock
- scripts/release.sh
We initially ignored the `composer.lock` because it generated a lock of rebase on PR when someone updated it and the master updated it too.
Now we have less contributions (sadly) so I think we won't run against that problem.
Also, it'll solve issue about people cloning the master and got angry because composer eat all the available memory to determine packages to install.
It'll also be much easier to make release (the release process file might not be up to date on how we should handle that change, I think I'll update it on the next release)
Scrutinizer & Travis will be faster too.
> Keep composer.lock

- composer.json
- composer.lock
- src/Wallabag/CoreBundle/Helper/DownloadImages.php
It was only used to make an absolute url when downloading images.
The deps is still there (in the `composer.lock`) because Graby use it (not for absolute but for encoding) : https://github.com/j0k3r/graby/blob/84a698f0aba5bc24343741d075d3760a88d90e17/src/Graby.php#L976
Fix https://github.com/wallabag/wallabag/issues/3540
> Drop SimplePie

- app/DoctrineMigrations/Version20190511165128.php
- src/Wallabag/CoreBundle/Entity/Tag.php
- tests/Wallabag/CoreBundle/Controller/TagControllerTest.php
`utf8mb4_unicode_ci` considers that 'caché' is equal to 'cache' which
can lead to attaching incorrect tags to entries. This issue is due to
some unicode normalization done by MySQL.
`utf8mb4_bin` makes no unicode normalization, letting wallabag to consider
'cache' and 'caché' as two different tags.
Fixes #3302
> mysql: change collation of tag label

- scripts/require.sh
- scripts/update.sh
If that folder doesn’t exist, it means the udpate script won’t be able to run because it uses git to retrieve the update.
Tests will fail because of it needs https://github.com/wallabag/wallabag/pull/4008 to be merged.
Related https://github.com/wallabag/wallabag/issues/4007
> Check if .git directory exist before making the update

- app/DoctrineMigrations/Version20190510141130.php
- tests/Wallabag/CoreBundle/Controller/EntryControllerTest.php
Looks like we missed one `wallabag_user` in migration.
It can work for most people but if someone use a different prefix, it'll break.
> Fix migration with prefix table name

- docker/php/Dockerfile
It's required in the 2.4 version
> Add missing tidy extension on Docker

- .gitignore
- src/Wallabag/ApiBundle/Controller/TaggingRuleRestController.php
- src/Wallabag/ApiBundle/Resources/config/routing_rest.yml
- src/Wallabag/CoreBundle/Controller/ConfigController.php
- src/Wallabag/CoreBundle/Entity/TaggingRule.php
- src/Wallabag/CoreBundle/Form/Type/TaggingRuleImportType.php
- src/Wallabag/CoreBundle/Resources/translations/messages.da.yml
- src/Wallabag/CoreBundle/Resources/translations/messages.de.yml
- src/Wallabag/CoreBundle/Resources/translations/messages.en.yml
- src/Wallabag/CoreBundle/Resources/translations/messages.es.yml
- src/Wallabag/CoreBundle/Resources/translations/messages.fa.yml
- src/Wallabag/CoreBundle/Resources/translations/messages.fr.yml
- src/Wallabag/CoreBundle/Resources/translations/messages.it.yml
- src/Wallabag/CoreBundle/Resources/translations/messages.oc.yml
- src/Wallabag/CoreBundle/Resources/translations/messages.pl.yml
- src/Wallabag/CoreBundle/Resources/translations/messages.pt.yml
- src/Wallabag/CoreBundle/Resources/translations/messages.ro.yml
- src/Wallabag/CoreBundle/Resources/translations/messages.ru.yml
- src/Wallabag/CoreBundle/Resources/translations/messages.th.yml
- src/Wallabag/CoreBundle/Resources/translations/messages.tr.yml
- src/Wallabag/CoreBundle/Resources/views/themes/baggy/Config/index.html.twig
- src/Wallabag/CoreBundle/Resources/views/themes/material/Config/index.html.twig
- tests/Wallabag/ApiBundle/Controller/TaggingRuleRestControllerTest.php
- tests/Wallabag/CoreBundle/Controller/ConfigControllerTest.php
- tests/Wallabag/CoreBundle/fixtures/tagging_rules_admin.json
| Tests pass?   | dunno
Fix #2284
The API will be accessible at `/api/taggingrule/export` it'll return the exported rules as a json file.
> Add ability to import/export tagging rules

- .travis.yml
- composer.lock
- phpstan.neon
It should now be PHPUnit 7.4.
Update PHPStan configuration accordingly.
Also, enable `inferPrivatePropertyTypeFromConstructor` for better phpDoc support in constructors.
> Remove PHPUnit lock

- composer.lock
- src/Wallabag/CoreBundle/Helper/FileCookieJar.php
- src/Wallabag/CoreBundle/Resources/config/services.yml
It happens sometimes on wallabag.it, the json inside the cookie is badly saved and the json isn't valid. It generates an exception and avoid people to use the api and import contents.
To fix that, we use a dedicated `FileCookieJar`, which extends the default one from Guzzle to fix these issues:
- line 31: add the `LOCK_EX`
- line 56/61: add a try catch when parsing the json from the cookie
Also updated deps
> Use a custom cookiejar to avoid error when the cookie is badly saved

- app/DoctrineMigrations/Version20190808124957.php
- app/config/config.yml
- composer.json
- composer.lock
- src/Wallabag/CoreBundle/Command/InstallCommand.php
- src/Wallabag/CoreBundle/DataFixtures/InternalSettingFixtures.php
- src/Wallabag/CoreBundle/Entity/Config.php
- src/Wallabag/CoreBundle/Entity/InternalSetting.php
In fact it's not _just_ a rename.
We are now able to use [our own entity](https://github.com/craue/CraueConfigBundle#using-a-custom-entity-for-settings) with the CraueConfigBundle which allow us to enforce a custom length on string field and avoid error with utf8mb4 on MySQL.
To fix that issue before we were in need to fork CraueConfigBundle to [hard apply these length changes](https://github.com/wallabag/CraueConfigBundle/commit/46cfd37febc51d62e84e4c64fdb166e7495ca172).
The recent 2.3.0 release fix that issue (see https://github.com/craue/CraueConfigBundle/pull/50). That's why we are in need to rename the table (getting rid of the bundle name from it)
Also updating deps:
- Updating symfony/polyfill-mbstring (v1.11.0 => v1.12.0)
- Updating symfony/polyfill-ctype (v1.11.0 => v1.12.0)
- …
> Rename internal settings table

- GNUmakefile
Also, run `npm install` before building.
Signed-off-by: Olivier Mehani <shtrom@ssji.net>
| CHANGELOG.md  | Not a thing anymore :grimacing: 
This allows to build the frontend code with `make dev`.
> Make dev depend on build

- app/config/wallabag.yml
- src/Wallabag/CoreBundle/DependencyInjection/Configuration.php
- tests/Wallabag/CoreBundle/Controller/ConfigControllerTest.php
- tests/Wallabag/CoreBundle/Helper/RedirectTest.php
- tests/Wallabag/UserBundle/EventListener/CreateConfigListenerTest.php
When you install wallabag from scratch, the default value for `reading_speed` was still `1.0`, but it has changed in #4053.
> Fixed default value for reading speed

- docker/php/Dockerfile
In order to run tests, increase the php memory limit of PHP docker from 128M to 512M
> Increase php memory limit PHP Docker

- src/Wallabag/CoreBundle/Controller/EntryController.php
- src/Wallabag/CoreBundle/Resources/views/themes/baggy/Entry/entries.html.twig
- src/Wallabag/CoreBundle/Resources/views/themes/material/Entry/entries.html.twig
Fix #3804
Add untagged list link to filter menu. Doesn’t display if on http://your-wallabag/untagged/list or if there is no untagged entry.
(I use dark reader extension on Firefox)
> 💄 Add untagged list link to filter menu

- scripts/dev.sh
As I develop in a virtual machine, I need to make the built-in server listen to 0.0.0.0 instead of 127.0.0.1. I added the `HOST` environment variable to be able to do so:
```
export HOST=0.0.0.0:8000
make dev
```
As it’s quite painful to answer to questions about wiping the database and creating a new superuser each time I run `make dev`, I added a `SKIP_WALLABAG_INITIALIZATION` environment variable to skip the `wallabag:install`.
> Add environment variables to control scripts/dev.sh behavior

- .gitignore
- GNUmakefile
- src/Wallabag/CoreBundle/Resources/views/base.html.twig
Should fix #4060
- add a setting called `custom_css` in `app/config/parameters.yml`, available for twig
- when set to true, Wallabag calls http://your-wallabag/custom.css on every page
- put a file named `custom.css` in `web/` directory: it will be used by Wallabag.
The green sidebar of the screenshot is created by `custom.css`.
> ✨ Allow custom styles system wide

- src/Wallabag/CoreBundle/Resources/views/themes/common/Developer/howto_app.html.twig
Resolves wallabag/wallabagger#107.
Currently the developer documentation uses the defunct http://v2.wallabag.org URL which can be confusing to someone configuring their first API client with wallabag.it.
This PR replaces that URL with the current https://app.wallabag.it. The instance running at wallabag.it might want to put this somewhere even more prominent, but making this change should help out with those (like me) who this confused when starting out with wallabag.it.
> Change API URL used in dev docs to app.wallabag.it

- GNUmakefile
This command should fail before calling other commands (which will fail to because the environment is wrong):
```bash
ENV=toto make install
```
Fix #4246
~~If anyone has a better idea on how to achieve that without multiple `if` condition, it'll be great!~~
> Ensure ENV is well defined when using make

- src/Wallabag/CoreBundle/Helper/FileCookieJar.php
As of latest Guzzle release, it's fixed so we can removed that code.
See https://github.com/guzzle/guzzle/pull/2335
> Cleanup cookie jar

- src/Wallabag/ApiBundle/Controller/EntryRestController.php
Fixes #4291
The event was triggered after the entry deletion, so wallabag had no way to find entry data.
> Fixed bug when we delete entry via API

- src/Wallabag/CoreBundle/Helper/EntriesExport.php
- src/Wallabag/CoreBundle/Resources/translations/messages.da.yml
- src/Wallabag/CoreBundle/Resources/translations/messages.de.yml
- src/Wallabag/CoreBundle/Resources/translations/messages.en.yml
- src/Wallabag/CoreBundle/Resources/translations/messages.es.yml
- src/Wallabag/CoreBundle/Resources/translations/messages.fa.yml
- src/Wallabag/CoreBundle/Resources/translations/messages.fr.yml
- src/Wallabag/CoreBundle/Resources/translations/messages.it.yml
- src/Wallabag/CoreBundle/Resources/translations/messages.ja.yml
- src/Wallabag/CoreBundle/Resources/translations/messages.oc.yml
- src/Wallabag/CoreBundle/Resources/translations/messages.pl.yml
- src/Wallabag/CoreBundle/Resources/translations/messages.pt.yml
- src/Wallabag/CoreBundle/Resources/translations/messages.ro.yml
- src/Wallabag/CoreBundle/Resources/translations/messages.ru.yml
- src/Wallabag/CoreBundle/Resources/translations/messages.th.yml
- src/Wallabag/CoreBundle/Resources/translations/messages.tr.yml
- src/Wallabag/CoreBundle/Resources/translations/messages.zh.yml
I think that publication date is a good improvement on ePub export. (see #2821)
> Added publication date on epub export

- app/config/config.yml
- app/config/parameters.yml.dist
It'll allow admin of a wallabag instance to define its own lifetime for the refresh token and the access token.
The default value are the recommended one from the wallabag team.
| Documentation | https://github.com/wallabag/doc/pull/121
Fix #4292
> Add ability to define lifetime token for the API

- src/Wallabag/CoreBundle/Controller/ConfigController.php
- src/Wallabag/CoreBundle/Resources/translations/messages.da.yml
- src/Wallabag/CoreBundle/Resources/translations/messages.de.yml
- src/Wallabag/CoreBundle/Resources/translations/messages.en.yml
- src/Wallabag/CoreBundle/Resources/translations/messages.es.yml
- src/Wallabag/CoreBundle/Resources/translations/messages.fa.yml
- src/Wallabag/CoreBundle/Resources/translations/messages.fr.yml
- src/Wallabag/CoreBundle/Resources/translations/messages.it.yml
- src/Wallabag/CoreBundle/Resources/translations/messages.ja.yml
- src/Wallabag/CoreBundle/Resources/translations/messages.oc.yml
- src/Wallabag/CoreBundle/Resources/translations/messages.pl.yml
- src/Wallabag/CoreBundle/Resources/translations/messages.pt.yml
- src/Wallabag/CoreBundle/Resources/translations/messages.ro.yml
- src/Wallabag/CoreBundle/Resources/translations/messages.ru.yml
- src/Wallabag/CoreBundle/Resources/translations/messages.th.yml
- src/Wallabag/CoreBundle/Resources/translations/messages.tr.yml
- src/Wallabag/CoreBundle/Resources/translations/messages.zh.yml
- src/Wallabag/CoreBundle/Resources/views/themes/baggy/Config/index.html.twig
- src/Wallabag/CoreBundle/Resources/views/themes/material/Config/index.html.twig
- tests/Wallabag/CoreBundle/Controller/ConfigControllerTest.php
Fixes #4217 
Today we don't ask user password because I think it should be a global feature: for each sensitive action (delete data, delete account, disable 2fa, etc.), we should ask user password.
> Added a button to disable 2FA when enabled

- src/Wallabag/CoreBundle/Controller/TagController.php
- tests/Wallabag/CoreBundle/Controller/TagControllerTest.php
The fix relies on a workaround available on TagsAssigner, see the
AssignTagsToEntry() signature for detail.
I replaced the findOneByLabel in the corresponding test to assert that
there is no duplicate.
Fixes #4216
> TagController: fix duplicated tags when renaming them

- .travis.yml
- composer.json
- composer.lock
- src/Wallabag/ImportBundle/Controller/PocketController.php
| Bug fix?      | ~
This PR replaces our fork of TCPDF with the original version and fixes some issues seen with PHP 7.4.
Note: I currently use the `master` version of Graby to run the tests, we may need to release a new version to include the change for the TCPDF dependency. (cc @j0k3r)
> Replace wallabag's fork of tcpdf with the original one, PHP 7.4 support

- README.md
Rewamp the readme logo & add a short text explaining how wallabag is translated now.
Also add the weblate badge.
> wallabag is now translated using Weblate

- src/Wallabag/CoreBundle/Resources/views/themes/material/layout.html.twig
The commit d9a68f6ced3f510e5a52d5f857ca9c19aed8924b introduced a change
in the way export and filter buttons are showed. It ended in hiding
them on the tag-related pages, preventing users to export entries for a
given tag.
> material: restore missing export and filter buttons on tags view

- app/Resources/static/themes/material/css/cards.scss
- src/Wallabag/CoreBundle/Resources/views/themes/material/Entry/_card_full_image.html.twig
- src/Wallabag/CoreBundle/Resources/views/themes/material/Entry/_card_list.html.twig
- src/Wallabag/CoreBundle/Resources/views/themes/material/Entry/_card_preview.html.twig
- src/Wallabag/CoreBundle/Resources/views/themes/material/Entry/entries.html.twig
| New feature?  | ~
Fixes #4466
This change is only on the `tag_entries` view, setting opacity of archived entries to 0.45:
> Reduce opacity of archived entries on tag view

- scripts/require.sh
The current link 404s and the link to https://doc.wallabag.org/en/admin/installation/installation.html does not give enough context about `composer` so I've linked to the requirements page instead.
> Fix link to composer installation requirements

- composer.lock
- Updating doctrine/dbal (2.10.3 => 2.10.4)
- Updating laminas/laminas-zendframework-bridge (1.1.0 => 1.1.1)
- Updating guzzlehttp/psr7 (1.6.1 => 1.7.0)
- Updating composer/semver (1.5.1 => 1.7.1)
- Updating j0k3r/graby-site-config (1.0.113 => 1.0.116)
- Updating php-http/discovery (1.10.0 => 1.12.0)
- Updating masterminds/html5 (2.7.3 => 2.7.4)
- Updating clue/stream-filter (v1.4.1 => v1.5.0)
- Updating jms/serializer (3.8.0 => 3.9.0)
- Updating phpseclib/phpseclib (2.0.28 => 2.0.29)
- Updating php-amqplib/php-amqplib (v2.11.3 => v2.12.1)
- Updating thecodingmachine/safe (v1.2.0 => v1.3)
- Updating symfony/http-client (v5.1.5 => v5.1.7)
- Updating symfony/mime (v5.1.3 => v5.1.7)
- Updating gedmo/doctrine-extensions (v2.4.41 => v2.4.42)
- Updating nikic/php-parser (v4.9.1 => v4.10.2)
- …
> Update PHP deps

- src/Wallabag/CoreBundle/Resources/views/themes/material/Entry/new_form.html.twig
- src/Wallabag/CoreBundle/Resources/views/themes/material/Entry/search_form.html.twig
This reverts commit 07dab0dbc9b86171da78572cc2903f3fb90c721d.
Hi don't get the initial commit. Maybe something changed on materializecss or I could be wrong but right now, we have to choose between the class and the tag content.
Before
After
> Fix duplicated icons

- RELEASE_PROCESS.md
- app/config/wallabag.yml
Small changes in the release process, the `composer.lock` is now inside the repo so we don't need to create a dedicated PR for it.
And jump to 2.4.1-dev 🎉
> Update release process and introduce 2.4.1-dev

- app/DoctrineMigrations/Version20190510141130.php
| Tests pass?   | ~
Fixes #4826
In an unspecified case the schema state was not consistent with the
expected migration plans. This fix ignores two statements by checking
if a foreign key is here or not.
This issue may have been caused by a rewrite of an old migration,
probably through 4acbeb93717612f361627f7d4b946fcb4477823c
I've also checked several migration paths with SQLite and PostgreSQL and did not encounter further issues.
> migrations: fix mysql migration for an edge case

- phpstan.neon
- src/Wallabag/CoreBundle/Command/CleanDownloadedImagesCommand.php
- src/Wallabag/CoreBundle/Helper/DownloadImages.php
| Bug fix?      | kind of
| New feature?  | kind of
Fixes #4827
There were a bug in versions prior to 2.4.0 where images weren't properly removed (mostly when coming from the API).
With that command, we'll be able to remove images which aren't associated to any entries.
Like other command you can pass a username to only clean one user.
> Add a command to clean downloaded images

- src/Wallabag/CoreBundle/Resources/views/themes/material/Entry/_card_full_image.html.twig
- src/Wallabag/CoreBundle/Resources/views/themes/material/Entry/_card_preview.html.twig
- src/Wallabag/CoreBundle/Resources/views/themes/material/Entry/_tags.html.twig
This PR is a "hidden" improvement as it does not change the way elements are actually shown.
However, making the `<li>` elements for tags consistent with the tag page will help people doing fun things with custom css (_blog post incoming_).
> views: add title to tag li elements, for consistency

- .github/workflows/assets.yml
- .github/workflows/coding-standards.yml
- .github/workflows/continuous-integration.yml
- .github/workflows/translations.yml
Since I created the 2.5.0 branch, GA on PR targeting that branch aren't triggered. This should fix this.
> Allow GitHub Actions to run on 2.* branches

- src/Wallabag/CoreBundle/Repository/EntryRepository.php
My query was buggy: we also need to find URL where hashedUrl is null and where url is not null (I had this case on wallabag.it)
> Fixed query to fetch URL to hash

- app/DoctrineMigrations/Version20201223222955.php
- src/Wallabag/CoreBundle/Controller/FeedController.php
- src/Wallabag/CoreBundle/Entity/Config.php
- src/Wallabag/CoreBundle/Form/Type/FeedType.php
- src/Wallabag/CoreBundle/Resources/translations/messages.en.yml
- src/Wallabag/CoreBundle/Resources/translations/messages.fr.yml
- src/Wallabag/CoreBundle/Resources/views/themes/common/Entry/entries.xml.twig
- src/Wallabag/CoreBundle/Resources/views/themes/material/Config/index.html.twig
- tests/Wallabag/CoreBundle/Controller/FeedControllerTest.php
When set to true, ATOM feed will return article source url instead of Wallabag Uri
Fix #4871
> Add a new config "use_source" to handle new ATOM format

- src/Wallabag/CoreBundle/Resources/views/themes/baggy/Config/index.html.twig
- src/Wallabag/CoreBundle/Resources/views/themes/material/Config/index.html.twig
| Bug fix?      | **yes**/no
| New feature?  | yes/**no**
| BC breaks?    | yes/**no**
| Deprecations? | yes/**no**
| Tests pass?   | **yes**/no
| Documentation | yes/**no**
| Translation   | yes/**no**
| CHANGELOG.md  | yes/**no**
On the configuration section there is a link to `myreadspeed.com`, a website which is no longer available (see craigmayhew/myreadspeed@9e7786c). This PR changes this link for one to the repo where it is located.
I am not sure whether this qualifies as a bug fix or a documentation fix, I marked it as the former.
> Fix myreadspeed links

- CHANGELOG.md
- app/config/wallabag.yml
- composer.lock
Proposal for the release note:
- A lot of bugs related to the dark theme were fixed
- A year old bug about the auto tagging system which created duplicated tags
- A lot of translations update, thanks to [translators](https://hosted.weblate.org/projects/wallabag/) !
- The link to calculate the reading speed was updated because the previous was dead, you can now use: https://wallabag.github.io/myreadspeed/
- 60+ siteconfig [were updated](https://github.com/j0k3r/graby-site-config/compare/1.0.122...1.0.129)
To update your instance, [just run `make update`.](https://doc.wallabag.org/en/admin/upgrade.html#upgrading-from-23x-to-23y)
_🤝  A little reminder that you can support our work on wallabag by sponsoring us on [Liberapay](https://liberapay.com/wallabag) or subscribe on …
> Prepare 2.4.2 release

- .github/dependabot.yml
I don't see value in checking for dependency updates on a daily basis as it makes quite a lot of noise in PR management.
However security updates don't respect the schedule so we will still receive security bumps as soon as they appear.
> dependabot: change schedule to check updates once a month

- src/Wallabag/ApiBundle/Controller/EntryRestController.php
- src/Wallabag/CoreBundle/Repository/EntryRepository.php
I've noticed that the endpoint `/api/entries/exists` used by the "Sweep articles" feature on the Android app failed almost all the time on my instance.
After checking the corresponding method I found that `EntryRestController::getEntriesExistsAction()` could be improved.
Here is the former way the method worked:
```
for id in [list of ids]
get full entry by id
if null
get full entry by given id
return array of ids or array of hashes
```
With this behavior on my instance I could expect up to 13k SQL requests when sweeping articles from the Android app. Morever the …
> Improve performance of REST exists call

- src/Wallabag/CoreBundle/Resources/views/themes/common/Entry/entries.xml.twig
According to the ATOM spec link elements must have a href:
https://validator.w3.org/feed/docs/atom.html
Also most feed readers (TinyTiny, Feedly, Thunderbird) prefer link elements in
this order:
- plain
- with attribute rel=alternate
- with attribute rel=via
As the content is work of the entry author, link to it by default. Not to the
wallabag instance entry.
This also makes it possible to share links with people who don't have access to
the wallabag instance via the RSS feed.
> Make RSS feed entry links valid and accessible

- src/Wallabag/CoreBundle/Repository/EntryRepository.php
When we are on `https://mywallabag/`, we are on the `homepage` current page, which is the unread view. This page needs to react as the unread page (`https://mywallabag/unread/list`).
This issue fixes a bug when we research articles. The search was done on all articles: it needs to be done on unread articles only.
> Fixed search on homepage

- src/Wallabag/CoreBundle/Resources/views/themes/material/Entry/_card_full_image.html.twig
- src/Wallabag/CoreBundle/Resources/views/themes/material/Entry/_card_list.html.twig
- src/Wallabag/CoreBundle/Resources/views/themes/material/Entry/_card_preview.html.twig
- src/Wallabag/CoreBundle/Resources/views/themes/material/Entry/entries.html.twig
Fixes #869
The feature was already implemented, but only in tag view. Now, we have it for all the routes where it's needed.
> Show when articles is read

- src/Wallabag/CoreBundle/Resources/views/themes/material/Entry/entry.html.twig
Should fix #5112. 
The random research will be done on all the articles. Because we don't know the current context: if we are on "starred" articles, we click on the random buttom, we have a random article inside the favorite ones. But, when we are on the article view, we don't know where we were before.
> Added random button on article view

- .github/workflows/coding-standards.yml
- .github/workflows/continuous-integration.yml
- .github/workflows/translations.yml
- phpunit.xml.dist
- src/Wallabag/CoreBundle/Doctrine/WallabagMigration.php
- src/Wallabag/CoreBundle/Entity/Entry.php
- tests/Wallabag/CoreBundle/Controller/EntryControllerTest.php
- tests/Wallabag/CoreBundle/Controller/TagControllerTest.php
- tests/Wallabag/ImportBundle/Controller/ElcuratorControllerTest.php
- tests/Wallabag/ImportBundle/Controller/InstapaperControllerTest.php
- tests/Wallabag/ImportBundle/Controller/PinboardControllerTest.php
- tests/Wallabag/ImportBundle/Controller/ReadabilityControllerTest.php
- tests/Wallabag/ImportBundle/Controller/WallabagV1ControllerTest.php
- tests/Wallabag/ImportBundle/Controller/WallabagV2ControllerTest.php
- tests/Wallabag/UserBundle/Controller/ManageControllerTest.php
Add `isTransactional` to `WallabagMigration` because PHP 8 behave differently with PDO transaction.
This is a workaround because we can't upgrade Doctrine Migration for now (upper versions have the fix, see https://github.com/doctrine/DoctrineMigrationsBundle/issues/393).
Fix https://github.com/wallabag/wallabag/issues/4987
- Build is now using Composer v2 (instead of v1)
- All actions have been updated to latest version
- Fix bug in PHP 8 were `$entry->getTags()` can't be properly used as a _traversable_ by `assertContains` during tests. Added a custom method `Entry::getTagsLabel()` which return a flatted tag array with only label
- Replace `assertNotRegExp` by `assertDoesNotMatchRegularExpression` because it was deprecated
> Add build test on PHP 8.0 & 8.1

- composer.json
- src/Wallabag/CoreBundle/Helper/DownloadImages.php
- tests/Wallabag/CoreBundle/Helper/DownloadImagesTest.php
Fix https://github.com/wallabag/wallabag/issues/5464
Read https://github.com/wallabag/wallabag/issues/5464#issuecomment-1028873406 for a better explanation.
> Avoid overlapping images when downloading them

- src/Wallabag/CoreBundle/Command/TagAllCommand.php
- src/Wallabag/CoreBundle/DataFixtures/ConfigFixtures.php
- src/Wallabag/CoreBundle/DataFixtures/TaggingRuleFixtures.php
- src/Wallabag/CoreBundle/Helper/RuleBasedTagger.php
- tests/Wallabag/CoreBundle/Controller/EntryControllerTest.php
- tests/Wallabag/CoreBundle/Helper/RuleBasedTaggerTest.php
By default, we assume the reading speed is 200 word per minute (WPM) when we save an entry.
User can change that value in the config and the rendering is properly performed with the user reading speed.
BUT, when the matching rule is applied, it uses the default reading time defined in the entry without applying the custom reading speed of the user.
This should fix that bug.
Also update the `wallabag:tag:all` to fix the bug when tagging all entries.
Fix https://github.com/wallabag/wallabag/issues/4935
> Fix tagging rule match when user has a custom reading speed

- app/config/wallabag.yml
Should close #5649. 
The greek translation was already there, just need to enable it in configuration.
> Enabled greek translation

- src/Wallabag/CoreBundle/Controller/FeedController.php
- src/Wallabag/CoreBundle/Repository/EntryRepository.php
- src/Wallabag/CoreBundle/Resources/views/themes/common/Entry/entries.xml.twig
- tests/Wallabag/CoreBundle/Controller/FeedControllerTest.php
There is now an option to sort the feed entires by updated_at, on the
controler : a sort querystring argument that accepts either "created"
or "updated".
Fixs #5658
> Add an option to sort the feed entries by `updated_at`

- composer.json
- src/Wallabag/CoreBundle/Helper/ContentProxy.php
- src/Wallabag/CoreBundle/Helper/EntriesExport.php
- tests/Wallabag/CoreBundle/Controller/ExportControllerTest.php
- var/SymfonyRequirements.php
> Replace `iconv()` calls with Transliterator

- docker/php/Dockerfile
| Bug fix?      | ye
Because Composer 2.3 isn't compatible with wallabag #5708.
> Fix composer version in docker dev configuration

- .github/workflows/assets.yml
- .github/workflows/coding-standards.yml
- .github/workflows/continuous-integration.yml
- .github/workflows/translations.yml
- app/config/tests/parameters_test.mysql.yml
The error on PHP 7.2 & 7.3 is:
> PDO::__construct(): The server requested authentication method unknown to the client [caching_sha2_password]
See:
- https://stackoverflow.com/q/53066962/569101
- https://stackoverflow.com/q/52364415/569101
- https://stackoverflow.com/q/51489616/569101
- https://stackoverflow.com/q/50026939/569101
- https://github.com/phpmyadmin/phpmyadmin/commit/1ae14b59a40ff5d8b62b50f9c1172dbea0e61b1f
Also upgrade `actions/checkout` to v3
> CI workaround for PHP < 7.4 & MySQL 8

- .github/workflows/assets.yml
- .github/workflows/coding-standards.yml
- .github/workflows/translations.yml
- Included permissions for the action. https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
[Keeping your GitHub Actions and workflows secure Part 1: Preventing pwn requests](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)
Restrict the GitHub token permissions only to the required ones; this way, even if the attackers will succeed in compromising your workflow, they won’t be able to do much.
Signed-off-by: naveensrinivasan <172697+naveensrinivasan@users.noreply.github.com>
> Set permissions for GitHub actions

- src/Wallabag/CoreBundle/Controller/ConfigController.php
- src/Wallabag/CoreBundle/Form/Type/ConfigType.php
- src/Wallabag/CoreBundle/Resources/views/themes/baggy/layout.html.twig
- a big message will be displayed to user using the Baggy theme
- switching from Material to Baggy is no more allowed in config (it'll be forced to material), here is the message when you selected the Baggy theme:
- the theme label in the config for Baggy is now _Baggy (DEPRECATED)_
See https://github.com/wallabag/wallabag/issues/3460
Do we need to bother translating the warning message about the forced theme? That message will be removed in 2.6.0 anyway.
> Deprecated Baggy

- composer.lock
This upgrades the PHP dependencies before working on removing deprecations, so we have an up to date list of deprecations.
Would be great if it can be part of 2.5.0
Deprecations [on master with PHP 8.0](https://github.com/wallabag/wallabag/runs/6273696005?check_suite_focus=true#step:12:130):
```
Remaining direct deprecation notices (1423)
Remaining indirect deprecation notices (5054)
Other deprecation notices (49)
```
After the upgrade, still on PHP 8.0 (current version used in Docker):
```
Remaining direct deprecation notices (1423)
Remaining indirect …
```
> Upgrade PHP dependencies

- src/Wallabag/ApiBundle/Controller/ConfigRestController.php
- src/Wallabag/ApiBundle/Resources/config/routing_rest.yml
- src/Wallabag/CoreBundle/DataFixtures/ConfigFixtures.php
- src/Wallabag/CoreBundle/Entity/Config.php
- tests/Wallabag/ApiBundle/Controller/ConfigRestControllerTest.php
Added a new API endpoint, to get user configuration (ping @bourvill).  
Maybe one day, we can improve this endpoint (to update configuration, etc). 
~~One issue with this new feature: I don't want to get the user entries in the json response. I need to fix this.~~
> Add new endpoint for API: config

- docker/php/Dockerfile
This ensure that it's possible to run tests with the Docker setup, so that Redis tests are executed, without the need of installing Redis on local machine.
There were an issue with a missing GD support for WebP that is now fixed
Bonus change is the update of the Composer version used in Docker.
Also, this downgrades the PHP version of the Docker image to be as near as possible to the lowest supported one (7.2).
I managed locally to have tests running and green on PHP 7.2, but there is an issue with deprecation report because of a bug in PHP < 7.3.16 (see [the …
> Fix PHP Docker image

- .github/CONTRIBUTING.md
- .github/workflows/continuous-integration.yml
- RELEASE_PROCESS.md
- composer.json
- composer.lock
closes #5776
This also reduces indirect deprecations from [367](https://github.com/wallabag/wallabag/runs/6414847405?check_suite_focus=true#step:12:156) to [340](https://github.com/wallabag/wallabag/runs/6415152661?check_suite_focus=true#step:10:156)
Dependencies update details:
| Production Changes                   | From   | To     | Compare                                                                              |
|--------------------------------------|--------|--------|---------------------------------------------------------------------------------- …
> Drop PHP prior to 7.4

- .github/workflows/coding-standards.yml
- .github/workflows/continuous-integration.yml
- .github/workflows/translations.yml
- composer.json
- composer.lock
- docker/php/Dockerfile
Composer was limited to 2.2 in #5708 because of SensioDistributionBundle. Now that #5761 removes it, we can go back to use latest Composer version :)
> Back to latest composer version

- .github/workflows/upload-release-package.yml
- RELEASE_PROCESS.md
- scripts/release.sh
And then upload it to the created release.
One less step during the release process 💪
We are using that GitHub Actions: https://github.com/shogo82148/actions-upload-release-asset
I've made some tests on [my fork](https://github.com/j0k3r/wallabag/actions/workflows/upload-release-package.yml) before submitting this PR.
I've also:
- updated the release script to clone the repo using `https` instead of `git` (otherwise it failed during the build)
- use `md5sum` instead of `md5` because the latest isn't available in GitHub Actions
> Automatically create the package after a release

- src/Wallabag/AnnotationBundle/Controller/WallabagAnnotationController.php
Remove one depreciation
```
1x: The "Wallabag\AnnotationBundle\Controller\WallabagAnnotationController" class extends "FOS\RestBundle\Controller\FOSRestController" that is deprecated since FOSRestBundle 2.5, use {@see AbstractFOSRestController} instead.
1x in AnnotationControllerTest::testGetAnnotations from Tests\Wallabag\AnnotationBundle\Controller
```
> Extend right FOSRestBundle controller class

- GNUmakefile
Using the docker compose setup running them lead to memory exceed error.
> Run tests without memory limit

- src/Wallabag/ApiBundle/Controller/TagRestController.php
- src/Wallabag/CoreBundle/Resources/views/themes/material/Tag/tags.html.twig
- tests/Wallabag/ApiBundle/Controller/TagRestControllerTest.php
So client will be able to do the same as in the web UI.
Also remove empty `div` from the tags template.
Fix https://github.com/wallabag/wallabag/issues/5970
I'm wondering if this goes to 2.6.0 or 2.5.2, @wallabag/core?
As it's a small change, I'm for 2.5.2
> Add `nbEntries` to the API tags list response

- composer.json
- composer.lock
- src/Wallabag/CoreBundle/Helper/DownloadImages.php
- tests/Wallabag/CoreBundle/Helper/DownloadImagesTest.php
- tests/Wallabag/CoreBundle/fixtures/modal-content.svg
We can't process a SVG using PHP (with GD) so instead we sanitize the SVG (to ensure it's a real SVG and not a bad input file) and then just copy the response from the server locally.
Using that method my only concern is about security. Is https://github.com/darylldoyle/svg-sanitizer safe enough to trust it?
What kind of other security check we can add?
Related https://github.com/wallabag/wallabag/issues/5328
> Add support to download SVG locally

- .github/release.yml
Instead of having each PR from @weblate we just put a link to all PRs for the closed milestone.
For example: https://github.com/wallabag/wallabag/pulls?q=is%3Apr+author%3Aweblate+milestone%3A2.5.2+is%3Amerged
> Remove `weblate` PR from the automated changelog

- app/config/config.yml
- app/config/routing.yml
- composer.json
- composer.lock
- src/Wallabag/ApiBundle/Controller/AnnotationRestController.php
- src/Wallabag/ApiBundle/Controller/ConfigRestController.php
- src/Wallabag/ApiBundle/Controller/EntryRestController.php
- src/Wallabag/ApiBundle/Controller/SearchRestController.php
- src/Wallabag/ApiBundle/Controller/TagRestController.php
- src/Wallabag/ApiBundle/Controller/TaggingRuleRestController.php
- src/Wallabag/ApiBundle/Controller/UserRestController.php
- src/Wallabag/ApiBundle/Controller/WallabagRestController.php
- src/Wallabag/CoreBundle/Resources/views/themes/common/Developer/howto_app.html.twig
- src/Wallabag/CoreBundle/Resources/views/themes/common/Developer/index.html.twig
| Tests pass?   | How to start?
| CHANGELOG.md  | Do I just start a new section?
I work on [Read It Later](https://gitlab.gnome.org/World/read-it-later) wallabag client and I want better api documentation. I think the first step is updating nelmio/api-doc. This will bring an extended way to document the api.
This PR updates to nelmio/api-doc 3.0 and translates the existing documentation to the new format. I tried to keep the same content as the old api doc.
I have two outstanding issues:
- The `{_format)` path parameters are not automatically shown in version 3.0. I don't see how this was added in the …
> Switch to Swagger for api documentation

- app/config/services.yml
- src/Wallabag/CoreBundle/Event/Listener/UserLocaleListener.php
- src/Wallabag/CoreBundle/GuzzleSiteAuthenticator/GrabySiteConfigBuilder.php
- src/Wallabag/CoreBundle/Helper/PreparePagerForEntries.php
- src/Wallabag/CoreBundle/Helper/Redirect.php
- src/Wallabag/UserBundle/EventListener/CreateConfigListener.php
Just some stuff deprecated and replaced by other Interface.
Might ease the Symfony upgrade (poke @yguedidi)
Also remove router from `src/Wallabag/CoreBundle/Helper/PreparePagerForEntries.php` because it's not used
> Remove some deprecation

- phpstan-baseline.neon
- src/Wallabag/ApiBundle/Controller/EntryRestController.php
- src/Wallabag/ApiBundle/Controller/UserRestController.php
- src/Wallabag/CoreBundle/Command/InstallCommand.php
- src/Wallabag/CoreBundle/Command/ReloadEntryCommand.php
- src/Wallabag/CoreBundle/Controller/EntryController.php
- src/Wallabag/CoreBundle/Event/EntryDeletedEvent.php
- src/Wallabag/CoreBundle/Event/EntrySavedEvent.php
- src/Wallabag/ImportBundle/Consumer/AbstractConsumer.php
- src/Wallabag/ImportBundle/Import/AbstractImport.php
- src/Wallabag/ImportBundle/Import/BrowserImport.php
- src/Wallabag/UserBundle/Controller/ManageController.php
- tests/Wallabag/CoreBundle/Event/Listener/LocaleListenerTest.php
- tests/Wallabag/UserBundle/EventListener/AuthenticationFailureListenerTest.php
- tests/Wallabag/UserBundle/EventListener/CreateConfigListenerTest.php
Looks like parameter for the `->dispatch(` have been flipped (event first then event name). Define events should now extends `Symfony\Contracts\EventDispatcher\Event`
> Fix EventDispatcher & events

- app/config/services.yml
- composer.lock
- phpstan-baseline.neon
- src/Wallabag/CoreBundle/Command/CleanDownloadedImagesCommand.php
- src/Wallabag/CoreBundle/Command/CleanDuplicatesCommand.php
- src/Wallabag/CoreBundle/Command/ExportCommand.php
- src/Wallabag/CoreBundle/Command/GenerateUrlHashesCommand.php
- src/Wallabag/CoreBundle/Command/InstallCommand.php
- src/Wallabag/CoreBundle/Command/ListUserCommand.php
- src/Wallabag/CoreBundle/Command/ReloadEntryCommand.php
- src/Wallabag/CoreBundle/Command/ShowUserCommand.php
- src/Wallabag/CoreBundle/Command/TagAllCommand.php
- src/Wallabag/ImportBundle/Command/ImportCommand.php
- src/Wallabag/ImportBundle/Command/RedisWorkerCommand.php
And use DI to retrieve services in commands (except for `RedisWorkerCommand` where the container is injected, hard to find a better way, at least for now).
Most of the work was done by @Kdecherf in https://github.com/wallabag/wallabag/pull/5342
> Remove `ContainerAwareCommand` from commands

- app/config/services_rabbit.yml
- composer.json
- composer.lock
- src/Wallabag/CoreBundle/Controller/EntryController.php
- src/Wallabag/CoreBundle/Controller/ExportController.php
- src/Wallabag/CoreBundle/Controller/FeedController.php
- src/Wallabag/CoreBundle/Controller/IgnoreOriginInstanceRuleController.php
- src/Wallabag/CoreBundle/Controller/SiteCredentialController.php
- src/Wallabag/CoreBundle/Controller/StaticController.php
- src/Wallabag/CoreBundle/Controller/TagController.php
- src/Wallabag/ImportBundle/Consumer/RabbitMQConsumerTotalProxy.php
- src/Wallabag/ImportBundle/Controller/ImportController.php
This is just a simple proxy because we can't lazy load RabbitMQ service just to count number of messages in the queue. As they are automatically injected in the controller now, we can't lazy load them.
Also forgot to use `AbstractController` in [previous PR about _controller as a service_](https://github.com/wallabag/wallabag/pull/6159).
> Add `RabbitMQConsumerTotalProxy` to lazy RabbitMQ services for messages

- docker/php/Dockerfile
- docker/php/config/parameters.yml
Also, add `mailer_dsn` and limit xdebug to allow installation of PHP < 8
- `database_path` is related to https://github.com/wallabag/wallabag/pull/6099
- `mailer_dsn` is related to https://github.com/wallabag/wallabag/pull/6150
Should fix #6173
> Fix `database_path` in Docker env

- app/config/config.yml
- composer.json
- composer.lock
- src/Wallabag/ApiBundle/Controller/AnnotationRestController.php
- src/Wallabag/ApiBundle/Controller/ConfigRestController.php
- src/Wallabag/ApiBundle/Controller/EntryRestController.php
- src/Wallabag/ApiBundle/Controller/SearchRestController.php
- src/Wallabag/ApiBundle/Controller/TagRestController.php
- src/Wallabag/ApiBundle/Controller/TaggingRuleRestController.php
- src/Wallabag/ApiBundle/Controller/UserRestController.php
- src/Wallabag/ApiBundle/Controller/WallabagRestController.php
Updates to latest [nelmio/api-doc-bundle](https://github.com/nelmio/NelmioApiDocBundle) and update the Wallabag API annotations to OpenApi 3.
Closes #6108
> Update annotations to OpenApi 3

- composer.json
Symfony 4 introduced a new structure, web has been renamed public.
~~This fix is maybe a breaking change, we could maybe customize `public-dir` while waiting for flex migration~~
Finally fix https://github.com/wallabag/wallabag/issues/6173
> Fix public folder for Symfony 4+

- src/Wallabag/CoreBundle/Resources/views/Config/index.html.twig
> fix for config links

- src/Wallabag/CoreBundle/Resources/views/themes/common/Entry/share.html.twig
Before:
After:
Thanks to @gabriel-vernilo
> Fix XSS on username on share page

- src/Wallabag/CoreBundle/Controller/ConfigController.php
- src/Wallabag/CoreBundle/Resources/views/themes/material/Config/index.html.twig
- tests/Wallabag/CoreBundle/Controller/ConfigControllerTest.php
The route `/account/delete` was accessible using a `GET` request, allowing any user click on the link while being connected to have his account deleted.
Thanks @leorac & @bauh0lz
> Fix CSRF on user deletion

- src/Wallabag/CoreBundle/Helper/DownloadImages.php
- tests/Wallabag/CoreBundle/Helper/DownloadImagesTest.php
Images were not downloaded if the final URL was after an HTTP redirection.
> Fix DownloadImages not following redirections

- src/Wallabag/CoreBundle/Resources/views/Entry/_feed_link.html.twig
I made some changes earlier and didn't think about other routes using this. So here is the code to fix this error:
```
request.CRITICAL: Uncaught PHP Exception Twig\Error\RuntimeError: "An exception has been thrown during the rendering of a template ("Unable to generate a URL for the named route ".fr" as such route does not exist.")." at /var/www/wallabag/src/Wallabag/CoreBundle/Resources/views/Entry/_feed_link.html.twig line 12 {"exception":"[object] (Twig\\Error\\RuntimeError(code: 0): An exception has been thrown during the rendering of a template (\"Unable to generate a URL for the named route \".fr\" as such route does not exist.\"). at /var/www/wallabag/src/Wallabag/CoreBundle/Resources/views/Entry/_feed_link.html.twig:12, Symfony\\Component\\Routing\\Exception\\RouteNotFoundExceptio …
```
> Fix RSS feed_route not set

- app/config/parameters.yml.dist
As discussed in https://github.com/wallabag/wallabag/issues/5890, we updated the default value of this setting to use our own domain name.
> Changed default value for domain_name parameter

- app/config/services.yml
- composer.lock
They should only be loaded from `app/config/services_test.yml` (they are already loaded from there). Otherwise we'll have an issue when clearing the cache in prod env:
```
In DefinitionErrorExceptionPass.php line 54:
Class "Doctrine\Bundle\FixturesBundle\Fixture" not found while loading "Wal
labag\AnnotationBundle\DataFixtures\AnnotationFixtures".
```
Also update deps to latest.
Fix #6647
> Do not autoload fixtures

- src/Wallabag/ApiBundle/Controller/WallabagRestController.php
- src/Wallabag/ApiBundle/Entity/ApplicationInfo.php
Add response description to the API doc of WallabagRestController.
I started with this controller as it is the simplest.
I move the creation of the response to a separate class to document the response.
I don't have much PHP experience, so I am not sure whether this is good practice.
> ApiDoc: Add response description to WallabagRestController

- app/DoctrineMigrations/Version20170606155640.php
Doctrine 3.5 reruns skipped migrations when invoking doctrine:migrations:migrate. This causes this migration to rerun and it errors since craue_config_setting table gets renamed in Version20190808124957.php to internal_setting table.
Fixes #6660
> Skip migration if the table was already renamed

- src/Wallabag/ApiBundle/Controller/UserRestController.php
- src/Wallabag/ApiBundle/Entity/Client.php
- src/Wallabag/UserBundle/Entity/User.php
Add descriptions to the response of user API calls. The API docs automatically generate an example response and show a model describing the response object.
Following are some screenshots of the rendered documentation.
> ApiDoc: Add response description to UserRestController

- app/config/config.yml
- app/config/parameters.yml.dist
- docker/php/config/parameters.yml
- src/Wallabag/CoreBundle/Controller/ConfigController.php
- src/Wallabag/CoreBundle/Resources/views/Config/index.html.twig
- src/Wallabag/UserBundle/Controller/ManageController.php
- src/Wallabag/UserBundle/Resources/views/Manage/edit.html.twig
- tests/Wallabag/CoreBundle/Controller/SecurityControllerTest.php
> Remove `twofactor_auth` parameter

- app/DoctrineMigrations/Version20221221092957.php
| New feature?  | o
Fix #6709
I don't now if this change will fit with MySQL.
> Keep escaped table name while migrating

- tests/Wallabag/CoreBundle/Controller/FeedControllerTest.php
| Bug fix?      | yes 🤞 
| Tests pass?   | yes 🤞 
We need to persist object and add a sleep call to be sure that the 2 objects have different `updatedAt` values. 
In fact, in this test, `$day3` and `$day4` are useless because these dates are not keeped: as we persist objects, the `updatedAt` field is updated with current date.
> Fix failing randomly test

- tests/Wallabag/CoreBundle/WallabagCoreTestCase.php
> Calling `WebTestCase::createClient()` while a kernel has been booted now throws an exception, ensure the kernel is shut down before calling the method
from https://github.com/symfony/symfony/blob/4.4/UPGRADE-5.0.md#frameworkbundle
remove ~9 direct depreciation, see from [2119](https://github.com/wallabag/wallabag/actions/runs/5743870218/job/15569056118#step:10:130) to [2110](https://github.com/wallabag/wallabag/actions/runs/5776682512/job/15656061556?pr=6803#step:10:130) for example
> Ensure the kernel is shut down before calling createClient

- src/Wallabag/CoreBundle/Event/Listener/LocaleListener.php
- tests/Wallabag/CoreBundle/Event/Listener/LocaleListenerTest.php
> Removed `GetResponseEvent`, use `RequestEvent` instead
from https://github.com/symfony/symfony/blob/4.4/UPGRADE-5.0.md#httpkernel
> Replace GetResponseEvent by RequestEvent

- src/Wallabag/CoreBundle/Resources/views/Entry/entries.html.twig
- src/Wallabag/CoreBundle/Resources/views/Entry/entry.html.twig
- src/Wallabag/CoreBundle/Resources/views/Tag/tags.html.twig
> The `Templating\Helper\TranslatorHelper::transChoice()` method has been removed, use the `trans()` one instead with a `%count%` parameter.
from https://github.com/symfony/symfony/blob/4.4/UPGRADE-5.0.md#frameworkbundle
> Move from transchoice to trans

- app/DoctrineMigrations/Version20160401000000.php
- app/DoctrineMigrations/Version20160812120952.php
- app/DoctrineMigrations/Version20161001072726.php
- app/DoctrineMigrations/Version20161022134138.php
- app/DoctrineMigrations/Version20161024212538.php
- app/DoctrineMigrations/Version20161214094402.php
- app/DoctrineMigrations/Version20170501115751.php
- app/DoctrineMigrations/Version20170510082609.php
- app/DoctrineMigrations/Version20170511211659.php
- app/DoctrineMigrations/Version20170719231144.php
- app/DoctrineMigrations/Version20171008195606.php
- app/DoctrineMigrations/Version20181128203230.php
- app/DoctrineMigrations/Version20181202073750.php
- app/DoctrineMigrations/Version20190425115043.php
- app/DoctrineMigrations/Version20190510141130.php
- app/DoctrineMigrations/Version20190511165128.php
- app/DoctrineMigrations/Version20190619093534.php
- app/DoctrineMigrations/Version20190806130304.php
- app/DoctrineMigrations/Version20190808124957.php
- app/DoctrineMigrations/Version20190826204730.php
- app/DoctrineMigrations/Version20221221092957.php
- src/Wallabag/CoreBundle/Command/InstallCommand.php
- src/Wallabag/CoreBundle/Doctrine/WallabagMigration.php
> Relying on the name of the platform is discouraged. To identify the platform, use its class name.
from https://github.com/doctrine/dbal/blob/3.6.x/UPGRADE.md#deprecated-abstractplatformgetname
remove ~177 direct depreciation, see from [2119](https://github.com/wallabag/wallabag/actions/runs/5743870218/job/15569056118#step:10:130) to [1942](https://github.com/wallabag/wallabag/actions/runs/5771991202/job/15646498327?pr=6799#step:10:130) for example
> Identify platforms by their class

- src/Wallabag/ImportBundle/Controller/ImportController.php
> Removed `Symfony\Bundle\FrameworkBundle\Controller\Controller`. Use `Symfony\Bundle\FrameworkBundle\Controller\AbstractController` instead.
from https://github.com/symfony/symfony/blob/4.4/UPGRADE-5.0.md#frameworkbundle
> Make ImportController extends AbstractController

- composer.json
- composer.lock
I hope I missed nothing, at least tests pass
> Split symfony/symfony

- app/AppKernel.php
- app/config/services.yml
- app/config/webpack/common.js
- docker/php/config/parameters.yml
- src/Wallabag/CoreBundle/Twig/WallabagExtension.php
> The `Kernel::getRootDir()` and the `kernel.root_dir` parameter have been removed
from https://github.com/symfony/symfony/blob/4.4/UPGRADE-5.0.md#httpkernel
> Replace kernel.root_dir by kernel.project_dir

- src/Wallabag/CoreBundle/Command/UpdatePicturesPathCommand.php
- tests/Wallabag/CoreBundle/Command/UpdatePicturesPathCommandTest.php
Should fix #2852. 
Tests missing.
> Add command to clean pictures path when changing instance URL

- app/DoctrineMigrations/Version20230728093912.php
- src/Wallabag/ApiBundle/Controller/EntryRestController.php
- src/Wallabag/CoreBundle/Command/ReloadEntryCommand.php
- src/Wallabag/CoreBundle/DataFixtures/EntryFixtures.php
- src/Wallabag/CoreBundle/Entity/Entry.php
- src/Wallabag/CoreBundle/Form/Type/EntryFilterType.php
- src/Wallabag/CoreBundle/Helper/ContentProxy.php
- src/Wallabag/CoreBundle/Repository/EntryRepository.php
- src/Wallabag/CoreBundle/Resources/views/Entry/entries.html.twig
- src/Wallabag/ImportBundle/Import/WallabagImport.php
- src/Wallabag/ImportBundle/Import/WallabagV1Import.php
- tests/Wallabag/ApiBundle/Controller/EntryRestControllerTest.php
- tests/Wallabag/CoreBundle/Command/ReloadEntryCommandTest.php
- tests/Wallabag/CoreBundle/Controller/EntryControllerTest.php
- tests/Wallabag/CoreBundle/Helper/ContentProxyTest.php
- translations/messages.en.yml
> Add `isNotParsed` field on Entry entity

- src/Wallabag/CoreBundle/Controller/EntryController.php
- tests/Wallabag/CoreBundle/Controller/EntryControllerTest.php
> Fix search when search term has useless space

- src/Wallabag/CoreBundle/Command/UpdatePicturesPathCommand.php
- src/Wallabag/CoreBundle/Controller/EntryController.php
- src/Wallabag/CoreBundle/Controller/TagController.php
- src/Wallabag/CoreBundle/DataFixtures/EntryFixtures.php
- src/Wallabag/CoreBundle/Form/Type/EntryFilterType.php
- src/Wallabag/CoreBundle/Twig/WallabagExtension.php
- tests/Wallabag/ApiBundle/Controller/EntryRestControllerTest.php
- tests/Wallabag/CoreBundle/Twig/WallabagExtensionTest.php
All self depreciation notices were about accepting null in some functions is deprecated.
And it looks like there was a bug in entry PATCH action tests that made them pass why not working as expected
> Resolve self depreciation

- app/config/parameters.yml.dist
- app/config/parameters_test.yml
- app/config/tests/parameters_test.mysql.yml
- app/config/tests/parameters_test.pgsql.yml
- app/config/tests/parameters_test.sqlite.yml
- docker/php/config/parameters.yml
As discussed in https://github.com/wallabag/wallabag/discussions/6785, this setting should be to `false`.
> Change public registration to false by default

- .github/workflows/assets.yml
- .github/workflows/coding-standards.yml
- .github/workflows/continuous-integration.yml
- .github/workflows/translations.yml
- composer.json
- composer.lock
SMTP is the default provider to send email.
But users tend to use Gmail from time to time. So, instead of a complex installation to allow it, we prefer to ship it with the default package.
Fix #6898
Also:
- update deps globally
- lock symfony/* deps to 4.4
> Add Google mailer

- app/config/config.yml
Cookie will be set as `secure` when the connection will be on HTTPS otherwise the cookie will be defined as `secure: false`.
I used `mkcert` to  test it locally.
See:
- https://symfony.com/doc/4.4/reference/configuration/framework.html#cookie-secure
- [CWE-614: Sensitive Cookie in HTTPS Session Without 'Secure' Attribute ](https://cwe.mitre.org/data/definitions/614.html)
> Force secure cookie on HTTPS connection

- .github/dependabot.yml
I put npm grouped deps inside the composer section, which is why it wasn't working. I move it in the right place and also added one grouped deps for Symfony*
> Move grouping deps in the right place

- package.json
- yarn.lock
`node-sass` is deprecated and replaced by dart-sass which is already in use as `sass`.
resolves #6957
> Remove deprecated `node-sass`

- src/Wallabag/CoreBundle/Controller/TagController.php
Fix PHP8.1+ deprecation:
````
Got error '
PHP message: PHP Deprecated:  explode(): Passing null to parameter #2 ($string) of type string is deprecated in /var/www/wallabag/src/Wallabag/CoreBundle/Controller/TagController.php on line 49
PHP message: PHP Deprecated:  strlen(): Passing null to parameter #1 ($string) of type string is deprecated in /var/www/wallabag/src/Wallabag/CoreBundle/Controller/TagController.php on line 52'
````
> Fix deprecated null tag parameter

- .github/dependabot.yml
`*symfony*` matches to much deps (ie `phpstan-symfony`, see https://github.com/wallabag/wallabag/pull/7004) which aren't related to Symfony release. `symfony/*` will properly match Symfony release better.
> Fix symfony pattern for dependabot

- .gitignore
If I get it correctly, the assets are generated during the release process so we should avoid the `wallassets` folder to be commited again. ping @yguedidi
> wallassets folder added to .gitignore

- app/config/services.yml
No more database connection errors on first composer install! 🎉 
Before: https://github.com/wallabag/wallabag/actions/runs/7303332338/job/19903631251#step:7:392
After: https://github.com/wallabag/wallabag/actions/runs/7332455594/job/19966621958?pr=7142#step:7:390
> Make database dependent commands lazy

- src/Wallabag/CoreBundle/Controller/ConfigController.php
- src/Wallabag/CoreBundle/Helper/ContentProxy.php
- tests/Wallabag/ApiBundle/Controller/ConfigRestControllerTest.php
- tests/Wallabag/ApiBundle/Controller/UserRestControllerTest.php
- tests/Wallabag/ApiBundle/Controller/WallabagRestControllerTest.php
- tests/Wallabag/ApiBundle/WallabagApiTestCase.php
- tests/Wallabag/CoreBundle/Command/InstallCommandTest.php
- tests/Wallabag/CoreBundle/WallabagCoreTestCase.php
Move from [176](https://github.com/wallabag/wallabag/actions/runs/7298018512/job/19888237846#step:10:107) direct deprecation notices to [73](https://github.com/wallabag/wallabag/actions/runs/7320835512/job/19940459396#step:10:104) on PHP 8.1 with sqlite!
72 are from Doctrine and I think it's OK to keep them for now.
The last on is about `Symfony\Component\DomCrawler\Crawler::text()` and it's OK to keep it also as we don't need whitespace normalization in [that single usage in tests](https://github.com/wallabag/wallabag/blob/master/tests/Wallabag/CoreBundle/Controller/EntryControllerTest.php#L594-L595).
Find below the remaining 73.
```
Remaining direct deprecation notices (73)
44x: Method Doctrine\ORM\Event\LifecycleEventArgs::getEntity() is deprecated and will be removed in Doctrine ORM …
```
> Fix deprecation

- phpstan-baseline.neon
- src/Wallabag/CoreBundle/Controller/ConfigController.php
- src/Wallabag/CoreBundle/Controller/EntryController.php
- src/Wallabag/CoreBundle/Controller/TagController.php
- src/Wallabag/CoreBundle/Helper/Redirect.php
- src/Wallabag/CoreBundle/Resources/views/Entry/_card_actions.html.twig
- src/Wallabag/CoreBundle/Resources/views/Entry/_card_list.html.twig
- src/Wallabag/CoreBundle/Resources/views/Entry/_tags.html.twig
- src/Wallabag/CoreBundle/Resources/views/Entry/entries.html.twig
- src/Wallabag/CoreBundle/Resources/views/Entry/entry.html.twig
- src/Wallabag/CoreBundle/Resources/views/Tag/tags.html.twig
- tests/Wallabag/CoreBundle/Controller/EntryControllerTest.php
- tests/Wallabag/CoreBundle/Controller/TagControllerTest.php
- tests/Wallabag/CoreBundle/Helper/RedirectTest.php
fixes #6944
easier to review commit by commit 😉
> Remove session-based redirection

- app/AppKernel.php
- app/config/config.yml
- app/config/config_test.yml
- app/config/parameters_test.yml
- app/config/tests/parameters_test.mysql.yml
- app/config/tests/parameters_test.pgsql.yml
- app/config/tests/parameters_test.sqlite.yml
Benefits:
- easier testing on different databases locally
- prepare for the use of environment variables for configuration
> Make tests use dev database config

- README.md
We have an Open Source free subscription to Blackfire to improve wallabag performance!
> Add Blackfire as sponsor

- src/Wallabag/CoreBundle/Event/Listener/CreateConfigListener.php
- tests/Wallabag/CoreBundle/Event/Listener/CreateConfigListenerTest.php
Sometimes I get an error because content is sent before header when using the sessions after using wallabag:instal.
So this PR makes the CreateConfigListener use the Session only when there is a request, so not in CLI context, when creating the default admin user
> Fix CreateConfigListener to not use session in CLI context

- app/DoctrineMigrations/Version20161001072726.php
- app/DoctrineMigrations/Version20161022134138.php
- app/DoctrineMigrations/Version20170510082609.php
- app/DoctrineMigrations/Version20170719231144.php
- app/DoctrineMigrations/Version20171008195606.php
- app/DoctrineMigrations/Version20181128203230.php
- app/DoctrineMigrations/Version20190511165128.php
- app/DoctrineMigrations/Version20190619093534.php
Benefit is that those migrations will actually execute but doing nothing, and this avoid keeping them as "pending" migrations to be executed.
This helps not having the message "you have not run migrations" when using migration diff.
And migration status will show no not run migrations :)
> Make migrations noop instead of skipping

- tests/Controller/Import/PinboardControllerTest.php
- tests/fixtures/Import/pinboard_export
From [4m04s](https://github.com/wallabag/wallabag/actions/runs/8018668664) on latest master CI run to now [3m14s](https://github.com/wallabag/wallabag/actions/runs/8027642340): ~ -50s
> Use lighter PDF file in Pinboard tests

- app/config/wallabag.yml
Galician language (gl) option is not in the drop down menu but available to use. I have manually tested this on my install and works fine letting users select galician language.
| Bug fix?  |    yes
| New feature?  no
> Add "gl" language to wallabag.yml

- app/config/config_test.yml
- app/config/parameters_test.yml
- app/config/services.yml
- app/config/tests/parameters_test.sqlite.yml
- src/Command/InstallCommand.php
- tests/Command/InstallCommandTest.php
- tests/WallabagTestCase.php
This mainly create a dedicated tmp database for each install command test.
Should allow running the tests on more cases instead of skipping them for such an important action that is the installation.
depends on:
> Improve install command

- docker-compose.yml
This remove errors in postegresql container logs that the "root" role doesn't exists
> Use wallabag user for PostgreSQL healthcheck

- src/Controller/ConfigController.php
- src/Repository/TaggingRuleRepository.php
- templates/Config/index.html.twig
- tests/Controller/ConfigControllerTest.php
- translations/messages.en.yml
- translations/messages.zh.yml
- translations/messages.zh_Hant.yml
Implements and closes #7520 
I put the reset tagging rules button in the reset area.
The button will only show up if the current user has tagging rules.
My first PR using PHP :smile:.Happy to make any changes.
> Feature: tagging rules reset

- .editorconfig
- assets/material/css/cards.scss
When running yarn here the new deprecation notices:
```
WARNING in ./assets/material/css/index.scss (./node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[1].use[1]!./node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[1].use[2]!./node_modules/sass-loader/dist/cjs.js!./assets/material/css/index.scss)
Module Warning (from ./node_modules/sass-loader/dist/cjs.js):
Deprecation Warning on line 270, column 6 of file:///var/www/html/assets/material/css/cards.scss:270:6:
Sass's behavior for declarations that appear after nested
rules will be changing to match …
```
> Fix Sass mixed declaration depreciation notices

- fixtures/EntryFixtures.php
- src/Controller/Api/EntryRestController.php
- src/Repository/EntryRepository.php
- tests/Command/ExportCommandTest.php
- tests/Controller/Api/EntryRestControllerTest.php
- tests/Controller/EntryControllerTest.php
Implemented filter by one http_status code. Happy to change if filter by multiple http status code is preferred.
Will close #7159
> Add `http_status` filter to `/api/entries`

- .github/workflows/continuous-integration.yml
- app/config/services_rabbit.yml
Should fix https://github.com/wallabag/wallabag/issues/7762
The bug was introduced here: https://github.com/wallabag/wallabag/commit/423f2f792d57386defce3369b8e780f1aac0b428 in this huge PR: https://github.com/wallabag/wallabag/pull/7137
RabbitMqBundle doesn't support lazy services, but in the documentation, it's written: `but you can set lazy: true in your connection configuration to avoid unnecessary connections to your message broker in every request`
I think that this setting is necessary for us, when the RabbitMQ server is not up. 
Our testsuite …
> Restored lazy connections for RabbitMQ

- docker-compose.yml
Removes the following deprecation notice:
the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion
> Remove Docker compose version

- src/Entity/TaggingRule.php
add missing 'r' here to allow creating tagging rules using the documented isStarred filter.
> fix(TaggingRule): allowed variable should match docs

- app/config/config.yml
- app/config/services.yml
- src/ExpressionLanguage/AuthenticatorProvider.php
- src/SiteConfig/LoginFormAuthenticator.php
- tests/SiteConfig/LoginFormAuthenticatorTest.php
The `request_html` is used only in login context, so no need for authentication cookie from the cookie jar, we can safely use Symfony HTTP Client there.
Also, among all site configs using `request_html` function, only the URL is passed as parameter, so I removed the support for passing Guzzle options to it.
> Make AuthenticatorProvider use Symfony HTTP Client

- docker/php/config/parameters.yml
- docker/php/env.example
Before this change the generated value was `database_path: '"%kernel.project_dir%/data/db/wallabag.sqlite"'`, including the double quotes in the value
> Fix database_path default value

- src/Import/PocketImport.php
Fixes #7635
Change NB_ELEMENTS in pocket importer to 30 to comply with Pocket API restrictions.
Tested on my instance and verified that import from pocket now works correctly.
> Change NB_ELEMENTS in pocket importer to 30 to comply with Pocket API

- src/Controller/Api/EntryRestController.php
- src/Controller/EntryController.php
- src/Entity/Entry.php
- tests/Controller/Api/EntryRestControllerTest.php
- tests/Controller/EntryControllerTest.php
> Add a validator on URL entity

- templates/Entry/entries.xml.twig
RFC4287 section 4.2.7.2 specifies that "rel=alternate" is effectively the default for the link element:
If the "rel" attribute is not present, the link
element MUST be interpreted as if the link relation type is
"alternate".
So having a plain `<link>` and a `<link rel="alternate">` is kind of weird, *especially* if they point to different resources. So we just remove the plain entry and *replace* it with the rel=alternate, which is really the default here.
The sample Atom feeds in RFC4287 (section 1.1) do give an example *only* with `rel="alternate"`:
<entry>
<title>Atom draft-07 snapshot</title>
<link rel="alternate" type="text/html"
href="http://example.org/2005/04/02/atom"/>
<link rel="enclosure" type="audio/mpeg" length="1337"
href="http://example.org/audio/ph34r_my_podcast.mp3"/>
To …
> restore pre-Atom behavior of linking directly to the article

- src/Wallabag/ImportBundle/Import/PocketImport.php
Backport https://github.com/wallabag/wallabag/pull/7797 to 2.6
Fixes https://github.com/wallabag/wallabag/issues/7635
> Change NB_ELEMENTS in pocket importer to 30

- .github/CONTRIBUTING.md
- .github/workflows/coding-standards.yml
- GNUmakefile
- docker/php/Dockerfile
- package.json
- webpack.config.js
- yarn.lock
This removes the deprecation notices introduced by #6823:
```
DEPRECATION  The ESLint integration is now deprecated and will be removed in the next major release. Please use the standalone ESLint CLI instead, or use the ESLint Webpack plugin directly.
WARNING  Webpack Encore requires version ^13.0.0 || ^14.0.0 of sass-loader. Your version 16.0.4 is too new. The related feature *may* still work properly. If you have issues, try downgrading the library, or upgrading Encore.
WARNING  Webpack Encore requires version ^13.0.0 || ^14.0.0 of sass-loader. Your …
```
> Remove linters from build process

- translations/CraueConfigBundle.de.yml
- translations/CraueConfigBundle.ru.yml
Extracted from #8012
I don't know if this will be added back when sync'ing with Weblate
> Remove legacy translation in CraueConfigBundle

- tests/Controller/EntryControllerTest.php
I can't see those tests failing anymore..!
Uses Wikipedia language page in the locale as it's more likely to always be up and responsive.
No brazilian on Wikipedia so used another brazilian dedicated website.
Of course kept the wallabag Wikipedia page for French! :)
> Fix volatile tests

- app/config/config.yml
- src/Controller/Api/DeveloperController.php
- src/Controller/ConfigController.php
- src/Controller/FeedController.php
- src/Mailer/AuthCodeMailer.php
- templates/Entry/entries.xml.twig
- tests/Mailer/AuthCodeMailerTest.php
Extracted from #8012
Goal is to remove usages of `getParameter()` for parameters that are in `parameters.yml` to prepare using environment variables and passing values through configuration with `%env(...)%`
> Make wallabag_url a Twig global

- src/Controller/Api/UserRestController.php
- src/Controller/Api/WallabagRestController.php
Extracted from #8012
Goal is to remove usages of `getParameter()` for parameters that are in `parameters.yml` to prepare using environment variables and passing values through configuration with `%env(...)%`
> Use constructor injection for registration parameter

- src/SiteConfig/GrabySiteConfigBuilder.php
- src/SiteConfig/LoginFormAuthenticator.php
- src/SiteConfig/SiteConfig.php
- tests/SiteConfig/LoginFormAuthenticatorTest.php
- tests/SiteConfig/SiteConfigTest.php
This PR is related to https://github.com/wallabag/wallabag/issues/7878
Currently, if a user defines a User-Agent for a website Wallabag uses this User-Agent only to get the content, not for the authentication request.
This PR pass the HTTP headers defined for the website to the authentication request.
> Use Graby's http headers configuration for the authentication request

- app/config/wallabag.yml
This PR allows uploads of files with mime type of 'application/vnd.ms-excel'.
I ran into the same problem as was described #7685. Peeking around I found out, that my uploaded instapaper export gets a mime type (from `$file->getClientMimeType()` on line 47 in `\Wallabag\Controller\Import\InstapaperController::indexAction`) of `application/vnd.ms-excel` which is not mentioned in `wallabag.allow_mimetypes` config entry. 
Since this is a client mime type, this might possibly be a Windows (11?) only issue. 
This PR allows this mime type. After applying this …
> Add 'application/vnd.ms-excel' to allowed MIME types config

- docker/php/env.example
Mainly to load fonts directly, before this there was a mismatch as localhost is not same as 127.0.0.1
This aligns with the URL provided in CONTRIBUTING.md
> Fix default DOMAIN_NAME to avoid Cross-Origin issues

- src/Controller/Api/EntryRestController.php
- src/Controller/Api/WallabagRestController.php
- src/Security/Voter/EntryVoter.php
- src/Security/Voter/MainVoter.php
- tests/Controller/Api/EntryRestControllerTest.php
- tests/Controller/Api/TagRestControllerTest.php
- tests/Controller/ConfigControllerTest.php
- tests/Controller/EntryControllerTest.php
- tests/Controller/TagControllerTest.php
- tests/Security/Voter/EntryVoterTest.php
- tests/Security/Voter/MainVoterTest.php
More precise security.
Replacing the entity manager clear by creating a new client is needed because without it tests about deleting an entry failed.
It's because of the clear, the user entity instance that is inside the entry and the one used in security became different instances, so the `===` check on user in EntryVoter failed.
> Add IsGranted to EntryRestController

- composer-dependency-analyser.php
- composer.json
- composer.lock
QR codes are not anymore generated by the back-end
| Production Changes                  | From    | To      | Compare |
|-------------------------------------|---------|---------|---------|
| bacon/bacon-qr-code                 | 2.0.8   | REMOVED |         |
| dasprid/enum                        | 1.0.6   | REMOVED |         |
| endroid/qr-code                     | 3.9.7   | REMOVED |         |
| khanamiryan/qrcode-detector-decoder | 1.0.6   | REMOVED |         |
| myclabs/php-enum                    | 1.8.5   | REMOVED |         |
| scheb/2fa-qr-code …
> Remove deprecated scheb/2fa-qr-code package

- phpstan-baseline.neon
- src/Wallabag/CoreBundle/Controller/ConfigController.php
- src/Wallabag/CoreBundle/Resources/views/Config/otp_app.html.twig
- translations/messages.en.yml
| Tests pass?   | dunno
Might fix #8138 (or at least provide a workaround)
> Avoid non-validated OTP to be enabled

- assets/scss/_cards.scss
- templates/Entry/Card/_content.html.twig
This PR replaces the hard-coded title truncate at 80 chars with a dynamic text-overflow ellipsis using CSS.
This cuts the title on client-side and shows an ellipsis if it exceeds two lines.
We can change to 3 lines for the card view if it seems too short.
<details>
<summary>Screenshots of the changes before and after</summary>
</details>
> Replace hardcoded title truncate with CSS text-overflow

- .github/workflows/continuous-integration.yml
`ubuntu-20.04` is now fully deprecated, see https://github.com/actions/runner-images/issues/11101
> Use `ubuntu-latest` in CI

- docker/php/Dockerfile
This is an alternative to #7351. As suggested by @Kdecherf, this patch takes as much as possible from https://github.com/wallabag/docker/blob/488814d1879ed3d371482c22474eebaee57946b8/Dockerfile#L7-L10.
I used this image for a few days as my local development environment on macOS (arm) and Linux (x86) without issues.
> fix(docker): install envsubst from source to support more targets

- src/Controller/Import/PocketCsvController.php
I made a mistake in the first version of PocketCsvController, I extended HtmlController.
> Fix PocketCsvController to extend AbstractController

- app/config/wallabag.yml
This pull request enables the Korean (한국어) language option in the user settings.
The translation files for Korean are already present in the repository, but the language was not configured in `parameters.wallabag.languages`, making it impossible for users to select. This change adds the necessary configuration line.
Fixes #8427
| Q             | A   |
|---------------|-----|
| Bug fix?      | yes |
| New feature?  | no  |
| BC breaks?    | no  |
| Deprecations? | no  |
| Tests pass?   | yes |
| Documentation | no  |
| Translation   | no  |
| CHANGELOG.md  | yes |
| License       | MIT |
> feat(locale): Add Korean to the list of available languages
