inc/poche/Poche.class.php
themes/baggy/home.twig
themes/default/home.twig

This adds 3 bits of functionality, one per commit.  Rebased on the dev branch this time as per the contributing guidelines. :)

Miscellaneous additions

---

.travis.yml
app/build.xml
app/phpunit.xml.dist
src/Wallabag/CoreBundle/Tests/Controller/EntryControllerTest.php

I've fixed travis & phpunit.
I also introduce `ant` which will be very helpful when the tests suites will became bigger and we will need to clear database, load fixtures, etc ...

Tests are working again

---

app/build.xml
app/phpunit.xml.dist
src/Wallabag/CoreBundle/Resources/public/js/bookmarklet.js
src/Wallabag/CoreBundle/Resources/views/_bookmarklet.html.twig
src/Wallabag/CoreBundle/Resources/views/_head.html.twig
src/Wallabag/CoreBundle/Resources/views/layout.html.twig
src/Wallabag/CoreBundle/Service/Extractor.php
src/Wallabag/CoreBundle/Tests/Controller/EntryControllerTest.php

Add some tests on EntryController also initialize database schema using `ant`

V2 api tests entry

---

inc/3rdparty/site_config/standard/gist.github.com.txt
inc/3rdparty/site_config/standard/jungle-world.com.txt
inc/3rdparty/site_config/standard/toolinux.com.txt

It should fix issues #979 and #1034, as well as helping on #989.

added site config for github gists, jungle-world.com and toolinux.com

---

inc/poche/Database.class.php
inc/poche/Poche.class.php

The stored message in DB used a not localized text.

Fix fetched entries when localized

---

themes/baggy/css/main.css

double closing parentheses

---

app/config/config_dev.yml
app/config/config_test.yml
app/config/parameters.yml.dist
app/config/security.yml
src/Wallabag/CoreBundle/Controller/SecurityController.php
src/Wallabag/CoreBundle/Entity/User.php
src/Wallabag/CoreBundle/Form/Type/ForgotPasswordType.php
src/Wallabag/CoreBundle/Form/Type/ResetPasswordType.php
src/Wallabag/CoreBundle/Resources/config/services.yml
src/Wallabag/CoreBundle/Resources/views/Mail/forgotPassword.txt.twig
src/Wallabag/CoreBundle/Resources/views/Security/checkEmail.html.twig
src/Wallabag/CoreBundle/Resources/views/Security/forgotPassword.html.twig
src/Wallabag/CoreBundle/Resources/views/Security/login.html.twig
src/Wallabag/CoreBundle/Resources/views/Security/reset.html.twig
src/Wallabag/CoreBundle/Tests/Controller/SecurityControllerTest.php

Handle forgot password

---

app/config/config.yml
app/config/parameters.yml.dist
build.xml
src/Wallabag/CoreBundle/Command/InstallCommand.php
src/Wallabag/CoreBundle/Doctrine/Mapping/PrefixedNamingStrategy.php
src/Wallabag/CoreBundle/Entity/Config.php
src/Wallabag/CoreBundle/Entity/Entry.php
src/Wallabag/CoreBundle/Entity/Tag.php
src/Wallabag/CoreBundle/Entity/User.php
src/Wallabag/CoreBundle/Resources/config/services.yml

Will fix #799 
Of course, after merging this, you will need to clear your caches and drop then recreate your database schema.
I finally went with naming strategy solution from Doctrine instead of using a listener.
See http://doctrine-orm.readthedocs.org/en/latest/reference/namingstrategy.html

Prefix table

---

src/Wallabag/CoreBundle/Controller/EntryController.php
src/Wallabag/CoreBundle/Entity/Entry.php
src/Wallabag/CoreBundle/Entity/Tag.php
src/Wallabag/CoreBundle/Form/Type/EditEntryType.php
src/Wallabag/CoreBundle/Form/Type/NewEntryType.php
src/Wallabag/CoreBundle/Resources/views/Entry/edit.html.twig
src/Wallabag/CoreBundle/Resources/views/Entry/entry.html.twig
src/Wallabag/CoreBundle/Tests/Controller/EntryControllerTest.php

Fix #218
I mean basic, because there is no javascript at all. It could be a nice edit-in-place. But for the moment, it is simple.

V2 Edit title

---

themes/default/config.twig

I'm sleepy, sorry.
Reverts wallabag/wallabag#1247

Revert "fix link to save your first article"

---

README.md
inc/poche/Tools.class.php
inc/poche/config.inc.default.php

This needs to be tested in many configurations please.
cc @MoriTanosuke

Enable base_url for proxies

---

app/config/parameters.yml.dist
src/Wallabag/CoreBundle/DataFixtures/ORM/LoadConfigData.php
src/Wallabag/CoreBundle/Tests/Controller/ConfigControllerTest.php
src/Wallabag/CoreBundle/Tests/Controller/SecurityControllerTest.php

set material to default theme \o/

---

themes/baggy/_head.twig
themes/default/_head.twig

just some stuff i noticed while I was working on #1275

Fix ff social

---

src/Wallabag/CoreBundle/Resources/views/themes/material/base.html.twig

rename favorite in starred

---

src/Wallabag/CoreBundle/Resources/views/themes/material/Entry/entry.html.twig

add link to original article in material theme

---

src/Wallabag/CoreBundle/Resources/views/Entry/entries.html.twig
src/Wallabag/CoreBundle/Resources/views/themes/material/Entry/entries.html.twig
src/Wallabag/CoreBundle/Tests/Controller/EntryControllerTest.php

fix #1350: fix pagination with filters

---

src/Wallabag/CoreBundle/Filter/EntryFilterType.php

TODO:
* ~~test~~
* if one field is not filled with the good format => error (in fact, it's the same thing for the reading time filter)
* ~~smart calendar (hi @modos189)~~ done in an other PR.

[WIP] filter by creation date

---

composer.json
composer.lock

I tried locally (composer clear cache, rm vendor -rf, composer install): no more "cloning ...". Only downloading.

fix 1356: diet for composer

---

src/Wallabag/CoreBundle/Controller/EntryController.php

I don't know if it's the good way (about the translation for example).

action labels depend on status

---

src/Wallabag/CoreBundle/Resources/views/themes/material/Entry/entries.html.twig

filters: enhance view for domain name

---

src/Wallabag/CoreBundle/Controller/TagController.php
src/Wallabag/CoreBundle/Entity/Tag.php
src/Wallabag/CoreBundle/Form/Type/NewTagType.php
src/Wallabag/CoreBundle/Repository/TagRepository.php
src/Wallabag/CoreBundle/Resources/views/Entry/entry.html.twig
src/Wallabag/CoreBundle/Resources/views/Tag/new_form.html.twig
src/Wallabag/CoreBundle/Resources/views/themes/material/Entry/entry.html.twig
src/Wallabag/CoreBundle/Resources/views/themes/material/Tag/new_form.html.twig
src/Wallabag/CoreBundle/Tests/Controller/TagControllerTest.php

assign tags to an entry

---

src/Wallabag/CoreBundle/Controller/EntryController.php

Fix redirect after deletion

---

src/Wallabag/CoreBundle/Resources/views/themes/material/public/css/main.css

This is a fix related to #1384

Apply margin only on settings page

---

src/Wallabag/CoreBundle/Resources/views/themes/material/Entry/entry.html.twig
src/Wallabag/CoreBundle/Resources/views/themes/material/Tag/new_form.html.twig
src/Wallabag/CoreBundle/Resources/views/themes/material/public/css/main.css
src/Wallabag/CoreBundle/Resources/views/themes/material/public/js/init.js

fix #1378: nice display for tags list

---

app/config/services.yml
src/Wallabag/CoreBundle/Resources/views/Entry/entries.html.twig
src/Wallabag/CoreBundle/Resources/views/themes/material/Entry/entries.html.twig

fix #1357, truncate domain name if it's too loooong

---

src/Wallabag/CoreBundle/Resources/views/Entry/entries.html.twig
src/Wallabag/CoreBundle/Resources/views/Entry/entry.html.twig
src/Wallabag/CoreBundle/Resources/views/themes/baggy/public/css/main.css
src/Wallabag/CoreBundle/Resources/views/themes/material/Entry/entries.html.twig
src/Wallabag/CoreBundle/Resources/views/themes/material/Entry/entry.html.twig
src/Wallabag/CoreBundle/Resources/views/themes/material/public/css/main.css

fix #972: add preview pictures

---

src/Wallabag/CoreBundle/Resources/views/themes/baggy/Entry/entries.html.twig
src/Wallabag/CoreBundle/Resources/views/themes/baggy/public/css/main.css
src/Wallabag/CoreBundle/Resources/views/themes/material/Entry/entries.xml.twig
src/Wallabag/CoreBundle/Resources/views/themes/material/Mail/forgotPassword.txt.twig

Follow up of #1402
Needs css animations. And media queries.

filters view on side for baggy

---

app/config/services.yml
src/Wallabag/CoreBundle/Resources/views/themes/baggy/Entry/entries.html.twig
src/Wallabag/CoreBundle/Resources/views/themes/material/Entry/entries.html.twig
src/Wallabag/CoreBundle/Twig/WallabagExtension.php

fix #1433: remove www. on entries view

---

inc/3rdparty/site_config/standard/pieria.co.uk.txt
inc/3rdparty/site_config/standard/rasgolatente.es.txt
inc/3rdparty/site_config/standard/thenews.coop.txt

pieria.co.uk
rasgolatente.es
thenews.coop

Add three new sites

---

inc/3rdparty/libraries/PHPePub/Zip.php

fix Content-Disposition header #1481

---

app/config/config.yml
app/config/services.yml
src/Wallabag/CoreBundle/Controller/ConfigController.php
src/Wallabag/CoreBundle/DependencyInjection/Configuration.php
src/Wallabag/CoreBundle/DependencyInjection/WallabagCoreExtension.php
src/Wallabag/CoreBundle/EventListener/LocaleListener.php
src/Wallabag/CoreBundle/EventListener/UserLocaleListener.php
src/Wallabag/CoreBundle/Form/Type/ConfigType.php
src/Wallabag/CoreBundle/Resources/config/services.yml
src/Wallabag/CoreBundle/Resources/translations/messages.fr.yml
src/Wallabag/CoreBundle/Tests/Controller/ConfigControllerTest.php
src/Wallabag/CoreBundle/Tests/EventListener/LocaleListenerTest.php
src/Wallabag/CoreBundle/Tests/EventListener/UserLocaleListenerTest.php

Need one test on listener. I wait for @j0k3r and the other PR.

[WIP] language selection on config screen

---

src/Wallabag/CoreBundle/Controller/EntryController.php

fix #1005 V2 redirect after deletion

---

app/SymfonyRequirements.php
composer.lock
src/Wallabag/CoreBundle/Resources/config/services.yml

I've allowed graby to redefine the logger so we can inject a logger from a different application and graby will inject its own log inside.
This is really useful when debugging.

Add graby log

---

app/config/parameters.yml.dist
app/config/tests/parameters.yml.dist.mysql
app/config/tests/parameters.yml.dist.pgsql
app/config/tests/parameters.yml.dist.sqlite
composer.json
composer.lock
src/Wallabag/CoreBundle/Controller/ExportController.php
src/Wallabag/CoreBundle/DataFixtures/ORM/LoadEntryData.php
src/Wallabag/CoreBundle/Entity/Entry.php
src/Wallabag/CoreBundle/Helper/EntriesExport.php
src/Wallabag/CoreBundle/Resources/config/services.yml
src/Wallabag/CoreBundle/Resources/views/themes/material/Entry/entries.html.twig
src/Wallabag/CoreBundle/Resources/views/themes/material/Entry/entry.html.twig
src/Wallabag/CoreBundle/Resources/views/themes/material/layout.html.twig
src/Wallabag/CoreBundle/Resources/views/themes/material/public/js/init.js
src/Wallabag/CoreBundle/Tests/Controller/ExportControllerTest.php

What routes would you like ?
For now I just have `/category/ebook/format` for groups of articles and `/ebook/id/format` for one entry.
Fix #79
Fix #701

V2 – Export entries

---

src/Wallabag/CoreBundle/Entity/TaggingRule.php
src/Wallabag/CoreBundle/Form/DataTransformer/StringToListTransformer.php
src/Wallabag/CoreBundle/Form/Type/TaggingRuleType.php
src/Wallabag/CoreBundle/Helper/ContentProxy.php
src/Wallabag/CoreBundle/Helper/RuleBasedTagger.php
src/Wallabag/CoreBundle/Tests/Controller/ExportControllerTest.php
src/Wallabag/CoreBundle/Tests/Form/DataTransformer/StringToListTransformerTest.php
src/Wallabag/CoreBundle/Tests/Helper/ContentProxyTest.php
src/Wallabag/CoreBundle/Tests/Helper/RuleBasedTaggerTest.php

changed table name for tagging rule

---

.travis.yml
composer.json
composer.lock

> Updates `composer.lock`.
Had to restrict scheb/two-factor-bundle to ~1.4.0 because of a circular service reference.
See https://github.com/scheb/two-factor-bundle/issues/33.

Updated composer.lock

---

app/AppKernel.php
app/config/config.yml
composer.json
composer.lock

Just the installation of doctrine migrations. 
No tests for that PR, right?

Installation & configuration of Doctrine Migrations

---

README.md

Setting the version will ensure people will have a functionnal app no matter what you do on the master v2 branch :)

Fix typo and set version in the README

---

docs/en/index.rst
docs/en/user/first_article.rst
src/Wallabag/CoreBundle/Controller/EntryController.php
src/Wallabag/CoreBundle/Controller/StaticController.php
src/Wallabag/CoreBundle/DataFixtures/ORM/LoadConfigData.php
src/Wallabag/CoreBundle/Repository/EntryRepository.php
src/Wallabag/CoreBundle/Resources/translations/messages.fr.yml
src/Wallabag/CoreBundle/Resources/views/themes/baggy/Static/quickstart.html.twig
src/Wallabag/CoreBundle/Resources/views/themes/material/Entry/new_form.html.twig
src/Wallabag/CoreBundle/Resources/views/themes/material/Static/quickstart.html.twig
src/Wallabag/CoreBundle/Tests/Controller/EntryControllerTest.php
src/Wallabag/UserBundle/DataFixtures/ORM/LoadUserData.php

Fix #1501 
Some URL are wrong, I know that. We'll change it when documentation will be finished and published.

Fix #1501 Quickstart for beginners

---

src/Wallabag/CoreBundle/Controller/EntryController.php
src/Wallabag/CoreBundle/Repository/EntryRepository.php
src/Wallabag/CoreBundle/Tests/Controller/EntryControllerTest.php
src/Wallabag/CoreBundle/Tests/WallabagCoreTestCase.php
src/Wallabag/ImportBundle/Import/PocketImport.php
src/Wallabag/ImportBundle/Import/WallabagV1Import.php
src/Wallabag/ImportBundle/Tests/Import/PocketImportTest.php
src/Wallabag/ImportBundle/Tests/Import/WallabagV1ImportTest.php

Fix `findOneByUrl` side effect in tests

---

app/config/config.yml
src/Wallabag/CoreBundle/Resources/translations/messages.de.yml
src/Wallabag/CoreBundle/Resources/translations/messages.fr.yml
src/Wallabag/CoreBundle/Resources/views/themes/baggy/Static/about.html.twig
src/Wallabag/CoreBundle/Resources/views/themes/material/Static/about.html.twig

As we don't want to use this service (they changed their website, we lost features, etc.), I think it's better to remove flattr into our application.

Remove Flattr references

---

src/Wallabag/UserBundle/Resources/views/TwoFactor/email_auth_code.html.twig

I don't know how to get the url address of the server =(
Instead I left a mark *{ wallabag_url }*, but you need to display the value of *wallabag_url* in *app/config/parameters.yml*
I mean, to address *{{ wallabag_url }}/themes/material/img/logo-other_themes.png* is */web/themes/material/img/logo-other_themes.png*

#1490 HTML in E-Mails

---

app/config/config_dev.yml
src/Wallabag/UserBundle/Mailer/AuthCodeMailer.php
src/Wallabag/UserBundle/Resources/config/services.yml
src/Wallabag/UserBundle/Resources/translations/wallabag_user.en.yml
src/Wallabag/UserBundle/Resources/translations/wallabag_user.fr.yml
src/Wallabag/UserBundle/Resources/views/TwoFactor/email_auth_code.html.twig
src/Wallabag/UserBundle/Tests/Mailer/AuthCodeMailerTest.php

Use HTML email for 2FA

---

app/config/config.yml
src/Wallabag/CoreBundle/Resources/translations/messages.tr.yml
src/Wallabag/UserBundle/Resources/translations/wallabag_user.tr.yml

Hi,
I love this package. And I did this to Turkish translation.
Best regards, Ogün Karakuş

Add Turkish translation

---

app/config/config.yml
app/config/parameters.yml.dist
app/config/tests/parameters.yml.dist.mysql
app/config/tests/parameters.yml.dist.pgsql
app/config/tests/parameters.yml.dist.sqlite
src/Wallabag/CoreBundle/Resources/views/themes/material/Entry/entries.html.twig
src/Wallabag/CoreBundle/Resources/views/themes/material/Entry/entry.html.twig

So that you need to type enter even more when entering `php bin/console wallabag:install` !

fix #1620 and introduce new parameters to export

---

app/config/tests/parameters.yml.dist.mysql
app/config/tests/parameters.yml.dist.pgsql
src/Wallabag/UserBundle/Resources/config/services.yml

Fix #1635: change database name for test environments (mysql/pgsql)

---

src/Wallabag/CoreBundle/Helper/EntriesExport.php

Exported entries were added twice in export file

---

src/Wallabag/CoreBundle/Controller/TagController.php
src/Wallabag/CoreBundle/Entity/Tag.php
src/Wallabag/CoreBundle/Repository/TagRepository.php
src/Wallabag/CoreBundle/Resources/views/themes/material/Entry/entry.html.twig
src/Wallabag/CoreBundle/Resources/views/themes/material/Tag/tags.html.twig
src/Wallabag/CoreBundle/Tests/Controller/TagControllerTest.php

remove tag from entry #1377

---

src/Wallabag/CoreBundle/Form/Type/NewUserType.php
src/Wallabag/CoreBundle/Resources/translations/validators.fr.yml
src/Wallabag/CoreBundle/Tests/Controller/ConfigControllerTest.php

This shows proper labels on the new user creation panel.

fix labels on new user prompt

---

src/Wallabag/CoreBundle/Resources/public/themes/baggy/css/main.css
src/Wallabag/CoreBundle/Resources/public/themes/baggy/js/init.js
src/Wallabag/CoreBundle/Resources/views/themes/baggy/Entry/entry.html.twig
src/Wallabag/CoreBundle/Resources/views/themes/baggy/layout.html.twig

Needs much more work, but here's a start.

improve baggy theme (add new tag panel)

---

app/config/config.yml
src/Wallabag/CoreBundle/Resources/translations/messages.ro.yml

Translation file for the 'Romanian' language. Also recognised by ro_RO. Known in romanian as "Română".

---

docs/en/developer/docker.rst
docs/en/developer/translate.rst
docs/en/index.rst

Documentation about translation

---

app/Resources/CraueConfigBundle/translations/CraueConfigBundle.ro.yml
src/Wallabag/CoreBundle/Resources/translations/validators.ro.yml

Translated another two files into romanian.

---

app/Resources/CraueConfigBundle/translations/CraueConfigBundle.pl.yml
app/config/config.yml

Hi, I prepared Polish translation

Polish translation

---

src/Wallabag/CoreBundle/Resources/translations/messages.fr.yml
src/Wallabag/CoreBundle/Resources/views/themes/baggy/Entry/entries.html.twig
src/Wallabag/CoreBundle/Resources/views/themes/material/Entry/entries.html.twig

Fix #1682
@wallabag/translators

translate estimated time minutes

---

src/Wallabag/ApiBundle/Controller/WallabagRestController.php
src/Wallabag/CoreBundle/Helper/ContentProxy.php
src/Wallabag/CoreBundle/Resources/config/services.yml
src/Wallabag/CoreBundle/Tests/Helper/ContentProxyTest.php
src/Wallabag/ImportBundle/Import/PocketImport.php
src/Wallabag/ImportBundle/Import/WallabagV1Import.php
src/Wallabag/ImportBundle/Tests/Import/PocketImportTest.php

| Fixed tickets | #1667
This'll fix #1667

Move assignTagsToEntry in ContentProxy helper

---

docs/en/index.rst
docs/en/user/installation.rst
docs/fr/index.rst
docs/fr/user/installation.rst

Need help to write requirements. @tcitworld, any idea?

Documentation for wallabag installation

---

docs/fr/user/installation.rst

typo in french documentation

---

app/AppKernel.php
app/config/config.yml
composer.json
docs/en/developer/maintenance.rst
docs/en/index.rst
docs/fr/developer/maintenance.rst
docs/fr/index.rst

| Fixed tickets | #1351 
~~We need to wait for this PR before merging https://github.com/lexik/LexikMaintenanceBundle/pull/52~~

Fix #1351: add maintenance mode

---

src/Wallabag/CoreBundle/Resources/translations/messages.fr.yml
src/Wallabag/CoreBundle/Resources/views/themes/baggy/Entry/entry.html.twig
src/Wallabag/CoreBundle/Resources/views/themes/material/Entry/entry.html.twig

display how much comments there are for an entry

---

src/Wallabag/CoreBundle/Resources/views/themes/material/Entry/entry.html.twig

move annotatorjs to the bottom of the body so that the "article" tag is loaded before

---

.github/CONTRIBUTING.md
.github/ISSUE_TEMPLATE.md

Fix #1711: Update CONTRIBUTING file

---

.composer-auth.json
.travis.yml

| Fixed tickets | #1703 
I created a personal token with no scope (tip found here https://github.com/composer/composer/issues/1314#issuecomment-151310499). We'll see if github authorizes it.

Fix: #1703: authentication for PR by external contributors

---

app/Resources/CraueConfigBundle/translations/CraueConfigBundle.da.yml
app/Resources/FOSUserBundle/translations/FOSUserBundle.da.yml
app/config/config.yml
src/Wallabag/CoreBundle/Resources/translations/messages.da.yml
src/Wallabag/CoreBundle/Resources/translations/validators.da.yml

Adding Danish translations to Wallabag v2

---

Gemfile
Gemfile.lock

Update Capistrano libraries with last versions

---

src/Wallabag/CoreBundle/Resources/translations/messages.fr.yml

minor typofix + missing quotes

---

README.md
app/config/config.yml
docs/en/user/installation.rst
docs/fr/user/installation.rst
src/Wallabag/CoreBundle/Resources/views/base.html.twig

Prepare wallabag for first beta :rocket:

---

.github/ISSUE_TEMPLATE.md

Add the way to install (package or composer)

---

RELEASE_PROCESS.md

The TL;DR duplicates what's below, but maybe some details are interesting to keep.
The part at the end about the PHP version needs to be finished.

Added RELEASE_PROCESS document

---

app/Resources/CraueConfigBundle/translations/CraueConfigBundle.es.yml
app/Resources/FOSUserBundle/translations/FOSUserBundle.es.yml
app/config/config.yml
src/Wallabag/CoreBundle/Resources/translations/messages.es.yml
src/Wallabag/CoreBundle/Resources/translations/validators.es.yml

V2 spanish translation

---

src/Wallabag/ApiBundle/Controller/WallabagRestController.php
src/Wallabag/ApiBundle/Tests/Controller/WallabagRestControllerTest.php

Add starred & archive properties to API

---

app/config/security.yml
src/Wallabag/ApiBundle/Controller/WallabagRestController.php
src/Wallabag/ApiBundle/Tests/Controller/WallabagRestControllerTest.php

V2 api version

---

src/Wallabag/CoreBundle/Resources/views/themes/baggy/Static/quickstart.html.twig
src/Wallabag/CoreBundle/Resources/views/themes/material/Static/quickstart.html.twig

Change documentation links in quickstart

---

src/Wallabag/CoreBundle/Resources/views/base.html.twig
src/Wallabag/ImportBundle/Tests/Import/PocketImportTest.php
src/Wallabag/ImportBundle/Tests/Import/WallabagV1ImportTest.php
src/Wallabag/ImportBundle/Tests/Import/WallabagV2ImportTest.php

Fix #1756: Added 'wallabag' in page title

---

docs/en/user/installation.rst
docs/fr/user/installation.rst

clarify that wllbg is compatible php 7

---

src/Wallabag/CoreBundle/Entity/Entry.php

API shows just what needed for user

---

src/Wallabag/ApiBundle/Tests/Controller/WallabagRestControllerTest.php

| Fixed tickets | https://github.com/wallabag/wallabag/pull/1786#issuecomment-196349245

add tests on user in API responses

---

src/Wallabag/CoreBundle/Resources/public/themes/material/css/main.css

| Fixed tickets | #1787
Fix #1787

fix tabs display on mobile view

---

src/Wallabag/CoreBundle/Resources/views/themes/baggy/layout.html.twig

Translate flash message in baggy theme

---

src/Wallabag/CoreBundle/Resources/views/themes/material/Entry/entry.html.twig

fix typo diaspora* share

---

app/Resources/FOSUserBundle/translations/FOSUserBundle.pl.yml

Correct translation

---

themes/baggy/css/messages.css
themes/default/_messages.twig

Preview with Baggy and default themes:

Add message on unread page about v2

---

themes/baggy/view.twig
themes/default/view.twig

| Tests pass?   | no way !
| Fixed tickets | #1309

remove buggy swipe actions

---

app/Resources/CraueConfigBundle/translations/CraueConfigBundle.oc.yml
app/Resources/FOSUserBundle/translations/FOSUserBundle.oc.yml
src/Wallabag/CoreBundle/Resources/translations/messages.oc.yml

I hope everything is fine now! Looking forward to seeing it running :)

Occitan version

---

src/Wallabag/CoreBundle/Resources/views/themes/baggy/layout.html.twig
src/Wallabag/CoreBundle/Resources/views/themes/material/layout.html.twig

| Fixed tickets | #1836 
Fix #1836

Hide search buttons

---

src/Wallabag/CoreBundle/Resources/translations/messages.da.yml
src/Wallabag/CoreBundle/Resources/translations/messages.de.yml
src/Wallabag/CoreBundle/Resources/translations/messages.en.yml
src/Wallabag/CoreBundle/Resources/translations/messages.es.yml
src/Wallabag/CoreBundle/Resources/translations/messages.fa.yml
src/Wallabag/CoreBundle/Resources/translations/messages.fr.yml
src/Wallabag/CoreBundle/Resources/translations/messages.oc.yml
src/Wallabag/CoreBundle/Resources/translations/messages.pl.yml
src/Wallabag/CoreBundle/Resources/translations/messages.ro.yml
src/Wallabag/CoreBundle/Resources/translations/messages.tr.yml

Fix Archive page title translation

---

docs/en/user/migration.rst
docs/fr/user/migration.rst

| Fixed tickets | #1764 
Fix #1764

Documentation about wallabag v1 CLI import

---

src/Wallabag/CoreBundle/Resources/views/themes/baggy/Entry/entries.html.twig
src/Wallabag/CoreBundle/Resources/views/themes/material/Entry/entries.html.twig

| Fixed tickets | #1859
Fix #1859

Round estimated time and add reading speed for Baggy

---

docs/en/user/migration.rst
docs/fr/user/migration.rst

Add production environment for CLI import

---

docs/en/developer/api.rst
docs/en/index.rst
docs/fr/developer/api.rst
docs/fr/index.rst
src/Wallabag/CoreBundle/Resources/translations/messages.da.yml
src/Wallabag/CoreBundle/Resources/translations/messages.de.yml
src/Wallabag/CoreBundle/Resources/translations/messages.en.yml
src/Wallabag/CoreBundle/Resources/translations/messages.es.yml
src/Wallabag/CoreBundle/Resources/translations/messages.fa.yml
src/Wallabag/CoreBundle/Resources/translations/messages.fr.yml
src/Wallabag/CoreBundle/Resources/translations/messages.oc.yml
src/Wallabag/CoreBundle/Resources/translations/messages.pl.yml
src/Wallabag/CoreBundle/Resources/translations/messages.ro.yml
src/Wallabag/CoreBundle/Resources/translations/messages.tr.yml
src/Wallabag/CoreBundle/Resources/views/themes/baggy/Developer/index.html.twig
src/Wallabag/CoreBundle/Resources/views/themes/material/Developer/index.html.twig

English documentation about wallabag API

---

src/Wallabag/CoreBundle/Resources/views/themes/material/Entry/entry.html.twig

| Fixed tickets | #1870
Fix #1870

Move tag form in Material theme

---

src/Wallabag/CoreBundle/Resources/views/themes/baggy/Config/index.html.twig
src/Wallabag/CoreBundle/Resources/views/themes/material/Config/index.html.twig

| Fixed tickets | #1889
Fix #1889

Fix typo on configuration page

---

src/Wallabag/CoreBundle/Resources/views/themes/baggy/Developer/index.html.twig
src/Wallabag/CoreBundle/Resources/views/themes/material/Developer/index.html.twig

Fix documentation link in developer page

---

src/Wallabag/CoreBundle/Resources/views/themes/material/Entry/entries.html.twig

| Fixed tickets | #1893
Fix #1893

Fix estimated reading time in material view

---

docs/en/user/installation.rst
docs/fr/user/installation.rst

| Fixed tickets | #1849 
Fix #1849: configuration to avoid 413 Request Entity Too Large.

Add documentation about importing large file into nginx

---

src/Wallabag/CoreBundle/Controller/EntryController.php

| Fixed tickets | #1886
Fix #1886
@j0k3r can you tell me if we need to refactor with `addEntryFormAction`? And do we need tests here?

Fix duplicate article when added via the bookmarklet

---

CHANGELOG.md
README.md
app/config/config.yml
docs/en/user/installation.rst
docs/fr/user/installation.rst

Prepare release 2.0.1

---

docs/en/user/errors_during_fetching.rst
docs/en/user/installation.rst
docs/fr/user/errors_during_fetching.rst
docs/fr/user/installation.rst

Fix doc links

---

src/Wallabag/CoreBundle/Resources/views/themes/baggy/Entry/entries.html.twig
src/Wallabag/CoreBundle/Resources/views/themes/material/Entry/entries.html.twig

add title hover on entry titles

---

composer.json
src/Wallabag/CoreBundle/Resources/views/themes/baggy/Static/about.html.twig
src/Wallabag/CoreBundle/Resources/views/themes/material/Static/about.html.twig

Remove useless dependancy

---

inc/poche/Poche.class.php
inc/poche/Tools.class.php

Fix UTF-8 encoding before JSON export

---

src/Wallabag/CoreBundle/Resources/views/themes/baggy/Entry/entries.xml.twig
src/Wallabag/CoreBundle/Resources/views/themes/material/Entry/entries.xml.twig

| Fixed tickets | #1926 
Fix #1926

Change guid and link in RSS feeds to give original entry URL

---

src/Wallabag/CoreBundle/Controller/EntryController.php
src/Wallabag/CoreBundle/Controller/TagController.php
src/Wallabag/CoreBundle/Helper/Redirect.php
src/Wallabag/CoreBundle/Resources/config/services.yml
src/Wallabag/CoreBundle/Tests/Helper/RedirectTest.php

| Fixed tickets | #1924
Fix #1924

Redirect to homepage if referer is null

---

src/Wallabag/CoreBundle/Resources/views/themes/baggy/Entry/entries.html.twig
src/Wallabag/CoreBundle/Resources/views/themes/material/Entry/entries.html.twig

| Fixed tickets | #1932 
Fix #1932

Hide pagination if we only have one entry to display

---

src/Wallabag/CoreBundle/Resources/views/themes/baggy/Entry/entries.html.twig
src/Wallabag/CoreBundle/Resources/views/themes/material/Entry/entries.html.twig

| Fixed tickets | #1932 
Fix #1932

Display pagination only if we have more than one page

---

.travis.yml

Update Travis configuration with branches renaming

---

docs/en/developer/translate.rst
docs/fr/developer/translate.rst

Actualisation des liens morts (Documentation de traduction)

---

app/config/capistrano/deploy/staging.rb
src/Wallabag/CoreBundle/Resources/views/themes/baggy/Developer/index.html.twig
src/Wallabag/CoreBundle/Resources/views/themes/baggy/Static/about.html.twig
src/Wallabag/CoreBundle/Resources/views/themes/baggy/Static/quickstart.html.twig
src/Wallabag/CoreBundle/Resources/views/themes/material/Developer/index.html.twig
src/Wallabag/CoreBundle/Resources/views/themes/material/Static/about.html.twig
src/Wallabag/CoreBundle/Resources/views/themes/material/Static/quickstart.html.twig

Update links in documentation

---

docs/en/developer/api.rst

| Fixed tickets | #1939
Fix #1939

Added some curl examples

---

src/Wallabag/UserBundle/Resources/views/Registration/confirmed.html.twig

| Fixed tickets | #1956 
Fix #1956

Fix translation for Go to your account button after subscription

---

CHANGELOG.md
README.md
app/config/config.yml
docs/en/user/installation.rst
docs/fr/user/installation.rst

Need to update `CHANGELOG.md`.

Prepare release 2.0.2

---

docs/en/developer/api.rst
docs/fr/developer/api.rst

Update API documentation with cURL examples

---

CHANGELOG.md
README.md
app/config/config.yml
docs/en/user/installation.rst
docs/fr/user/installation.rst

Prepare release 2.0.3

---

docs/en/index.rst
docs/en/user/faq.rst
docs/fr/index.rst
docs/fr/user/faq.rst

| Fixed tickets | #1961
Fix #1961

Add FAQ page in documentation

---

docs/en/developer/api.rst
docs/fr/developer/api.rst

Added documentation about https://github.com/foxmask/wallabag_api by @foxmask.

Create 3rd Resources chapter in API documentation

---

docs/en/developer/api.rst
docs/fr/developer/api.rst

Thanks @tcitworld for your help!

Fix typos in API documentation

---

src/Wallabag/CoreBundle/Resources/translations/messages.es.yml

Es translation

---

docs/en/user/installation.rst
docs/fr/user/installation.rst

Rights access to the folders of the project

---

docs/en/user/migration.rst
docs/fr/user/migration.rst

Fix old branch name urls

---

src/Wallabag/ApiBundle/Controller/WallabagRestController.php
src/Wallabag/ApiBundle/Tests/Controller/WallabagRestControllerTest.php

| Fixed tickets | #2009 
Fix #2009

Set the title via POST /api/entries

---

docs/en/user/upgrade.rst

Creation of an upgrade page in the documentation

upgrade.rst (Creation of an upgrade page in the documentation)

---

docs/en/index.rst

Following: https://github.com/wallabag/wallabag/pull/2011#issuecomment-216219705

integrate upgrade.rst

---

src/Wallabag/CoreBundle/Form/Type/EntryFilterType.php
src/Wallabag/CoreBundle/Tests/Controller/ConfigControllerTest.php
src/Wallabag/CoreBundle/Tests/Controller/EntryControllerTest.php

| Fixed tickets | #1975 
Fix #1975 
I'm sure that @j0k3r will tell me "tests are missing"... :smile:

Fix filter reading time

---

src/Wallabag/CoreBundle/Controller/TagController.php
src/Wallabag/CoreBundle/Repository/TagRepository.php
src/Wallabag/CoreBundle/Resources/views/themes/baggy/Tag/tags.html.twig
src/Wallabag/CoreBundle/Resources/views/themes/material/Tag/tags.html.twig

| Fixed tickets | #1994 
Fix #1994
* Remove unused method in tag repository (I don't know why we used pager for tags)

Fix tags listing

---

app/config/config.yml

add italian as available language

Update config.yml, add italian as available language

---

src/Wallabag/CoreBundle/Resources/public/themes/material/css/main.css
src/Wallabag/CoreBundle/Resources/views/themes/baggy/Entry/entries.html.twig
src/Wallabag/CoreBundle/Resources/views/themes/baggy/Entry/pager.html.twig
src/Wallabag/CoreBundle/Resources/views/themes/material/Entry/entries.html.twig
src/Wallabag/CoreBundle/Resources/views/themes/material/Entry/pager.html.twig

| Fixed tickets | #2008, #2021
Fix #2008

Fix pagination bar on small devices

---

src/Wallabag/CoreBundle/Entity/Tag.php
src/Wallabag/CoreBundle/Resources/views/themes/baggy/Tag/tags.html.twig
src/Wallabag/CoreBundle/Resources/views/themes/material/Tag/tags.html.twig

| Fixed tickets | #2006 
Fix #2006
What kind of tests?

Fix number of entries in tag/list

---

docs/en/developer/translate.rst
docs/fr/developer/translate.rst
src/Wallabag/CoreBundle/Resources/translations/messages.da.yml
src/Wallabag/CoreBundle/Resources/translations/messages.de.yml
src/Wallabag/CoreBundle/Resources/translations/messages.en.yml
src/Wallabag/CoreBundle/Resources/translations/messages.es.yml
src/Wallabag/CoreBundle/Resources/translations/messages.fa.yml
src/Wallabag/CoreBundle/Resources/translations/messages.fr.yml
src/Wallabag/CoreBundle/Resources/translations/messages.it.yml
src/Wallabag/CoreBundle/Resources/translations/messages.oc.yml
src/Wallabag/CoreBundle/Resources/translations/messages.pl.yml
src/Wallabag/CoreBundle/Resources/translations/messages.ro.yml
src/Wallabag/CoreBundle/Resources/translations/messages.tr.yml
src/Wallabag/CoreBundle/Resources/translations/validators.da.yml
src/Wallabag/CoreBundle/Resources/translations/validators.de.yml
src/Wallabag/CoreBundle/Resources/translations/validators.en.yml
src/Wallabag/CoreBundle/Resources/translations/validators.es.yml
src/Wallabag/CoreBundle/Resources/translations/validators.fa.yml
src/Wallabag/CoreBundle/Resources/translations/validators.fr.yml
src/Wallabag/CoreBundle/Resources/translations/validators.it.yml
src/Wallabag/CoreBundle/Resources/translations/validators.oc.yml
src/Wallabag/CoreBundle/Resources/translations/validators.pl.yml
src/Wallabag/CoreBundle/Resources/translations/validators.ro.yml
src/Wallabag/CoreBundle/Resources/translations/validators.tr.yml

| Fixed tickets | #2003 
Fix #2003

Fix translation for validators

---

CHANGELOG.md
README.md
app/config/config.yml
docs/en/user/installation.rst
docs/fr/user/installation.rst

Prepare wallabag 2.0.4

---

docs/en/user/installation.rst
docs/fr/user/installation.rst

new details in the doc about the rights access again;)

---

docs/en/user/installation.rst

Added information about permissions on data/

---

.github/CONTRIBUTING.md

| Fixed tickets | #2059 
Fix #2059

Update CONTRIBUTING file

---

src/Wallabag/CoreBundle/Resources/views/themes/material/Entry/entries.html.twig

| Fixed tickets | #2065 
Fix #2065

Replace vertical dots in material theme with horizontal dots

---

src/Wallabag/ApiBundle/Controller/WallabagRestController.php
src/Wallabag/ApiBundle/Tests/Controller/WallabagRestControllerTest.php

Starred and Archived clears if article is already exists

---

src/Wallabag/UserBundle/Resources/views/TwoFactor/email_auth_code.html.twig

| Fixed tickets | #2045
Fix the broken url to image ressource hosted on wallabag.org

Fix image path in 2-factor authentification email

---

src/Wallabag/CoreBundle/Resources/translations/messages.en.yml

| Tests pass?   | Didn't run tests - just a translation fix
| License       | [unlicensed](http://unlicense.org/)

Improve English translation

---

docs/en/user/faq.rst
docs/en/user/installation.rst

| Tests pass?   | didn't run tests
| Fixed tickets | #2108 
| License       | [unlicensed](http://unlicense.org/)
I'd like to have added a bit more regarding php and php-fpm setup but my problems were specific to my particular setup and I wanted to be general. Maybe we could add a new page altogether for distro-specific instructions - I could cover CentOS if others were able to cover Debian, Arch, and others. However, I assume most people will just use composer, which would presumably make installation a lot easier although it didn't work in my case.

Docs proposal

---

src/Wallabag/CoreBundle/Controller/EntryController.php
src/Wallabag/CoreBundle/DataFixtures/ORM/LoadConfigData.php
src/Wallabag/CoreBundle/DataFixtures/ORM/LoadTaggingRuleData.php
src/Wallabag/CoreBundle/Entity/Entry.php
src/Wallabag/CoreBundle/Entity/Tag.php
src/Wallabag/CoreBundle/Resources/translations/messages.da.yml
src/Wallabag/CoreBundle/Resources/translations/messages.de.yml
src/Wallabag/CoreBundle/Resources/translations/messages.en.yml
src/Wallabag/CoreBundle/Resources/translations/messages.es.yml
src/Wallabag/CoreBundle/Resources/translations/messages.fa.yml
src/Wallabag/CoreBundle/Resources/translations/messages.fr.yml
src/Wallabag/CoreBundle/Resources/translations/messages.it.yml
src/Wallabag/CoreBundle/Resources/translations/messages.oc.yml
src/Wallabag/CoreBundle/Resources/translations/messages.pl.yml
src/Wallabag/CoreBundle/Resources/translations/messages.ro.yml
src/Wallabag/CoreBundle/Resources/translations/messages.tr.yml
src/Wallabag/CoreBundle/Tests/Controller/EntryControllerTest.php

| Fixed tickets | #2121 
Fix #2121

Fix the deletion of Tags/Entries relation when delete an entry

---

CHANGELOG.md
README.md
app/config/config.yml
docs/en/user/installation.rst
docs/fr/user/installation.rst

Prepare 2.0.5
https://github.com/wallabag/wallabag/compare/2.0.4...master

Prepare wallabag 2.0.5

---

bin/php-cs-fixer

| Fixed tickets | https://github.com/wallabag/wallabag/pull/2155

Update symlink to php-cs-fixer

---

src/Wallabag/CoreBundle/Resources/translations/messages.fr.yml

Fix a few french translations typos

---

package.json

Add modules when NodeJS versions are too low.

---

Gruntfile.js
bower.json

Another one, sorry for the inconvenience, works great now.

fix font paths

---

app/Resources/static/themes/material/css/main.css
src/Wallabag/CoreBundle/Resources/translations/messages.da.yml
src/Wallabag/CoreBundle/Resources/translations/messages.de.yml
src/Wallabag/CoreBundle/Resources/translations/messages.en.yml
src/Wallabag/CoreBundle/Resources/translations/messages.es.yml
src/Wallabag/CoreBundle/Resources/translations/messages.fa.yml
src/Wallabag/CoreBundle/Resources/translations/messages.fr.yml
src/Wallabag/CoreBundle/Resources/translations/messages.it.yml
src/Wallabag/CoreBundle/Resources/translations/messages.oc.yml
src/Wallabag/CoreBundle/Resources/translations/messages.pl.yml
src/Wallabag/CoreBundle/Resources/translations/messages.ro.yml
src/Wallabag/CoreBundle/Resources/translations/messages.tr.yml
src/Wallabag/CoreBundle/Resources/views/themes/material/Entry/entries.html.twig
src/Wallabag/CoreBundle/Resources/views/themes/material/Entry/entry.html.twig

| Fixed tickets | #1995
Should be tested on old browsers.
Originally at #2166

Add tags on entries view and minor ui fixes

---

src/Wallabag/ApiBundle/Controller/WallabagRestController.php
src/Wallabag/CoreBundle/Repository/EntryRepository.php
tests/Wallabag/ApiBundle/Controller/WallabagRestControllerTest.php

| Fixed tickets | #1982
May need documentation updates.
Fix #1982

Add since parameter

---

src/Wallabag/ApiBundle/Controller/WallabagRestController.php
src/Wallabag/CoreBundle/Repository/EntryRepository.php
tests/Wallabag/ApiBundle/Controller/WallabagRestControllerTest.php

| New feature?  | should have been there before
| Fixed tickets | #1984 
Tag-related, so I targeted 2.1.

Add filter for tags on API

---

src/Wallabag/CoreBundle/Resources/views/themes/material/layout.html.twig

Fix 3rd-Party Apps links (Chrome & Firefox)

---

app/Resources/static/themes/baggy/css/main.css
app/Resources/static/themes/material/css/main.css
src/Wallabag/CoreBundle/Resources/views/themes/baggy/Entry/entries.html.twig
src/Wallabag/CoreBundle/Resources/views/themes/material/Entry/entries.html.twig

Also, a couple of UI improvement and CSS fixing.
Follows #2170 but for baggy this time.

Bring tags on entries view to baggy

---

src/Wallabag/CoreBundle/Resources/translations/messages.es.yml

Fixed spelling Artúclos --> Artículos

---

.travis.yml
bin/symfony_requirements
composer.json

Run PHP 7.1 on Travis

---

src/Wallabag/CoreBundle/Repository/EntryRepository.php

add some missing phpdoc parameters

---

.travis.yml
composer.json
tests/Wallabag/CoreBundle/EventListener/LocaleListenerTest.php

Fix PHPunit 5 warnings

---

CHANGELOG.md
README.md
app/config/config.yml
docs/de/user/installation.rst
docs/en/user/installation.rst
docs/fr/user/installation.rst

Prepare release 2.0.6

---

src/Wallabag/CoreBundle/Controller/EntryController.php
src/Wallabag/CoreBundle/Controller/ExportController.php
src/Wallabag/CoreBundle/Controller/TagController.php
src/Wallabag/CoreBundle/DataFixtures/ORM/LoadTagData.php
src/Wallabag/CoreBundle/Helper/PreparePagerForEntries.php
src/Wallabag/CoreBundle/Resources/config/services.yml
src/Wallabag/CoreBundle/Resources/translations/messages.da.yml
src/Wallabag/CoreBundle/Resources/translations/messages.de.yml
src/Wallabag/CoreBundle/Resources/translations/messages.en.yml
src/Wallabag/CoreBundle/Resources/translations/messages.es.yml
src/Wallabag/CoreBundle/Resources/translations/messages.fa.yml
src/Wallabag/CoreBundle/Resources/translations/messages.fr.yml
src/Wallabag/CoreBundle/Resources/translations/messages.oc.yml
src/Wallabag/CoreBundle/Resources/translations/messages.pl.yml
src/Wallabag/CoreBundle/Resources/translations/messages.ro.yml
src/Wallabag/CoreBundle/Resources/translations/messages.tr.yml
src/Wallabag/CoreBundle/Resources/views/themes/baggy/Entry/entries.html.twig
src/Wallabag/CoreBundle/Resources/views/themes/baggy/Tag/tags.html.twig
src/Wallabag/CoreBundle/Resources/views/themes/material/Entry/entries.html.twig
src/Wallabag/CoreBundle/Resources/views/themes/material/Tag/tags.html.twig
tests/Wallabag/CoreBundle/Controller/TagControllerTest.php

Just a first draft. 
Feel free to comment. For example, I'm not sure that my service is useful. 
TODO :

Links on each tag in Tags view

---

app/DoctrineMigrations/Version20160812120952.php
src/Wallabag/ApiBundle/Entity/Client.php
src/Wallabag/CoreBundle/Controller/DeveloperController.php
src/Wallabag/CoreBundle/Form/Type/ClientType.php
src/Wallabag/CoreBundle/Resources/translations/messages.en.yml
src/Wallabag/CoreBundle/Resources/translations/messages.fr.yml
src/Wallabag/CoreBundle/Resources/views/themes/baggy/Developer/client.html.twig
src/Wallabag/CoreBundle/Resources/views/themes/baggy/Developer/client_parameters.html.twig
src/Wallabag/CoreBundle/Resources/views/themes/baggy/Developer/index.html.twig
src/Wallabag/CoreBundle/Resources/views/themes/material/Developer/client.html.twig
src/Wallabag/CoreBundle/Resources/views/themes/material/Developer/client_parameters.html.twig
src/Wallabag/CoreBundle/Resources/views/themes/material/Developer/index.html.twig
tests/Wallabag/CoreBundle/Controller/DeveloperControllerTest.php

| Fixed tickets | #1765
Needs migrations.
Fix #1765 
Following #2107
Originally at  #2119

Name api clients

---

app/config/config.yml

Enable CORS headers for OAUTH part

---

.travis.yml

Related: https://github.com/symfony/symfony/pull/18947/files

Run tests on an uptodate HHVM

---

app/config/config.yml

| Bug fix?      | yes|
| New feature?  | no|
| BC breaks?    | no|

Enable PATCH method for CORS in API part

---

src/Wallabag/CoreBundle/Controller/EntryController.php
src/Wallabag/CoreBundle/Resources/translations/messages.da.yml
src/Wallabag/CoreBundle/Resources/translations/messages.de.yml
src/Wallabag/CoreBundle/Resources/translations/messages.en.yml
src/Wallabag/CoreBundle/Resources/translations/messages.es.yml
src/Wallabag/CoreBundle/Resources/translations/messages.fa.yml
src/Wallabag/CoreBundle/Resources/translations/messages.fr.yml
src/Wallabag/CoreBundle/Resources/translations/messages.it.yml
src/Wallabag/CoreBundle/Resources/translations/messages.oc.yml
src/Wallabag/CoreBundle/Resources/translations/messages.pl.yml
src/Wallabag/CoreBundle/Resources/translations/messages.ro.yml
src/Wallabag/CoreBundle/Resources/translations/messages.tr.yml
src/Wallabag/CoreBundle/Resources/views/themes/baggy/Entry/entry.html.twig
src/Wallabag/CoreBundle/Resources/views/themes/material/Entry/entries.html.twig
src/Wallabag/CoreBundle/Resources/views/themes/material/Entry/entry.html.twig
src/Wallabag/ImportBundle/Import/PocketImport.php

| Fixed tickets | #2041 
Fix #2041

Replaced favorite word/icon with star one

---

CHANGELOG.md
README.md
app/config/config.yml
docs/de/user/installation.rst
docs/en/user/installation.rst
docs/fr/user/installation.rst

Prepare wallabag 2.0.7

---

docs/de/user/errors_during_fetching.rst
docs/en/user/errors_during_fetching.rst
docs/fr/user/errors_during_fetching.rst

| Bug fix?      | yes|
| New feature?  | no|
| BC breaks?    | no|
| Deprecations? | no|
| Tests pass?   | yes|
| Documentation | yes|
| Fixed tickets |-
No functional changes.

Fixes mailto link in documentation

---

app/config/config.yml
app/config/parameters.yml.dist
src/Wallabag/UserBundle/Controller/RegistrationController.php
src/Wallabag/UserBundle/Controller/SecurityController.php
src/Wallabag/UserBundle/DependencyInjection/Configuration.php
src/Wallabag/UserBundle/DependencyInjection/WallabagUserExtension.php
src/Wallabag/UserBundle/Resources/views/Security/login.html.twig
tests/Wallabag/CoreBundle/Command/InstallCommandTest.php
tests/Wallabag/CoreBundle/Controller/SecurityControllerTest.php

| Tests pass?   |no
| Fixed tickets | #1873

Add option to disable registration

---

src/Wallabag/CoreBundle/Resources/views/themes/share.html.twig

Add original link in public view of the article

---

app/Resources/static/themes/material/css/main.css
src/Wallabag/CoreBundle/Resources/views/themes/material/Entry/entry.html.twig

Add icon for public share link

---

src/Wallabag/CoreBundle/Resources/views/themes/_title.html.twig
src/Wallabag/CoreBundle/Resources/views/themes/baggy/Entry/entries.html.twig
src/Wallabag/CoreBundle/Resources/views/themes/material/Entry/entries.html.twig

| Fixed tickets | #2244
Fixed #2244

Changed where page title is displayed

---

src/Wallabag/CoreBundle/Controller/EntryController.php
src/Wallabag/CoreBundle/Controller/ExportController.php
src/Wallabag/CoreBundle/Repository/EntryRepository.php
src/Wallabag/CoreBundle/Resources/translations/messages.da.yml
src/Wallabag/CoreBundle/Resources/translations/messages.de.yml
src/Wallabag/CoreBundle/Resources/translations/messages.en.yml
src/Wallabag/CoreBundle/Resources/translations/messages.es.yml
src/Wallabag/CoreBundle/Resources/translations/messages.fa.yml
src/Wallabag/CoreBundle/Resources/translations/messages.fr.yml
src/Wallabag/CoreBundle/Resources/translations/messages.it.yml
src/Wallabag/CoreBundle/Resources/translations/messages.oc.yml
src/Wallabag/CoreBundle/Resources/translations/messages.pl.yml
src/Wallabag/CoreBundle/Resources/translations/messages.ro.yml
src/Wallabag/CoreBundle/Resources/translations/messages.tr.yml
src/Wallabag/CoreBundle/Resources/views/themes/_title.html.twig
src/Wallabag/CoreBundle/Resources/views/themes/baggy/Tag/tags.html.twig
src/Wallabag/CoreBundle/Resources/views/themes/material/Tag/tags.html.twig
tests/Wallabag/CoreBundle/Controller/EntryControllerTest.php

| Fixed tickets | #1631 
Fix #1631
Needs : 
* tests
* documentation

Add untagged entries

---

docs/en/user/import.rst
docs/fr/user/import.rst
src/Wallabag/CoreBundle/Resources/translations/messages.da.yml
src/Wallabag/CoreBundle/Resources/translations/messages.de.yml
src/Wallabag/CoreBundle/Resources/translations/messages.en.yml
src/Wallabag/CoreBundle/Resources/translations/messages.es.yml
src/Wallabag/CoreBundle/Resources/translations/messages.fa.yml
src/Wallabag/CoreBundle/Resources/translations/messages.fr.yml
src/Wallabag/CoreBundle/Resources/translations/messages.it.yml
src/Wallabag/CoreBundle/Resources/translations/messages.oc.yml
src/Wallabag/CoreBundle/Resources/translations/messages.pl.yml
src/Wallabag/CoreBundle/Resources/translations/messages.ro.yml
src/Wallabag/CoreBundle/Resources/translations/messages.tr.yml
src/Wallabag/CoreBundle/Resources/views/themes/baggy/Static/quickstart.html.twig
src/Wallabag/CoreBundle/Resources/views/themes/material/Static/quickstart.html.twig
src/Wallabag/ImportBundle/Controller/ReadabilityController.php
src/Wallabag/ImportBundle/Import/ReadabilityImport.php
src/Wallabag/ImportBundle/Resources/config/services.yml
src/Wallabag/ImportBundle/Resources/views/Readability/index.html.twig
tests/Wallabag/ImportBundle/Controller/ImportControllerTest.php
tests/Wallabag/ImportBundle/Controller/ReadabilityControllerTest.php
tests/Wallabag/ImportBundle/Import/ReadabilityImportTest.php
tests/Wallabag/ImportBundle/fixtures/readability-read.json
tests/Wallabag/ImportBundle/fixtures/readability.json

| Documentation | todo
| Fixed tickets | https://github.com/wallabag/wallabag/issues/2253
Based on the JSON export instead of the API (which will be shutting down by the September 30, 2016).
This is a WIP, I spent few minutes this morning to setup a working draft.

Add Readability import

---

app/Resources/static/themes/baggy/css/print.css
app/Resources/static/themes/material/css/print.css
src/Wallabag/CoreBundle/Resources/views/themes/baggy/Entry/entry.html.twig
src/Wallabag/CoreBundle/Resources/views/themes/material/Entry/entry.html.twig

Fix print / article views

---

app/Resources/static/themes/material/css/main.css
src/Wallabag/CoreBundle/Resources/views/themes/material/Config/index.html.twig

| Fixed tickets | #1788 
Fix #1788

Fixed different font-size for labels in config screen

---

app/config/services.yml
src/Wallabag/ApiBundle/Controller/WallabagRestController.php
src/Wallabag/CoreBundle/Controller/TagController.php
src/Wallabag/CoreBundle/Repository/EntryRepository.php
src/Wallabag/CoreBundle/Repository/TagRepository.php
src/Wallabag/CoreBundle/Resources/config/services.yml
src/Wallabag/CoreBundle/Resources/views/themes/material/layout.html.twig
src/Wallabag/CoreBundle/Twig/WallabagExtension.php

Added tags counter in sidebar (material theme)

---

CHANGELOG.md
README.md
app/config/config.yml
docs/de/user/installation.rst
docs/de/user/upgrade.rst
docs/en/user/installation.rst
docs/en/user/upgrade.rst
docs/fr/user/installation.rst
docs/fr/user/upgrade.rst

Prepare wallabag 2.0.8

---

src/Wallabag/CoreBundle/Resources/views/themes/baggy/Entry/entry.html.twig
src/Wallabag/CoreBundle/Resources/views/themes/material/Entry/entry.html.twig

| Fixed tickets | #2286 
Fix #2286

Fixed label for mark as read link in entry view

---

app/Resources/CraueConfigBundle/translations/CraueConfigBundle.pl.yml
src/Wallabag/CoreBundle/Resources/translations/messages.pl.yml
src/Wallabag/UserBundle/Resources/translations/wallabag_user.pl.yml

create wallabag_user.pl.yml file

polish version

---

app/config/config.yml
docs/en/user/import.rst
docs/fr/user/import.rst
src/Wallabag/CoreBundle/Resources/translations/messages.da.yml
src/Wallabag/CoreBundle/Resources/translations/messages.de.yml
src/Wallabag/CoreBundle/Resources/translations/messages.en.yml
src/Wallabag/CoreBundle/Resources/translations/messages.es.yml
src/Wallabag/CoreBundle/Resources/translations/messages.fa.yml
src/Wallabag/CoreBundle/Resources/translations/messages.fr.yml
src/Wallabag/CoreBundle/Resources/translations/messages.it.yml
src/Wallabag/CoreBundle/Resources/translations/messages.oc.yml
src/Wallabag/CoreBundle/Resources/translations/messages.pl.yml
src/Wallabag/CoreBundle/Resources/translations/messages.ro.yml
src/Wallabag/CoreBundle/Resources/translations/messages.tr.yml
src/Wallabag/ImportBundle/Command/RedisWorkerCommand.php
src/Wallabag/ImportBundle/Controller/ImportController.php
src/Wallabag/ImportBundle/Controller/InstapaperController.php
src/Wallabag/ImportBundle/Import/AbstractImport.php
src/Wallabag/ImportBundle/Import/BrowserImport.php
src/Wallabag/ImportBundle/Import/InstapaperImport.php
src/Wallabag/ImportBundle/Import/ReadabilityImport.php
src/Wallabag/ImportBundle/Import/WallabagImport.php
src/Wallabag/ImportBundle/Resources/config/rabbit.yml
src/Wallabag/ImportBundle/Resources/config/redis.yml
src/Wallabag/ImportBundle/Resources/config/services.yml
src/Wallabag/ImportBundle/Resources/views/Instapaper/index.html.twig
tests/Wallabag/ImportBundle/Controller/ImportControllerTest.php
tests/Wallabag/ImportBundle/Controller/InstapaperControllerTest.php
tests/Wallabag/ImportBundle/Import/InstapaperImportTest.php
tests/Wallabag/ImportBundle/fixtures/instapaper-export.csv

Also update ImportController with latest import (chrome, firefox & instapaper).

Add Instapaper import

---

app/Resources/static/themes/material/css/main.css

| Fixed tickets | #2302, #2281 
Fix #2302, #2281

Remove CSS class who caused long loading on Firefox

---

src/Wallabag/CoreBundle/Resources/translations/messages.da.yml
src/Wallabag/CoreBundle/Resources/translations/messages.de.yml
src/Wallabag/CoreBundle/Resources/translations/messages.en.yml
src/Wallabag/CoreBundle/Resources/translations/messages.es.yml
src/Wallabag/CoreBundle/Resources/translations/messages.fa.yml
src/Wallabag/CoreBundle/Resources/translations/messages.fr.yml
src/Wallabag/CoreBundle/Resources/translations/messages.it.yml
src/Wallabag/CoreBundle/Resources/translations/messages.oc.yml
src/Wallabag/CoreBundle/Resources/translations/messages.pl.yml
src/Wallabag/CoreBundle/Resources/translations/messages.ro.yml
src/Wallabag/CoreBundle/Resources/translations/messages.tr.yml

to be ready for the future of Wallabag :)

Occitan version update

---

src/Wallabag/CoreBundle/Controller/ConfigController.php
src/Wallabag/CoreBundle/Resources/translations/messages.da.yml
src/Wallabag/CoreBundle/Resources/translations/messages.de.yml
src/Wallabag/CoreBundle/Resources/translations/messages.en.yml
src/Wallabag/CoreBundle/Resources/translations/messages.es.yml
src/Wallabag/CoreBundle/Resources/translations/messages.fa.yml
src/Wallabag/CoreBundle/Resources/translations/messages.fr.yml
src/Wallabag/CoreBundle/Resources/translations/messages.it.yml
src/Wallabag/CoreBundle/Resources/translations/messages.oc.yml
src/Wallabag/CoreBundle/Resources/translations/messages.pl.yml
src/Wallabag/CoreBundle/Resources/translations/messages.ro.yml
src/Wallabag/CoreBundle/Resources/views/themes/baggy/Config/index.html.twig
src/Wallabag/CoreBundle/Resources/views/themes/material/Config/index.html.twig
tests/Wallabag/CoreBundle/Controller/ConfigControllerTest.php

| Fixed tickets | https://github.com/wallabag/wallabag/issues/1794
Should fix https://github.com/wallabag/wallabag/issues/1794

Add ability to edit a tagging rule

---

app/Resources/static/themes/material/css/main.css
src/Wallabag/CoreBundle/Resources/translations/messages.da.yml
src/Wallabag/CoreBundle/Resources/translations/messages.de.yml
src/Wallabag/CoreBundle/Resources/translations/messages.en.yml
src/Wallabag/CoreBundle/Resources/translations/messages.es.yml
src/Wallabag/CoreBundle/Resources/translations/messages.fa.yml
src/Wallabag/CoreBundle/Resources/translations/messages.fr.yml
src/Wallabag/CoreBundle/Resources/translations/messages.it.yml
src/Wallabag/CoreBundle/Resources/translations/messages.oc.yml
src/Wallabag/CoreBundle/Resources/translations/messages.pl.yml
src/Wallabag/CoreBundle/Resources/translations/messages.ro.yml
src/Wallabag/CoreBundle/Resources/translations/messages.tr.yml
src/Wallabag/CoreBundle/Resources/views/themes/common/Static/quickstart.html.twig
tests/Wallabag/CoreBundle/Controller/EntryControllerTest.php

@mruminski @Strubbl @jlnostr I need your help to translate new strings. 
Preview:

Changed quickstart layout

---

src/Wallabag/ApiBundle/Controller/WallabagRestController.php
src/Wallabag/CoreBundle/Repository/EntryRepository.php
tests/Wallabag/ApiBundle/Controller/WallabagRestControllerTest.php

| Fixed tickets | https://github.com/wallabag/wallabag/issues/2305
Should fix https://github.com/wallabag/wallabag/issues/2305
We forgot to pass them to the factory.

Fix parameters in API _links

---

src/Wallabag/CoreBundle/Resources/translations/messages.de.yml

Könnt ihr bitte meine Übersetzung auf Fehler/Verbesserungen prüfen, @mruminski @jlnostr ?
@nicosomb i translated some more missing strings than the quickstart ones. Hope that is okay.

for 2.1, translate all strings to German, which haven't been translated yet

---

app/Resources/static/themes/material/css/main.css
src/Wallabag/CoreBundle/Resources/views/themes/common/Static/quickstart.html.twig

I made sh*t with quickstart CSS.

Fixed CSS for quickstart links

---

CHANGELOG.md
README.md
docs/de/user/installation.rst
docs/en/user/installation.rst
docs/fr/user/installation.rst

:rocket: :tada: :champagne: ❤️

Prepare wallabag 2.1.0 :rocket:

---

src/Wallabag/CoreBundle/Resources/translations/messages.de.yml

| Bug fix?      | |no
| New feature?  | |no
| BC breaks?    | |no
| Deprecations? | |no
| Tests pass?   | |no
| Documentation | |no
just one sentence which was not translated very good.

 small improvement for german translation

---

docs/de/user/installation.rst
docs/en/user/installation.rst
docs/fr/user/installation.rst

| Fixed tickets | 2342
Fix issue #2342

Add php-bcmath extension to requirements

---

CHANGELOG.md
README.md
app/config/config.yml
docs/de/user/installation.rst
docs/de/user/upgrade-2.0.x-2.1.y.rst
docs/en/user/installation.rst
docs/en/user/upgrade-2.0.x-2.1.y.rst
docs/fr/user/installation.rst
docs/fr/user/upgrade-2.0.x-2.1.y.rst

Prepare wallabag 2.1.1

---

.travis.yml

try to reduce assets build npm connection failing by updating nodejs

---

src/Wallabag/ApiBundle/Controller/WallabagRestController.php
tests/Wallabag/ApiBundle/Controller/WallabagRestControllerTest.php

Fix exists API call

---

src/Wallabag/AnnotationBundle/Entity/Annotation.php
src/Wallabag/CoreBundle/DataFixtures/ORM/LoadEntryData.php
src/Wallabag/CoreBundle/Entity/Entry.php
src/Wallabag/CoreBundle/Helper/EntriesExport.php
src/Wallabag/CoreBundle/Resources/translations/messages.da.yml
src/Wallabag/CoreBundle/Resources/translations/messages.de.yml
src/Wallabag/CoreBundle/Resources/translations/messages.en.yml
src/Wallabag/CoreBundle/Resources/translations/messages.es.yml
src/Wallabag/CoreBundle/Resources/translations/messages.fa.yml
src/Wallabag/CoreBundle/Resources/translations/messages.fr.yml
src/Wallabag/CoreBundle/Resources/translations/messages.it.yml
src/Wallabag/CoreBundle/Resources/translations/messages.oc.yml
src/Wallabag/CoreBundle/Resources/translations/messages.pl.yml
src/Wallabag/CoreBundle/Resources/translations/messages.ro.yml
src/Wallabag/CoreBundle/Resources/translations/messages.tr.yml
tests/Wallabag/CoreBundle/Controller/ExportControllerTest.php
tests/Wallabag/CoreBundle/Controller/TagControllerTest.php

| Fixed tickets | https://github.com/wallabag/wallabag/issues/2256
Should fix https://github.com/wallabag/wallabag/issues/2256
Tags & Annotations weren’t really well exported.
This is now fixed (+ tests)

Fix relations export for Entry

---

src/Wallabag/CoreBundle/Resources/translations/messages.da.yml
src/Wallabag/CoreBundle/Resources/translations/messages.de.yml
src/Wallabag/CoreBundle/Resources/translations/messages.en.yml
src/Wallabag/CoreBundle/Resources/translations/messages.es.yml
src/Wallabag/CoreBundle/Resources/translations/messages.fa.yml
src/Wallabag/CoreBundle/Resources/translations/messages.fr.yml
src/Wallabag/CoreBundle/Resources/translations/messages.it.yml
src/Wallabag/CoreBundle/Resources/translations/messages.oc.yml
src/Wallabag/CoreBundle/Resources/translations/messages.pl.yml
src/Wallabag/CoreBundle/Resources/translations/messages.ro.yml
src/Wallabag/CoreBundle/Resources/translations/messages.tr.yml
src/Wallabag/CoreBundle/Resources/views/themes/common/Entry/share.html.twig
tests/Wallabag/CoreBundle/Controller/EntryControllerTest.php

| Fixed tickets | #2289 
Fix #2289
@tcitworld @j0k3r tell me if we need more OpenGraph tags.

Added OpenGraph support for public articles

---

docs/en/user/errors_during_fetching.rst
docs/fr/user/errors_during_fetching.rst

Found in #2358, thank you @j0k3r

Added documentation about siteconfig fix

---

src/Wallabag/CoreBundle/Resources/views/themes/common/Entry/share.html.twig
tests/Wallabag/CoreBundle/Controller/EntryControllerTest.php

Added default picture if preview picture is null

---

app/config/routing.yml
src/Wallabag/ApiBundle/Controller/DeveloperController.php
src/Wallabag/ApiBundle/Entity/Client.php
src/Wallabag/ApiBundle/Form/Type/ClientType.php
tests/Wallabag/ApiBundle/Controller/DeveloperControllerTest.php

| Fixed tickets | #2350 
Fix #2350

Changed relation between API client and refresh token

---

src/Wallabag/CoreBundle/Resources/views/themes/material/Entry/entries.html.twig
src/Wallabag/CoreBundle/Resources/views/themes/material/Entry/entry.html.twig
src/Wallabag/CoreBundle/Resources/views/themes/material/layout.html.twig

Few HTML tags were not closed correctly. This PR fixes that.

Fix few invalid HTML tags

---

src/Wallabag/CoreBundle/Command/InstallCommand.php

| New feature?  | yes (but more an improvment)
We often got issue with message “The command "doctrine:database:create" terminated with an error code: 1.”.
Using the `BufferedOutput` we can store the output and only display it if an error occurs.
Here is the output (from a debug perspective):

When a sub command fail, display error message

---

src/Wallabag/CoreBundle/Resources/views/themes/common/Entry/share.html.twig

As described here (https://dev.twitter.com/cards/overview), this Twitter Card format don't need whitelisting from twitter. 
I respect the format found here: https://dev.twitter.com/cards/types/summary

Added support of Twitter Cards for public articles

---

docs/en/index.rst

Fix links on english documentation homepage

---

docs/en/developer/redis.rst
docs/en/user/installation.rst
docs/en/user/upgrade-2.0.x-2.1.1.rst

Minor fixes in the english documentation

---

docs/de/index.rst
docs/fr/index.rst

| Fixed tickets | #2423
Fix #2423

Fixed french and german doc homepages

---

docs/de/user/configuration.rst
docs/en/user/configuration.rst
docs/fr/user/configuration.rst

| Fixed tickets | #2060
Fix #2060
@Strubbl @jlnostr need your help :)

Added information about tagging rules in documentation

---

app/DoctrineMigrations/Version20160410190541.php
app/DoctrineMigrations/Version20160812120952.php
app/DoctrineMigrations/Version20160911214952.php
app/DoctrineMigrations/Version20160916201049.php

| Fixed tickets | https://github.com/wallabag/wallabag/issues/2364
Should fix https://github.com/wallabag/wallabag/issues/2364

Fix PostgreSQL migrations

---

Makefile
scripts/dev.sh

Bring make dev

---

src/Wallabag/CoreBundle/Resources/views/themes/common/Static/about.html.twig

| Bug fix?      | yes|
| New feature?  | 
| Deprecations? |
| Documentation | yes|

add link to German documentation in about page

---

app/Resources/CraueConfigBundle/translations/CraueConfigBundle.de.yml
src/Wallabag/CoreBundle/Resources/translations/messages.de.yml
src/Wallabag/CoreBundle/Resources/translations/messages.en.yml

| Bug fix?      | |no
| New feature?  | |no
| Deprecations? | 
| Documentation | |no
i have changed one string in the english translation, too - to emphasize that Bookmarks is a file name.
// cc @jlnostr

German: improve existing and add missing translation

---

app/Resources/CraueConfigBundle/views/Settings/modify.html.twig
src/Wallabag/CoreBundle/Resources/views/themes/common/Static/about.html.twig
src/Wallabag/CoreBundle/Resources/views/themes/material/Config/index.html.twig

| Fixed tickets | https://github.com/wallabag/wallabag/issues/2127
Signed-off-by: Thomas Citharel <tcit@tcit.fr>

Fix tabs on material

---

app/Resources/CraueConfigBundle/views/Settings/modify.html.twig

| Fixed tickets | #2458 
Fix #2458

Fixed hardcoded title for internal settings

---

docs/de/user/upgrade-2.1.x-2.1.y.rst
docs/en/user/upgrade-2.1.x-2.1.y.rst
docs/fr/user/upgrade-2.1.x-2.1.y.rst

Removed MD5 hash in documentation

---

app/config/config.yml

Update wallabag version for master branch

---

composer.json

Maybe wait a bit for first release

use new tcpdf library version

---

docs/en/user/android.rst

Fix missing words in Android application documentation

---

docs/en/index.rst
docs/en/user/backup.rst

| Fixed tickets | 2479
Fixes issue #2479

Document what to backup in Wallabag

---

src/Wallabag/AnnotationBundle/Controller/WallabagAnnotationController.php
src/Wallabag/AnnotationBundle/Repository/AnnotationRepository.php
src/Wallabag/ApiBundle/Controller/WallabagRestController.php
tests/Wallabag/AnnotationBundle/Controller/AnnotationControllerTest.php
tests/Wallabag/AnnotationBundle/WallabagAnnotationTestCase.php

| Tests pass?   | WIP
| Fixed tickets | https://github.com/wallabag/wallabag/issues/1800

bring annotations to API

---

app/config/config.yml

We link to the troubleshooting guide and give the mail link to help end-user.

Add relevant links to fetch content error page

---

src/Wallabag/CoreBundle/Controller/TagController.php
src/Wallabag/CoreBundle/Resources/translations/messages.da.yml
src/Wallabag/CoreBundle/Resources/translations/messages.de.yml
src/Wallabag/CoreBundle/Resources/translations/messages.en.yml
src/Wallabag/CoreBundle/Resources/translations/messages.es.yml
src/Wallabag/CoreBundle/Resources/translations/messages.fa.yml
src/Wallabag/CoreBundle/Resources/translations/messages.fr.yml
src/Wallabag/CoreBundle/Resources/translations/messages.it.yml
src/Wallabag/CoreBundle/Resources/translations/messages.oc.yml
src/Wallabag/CoreBundle/Resources/translations/messages.pl.yml
src/Wallabag/CoreBundle/Resources/translations/messages.pt.yml
src/Wallabag/CoreBundle/Resources/translations/messages.ro.yml
src/Wallabag/CoreBundle/Resources/translations/messages.tr.yml
src/Wallabag/CoreBundle/Resources/views/themes/baggy/Entry/entries.html.twig
src/Wallabag/CoreBundle/Resources/views/themes/common/Entry/_title.html.twig
src/Wallabag/CoreBundle/Resources/views/themes/material/Entry/entries.html.twig

| Fixed tickets | #2472 
Fix #2472
@j0k3r @tcitworld do we need to refactor the title block in entries.html.twig?

Added tag label in the page title

---

Makefile
scripts/install.sh

| Documentation | yes, sort of
| Fixed tickets | #2498 
Fix #2498

Added a check in Makefile to see if composer is installed

---

docs/de/developer/rabbitmq.rst
docs/de/developer/redis.rst
docs/en/developer/rabbitmq.rst
docs/en/developer/redis.rst
docs/fr/developer/rabbitmq.rst
docs/fr/developer/redis.rst

Added the whole path to parameters.yml file

---

app/DoctrineMigrations/Version20161024212538.php
src/Wallabag/ApiBundle/Controller/DeveloperController.php
src/Wallabag/ApiBundle/Entity/Client.php
src/Wallabag/UserBundle/Entity/User.php
tests/Wallabag/AnnotationBundle/Controller/AnnotationControllerTest.php
tests/Wallabag/ApiBundle/Controller/DeveloperControllerTest.php

| Fixed tickets | #2062
Fix #2062 
Todo

Added relation between API Client and User

---

src/Wallabag/CoreBundle/Controller/ExportController.php
src/Wallabag/CoreBundle/Resources/views/themes/baggy/Entry/entries.html.twig
src/Wallabag/CoreBundle/Resources/views/themes/material/Entry/entries.html.twig
tests/Wallabag/CoreBundle/Controller/ExportControllerTest.php

| Fixed tickets | #2505 
Fix #2505
Quick and very dirty. If it's too dirty, please close this PR 😃

Fixed entries export filtered with a tag

---

Capfile
Gemfile
Gemfile.lock
app/config/capistrano/deploy.rb

I deployed on v2.wallabag.org via this configuration.

Updated Capistrano configuration

---

docs/de/developer/api.rst
docs/en/developer/api.rst
docs/fr/developer/api.rst

| Bug fix?      | |no
| New feature?  | |no
| Deprecations? | 
| Documentation | yes|

docs: update 3rd party projects by Strubbl

---

app/Resources/FOSUserBundle/translations/FOSUserBundle.fr.yml
src/Wallabag/CoreBundle/Resources/translations/messages.fr.yml
src/Wallabag/CoreBundle/Resources/translations/validators.fr.yml
src/Wallabag/UserBundle/Resources/translations/wallabag_user.fr.yml

| Q | A |
| --- | --- |
| Bug fix? | no |
| New feature? | no |
| BC breaks? | ? |
| Deprecations? | no |
| Tests pass? | ? |
| Documentation | no |
| Translation | yes |
| Fixed tickets |  |
| License | MIT |
First batch of correction on french translation.
Note: to find french translation file we need to search `filename:*fr*`

Translation update - French

---

docs/de/user/faq.rst
docs/en/user/faq.rst
docs/fr/user/faq.rst

| Fixed tickets | #2529 
Fix #2529
@jlnostr @Strubbl I need you for the german documentation please :)

Added documentation about failed to load external entity error

---

src/Wallabag/CoreBundle/Resources/translations/messages.oc.yml

Update of the OC version

---

docs/de/user/upgrade-2.1.x-2.1.y.rst
docs/en/user/upgrade-2.1.x-2.1.y.rst
docs/fr/user/upgrade-2.1.x-2.1.y.rst

Update the upgrade documentation

---

docs/de/user/upgrade-2.0.x-2.1.1.rst
docs/en/user/upgrade-2.0.x-2.1.1.rst
docs/fr/user/upgrade-2.0.x-2.1.1.rst

Updated default parameters.yml file in documentation

---

src/Wallabag/CoreBundle/Form/Type/EntryFilterType.php
src/Wallabag/CoreBundle/Helper/PreparePagerForEntries.php

Replaced TokenStorage with TokenStorageInterface

---

scripts/update.sh

Reorder variable assignation in update.sh script, fix #2554

---

src/Wallabag/CoreBundle/Form/Type/NewTagType.php
src/Wallabag/CoreBundle/Resources/translations/messages.da.yml
src/Wallabag/CoreBundle/Resources/translations/messages.de.yml
src/Wallabag/CoreBundle/Resources/translations/messages.en.yml
src/Wallabag/CoreBundle/Resources/translations/messages.es.yml
src/Wallabag/CoreBundle/Resources/translations/messages.fa.yml
src/Wallabag/CoreBundle/Resources/translations/messages.fr.yml
src/Wallabag/CoreBundle/Resources/translations/messages.it.yml
src/Wallabag/CoreBundle/Resources/translations/messages.oc.yml
src/Wallabag/CoreBundle/Resources/translations/messages.pl.yml
src/Wallabag/CoreBundle/Resources/translations/messages.pt.yml
src/Wallabag/CoreBundle/Resources/translations/messages.ro.yml
src/Wallabag/CoreBundle/Resources/translations/messages.tr.yml
src/Wallabag/CoreBundle/Resources/views/themes/material/Entry/entry.html.twig
src/Wallabag/CoreBundle/Resources/views/themes/material/Tag/new_form.html.twig

| Fixed tickets | #2376 
Fix #2376

Added new tag form in mobile view for Material theme

---

src/Wallabag/CoreBundle/Controller/ConfigController.php
src/Wallabag/CoreBundle/Resources/translations/messages.da.yml
src/Wallabag/CoreBundle/Resources/translations/messages.de.yml
src/Wallabag/CoreBundle/Resources/translations/messages.en.yml
src/Wallabag/CoreBundle/Resources/translations/messages.es.yml
src/Wallabag/CoreBundle/Resources/translations/messages.fa.yml
src/Wallabag/CoreBundle/Resources/translations/messages.fr.yml
src/Wallabag/CoreBundle/Resources/translations/messages.it.yml
src/Wallabag/CoreBundle/Resources/translations/messages.oc.yml
src/Wallabag/CoreBundle/Resources/translations/messages.pl.yml
src/Wallabag/CoreBundle/Resources/translations/messages.pt.yml
src/Wallabag/CoreBundle/Resources/translations/messages.ro.yml
src/Wallabag/CoreBundle/Resources/translations/messages.tr.yml

No need to disconnect to apply the language substitution

Changed behavior when we change language

---

app/DoctrineMigrations/Version20161106113822.php
app/DoctrineMigrations/Version20161117071626.php
docs/de/user/configuration.rst
docs/en/user/configuration.rst
docs/fr/user/configuration.rst
src/Wallabag/CoreBundle/DataFixtures/ORM/LoadConfigData.php
src/Wallabag/CoreBundle/Entity/Config.php
src/Wallabag/CoreBundle/Form/Type/ConfigType.php
src/Wallabag/CoreBundle/Helper/Redirect.php
src/Wallabag/CoreBundle/Resources/config/services.yml
src/Wallabag/CoreBundle/Resources/translations/messages.da.yml
src/Wallabag/CoreBundle/Resources/translations/messages.de.yml
src/Wallabag/CoreBundle/Resources/translations/messages.en.yml
src/Wallabag/CoreBundle/Resources/translations/messages.es.yml
src/Wallabag/CoreBundle/Resources/translations/messages.fa.yml
src/Wallabag/CoreBundle/Resources/translations/messages.fr.yml
src/Wallabag/CoreBundle/Resources/translations/messages.it.yml
src/Wallabag/CoreBundle/Resources/translations/messages.oc.yml
src/Wallabag/CoreBundle/Resources/translations/messages.pl.yml
src/Wallabag/CoreBundle/Resources/translations/messages.pt.yml
src/Wallabag/CoreBundle/Resources/translations/messages.ro.yml
src/Wallabag/CoreBundle/Resources/translations/messages.tr.yml
src/Wallabag/CoreBundle/Resources/views/themes/baggy/Config/index.html.twig
src/Wallabag/CoreBundle/Resources/views/themes/material/Config/index.html.twig
tests/Wallabag/CoreBundle/Controller/ConfigControllerTest.php
tests/Wallabag/CoreBundle/Controller/EntryControllerTest.php
tests/Wallabag/CoreBundle/Helper/DownloadImagesTest.php
tests/Wallabag/CoreBundle/Helper/RedirectTest.php

| Tests pass?   |  no
| Fixed tickets | #496 
Added a new option in configuration: 
Fix #496
@j0k3r @tcitworld I need help for the tests. 
@Strubbl @jlnostr I need help to translate this PR.

Added a configuration to define the redirection after archiving an entry

---

tests/Wallabag/ImportBundle/Controller/ChromeControllerTest.php
tests/Wallabag/ImportBundle/Controller/FirefoxControllerTest.php
tests/Wallabag/ImportBundle/Controller/InstapaperControllerTest.php
tests/Wallabag/ImportBundle/Controller/PinboardControllerTest.php
tests/Wallabag/ImportBundle/Controller/ReadabilityControllerTest.php
tests/Wallabag/ImportBundle/Controller/WallabagV1ControllerTest.php
tests/Wallabag/ImportBundle/Controller/WallabagV2ControllerTest.php

So we’ll quickly be able to see what kind of test is failing when viewing Travis

Put log in the most common failure tests

---

CHANGELOG.md
app/config/config.yml

Prepare wallabag 2.1.4 :rocket:

---

RELEASE_PROCESS.md

This change was missing from the release process.

Add .travis.yml change to RELEASE_PROCESS

---

src/Wallabag/CoreBundle/Command/InstallCommand.php

| Fixed tickets | fix #2061
wallabag can’t work on PostgreSQL <= 9.1.
The install command now check this constraint.

wallabag can’t work on PostgreSQL <= 9.1

---

CHANGELOG.md

Updated changelog for 2.1.4

---

app/config/config.yml

Change version to 2.2.0-dev

---

CHANGELOG.md
app/config/config.yml

Prepare wallabag 2.1.5

---

app/config/config.yml

| Fixed tickets | #2056 
Resolves refresh token lifetime issue

Fix #2056 update config.yml

---

app/AppKernel.php
app/DoctrineMigrations/Version20161122144743.php
app/Resources/CraueConfigBundle/translations/CraueConfigBundle.da.yml
app/Resources/CraueConfigBundle/translations/CraueConfigBundle.de.yml
app/Resources/CraueConfigBundle/translations/CraueConfigBundle.en.yml
app/Resources/CraueConfigBundle/translations/CraueConfigBundle.es.yml
app/Resources/CraueConfigBundle/translations/CraueConfigBundle.fa.yml
app/Resources/CraueConfigBundle/translations/CraueConfigBundle.fr.yml
app/Resources/CraueConfigBundle/translations/CraueConfigBundle.it.yml
app/Resources/CraueConfigBundle/translations/CraueConfigBundle.oc.yml
app/Resources/CraueConfigBundle/translations/CraueConfigBundle.pl.yml
app/Resources/CraueConfigBundle/translations/CraueConfigBundle.pt.yml
app/Resources/CraueConfigBundle/translations/CraueConfigBundle.ro.yml
app/Resources/CraueConfigBundle/translations/CraueConfigBundle.tr.yml
app/config/parameters.yml.dist
composer.json
docs/de/developer/paywall.rst
docs/de/index.rst
docs/en/developer/paywall.rst
docs/en/index.rst
docs/fr/developer/paywall.rst
docs/fr/index.rst
src/Wallabag/CoreBundle/Command/InstallCommand.php
src/Wallabag/CoreBundle/DataFixtures/ORM/LoadSettingData.php
src/Wallabag/CoreBundle/GuzzleSiteAuthenticator/GrabySiteConfigBuilder.php
src/Wallabag/CoreBundle/Helper/HttpClientFactory.php
src/Wallabag/CoreBundle/Resources/config/services.yml
tests/Wallabag/CoreBundle/GuzzleSiteAuthenticator/GrabySiteConfigBuilderTest.php

| Q | A |
| --- | --- |
| Bug fix? | no |
| New feature? | yes |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Documentation | no |
| Translation | no |
| Fixed tickets | #438 |
| License | MIT |
Fix #438.
Previously at #1586
Thank you so much @bdunogier
Todo

Added authentication for restricted access articles

---

src/Wallabag/CoreBundle/Form/Type/EntryFilterType.php
tests/Wallabag/CoreBundle/Controller/EntryControllerTest.php

| Fixed tickets | #2652 
Fixes #2652

Enforce lowercase on domain name filter

---

app/DoctrineMigrations/Version20161128131503.php
src/Wallabag/CoreBundle/Resources/translations/messages.da.yml
src/Wallabag/CoreBundle/Resources/translations/messages.de.yml
src/Wallabag/CoreBundle/Resources/translations/messages.en.yml
src/Wallabag/CoreBundle/Resources/translations/messages.es.yml
src/Wallabag/CoreBundle/Resources/translations/messages.fa.yml
src/Wallabag/CoreBundle/Resources/translations/messages.fr.yml
src/Wallabag/CoreBundle/Resources/translations/messages.it.yml
src/Wallabag/CoreBundle/Resources/translations/messages.oc.yml
src/Wallabag/CoreBundle/Resources/translations/messages.pl.yml
src/Wallabag/CoreBundle/Resources/translations/messages.pt.yml
src/Wallabag/CoreBundle/Resources/translations/messages.ro.yml
src/Wallabag/CoreBundle/Resources/translations/messages.tr.yml
src/Wallabag/UserBundle/Form/UserType.php
src/Wallabag/UserBundle/Resources/views/Manage/edit.html.twig
src/Wallabag/UserBundle/Resources/views/Manage/index.html.twig
tests/Wallabag/UserBundle/Controller/ManageControllerTest.php

| Fixed tickets | #2656 
Fix #2656

Removed FOSUser attributes removed in alpha4

---

docs/de/developer/asynchronous.rst
docs/en/developer/asynchronous.rst
docs/fr/developer/asynchronous.rst

Fixed typo in asynchronous documentation

---

src/Wallabag/UserBundle/Resources/translations/wallabag_user.en.yml
src/Wallabag/UserBundle/Resources/views/TwoFactor/email_auth_code.html.twig

Fixed 404 for wallabag logo in 2FA

---

src/Wallabag/CoreBundle/Resources/config/parameters.yml
src/Wallabag/CoreBundle/Resources/translations/messages.da.yml
src/Wallabag/CoreBundle/Resources/translations/messages.de.yml
src/Wallabag/CoreBundle/Resources/translations/messages.en.yml
src/Wallabag/CoreBundle/Resources/translations/messages.es.yml
src/Wallabag/CoreBundle/Resources/translations/messages.fa.yml
src/Wallabag/CoreBundle/Resources/translations/messages.fr.yml
src/Wallabag/CoreBundle/Resources/translations/messages.it.yml
src/Wallabag/CoreBundle/Resources/translations/messages.oc.yml
src/Wallabag/CoreBundle/Resources/translations/messages.pl.yml
src/Wallabag/CoreBundle/Resources/translations/messages.pt.yml
src/Wallabag/CoreBundle/Resources/translations/messages.ro.yml
src/Wallabag/CoreBundle/Resources/translations/messages.tr.yml
src/Wallabag/CoreBundle/Resources/views/themes/common/Static/howto.html.twig

| Fixed tickets | #2671
Fix #2671

Updated addons links

---

src/Wallabag/UserBundle/Resources/translations/wallabag_user.de.yml

| Bug fix?      | yes/
| New feature?  | /no
| BC breaks?    | /no
| Deprecations? | /no
| Tests pass?   | yes/
| Documentation | /no
| Translation   | yes/
| Fixed tickets | #2673
add missing german translation

add translations/wallabag_user.de.yml (fixes #2673)

---

src/Wallabag/CoreBundle/Helper/DownloadImages.php

| Fixed tickets | #2687
Fix #2687

Replaced chmod for download pictures feature

---

app/DoctrineMigrations/Version20161128084725.php
app/config/config.yml
src/Wallabag/CoreBundle/DataFixtures/ORM/LoadConfigData.php
src/Wallabag/CoreBundle/DependencyInjection/Configuration.php
src/Wallabag/CoreBundle/DependencyInjection/WallabagCoreExtension.php
src/Wallabag/UserBundle/EventListener/CreateConfigListener.php
src/Wallabag/UserBundle/Resources/config/services.yml
tests/Wallabag/UserBundle/EventListener/CreateConfigListenerTest.php

No default value are allowed for `list_mode` https://travis-ci.org/wallabag/wallabag/jobs/183213620#L502

Add default value for list_mode

---

.travis.yml
app/config/routing.yml
composer.json
src/Wallabag/ApiBundle/Controller/DeveloperController.php
src/Wallabag/CoreBundle/Controller/ConfigController.php
src/Wallabag/CoreBundle/Controller/EntryController.php
src/Wallabag/CoreBundle/Controller/TagController.php
src/Wallabag/ImportBundle/Controller/BrowserController.php
src/Wallabag/ImportBundle/Controller/InstapaperController.php
src/Wallabag/ImportBundle/Controller/PinboardController.php
src/Wallabag/ImportBundle/Controller/ReadabilityController.php
src/Wallabag/ImportBundle/Controller/WallabagController.php

Upgrade to Symfony 3.2

---

app/config/config.yml
app/config/parameters.yml.dist
docs/de/developer/asynchronous.rst
docs/en/developer/asynchronous.rst
docs/fr/developer/asynchronous.rst

Added Quality of Service to improve RabbitMQ workers.

Added QoS for RabbitMQ

---

.travis.yml
Makefile
app/DoctrineMigrations/Version20160410190541.php
app/DoctrineMigrations/Version20161214094403.php
src/Wallabag/CoreBundle/Controller/EntryController.php
src/Wallabag/CoreBundle/Entity/Entry.php
tests/Wallabag/CoreBundle/Controller/EntryControllerTest.php

Public sharing was quite long on app.wallabag.it 🐌

Added index on entry.uuid

---

src/Wallabag/CoreBundle/Resources/translations/messages.fr.yml

Minor typo fix

---

src/Wallabag/CoreBundle/Resources/config/parameters.yml

Firefox add-on URL updated

---

COPYING.md
README.md

Update copyright year to 2017 in README.md and COPYING.md files.

Update copyright year

---

app/config/config.yml

| Fixed tickets | #2693
Fix #2693.

Fixed API error No matching accepted Response format could be determined

---

src/Wallabag/CoreBundle/Resources/views/themes/baggy/Entry/entries.html.twig
src/Wallabag/CoreBundle/Resources/views/themes/baggy/Entry/entry.html.twig
src/Wallabag/CoreBundle/Resources/views/themes/common/Entry/entries.xml.twig
src/Wallabag/CoreBundle/Resources/views/themes/common/Entry/share.html.twig
src/Wallabag/CoreBundle/Resources/views/themes/material/Entry/_card_full_image.html.twig
src/Wallabag/CoreBundle/Resources/views/themes/material/Entry/_card_no_preview.html.twig
src/Wallabag/CoreBundle/Resources/views/themes/material/Entry/_card_preview.html.twig
src/Wallabag/CoreBundle/Resources/views/themes/material/Entry/entry.html.twig
var/SymfonyRequirements.php

Because we can edit the entry title and share the article publicly, it's possible via javascript to inject malicious code. 
Thank you [jeancreed1](https://twitter.com/jeancreed1).

Fixed possible JS injection via the title edition

---

CHANGELOG.md
app/config/config.yml

Prepare wallabag 2.1.6 🚀
Need to merge https://github.com/wallabag/wallabag/pull/2758 before.

Prepare wallabag 2.1.6 :rocket:

---

src/Wallabag/CoreBundle/Command/ExportCommand.php
src/Wallabag/CoreBundle/Helper/EntriesExport.php
tests/Wallabag/CoreBundle/Command/ExportCommandTest.php

add cli export

---

composer.json

Related https://github.com/K-Phoen/rulerz/issues/61

Lock kphoen/rulerz to avoid breaking changes

---

app/DoctrineMigrations/Version20170127093841.php
docs/de/user/query-upgrade-21-22.rst
docs/de/user/upgrade.rst
docs/en/user/query-upgrade-21-22.rst
docs/en/user/upgrade.rst
docs/fr/user/query-upgrade-21-22.rst
docs/fr/user/upgrade.rst

Added indexes on is_archived and is_starred

Added indexes on is_archived and is_starred

---

CHANGELOG.md
app/config/config.yml

Prepare wallabag 2.2.1 :rocket:

---

docs/de/user/upgrade.rst
docs/en/user/upgrade.rst
docs/fr/user/upgrade.rst

Added details about upgrade from 2.1.x or 2.2.0

---

src/Wallabag/CoreBundle/Resources/translations/messages.pl.yml

Update polish strings

---

src/Wallabag/CoreBundle/Resources/translations/messages.de.yml

I just translated the missing strings I found during the translation of #2824.

Translate missing strings for de-DE.

---

composer.json
src/Wallabag/CoreBundle/Resources/translations/messages.da.yml
src/Wallabag/CoreBundle/Resources/translations/messages.de.yml
src/Wallabag/CoreBundle/Resources/translations/messages.en.yml
src/Wallabag/CoreBundle/Resources/translations/messages.es.yml
src/Wallabag/CoreBundle/Resources/translations/messages.fa.yml
src/Wallabag/CoreBundle/Resources/translations/messages.fr.yml
src/Wallabag/CoreBundle/Resources/translations/messages.it.yml
src/Wallabag/CoreBundle/Resources/translations/messages.oc.yml
src/Wallabag/CoreBundle/Resources/translations/messages.pl.yml
src/Wallabag/CoreBundle/Resources/translations/messages.pt.yml
src/Wallabag/CoreBundle/Resources/translations/messages.ro.yml
src/Wallabag/CoreBundle/Resources/translations/messages.tr.yml

Just changed the name for Developer section. 
ping @wallabag/translators

Renamed Developer section to API client management

---

app/Resources/CraueConfigBundle/translations/CraueConfigBundle.oc.yml

Update of CraueConfigBundle in Occitan

---

composer.json

| Deprecations? |  no
See https://github.com/sensiolabs/SensioFrameworkExtraBundle/commit/ed86f6fb1753e76b39ff8b87f527045ca6b97169

Restored correct version for framework-extra-bundle

---

src/Wallabag/CoreBundle/Resources/translations/messages.oc.yml

Update Oc version

---

docs/en/user/configuring_mobile.rst

Documentation on how to configure mobile apps to work with wallabag.it

---

src/Wallabag/CoreBundle/Resources/translations/messages.pl.yml

remove misspells in messages.pl.yml file

fix misspells in polish translation

---

src/Wallabag/CoreBundle/Helper/HttpClientFactory.php
src/Wallabag/CoreBundle/Resources/config/services.yml

| Fixed tickets | https://github.com/wallabag/wallabag/issues/2868
It might help to figure out if we have enabled it or not

Log restricted access value

---

docs/de/developer/api.rst
docs/en/developer/api.rst
docs/fr/developer/api.rst

| Bug fix?      | 
| New feature?  | 
| Deprecations? | 

docs 3rd party tools: update java wrapper, add cmd tool to add article

---

src/Wallabag/CoreBundle/Resources/translations/messages.it.yml

Changed "Pimi passi" to "Primi passi

Fixed typo in "first_steps"

---

docs/ita/conf.py
docs/ita/developer/api.rst
docs/ita/developer/asynchronous.rst
docs/ita/developer/docker.rst
docs/ita/developer/documentation.rst
docs/ita/developer/paywall.rst
docs/ita/developer/testsuite.rst
docs/ita/developer/translate.rst
docs/ita/index.rst
docs/ita/requirements.txt
docs/ita/user/android.rst
docs/ita/user/articles.rst
docs/ita/user/backup.rst
docs/ita/user/configuration.rst
docs/ita/user/create_account.rst
docs/ita/user/errors_during_fetching.rst
docs/ita/user/faq.rst
docs/ita/user/filters.rst
docs/ita/user/import.rst
docs/ita/user/installation.rst
docs/ita/user/parameters.rst
docs/ita/user/upgrade.rst

There are some missing links in various articles. Please let me know how I can fix this :)

Italian documentation added

---

docs/fr/user/installation.rst

Doc - information about Apache 2.4

---

app/Resources/CraueConfigBundle/translations/CraueConfigBundle.es.yml
src/Wallabag/CoreBundle/Resources/translations/messages.es.yml
src/Wallabag/UserBundle/Resources/translations/wallabag_user.es.yml

Will be a 2nd part with missing translations but in other PR.

Update Spanish translation

---

docs/de/user/configuring_mobile.rst

see https://github.com/wallabag/wallabag/pull/2882#discussion_r101806434
Just fixing a little typo.

Remove word repetition from german translation

---

README.md

Added wallabag.it link in README

---

docs/de/user/configuration.rst
docs/en/user/configuration.rst
docs/fr/user/configuration.rst
docs/it/user/configuration.rst

Alert that 2FA must be authorized in app/config/parameters.yml

Alert that 2FA must be authorized in app/config/parameters.yml

---

app/Resources/CraueConfigBundle/translations/CraueConfigBundle.pl.yml

Update Polish translation

---

docs/de/user/installation.rst
docs/en/user/installation.rst
docs/fr/user/installation.rst
docs/it/user/installation.rst

Add activation of 'rewrite' mod of Apache.
I let you do modifications for Italian and German documentations.

Add activation of 'rewrite' mod of Apache

---

scripts/release.sh

Fixed symlinks issue during release creation

---

CHANGELOG.md

Updated CHANGELOG with latest changes

---

app/config/config.yml

Updated wallabag version in config.yml.

Changed wallabag version

---

docs/en/developer/paywall.rst

Update paywall.rst (EN) with details + clear cache

---

docs/fr/developer/paywall.rst

[FR] Update paywall.rst (more details and clear cache)

Update paywall.rst (more details and clear cache)

---

docs/de/user/installation.rst
docs/en/user/installation.rst
docs/fr/user/installation.rst
docs/it/user/installation.rst

Thanks for the great app and especially the latest continued effort into making it better and better.
I have packaged wallabag for Cloudron and this pull request would add it to the docs. Please let me know if this is not applicable. First time for me to use .rst files.

Add Cloudron as installation method

---

app/config/config.yml

No need to have a migration here. 
It's only for new users (or fresh install).

Changed default value for list mode (grid instead of list)

---

src/Wallabag/AnnotationBundle/Repository/AnnotationRepository.php
src/Wallabag/CoreBundle/Controller/ConfigController.php
src/Wallabag/CoreBundle/Repository/EntryRepository.php
src/Wallabag/CoreBundle/Repository/TagRepository.php
src/Wallabag/CoreBundle/Resources/translations/messages.da.yml
src/Wallabag/CoreBundle/Resources/translations/messages.de.yml
src/Wallabag/CoreBundle/Resources/translations/messages.en.yml
src/Wallabag/CoreBundle/Resources/translations/messages.es.yml
src/Wallabag/CoreBundle/Resources/translations/messages.fa.yml
src/Wallabag/CoreBundle/Resources/translations/messages.fr.yml
src/Wallabag/CoreBundle/Resources/translations/messages.it.yml
src/Wallabag/CoreBundle/Resources/translations/messages.oc.yml
src/Wallabag/CoreBundle/Resources/translations/messages.pl.yml
src/Wallabag/CoreBundle/Resources/translations/messages.pt.yml
src/Wallabag/CoreBundle/Resources/translations/messages.ro.yml
src/Wallabag/CoreBundle/Resources/translations/messages.tr.yml
src/Wallabag/CoreBundle/Resources/views/themes/baggy/Config/index.html.twig
src/Wallabag/CoreBundle/Resources/views/themes/material/Config/index.html.twig
tests/Wallabag/CoreBundle/Controller/ConfigControllerTest.php

Allow to remove all archived entries

---

app/DoctrineMigrations/Version20160410190541.php
app/DoctrineMigrations/Version20160812120952.php
app/DoctrineMigrations/Version20160911214952.php
app/DoctrineMigrations/Version20160916201049.php
app/DoctrineMigrations/Version20161001072726.php
app/DoctrineMigrations/Version20161022134138.php
app/DoctrineMigrations/Version20161024212538.php
app/DoctrineMigrations/Version20161031132655.php
app/DoctrineMigrations/Version20161104073720.php
app/DoctrineMigrations/Version20161106113822.php
app/DoctrineMigrations/Version20161117071626.php
app/DoctrineMigrations/Version20161214094402.php
app/DoctrineMigrations/Version20161214094403.php
app/DoctrineMigrations/Version20170127093841.php
app/DoctrineMigrations/Version20170407200919.php
src/Wallabag/CoreBundle/Entity/Entry.php
src/Wallabag/CoreBundle/Form/Type/EditEntryType.php
src/Wallabag/CoreBundle/Resources/translations/messages.da.yml
src/Wallabag/CoreBundle/Resources/translations/messages.de.yml
src/Wallabag/CoreBundle/Resources/translations/messages.en.yml
src/Wallabag/CoreBundle/Resources/translations/messages.es.yml
src/Wallabag/CoreBundle/Resources/translations/messages.fa.yml
src/Wallabag/CoreBundle/Resources/translations/messages.fr.yml
src/Wallabag/CoreBundle/Resources/translations/messages.it.yml
src/Wallabag/CoreBundle/Resources/translations/messages.oc.yml
src/Wallabag/CoreBundle/Resources/translations/messages.pl.yml
src/Wallabag/CoreBundle/Resources/translations/messages.pt.yml
src/Wallabag/CoreBundle/Resources/translations/messages.ro.yml
src/Wallabag/CoreBundle/Resources/translations/messages.tr.yml
src/Wallabag/CoreBundle/Resources/views/themes/material/Entry/edit.html.twig

| Documentation | not needed
| Fixed tickets | #2598 
Refer to #2598

Remove isPublic from Entry entity fix #2598

---

app/DoctrineMigrations/Version20170420134133.php

Cleaned craue_config_setting by removing useless download_pictures setting

---

.gitignore

Ignore tests exported files

---

src/Wallabag/ApiBundle/Controller/EntryRestController.php
src/Wallabag/ApiBundle/Controller/TagRestController.php
tests/Wallabag/ApiBundle/Controller/EntryRestControllerTest.php

Added API endpoint to handle a list of URL and to add/delete tags

---

RELEASE_PROCESS.md
docs/de/user/upgrade.rst
docs/en/user/upgrade.rst
docs/fr/user/upgrade.rst
docs/it/user/installation.rst
docs/it/user/upgrade.rst

| Tests pass?   | ~
| Fixed tickets | #3061 

Small typo in documentation fix #3061

---

src/Wallabag/CoreBundle/Resources/views/themes/material/Entry/entry.html.twig

| Fixed tickets | #2707 
Before
After

Fixed sandwich menu position in entry view (material theme)

---

docs/en/user/import.rst
src/Wallabag/ImportBundle/Command/ImportCommand.php
tests/Wallabag/ImportBundle/Command/ImportCommandTest.php

| Deprecations? | yes !
Needed that for framabag.

Use username to import

---

app/config/config.yml
src/Wallabag/ApiBundle/Controller/EntryRestController.php
src/Wallabag/CoreBundle/DependencyInjection/Configuration.php
src/Wallabag/CoreBundle/DependencyInjection/WallabagCoreExtension.php
tests/Wallabag/ApiBundle/Controller/EntryRestControllerTest.php

You can pass an array like this one: 
```
["http://...","http://..."]"
``` 
and add / delete URL in mass.

Added API endpoint to handle a list of URL

---

docs/en/developer/console_commands.rst
docs/fr/developer/console_commands.rst
src/Wallabag/CoreBundle/Command/CleanDuplicatesCommand.php
src/Wallabag/CoreBundle/Repository/EntryRepository.php
tests/Wallabag/CoreBundle/Command/CleanDuplicatesCommandTest.php
tests/Wallabag/CoreBundle/Command/ExportCommandTest.php
tests/Wallabag/CoreBundle/Helper/ContentProxyTest.php

| Documentation | needed
| Fixed tickets | #2884

Clean Duplicates Command

---

src/Wallabag/CoreBundle/Command/InstallCommand.php
tests/Wallabag/ApiBundle/Controller/EntryRestControllerTest.php
tests/Wallabag/CoreBundle/Command/ExportCommandTest.php
tests/Wallabag/CoreBundle/Command/InstallCommandTest.php
tests/Wallabag/CoreBundle/Helper/ContentProxyTest.php

Added migrations execution after fresh install

---

src/Wallabag/UserBundle/Resources/views/Security/login.html.twig

Translate error message in login page

---

src/Wallabag/CoreBundle/Resources/views/themes/common/Static/about.html.twig

Update graby* licenses

---

src/Wallabag/CoreBundle/Form/Type/EntryFilterType.php
tests/Wallabag/CoreBundle/Controller/EntryControllerTest.php

| Tests pass?   | ~
| Fixed tickets | #2979 

Disable negative numbers in filters

---

.travis.yml

This might speed up future build if the yarn cache already exists!

Cache yarn cache in Travis

---

app/DoctrineMigrations/Version20170511115400.php
src/Wallabag/CoreBundle/Entity/Entry.php
src/Wallabag/CoreBundle/Helper/ContentProxy.php
tests/Wallabag/CoreBundle/Controller/EntryControllerTest.php

Added headers field in Entry

---

src/Wallabag/CoreBundle/Helper/RuleBasedTagger.php
src/Wallabag/CoreBundle/Resources/config/services.yml
tests/Wallabag/CoreBundle/Helper/RuleBasedTaggerTest.php

Added logger when we match Tagging rules

---

app/Resources/CraueConfigBundle/views/Settings/modify.html.twig
app/config/config.yml
app/config/services.yml
composer.json
var/SymfonyRequirements.php

Upgraded CraueConfigBundle to 2.0

---

src/Wallabag/CoreBundle/Resources/views/themes/common/Developer/index.html.twig
src/Wallabag/CoreBundle/Resources/views/themes/common/Static/about.html.twig
src/Wallabag/CoreBundle/Resources/views/themes/common/Static/quickstart.html.twig

| Fixed tickets | #3116
For each link, I added a RedirectPermament rule in apache config.

Fixed documentation URL

---

tests/Wallabag/ImportBundle/Controller/FirefoxControllerTest.php

SO switched to http yesterday
https://nickcraver.com/blog/2017/05/22/https-on-stack-overflow/

Fix SO tests

---

src/Wallabag/CoreBundle/Resources/translations/messages.da.yml
src/Wallabag/CoreBundle/Resources/translations/messages.de.yml
src/Wallabag/CoreBundle/Resources/translations/messages.en.yml
src/Wallabag/CoreBundle/Resources/translations/messages.es.yml
src/Wallabag/CoreBundle/Resources/translations/messages.fa.yml
src/Wallabag/CoreBundle/Resources/translations/messages.fr.yml
src/Wallabag/CoreBundle/Resources/translations/messages.it.yml
src/Wallabag/CoreBundle/Resources/translations/messages.oc.yml
src/Wallabag/CoreBundle/Resources/translations/messages.pl.yml
src/Wallabag/CoreBundle/Resources/translations/messages.pt.yml
src/Wallabag/CoreBundle/Resources/translations/messages.ro.yml
src/Wallabag/CoreBundle/Resources/translations/messages.tr.yml
src/Wallabag/CoreBundle/Resources/views/themes/baggy/Entry/entries.html.twig
src/Wallabag/CoreBundle/Resources/views/themes/baggy/Entry/entry.html.twig
src/Wallabag/CoreBundle/Resources/views/themes/material/Entry/_card_actions.html.twig
src/Wallabag/CoreBundle/Resources/views/themes/material/Entry/_card_list.html.twig
src/Wallabag/CoreBundle/Resources/views/themes/material/Entry/entry.html.twig

| New feature?  | kind of
| Translation   | needed
I don't know why don't we add them in the first place.
@wallabag/translators can you give us the translation of:
- Are you sure you want to remove that article?
- Are you sure you want to remove that tag from that article?

Add some deletion confirmation to avoid mistake

---

src/Wallabag/ApiBundle/Controller/UserRestController.php
src/Wallabag/ApiBundle/Resources/config/routing_rest.yml
src/Wallabag/UserBundle/Controller/ManageController.php
src/Wallabag/UserBundle/Entity/User.php
tests/Wallabag/ApiBundle/Controller/UserRestControllerTest.php
tests/Wallabag/ApiBundle/WallabagApiTestCase.php
tests/Wallabag/UserBundle/Controller/ManageControllerTest.php

Signed-off-by: Thomas Citharel <tcit@tcit.fr>
| Fixed tickets | #3056 

Register through API

---

.github/ISSUE_TEMPLATE.md

| Fixed tickets | https://github.com/wallabag/wallabag/issues/3166
Thanks @tdelmas

Fix link in Github template

---

src/Wallabag/CoreBundle/Entity/Entry.php
src/Wallabag/CoreBundle/GuzzleSiteAuthenticator/GrabySiteConfigBuilder.php
src/Wallabag/CoreBundle/Helper/RuleBasedTagger.php
tests/Wallabag/CoreBundle/Command/InstallCommandTest.php

| Fixed tickets | https://github.com/wallabag/wallabag/issues/1360
Waiting for https://github.com/wallabag/guzzle-site-authenticator/pull/21 to fix one error.

Fix some Scrutinizer issues

---

app/AppKernel.php
app/config/config_test.yml
app/config/parameters_test.yml
app/config/tests/parameters_test.mysql.yml
app/config/tests/parameters_test.pgsql.yml
app/config/tests/parameters_test.sqlite.yml
composer.json
phpunit.xml.dist
src/Wallabag/CoreBundle/Command/InstallCommand.php
src/Wallabag/CoreBundle/Controller/ConfigController.php
src/Wallabag/CoreBundle/Event/Subscriber/SQLiteCascadeDeleteSubscriber.php
tests/Wallabag/ApiBundle/Controller/DeveloperControllerTest.php
tests/Wallabag/ApiBundle/Controller/EntryRestControllerTest.php
tests/Wallabag/ApiBundle/Controller/TagRestControllerTest.php
tests/Wallabag/ApiBundle/WallabagApiTestCase.php
tests/Wallabag/CoreBundle/Command/ExportCommandTest.php
tests/Wallabag/CoreBundle/Command/InstallCommandTest.php
tests/Wallabag/CoreBundle/Controller/ConfigControllerTest.php
tests/Wallabag/CoreBundle/Controller/EntryControllerTest.php
tests/Wallabag/CoreBundle/Controller/ExportControllerTest.php
tests/Wallabag/CoreBundle/Controller/TagControllerTest.php
tests/Wallabag/CoreBundle/WallabagCoreTestCase.php
tests/Wallabag/ImportBundle/Command/ImportCommandTest.php
tests/Wallabag/ImportBundle/Controller/WallabagV2ControllerTest.php

Attempt to have isolated tests with the use of https://github.com/dmaicher/doctrine-test-bundle.

Isolated tests

---

app/config/parameters.yml.dist

| Deprecations? | yes ⚠️
| Fixed tickets | #2766
In fact, maybe we only need to changes parameters.yml.dist. @wallabag/core I want your opinion. 
We also need to update http://github.com/wallabag/doc/ I will do that after when this PR will be merged.

Defined MySQL as the default rdbms for wallabag

---

app/Resources/CraueConfigBundle/translations/CraueConfigBundle.pl.yml

Update PL translation

---

src/Wallabag/CoreBundle/Resources/translations/messages.it.yml

Related to https://github.com/wallabag/wallabag/pull/3147#issuecomment-304854955
@matteocoder could you update that PR with other missing translation from the `messages.it.yml` file?
Thanks !! :1st_place_medal:

Update Italian translation

---

src/Wallabag/CoreBundle/Command/ShowUserCommand.php
tests/Wallabag/CoreBundle/Command/ShowUserCommandTest.php

| Documentation | https://github.com/wallabag/doc/pull/6
| Fixed tickets | part of #3156
Basic `wallabag:user:show` command.

Show user command

---

.github/ISSUE_TEMPLATE.md

Added link to community in issue template

---

docs/en/user/configuration.rst
src/Wallabag/CoreBundle/Resources/translations/messages.da.yml
src/Wallabag/CoreBundle/Resources/translations/messages.en.yml
src/Wallabag/CoreBundle/Resources/translations/messages.fa.yml
src/Wallabag/CoreBundle/Resources/translations/messages.it.yml
src/Wallabag/CoreBundle/Resources/translations/messages.pt.yml
src/Wallabag/CoreBundle/Resources/translations/messages.ro.yml
src/Wallabag/CoreBundle/Resources/translations/messages.tr.yml

| Fixed tickets | #3199 
Label improvement + add missing word.

Config label improvement #3199

---

src/Wallabag/CoreBundle/Resources/views/themes/baggy/Tag/tags.html.twig

| Fixed tickets | https://github.com/wallabag/wallabag/issues/3201

Fix tags count in tags list on baggy

---

src/Wallabag/CoreBundle/Resources/translations/messages.da.yml
src/Wallabag/CoreBundle/Resources/translations/messages.de.yml
src/Wallabag/CoreBundle/Resources/translations/messages.en.yml
src/Wallabag/CoreBundle/Resources/translations/messages.es.yml
src/Wallabag/CoreBundle/Resources/translations/messages.fa.yml
src/Wallabag/CoreBundle/Resources/translations/messages.fr.yml
src/Wallabag/CoreBundle/Resources/translations/messages.it.yml
src/Wallabag/CoreBundle/Resources/translations/messages.oc.yml
src/Wallabag/CoreBundle/Resources/translations/messages.pl.yml
src/Wallabag/CoreBundle/Resources/translations/messages.pt.yml
src/Wallabag/CoreBundle/Resources/translations/messages.ro.yml
src/Wallabag/CoreBundle/Resources/translations/messages.tr.yml
src/Wallabag/CoreBundle/Resources/views/themes/baggy/Config/index.html.twig
src/Wallabag/CoreBundle/Resources/views/themes/material/Config/index.html.twig

Add a missing translation.
cc @wallabag/translators

Fix translations on QR code instructions

---

src/Wallabag/CoreBundle/Resources/translations/messages.it.yml

Here is the fully translated messages.it.yml file.
On the other hand, I have other translations to submit that are from already merged pull requests. Does it mean that I need to open new PR for each of them?

Revised messages.it.yml file

---

src/Wallabag/ApiBundle/Controller/EntryRestController.php
tests/Wallabag/ApiBundle/Controller/EntryRestControllerTest.php

| Fixed tickets | https://github.com/wallabag/wallabag/issues/3243

Avoid BC on exists endpoint

---

src/Wallabag/ApiBundle/Controller/EntryRestController.php
src/Wallabag/CoreBundle/Entity/Entry.php
src/Wallabag/CoreBundle/Helper/ContentProxy.php
tests/Wallabag/ApiBundle/Controller/EntryRestControllerTest.php
tests/Wallabag/CoreBundle/Helper/ContentProxyTest.php

| Fixed tickets | https://github.com/wallabag/wallabag/issues/3249 & https://github.com/wallabag/wallabag/issues/3232
The PATCH method for the entry should only update what user sent to us and not the whole entry as it was before. (https://github.com/wallabag/wallabag/issues/3249)
Also, sending tags when patching an entry will now remove all current tags & assocatied new ones. (https://github.com/wallabag/wallabag/issues/3232)

Fix PATCH method

---

src/Wallabag/ApiBundle/Controller/DeveloperController.php
tests/Wallabag/ApiBundle/Controller/DeveloperControllerTest.php

| Documentation | needs update
| Fixed tickets | https://github.com/wallabag/wallabag/issues/3262
This revert https://github.com/wallabag/wallabag/pull/3227
Docs needs to be updated too (revert that PR https://github.com/wallabag/doc/pull/20).

Revert client_credentials grant types

---

.travis.yml

Testing on PHP 7.2

---

src/Wallabag/CoreBundle/Helper/ContentProxy.php
tests/Wallabag/ApiBundle/Controller/EntryRestControllerTest.php

Hi,
Don't know if it's the best way to do this but it a blocker to me because we're using it on wallabagger.

Fix updatePublishedAt on already parsed article's date

---

src/Wallabag/CoreBundle/Command/InstallCommand.php

Remove unused use statement in install command

---

src/Wallabag/CoreBundle/Command/CleanDuplicatesCommand.php
src/Wallabag/CoreBundle/Command/ExportCommand.php
src/Wallabag/CoreBundle/Command/ShowUserCommand.php

Remove unused method getDoctrine in several commands

---

src/Wallabag/CoreBundle/Command/ShowUserCommand.php

Better rendering for show user command using symfony style

---

src/Wallabag/CoreBundle/Controller/EntryController.php
src/Wallabag/CoreBundle/Resources/translations/messages.da.yml
src/Wallabag/CoreBundle/Resources/translations/messages.de.yml
src/Wallabag/CoreBundle/Resources/translations/messages.en.yml
src/Wallabag/CoreBundle/Resources/translations/messages.es.yml
src/Wallabag/CoreBundle/Resources/translations/messages.fa.yml
src/Wallabag/CoreBundle/Resources/translations/messages.fr.yml
src/Wallabag/CoreBundle/Resources/translations/messages.it.yml
src/Wallabag/CoreBundle/Resources/translations/messages.oc.yml
src/Wallabag/CoreBundle/Resources/translations/messages.pl.yml
src/Wallabag/CoreBundle/Resources/translations/messages.pt.yml
src/Wallabag/CoreBundle/Resources/translations/messages.ro.yml
src/Wallabag/CoreBundle/Resources/translations/messages.tr.yml
src/Wallabag/CoreBundle/Resources/views/themes/common/Entry/_title.html.twig

| Fixed tickets | #3019 
This is a another proposal (see #3221) in order to solve #3019.

Add a dedicated title for all entries page

---

src/Wallabag/ImportBundle/Import/BrowserImport.php

Add missing abstract method prepareEntry in BrowserImport

---

src/Wallabag/AnnotationBundle/Repository/AnnotationRepository.php
src/Wallabag/ApiBundle/Controller/EntryRestController.php
src/Wallabag/CoreBundle/GuzzleSiteAuthenticator/GrabySiteConfigBuilder.php
src/Wallabag/CoreBundle/Helper/EntriesExport.php
src/Wallabag/CoreBundle/Repository/EntryRepository.php
src/Wallabag/CoreBundle/Repository/TagRepository.php
src/Wallabag/ImportBundle/Controller/WallabagController.php
src/Wallabag/ImportBundle/Import/BrowserImport.php
src/Wallabag/UserBundle/Repository/UserRepository.php

Fix some namespaces and phpdoc

---

src/Wallabag/CoreBundle/Command/CleanDuplicatesCommand.php
src/Wallabag/CoreBundle/Command/ExportCommand.php
src/Wallabag/CoreBundle/Command/InstallCommand.php
src/Wallabag/CoreBundle/Command/ShowUserCommand.php
src/Wallabag/CoreBundle/Command/TagAllCommand.php
tests/Wallabag/CoreBundle/Command/ExportCommandTest.php
tests/Wallabag/CoreBundle/Command/ShowUserCommandTest.php
tests/Wallabag/CoreBundle/Command/TagAllCommandTest.php

Example with the install command:

Better rendering for all core commands

---

src/Wallabag/CoreBundle/Command/ListUserCommand.php
src/Wallabag/UserBundle/Repository/UserRepository.php
tests/Wallabag/CoreBundle/Command/ListUserCommandTest.php

Add list users command

---

app/Resources/CraueConfigBundle/translations/CraueConfigBundle.oc.yml
src/Wallabag/CoreBundle/Resources/translations/messages.oc.yml
src/Wallabag/UserBundle/Resources/translations/wallabag_user.oc.yml

Mise à jour des traductions des nouvelles chaînes de caractères + correction de fautes.
src/Wallabag/CoreBundle/Resources/translations/messages.oc.yml
Ligne 538 je ne suis pas sûr de l'espacement nécessaire.

Occitan language updates

---

src/Wallabag/CoreBundle/Resources/translations/messages.oc.yml

Apostrophe par erreur, et "aller À votre compte" et non "sur", pas choquant mais mieux je pense en OC.
| Q              | A

Translation : OC small changes

---

README.md

Update Readme with crucial information

---

src/Wallabag/CoreBundle/Resources/translations/messages.de.yml

Missing quotation marks have been added and small grammar fixes.
This time for wallabag branch 2.3 instead of master.

Add missing quotation marks and small fixes (2)

---

app/Resources/static/themes/_global/index.js
app/Resources/static/themes/_global/js/shortcuts/main.js

| Bug fix?      | sort of
| Fixed tickets | n/a
Few days ago I faced an error while executing grunt tasks and webpack regarding some comments. I can't reproduce it anymore but anyway here is the fix.

Fix webpack error on comments

---

src/Wallabag/CoreBundle/Helper/EntriesExport.php
src/Wallabag/CoreBundle/Resources/config/services.yml
src/Wallabag/CoreBundle/Resources/translations/messages.da.yml
src/Wallabag/CoreBundle/Resources/translations/messages.de.yml
src/Wallabag/CoreBundle/Resources/translations/messages.en.yml
src/Wallabag/CoreBundle/Resources/translations/messages.es.yml
src/Wallabag/CoreBundle/Resources/translations/messages.fa.yml
src/Wallabag/CoreBundle/Resources/translations/messages.fr.yml
src/Wallabag/CoreBundle/Resources/translations/messages.it.yml
src/Wallabag/CoreBundle/Resources/translations/messages.oc.yml
src/Wallabag/CoreBundle/Resources/translations/messages.pl.yml
src/Wallabag/CoreBundle/Resources/translations/messages.pt.yml
src/Wallabag/CoreBundle/Resources/translations/messages.ro.yml
src/Wallabag/CoreBundle/Resources/translations/messages.tr.yml

| Tests pass?   | yes I think 😇 
| Fixed tickets | #3277

Translated first page of exported article

---

app/DoctrineMigrations/Version20171008195606.php
src/Wallabag/CoreBundle/Entity/Entry.php

| Tests pass?   | yes 🤞 
| Fixed tickets | #3286
Not sure about Postgres migration. I don't install PG on my new laptop, so if someone can help me here 😗 ...

Changed reading_time field to prevent null values

---

CHANGELOG.md
RELEASE_PROCESS.md
app/config/wallabag.yml

Prepare wallabag 2.3.0

---

src/Wallabag/CoreBundle/Resources/views/themes/material/Config/index.html.twig

views/config: fix overlaying drop down menu

---

.editorconfig

Update .editorconfig for makefile in order to use tabs

Update .editorconfig for makefile

---

tests/Wallabag/CoreBundle/Controller/EntryControllerTest.php
tests/Wallabag/ImportBundle/Controller/FirefoxControllerTest.php

Fix the tests

---

app/Resources/CraueConfigBundle/translations/CraueConfigBundle.en.yml

Spelling: diaspora, e-mail, moved ?, URL, sharing

---

composer.json
src/Wallabag/ImportBundle/Consumer/RedisEntryConsumer.php

| Bug fix?      | kind of
The 1.3.0 tag is introducing BC so we jump to the 2.*
See https://github.com/javibravo/simpleue/issues/7

Jump to Simpleue 2.0

---

app/Resources/CraueConfigBundle/translations/CraueConfigBundle.th.yml
app/config/wallabag.yml
src/Wallabag/CoreBundle/Resources/translations/messages.th.yml
src/Wallabag/CoreBundle/Resources/translations/validators.th.yml
src/Wallabag/UserBundle/Resources/translations/wallabag_user.th.yml

Add Thai language

---

app/Resources/CraueConfigBundle/translations/CraueConfigBundle.de.yml
src/Wallabag/CoreBundle/Resources/translations/validators.de.yml

Translate new strings

---

src/Wallabag/ApiBundle/Controller/UserRestController.php

I didn't try to find which package introduced a BC (might be user-bundle or jms serializer)

Fix bad key matching

---

app/DoctrineMigrations/Version20170719231144.php

Fix migration from #3139

---

.github/PULL_REQUEST_TEMPLATE.md
CHANGELOG.md
RELEASE_PROCESS.md

Updated changelog for 2.3

---

src/Wallabag/CoreBundle/Resources/views/themes/common/Entry/_rss_link.html.twig

| Tests pass?   | yes/
| Fixed tickets | #3483

Displayed the RSS icon on homepage route

---

web/robots.txt

| Deprecations? | -no
| Fixed tickets | #3508
Fix #3508

Updated robots.txt to prevent crawling

---

app/DoctrineMigrations/Version20170719231144.php

| Fixed tickets | #3494
Fix #3494

Fixed lower case tags migration

---

app/Resources/CraueConfigBundle/translations/CraueConfigBundle.pt.yml
src/Wallabag/UserBundle/Resources/translations/wallabag_user.pt.yml

Update PT translations

---

CHANGELOG.md
app/config/wallabag.yml

Changelog updated for wallabag 2.3.1

Prepared wallabag 2.3.1

---

scripts/update.sh

fixes #2957
| Fixed tickets | #2957

add `set -eu` to update.sh

---

CHANGELOG.md
app/config/wallabag.yml

Changelog updated for wallabag 2.3.2

Prepare 2.3.2 release

---

src/Wallabag/CoreBundle/Helper/DownloadImages.php
tests/Wallabag/CoreBundle/Helper/DownloadImagesTest.php

Hi there,
A long time issue bothering me. This is a fix for the `srcset` image attribute handling. Should fix #2981 and #3217. Every image variation handled. Keep in mind that the storage size might be a lot bigger.
Have a nice day.

Fix srcset attribute on images downloaded

---

app/Resources/CraueConfigBundle/translations/CraueConfigBundle.oc.yml
src/Wallabag/CoreBundle/Resources/translations/messages.oc.yml
src/Wallabag/UserBundle/Resources/translations/wallabag_user.oc.yml

Simplement une mise à jour de la traduction.

[i18n] Occitan update

---

src/Wallabag/CoreBundle/Resources/translations/messages.en.yml

Not completely sure what "Thought of the developers" alludes to.
Maybe it should be just "Thought of developers" ?

Spelling: GitHub, Log out, of the dev

---

CHANGELOG.md
app/config/wallabag.yml

Changelog updated for wallabag 2.3.3

Prepare 2.3.3 release

---

README.md

The YunoHost have working Wallabag package with working install,remove,update,backup and restore scripts. YunoHost makes self -hosting easy for the end users. Please add the this badge so that people can find this solution.

Propose YunoHost badge for installing

---

src/Wallabag/UserBundle/Resources/views/Security/login.html.twig

Some quick code to add the autofocus to the username field.

Autofocus the username field on the login page

---

app/Resources/CraueConfigBundle/translations/CraueConfigBundle.en.yml
src/Wallabag/CoreBundle/Resources/translations/messages.en.yml

Installed wallabag on my server, noticed a typo that kind of bothered me, submitted a PR that fixes the typo.
EDIT: Spotted another one. Tagging this as "translation" at this point.

Fixes a typo

---

.scrutinizer.yml
package.json
src/Wallabag/CoreBundle/Repository/EntryRepository.php
tests/Wallabag/CoreBundle/Controller/EntryControllerTest.php
yarn.lock

Add some missing parameters from a previous PR: https://github.com/wallabag/wallabag/pull/3712
Jump to the new Scrutinizer PHP analysis engine.
And fix language tests.

Fix sort parameters

---

tests/Wallabag/CoreBundle/Controller/EntryControllerTest.php
tests/Wallabag/ImportBundle/Controller/InstapaperControllerTest.php
tests/Wallabag/ImportBundle/Controller/WallabagV2ControllerTest.php
tests/Wallabag/ImportBundle/fixtures/instapaper-export.csv
tests/Wallabag/ImportBundle/fixtures/wallabag-v2.json

Liberation goes https

---

docker/php/Dockerfile

| Fixed tickets | #3732
Fix errors during docker-compose build with php:fpm (Php v7.2)

Fix dockerfile php72

---

.travis.yml
CHANGELOG.md
app/config/wallabag.yml
composer.json
tests/Wallabag/CoreBundle/Controller/EntryControllerTest.php

Changelog updated for wallabag 2.3.4 and fixing tests.

Prepare 2.3.4 release

---

RELEASE_PROCESS.md
app/config/wallabag.yml
scripts/release.sh

After the latest release, I update the documentation about it so it’s more clear

Jump to 2.3.5-dev and update release process

---

CHANGELOG.md
RELEASE_PROCESS.md
app/config/wallabag.yml

Changelog updated for wallabag 2.3.5.

Prepare 2.3.5 release

---

RELEASE_PROCESS.md
app/config/wallabag.yml
scripts/release.sh

Fix release archive in `release.sh` and also fix a typo in the release process

Jump to 2.3.6-dev and update release process

---

src/Wallabag/ApiBundle/Controller/TagRestController.php
src/Wallabag/CoreBundle/DataFixtures/ORM/LoadEntryData.php
src/Wallabag/CoreBundle/DataFixtures/ORM/LoadTagData.php
src/Wallabag/CoreBundle/Repository/TagRepository.php
tests/Wallabag/ApiBundle/Controller/TagRestControllerTest.php

Fix tag API leak

---

CHANGELOG.md
app/config/wallabag.yml

Changelog updated for wallabag 2.3.6.

Prepare 2.3.6 release

---

app/config/wallabag.yml

Jump to 2.3.7-dev

---

composer.json
src/Wallabag/CoreBundle/Helper/PreparePagerForEntries.php
src/Wallabag/CoreBundle/Repository/SiteCredentialRepository.php
src/Wallabag/ImportBundle/Import/InstapaperImport.php

| BC breaks?    | probably not
Bump ocramius/proxy-manager to the latest PHP 7.1 supported version

Bump ocramius/proxy-manager

---

app/config/config.yml
src/Wallabag/CoreBundle/Form/Type/EntryFilterType.php
src/Wallabag/CoreBundle/Helper/PreparePagerForEntries.php
src/Wallabag/CoreBundle/Repository/SiteCredentialRepository.php
src/Wallabag/ImportBundle/Import/BrowserImport.php
src/Wallabag/ImportBundle/Import/ChromeImport.php
src/Wallabag/ImportBundle/Import/FirefoxImport.php
src/Wallabag/ImportBundle/Import/InstapaperImport.php
src/Wallabag/ImportBundle/Import/WallabagImport.php
src/Wallabag/ImportBundle/Import/WallabagV1Import.php

Following https://github.com/wallabag/wallabag/pull/3368
Fix #3367
I wasn't able to push change to the `master` of @Rurik19 so I cherry-picked commits in a new PR.

Fix CORS for API

---

src/Wallabag/CoreBundle/Helper/EntriesExport.php

epub export: fix missing cover image, only for exports of one article

---

app/Resources/static/themes/material/css/cards.scss
app/Resources/static/themes/material/css/media_queries.scss

Production assets will be provided by the last UI PR accepted.
Fixes #3877

material: fix left padding of content on medium screens

---

CHANGELOG.md
app/config/wallabag.yml

Changelog updated for wallabag 2.3.7.

Prepare 2.3.7 release

---

app/config/wallabag.yml

Jump to 2.3.8-dev

---

scripts/dev.sh
scripts/install.sh
scripts/update.sh

Make dev/install/update script posix compatible

---

CHANGELOG.md
app/config/wallabag.yml

Changelog updated for wallabag 2.3.8.

Prepare 2.3.8 release

---

docker/php/Dockerfile

Following:
- https://github.com/wallabag/wallabag/issues/3899
- https://github.com/wallabag/wallabag/issues/3961

Force PHP version in Dockerfile

---

tests/Wallabag/CoreBundle/Controller/EntryControllerTest.php

Fix test as site jumped from `http` to `https`.

Fix http/https test

---

app/AppKernel.php
app/config/config.yml
composer.json
src/Wallabag/ApiBundle/Controller/EntryRestController.php
src/Wallabag/CoreBundle/Helper/ContentProxy.php
src/Wallabag/CoreBundle/Helper/DownloadImages.php
src/Wallabag/CoreBundle/Helper/HttpClientFactory.php
src/Wallabag/CoreBundle/Resources/config/services.yml
src/Wallabag/ImportBundle/Import/PocketImport.php
src/Wallabag/ImportBundle/Import/WallabagV2Import.php
src/Wallabag/ImportBundle/Resources/config/services.yml
tests/Wallabag/CoreBundle/Helper/ContentProxyTest.php
tests/Wallabag/CoreBundle/Helper/DownloadImagesTest.php
tests/Wallabag/ImportBundle/Import/PocketImportTest.php

Try wallabag with a branch of Graby which supports httplug
@see https://github.com/j0k3r/graby/issues/107

Use httplug and graby 2.0

---

app/config/parameters.yml.dist

| Bug fix?      | not really
Fix #3625

Try to force people to update the secret

---

app/AppKernel.php
app/config/config_prod.yml
app/config/parameters.yml.dist
composer.json
composer.lock

| Documentation | https://github.com/wallabag/doc/pull/94
Only enable in production

Add Sentry support

---

src/Wallabag/CoreBundle/Resources/translations/messages.da.yml
src/Wallabag/CoreBundle/Resources/translations/messages.de.yml
src/Wallabag/CoreBundle/Resources/translations/messages.en.yml
src/Wallabag/CoreBundle/Resources/translations/messages.es.yml
src/Wallabag/CoreBundle/Resources/translations/messages.fa.yml
src/Wallabag/CoreBundle/Resources/translations/messages.fr.yml
src/Wallabag/CoreBundle/Resources/translations/messages.it.yml
src/Wallabag/CoreBundle/Resources/translations/messages.oc.yml
src/Wallabag/CoreBundle/Resources/translations/messages.pl.yml
src/Wallabag/CoreBundle/Resources/translations/messages.pt.yml
src/Wallabag/CoreBundle/Resources/translations/messages.ro.yml
src/Wallabag/CoreBundle/Resources/translations/messages.ru.yml
src/Wallabag/CoreBundle/Resources/translations/messages.th.yml
src/Wallabag/CoreBundle/Resources/translations/messages.tr.yml
src/Wallabag/CoreBundle/Resources/views/themes/baggy/layout.html.twig
src/Wallabag/CoreBundle/Resources/views/themes/material/layout.html.twig

Just in case people want to see that page again.
Fixes https://github.com/wallabag/wallabag/issues/2574

Add quickstart into the menu

---

src/Wallabag/CoreBundle/Controller/ConfigController.php
src/Wallabag/CoreBundle/Resources/translations/messages.da.yml
src/Wallabag/CoreBundle/Resources/translations/messages.de.yml
src/Wallabag/CoreBundle/Resources/translations/messages.en.yml
src/Wallabag/CoreBundle/Resources/translations/messages.es.yml
src/Wallabag/CoreBundle/Resources/translations/messages.fa.yml
src/Wallabag/CoreBundle/Resources/translations/messages.fr.yml
src/Wallabag/CoreBundle/Resources/translations/messages.it.yml
src/Wallabag/CoreBundle/Resources/translations/messages.oc.yml
src/Wallabag/CoreBundle/Resources/translations/messages.pl.yml
src/Wallabag/CoreBundle/Resources/translations/messages.pt.yml
src/Wallabag/CoreBundle/Resources/translations/messages.ro.yml
src/Wallabag/CoreBundle/Resources/translations/messages.ru.yml
src/Wallabag/CoreBundle/Resources/translations/messages.th.yml
src/Wallabag/CoreBundle/Resources/translations/messages.tr.yml
src/Wallabag/CoreBundle/Resources/views/themes/baggy/Config/index.html.twig
src/Wallabag/CoreBundle/Resources/views/themes/material/Config/index.html.twig
tests/Wallabag/CoreBundle/Controller/ConfigControllerTest.php

Add ability to revoke feed token

---

src/Wallabag/CoreBundle/Controller/TagController.php
src/Wallabag/CoreBundle/Repository/EntryRepository.php
src/Wallabag/CoreBundle/Resources/translations/messages.da.yml
src/Wallabag/CoreBundle/Resources/translations/messages.de.yml
src/Wallabag/CoreBundle/Resources/translations/messages.en.yml
src/Wallabag/CoreBundle/Resources/translations/messages.es.yml
src/Wallabag/CoreBundle/Resources/translations/messages.fa.yml
src/Wallabag/CoreBundle/Resources/translations/messages.fr.yml
src/Wallabag/CoreBundle/Resources/translations/messages.it.yml
src/Wallabag/CoreBundle/Resources/translations/messages.oc.yml
src/Wallabag/CoreBundle/Resources/translations/messages.pl.yml
src/Wallabag/CoreBundle/Resources/translations/messages.pt.yml
src/Wallabag/CoreBundle/Resources/translations/messages.ro.yml
src/Wallabag/CoreBundle/Resources/translations/messages.ru.yml
src/Wallabag/CoreBundle/Resources/translations/messages.th.yml
src/Wallabag/CoreBundle/Resources/translations/messages.tr.yml
src/Wallabag/CoreBundle/Resources/views/themes/baggy/Tag/tags.html.twig
src/Wallabag/CoreBundle/Resources/views/themes/material/Tag/tags.html.twig

Show untagged entries count on tag list

---

src/Wallabag/CoreBundle/Resources/translations/messages.da.yml
src/Wallabag/CoreBundle/Resources/translations/messages.de.yml
src/Wallabag/CoreBundle/Resources/translations/messages.en.yml
src/Wallabag/CoreBundle/Resources/translations/messages.es.yml
src/Wallabag/CoreBundle/Resources/translations/messages.fa.yml
src/Wallabag/CoreBundle/Resources/translations/messages.fr.yml
src/Wallabag/CoreBundle/Resources/translations/messages.it.yml
src/Wallabag/CoreBundle/Resources/translations/messages.oc.yml
src/Wallabag/CoreBundle/Resources/translations/messages.pl.yml
src/Wallabag/CoreBundle/Resources/translations/messages.pt.yml
src/Wallabag/CoreBundle/Resources/translations/messages.ro.yml
src/Wallabag/CoreBundle/Resources/translations/messages.ru.yml
src/Wallabag/CoreBundle/Resources/translations/messages.th.yml
src/Wallabag/CoreBundle/Resources/translations/messages.tr.yml
src/Wallabag/CoreBundle/Resources/views/themes/baggy/Config/index.html.twig
src/Wallabag/CoreBundle/Resources/views/themes/material/Config/index.html.twig

Just so the user can see its login
Fix #3645

Display login in config / user

---

.travis.yml

Travis has moved our build from Trusty to Xenial, some changes are required.

Fix Travis build on Xenial dist

---

app/DoctrineMigrations/Version20190619093534.php

Fix `reading_time` being NULL on SQLite

---

.github/CONTRIBUTING.md
docker-compose.yml
docker/php/Dockerfile

Fix #3989 (poke @buoyantair)
Also:
- update the docker-compose to use Alpine image (lighter)
- update the PHP Dockerfile to use Imagick instead of GD (for GIF support when downloading images) and add support for SQLite

Improve CONTRIBUTING guide

---

src/Wallabag/CoreBundle/Resources/translations/messages.oc.yml

Cette PR met à jour la traducion en occitan, dans sa variante standard, à base de languedocien.
J'espère que les ' et " sont correctement utilisés.

Update of Occitan language

---

.travis.yml

PHP 7.4 will be available before the 8.0

Test on PHP 7.4 instead of PHP 8.0 on Travis

---

src/Wallabag/CoreBundle/Resources/translations/messages.fr.yml

Fixed some :fr: typos

---

src/Wallabag/UserBundle/Resources/views/Authentication/form.html.twig

Fixed translation for 2FA

---

src/Wallabag/CoreBundle/Resources/translations/messages.es.yml
src/Wallabag/CoreBundle/Resources/translations/validators.es.yml

Update spanish translations

---

src/Wallabag/CoreBundle/Resources/translations/messages.pt.yml
src/Wallabag/CoreBundle/Resources/translations/validators.pt.yml

Updating portuguese translations

---

src/Wallabag/CoreBundle/Resources/views/themes/material/Entry/new_form.html.twig
src/Wallabag/CoreBundle/Resources/views/themes/material/Entry/search_form.html.twig

Fixes #4130 
Fix duplicated icons on "Search engine" and "new link" forms

🐛 — Fix duplicated icons on "Search engine" and "new link" forms

---

composer.lock
tests/Wallabag/CoreBundle/Controller/EntryControllerTest.php

- Updating twig/twig (v2.12.0 => v2.12.1)
- Updating symfony/mime (v4.3.4 => v4.3.5)
- Updating friendsofsymfony/rest-bundle (2.5.0 => 2.6.0)
- Updating j0k3r/graby-site-config (1.0.91 => 1.0.93)
- Updating monolog/monolog (1.24.0 => 1.25.1)
- Updating simplepie/simplepie (1.5.2 => 1.5.3)
- Updating symfony/http-client-contracts (v1.1.6 => v1.1.7)
- Updating symfony/http-client (v4.3.4 => v4.3.5)
- Updating nette/utils (v3.0.1 => v3.0.2)
- Updating phpstan/phpstan (0.11.17 => 0.11.18)
- Updating zendframework/zend-code (3.3.2 => 3.4.0)
- Updating php-amqplib/php-amqplib (v2.10.0 => v2.10.1)
- Updating beberlei/assert (v3.2.3 => v3.2.6)
- Updating zendframework/zend-diactoros (2.1.3 => 2.1.5)
- Updating sentry/sentry (2.2.1 => 2.2.2)

Fix tests & update deps

---

docker/php/Dockerfile

In order to do `composer install` on php Docker container using for development purpose, I add the extensions requiring during the `composer install`

Add package and PHP extension to PHP docker

---

app/config/config.yml
src/Wallabag/CoreBundle/Resources/translations/messages.da.yml
src/Wallabag/CoreBundle/Resources/translations/messages.de.yml
src/Wallabag/CoreBundle/Resources/translations/messages.en.yml
src/Wallabag/CoreBundle/Resources/translations/messages.es.yml
src/Wallabag/CoreBundle/Resources/translations/messages.fa.yml
src/Wallabag/CoreBundle/Resources/translations/messages.fr.yml
src/Wallabag/CoreBundle/Resources/translations/messages.it.yml
src/Wallabag/CoreBundle/Resources/translations/messages.oc.yml
src/Wallabag/CoreBundle/Resources/translations/messages.pl.yml
src/Wallabag/CoreBundle/Resources/translations/messages.pt.yml
src/Wallabag/CoreBundle/Resources/translations/messages.ro.yml
src/Wallabag/CoreBundle/Resources/translations/messages.ru.yml
src/Wallabag/CoreBundle/Resources/translations/messages.th.yml
src/Wallabag/CoreBundle/Resources/translations/messages.tr.yml
src/Wallabag/ImportBundle/Controller/ElcuratorController.php
src/Wallabag/ImportBundle/Import/ElcuratorImport.php
src/Wallabag/ImportBundle/Resources/config/rabbit.yml
src/Wallabag/ImportBundle/Resources/config/redis.yml
src/Wallabag/ImportBundle/Resources/config/services.yml
src/Wallabag/ImportBundle/Resources/views/Elcurator/index.html.twig
tests/Wallabag/ImportBundle/Controller/ElcuratorControllerTest.php
tests/Wallabag/ImportBundle/Controller/ImportControllerTest.php
tests/Wallabag/ImportBundle/Controller/PinboardControllerTest.php
tests/Wallabag/ImportBundle/fixtures/elcurator.json

https://www.elcurator.net will shutdown on december.

Added elCurator import

---

src/Wallabag/ImportBundle/Controller/ImportController.php

I forgot some checks with elCurator import

Fixed elCurator check for RabbitMQ / Redis

---

src/Wallabag/AnnotationBundle/Entity/Annotation.php
src/Wallabag/AnnotationBundle/Form/NewAnnotationType.php
src/Wallabag/ApiBundle/Controller/AnnotationRestController.php
tests/Wallabag/AnnotationBundle/Controller/AnnotationControllerTest.php

API return an error with empty quote

---

src/Wallabag/CoreBundle/Entity/Entry.php
src/Wallabag/CoreBundle/Resources/views/base.html.twig
src/Wallabag/CoreBundle/Resources/views/themes/baggy/Entry/entry.html.twig
src/Wallabag/CoreBundle/Resources/views/themes/material/Entry/entry.html.twig
tests/Wallabag/CoreBundle/Entity/EntryTest.php

Another quick one using the app language for the main html tag and the grabbed site one for our entry content.

Use lang attribute

---

app/config/config_dev.yml
app/config/wallabag.yml
docker-compose.yml
src/Wallabag/CoreBundle/Resources/translations/messages.da.yml
src/Wallabag/CoreBundle/Resources/translations/messages.en.yml
src/Wallabag/CoreBundle/Resources/translations/messages.es.yml
src/Wallabag/CoreBundle/Resources/translations/messages.fa.yml
src/Wallabag/CoreBundle/Resources/translations/messages.fr.yml
src/Wallabag/CoreBundle/Resources/translations/messages.it.yml
src/Wallabag/CoreBundle/Resources/translations/messages.oc.yml
src/Wallabag/CoreBundle/Resources/translations/messages.pl.yml
src/Wallabag/CoreBundle/Resources/translations/messages.pt.yml
src/Wallabag/CoreBundle/Resources/translations/messages.ro.yml
src/Wallabag/CoreBundle/Resources/translations/messages.ru.yml
src/Wallabag/CoreBundle/Resources/translations/messages.th.yml
src/Wallabag/CoreBundle/Resources/translations/messages.tr.yml

- http to https
- replaced generic .com by specific TLD
- updated some dead urls

cosmetic changes

---

.travis.yml
src/Wallabag/CoreBundle/Controller/ExportController.php
src/Wallabag/CoreBundle/Resources/views/themes/baggy/Entry/entries.html.twig
src/Wallabag/CoreBundle/Resources/views/themes/material/Entry/entries.html.twig
tests/Wallabag/CoreBundle/Controller/ExportControllerTest.php

Fixes #4240
*Note:* this PR also updates the configuration file for Travis in order to prevent the double push/pr builds triggered on PR not coming from forks. Now, pushing to any branch other than master on this repository without making a PR will not trigger a build on Travis.

Fix entries export from search view

---

GNUmakefile
app/config/services.yml
src/Wallabag/CoreBundle/Resources/views/base.html.twig
src/Wallabag/CoreBundle/Twig/WallabagExtension.php
tests/Wallabag/CoreBundle/Twig/WallabagExtensionTest.php

Hello there,
I get the point of this custom.css file but I think we should avoid requesting files when they are empty. I would prefer writing documentation about this rather then doing an extra HTTP request.
If this PR is okay for you, let me know the best place to write about it in the doc repo.

Load custom.css only if exists

---

app/Resources/CraueConfigBundle/translations/CraueConfigBundle.ja.yml
app/config/wallabag.yml
src/Wallabag/CoreBundle/Resources/translations/messages.ja.yml
src/Wallabag/CoreBundle/Resources/translations/validators.ja.yml
src/Wallabag/UserBundle/Resources/translations/wallabag_user.ja.yml

add option "Japanese(日本語)" & add Japanese translation.

add Japanese translation

---

composer.json
composer.lock

Replace grandt/phpepub with wallabag version

---

src/Wallabag/CoreBundle/Resources/translations/messages.ja.yml

- Some mistranslations have been corrected.
- Some expressions have been updated to make them easier to understand.

update Japanese translation

---

src/Wallabag/CoreBundle/GuzzleSiteAuthenticator/GrabySiteConfigBuilder.php

Today, when we are in a Symfony Command (for example, `ImportCommand`), if we want to save an URL for paywalled websites, as we are not authenticated, the whole content is not saved. 
So we need to improve the Command, to create a Token Storage. 
But, when we create it, Graby losed it because the current user in `GrabySiteConfigBuilder` is initialized in the constructor. 
My PR is here to change this behavior. 
@wallabag/core need your review

Changed authentication order in GrabySiteConfigBuilder

---

src/Wallabag/ImportBundle/Command/ImportCommand.php

| Tests pass?   | yes I hope :D 
As explained in #4318, there is a bug with the Import Command: websites where we need to be authenticated are not parsed as it should be.
This PR creates a token. Graby can now get the current user and use credentials.

Added authentication during import command for paywalled websites

---

src/Wallabag/CoreBundle/Resources/translations/messages.da.yml
src/Wallabag/CoreBundle/Resources/translations/messages.de.yml
src/Wallabag/CoreBundle/Resources/translations/messages.en.yml
src/Wallabag/CoreBundle/Resources/translations/messages.es.yml
src/Wallabag/CoreBundle/Resources/translations/messages.fa.yml
src/Wallabag/CoreBundle/Resources/translations/messages.fr.yml
src/Wallabag/CoreBundle/Resources/translations/messages.it.yml
src/Wallabag/CoreBundle/Resources/translations/messages.ja.yml
src/Wallabag/CoreBundle/Resources/translations/messages.oc.yml
src/Wallabag/CoreBundle/Resources/translations/messages.pl.yml
src/Wallabag/CoreBundle/Resources/translations/messages.pt.yml
src/Wallabag/CoreBundle/Resources/translations/messages.ro.yml
src/Wallabag/CoreBundle/Resources/translations/messages.ru.yml
src/Wallabag/CoreBundle/Resources/translations/messages.th.yml
src/Wallabag/CoreBundle/Resources/translations/messages.tr.yml
src/Wallabag/CoreBundle/Resources/translations/messages.zh.yml
src/Wallabag/CoreBundle/Resources/views/themes/material/Entry/entries.html.twig

Added confirmation before mass deleting articles

---

src/Wallabag/CoreBundle/Resources/translations/messages.ja.yml

- Japanese translation is updated.

Update Japanese translation (messages.ja.yml)

---

app/config/wallabag.yml

Following https://github.com/wallabag/wallabag/pull/4517

Add Croatian translation

---

composer.json
composer.lock

As new maintainer is in the place.
See https://github.com/predis/predis/issues/587#issuecomment-671791015

Move predis/predis to stable version

---

src/Wallabag/CoreBundle/Resources/views/themes/material/Entry/new_form.html.twig
src/Wallabag/CoreBundle/Resources/views/themes/material/Entry/search_form.html.twig

|Before|After
|------|-----
|![image](https://user-images.githubusercontent.com/2197836/91171330-9a0ca380-e6da-11ea-9650-c37af17789d1.png)|![image](https://user-images.githubusercontent.com/2197836/91171353-a42ea200-e6da-11ea-8f72-129d7060d241.png)

Fix icons not showing aside nav forms

---

package.json
yarn.lock

See https://github.com/jakubpawlowicz/clean-css/commit/2929bafbf8cdf7dccb24e0949c70833764fa87e3

Update annotator to fix clean-css security

---

src/Wallabag/CoreBundle/Resources/translations/messages.en.yml
src/Wallabag/CoreBundle/Resources/translations/messages.fr.yml

The big PR removed some translations.
I hope I added them back.
Following https://github.com/wallabag/wallabag/pull/4442
Related https://github.com/wallabag/wallabag/issues/4621#issuecomment-705202522

Looks like when merging stuff from Weblate we lost translations

---

app/config/wallabag.yml

Since the NL translation is 100% i think it deserves a place in the settings page :-)

Added dutch translation to the settings

---

.github/workflows/assets.yml
composer.json
composer.lock
yarn.lock

Also re-enable assets diff in GitHub Actions.

Update deps (PHP & JS)

---

CHANGELOG.md
app/config/wallabag.yml

Prepare 2.4.0 release

---

web/manifest.json

Hi there,
I forget this on my previous build cleaning.

Fix path icons from manifest.json

---

src/Wallabag/CoreBundle/Command/GenerateUrlHashesCommand.php
src/Wallabag/CoreBundle/Repository/EntryRepository.php

Fixed #4864
My local environment is not yet well configured, so I can't test this improvement 😁 sorry if I broke the testsuite (or if this code is not correct). It's ready for review .. Or not!

Added a query to parse only non-hashed URL

---

src/Wallabag/CoreBundle/Controller/ConfigController.php
src/Wallabag/CoreBundle/Resources/translations/messages.en.yml
src/Wallabag/CoreBundle/Resources/translations/messages.fr.yml
src/Wallabag/CoreBundle/Resources/views/themes/material/Config/otp_app.html.twig

| Bug fix?      | ~
| New feature?  | ~
Fixes #4818

Show OTP secret next to the QR Code

---

app/config/config.yml
app/config/parameters.yml.dist
src/Wallabag/CoreBundle/Resources/views/themes/baggy/Config/otp_app.html.twig
src/Wallabag/CoreBundle/Resources/views/themes/material/Config/otp_app.html.twig

Add label and issuer to otp config

---

CHANGELOG.md
app/config/wallabag.yml
composer.lock

- update changelog
- bump version
- update deps

Prepare 2.4.1

---

src/Wallabag/CoreBundle/Controller/EntryController.php
src/Wallabag/CoreBundle/Form/Type/EntryFilterType.php
tests/Wallabag/CoreBundle/Controller/EntryControllerTest.php

Preselect currently active section in the filter menu

---

src/Wallabag/CoreBundle/Twig/WallabagExtension.php

Fix translation of date in the footer using IntlDateFormatter

---

src/Wallabag/CoreBundle/Helper/RuleBasedTagger.php
tests/Wallabag/CoreBundle/Helper/RuleBasedTaggerTest.php

Convert tag label to lowercase in RuleBasedTagger

---

src/Wallabag/CoreBundle/Repository/TagRepository.php

Tag view: order tags by label

---

tests/Wallabag/CoreBundle/Controller/EntryControllerTest.php

Fixed unavailable russian website in test

---

app/config/wallabag.yml

Added option for Czech language.

Add Czech language

---

scripts/release.sh

Fix shellcheck warnings in order to improve robustness of this script.

Change the name of the static package's root directory 

---

src/Wallabag/CoreBundle/Controller/FeedController.php

Fixed wrong number of entries for tag feeds.

Fixed wrong number of entries for tag feeds

---

tests/Wallabag/ImportBundle/Controller/ChromeControllerTest.php
tests/Wallabag/ImportBundle/fixtures/chrome-bookmarks

Replace it with a more robust website 🤩

Fix test with `usinenouvelle.com` being flaky these times

---

src/Wallabag/CoreBundle/Helper/DownloadImages.php
tests/Wallabag/CoreBundle/Helper/DownloadImagesTest.php

Continue the work from https://github.com/wallabag/wallabag/pull/5660 by @fly9i
Fix https://github.com/wallabag/wallabag/issues/5107

Add support to download webp image locally

---

composer.json
composer.lock
src/Wallabag/CoreBundle/Helper/EntriesExport.php

Ensure language has `_` instead of `-`
And update wallabag/phpepub
Fix https://github.com/wallabag/wallabag/issues/5596

Fix epub language

---

.github/workflows/coding-standards.yml
.github/workflows/continuous-integration.yml
.github/workflows/translations.yml
composer.json
composer.lock
var/SymfonyRequirements.php

SensioDistributionBundle isn't compatible anymore with Composer 2.3 which break the build when bootstrapping the application.
To install wallabag you must use a version lower than Composer 2.3.

Composer 2.3 isn't compatible with wallabag

---

docker/php/Dockerfile
docker/php/config/parameters.yml
docker/php/env.example

Put the SQLite database in the right expected folder `data/db/` so it's Git ignored and consistent with the test database location

Fix SQLite database location

---

GNUmakefile

In case it's installed and enabled, this will disable it at least when running tests. It gives a performance boost

Disable XDebug in test make recipe

---

.gitignore

Exclude local phpunit.xml

---

src/Wallabag/CoreBundle/Controller/TagController.php
src/Wallabag/CoreBundle/Resources/translations/messages.en.yml
src/Wallabag/CoreBundle/Resources/views/themes/material/Entry/entries.html.twig
tests/Wallabag/CoreBundle/Controller/TagControllerTest.php

Fix #1231. 
Tests need to be fixed.

Add action to assign a search as a tag to each result

---

CHANGELOG.md
app/config/wallabag.yml
composer.lock

Please check the changelog, maybe some PR are better in a different _category_. Let me know.

Prepare 2.5.0 release

---

src/Wallabag/UserBundle/Resources/views/Authentication/form.html.twig

Following bundle inheritance removal https://github.com/wallabag/wallabag/pull/5746
Fix https://github.com/wallabag/wallabag/issues/5824

Fix error about template not found in 2fa form

---

CHANGELOG.md
app/config/wallabag.yml
composer.lock
docker/php/Dockerfile
yarn.lock

See https://github.com/wallabag/wallabag/milestone/70?closed=1
And also update Composer & Yarn deps.

Prepare 2.5.1

---

src/Wallabag/CoreBundle/Resources/config/services.yml

Remove 90 depreciations, move from 1492 to 1402

Register missed commands

---

.github/workflows/dependabot-automerge-js.yml
yarn.lock

Reducing the time consuming of merging deps which shouldn't break the project

Allow auto merging of Dependabot JS minor or patch

---

CHANGELOG.md
app/config/wallabag.yml
composer.lock

See https://github.com/wallabag/wallabag/milestone/71?closed=1
And also update Composer deps.

Prepare 2.5.2

---

app/config/config.yml
app/config/routing.yml
app/config/routing_rest.yml
app/config/services.yml
src/Wallabag/AnnotationBundle/Controller/WallabagAnnotationController.php
src/Wallabag/AnnotationBundle/Resources/config/routing_annotations.yml
src/Wallabag/ApiBundle/Controller/AnnotationRestController.php
src/Wallabag/ApiBundle/Controller/ConfigRestController.php
src/Wallabag/ApiBundle/Controller/EntryRestController.php
src/Wallabag/ApiBundle/Controller/SearchRestController.php
src/Wallabag/ApiBundle/Controller/TagRestController.php
src/Wallabag/ApiBundle/Controller/TaggingRuleRestController.php
src/Wallabag/ApiBundle/Controller/UserRestController.php
src/Wallabag/ApiBundle/Controller/WallabagRestController.php

Also add a new alias for rulerz to remove a deprecation.

Remove deprecated options from FOSRest

---

src/Wallabag/CoreBundle/Controller/TagController.php
src/Wallabag/CoreBundle/Form/Type/NewTagType.php

One user can add a new tag to an entry from an other user.
I've also limited tag length to 20 chars (and limit adding more than 5 tags at once)
Thanks @juylang

Fix adding tag to entries from other people

---

CHANGELOG.md
app/config/wallabag.yml
composer.lock

An other security release!
- Update changelog
- Update deps

Prepare 2.5.4

---

.github/workflows/continuous-integration.yml

Just to see if everything is ok!

Enable PHP 8.2 in CI

---

translations/messages.en.yml

Added a missing translation

---

src/Wallabag/CoreBundle/Resources/views/Entry/entries.html.twig

grrrr I forgot one file in #6617.

Update translation key

---

src/Wallabag/CoreBundle/Resources/views/Entry/entries.html.twig

Remove hardcoded string

---

src/Wallabag/CoreBundle/Resources/views/Static/quickstart.html.twig
translations/messages.en.yml

Update quickstart content

---

CHANGELOG.md
app/config/wallabag.yml

Prepare 2.6.0 release

---

src/Wallabag/CoreBundle/Resources/views/Entry/_card_actions.html.twig

Add confirmation alert when deleting articles from list view

---

CHANGELOG.md
app/config/wallabag.yml

Prepare 2.6.1 release

---

app/DoctrineMigrations/Version20221221092957.php

Wrong table name in migration.

Fix table name in migration

---

src/Wallabag/CoreBundle/Resources/views/Entry/_feed_link.html.twig

Fix undefined variable

---

src/Wallabag/CoreBundle/Controller/ExportController.php
src/Wallabag/CoreBundle/Resources/views/Entry/entries.html.twig
tests/Wallabag/CoreBundle/Controller/ExportControllerTest.php

Fix https://github.com/wallabag/wallabag/issues/6679

Fix export for same domain entries

---

.github/CONTRIBUTING.md

Add test and formatter commands to CONTRIBUTING.md

Document how to run tests and formatter for new contributors

---

docker/php/Dockerfile

Update dev docker base image to php:8.1-fpm

---

CHANGELOG.md
app/config/wallabag.yml
composer.lock

Prepare 2.6.2 release

---

.github/workflows/coding-standards.yml
composer.json
composer.lock

Add composer normalizer

---

src/Wallabag/AnnotationBundle/DataFixtures/AnnotationFixtures.php
src/Wallabag/CoreBundle/DataFixtures/ConfigFixtures.php
src/Wallabag/CoreBundle/DataFixtures/EntryFixtures.php
src/Wallabag/CoreBundle/DataFixtures/IgnoreOriginUserRuleFixtures.php
src/Wallabag/CoreBundle/DataFixtures/SiteCredentialFixtures.php
src/Wallabag/CoreBundle/DataFixtures/TaggingRuleFixtures.php

from [code](https://github.com/doctrine/data-fixtures/blob/1.6.x/src/AbstractFixture.php#L94-L101)
remove ~577 direct depreciation, see from [2119](https://github.com/wallabag/wallabag/actions/runs/5743870218/job/15569056118#step:10:130) to [1542](https://github.com/wallabag/wallabag/actions/runs/5771745420/job/15646010228?pr=6798#step:10:130) for example

Add mandatory $class parameter

---

bin/console
web/app_dev.php

> - Removed the component in favor of the `ErrorHandler` component
> - Replace uses of `Symfony\Component\Debug\Debug` by `Symfony\Component\ErrorHandler\Debug`
from https://github.com/symfony/symfony/blob/4.4/UPGRADE-5.0.md#debug

Replace Debug component by ErrorHandler component

---

tests/Wallabag/AnnotationBundle/WallabagAnnotationTestCase.php
tests/Wallabag/ApiBundle/WallabagApiTestCase.php
tests/Wallabag/CoreBundle/Controller/SiteCredentialControllerTest.php
tests/Wallabag/CoreBundle/WallabagCoreTestCase.php

from [code](https://github.com/symfony/symfony/blob/4.4/src/Symfony/Bundle/FrameworkBundle/Client.php#L26)

Replace Client by KernelBrowser

---

tests/Wallabag/CoreBundle/Controller/EntryControllerTest.php
tests/Wallabag/UserBundle/Controller/ManageControllerTest.php

from [the PHPDoc](https://github.com/symfony/symfony/blob/4.4/src/Symfony/Component/DomCrawler/Crawler.php#L726)

Make Crawler::extract get an array

---

scripts/require.sh

Fix #3589
@Strubbl could you please try if it sounds ok for you?

Add check if git is installed

---

CHANGELOG.md
app/config/wallabag.yml
composer.lock
src/Wallabag/ApiBundle/Controller/DeveloperController.php
src/Wallabag/CoreBundle/Resources/views/Config/index.html.twig
src/Wallabag/CoreBundle/Resources/views/Developer/index.html.twig

Prepare wallabag 2.6.3

---

app/config/config.yml
app/config/services.yml
app/config/services_rabbit.yml
app/config/services_redis.yml
app/config/wallabag.yml
phpstan-baseline.neon
src/Wallabag/ImportBundle/Command/ImportCommand.php
src/Wallabag/ImportBundle/Consumer/RabbitMQConsumerTotalProxy.php
src/Wallabag/ImportBundle/Controller/HtmlController.php
src/Wallabag/ImportBundle/Controller/ImportController.php
src/Wallabag/ImportBundle/Controller/PocketHtmlController.php
src/Wallabag/ImportBundle/Controller/ShaarliController.php
src/Wallabag/ImportBundle/Import/HtmlImport.php
src/Wallabag/ImportBundle/Import/PocketHtmlImport.php
src/Wallabag/ImportBundle/Import/ShaarliImport.php
src/Wallabag/ImportBundle/Resources/views/PocketHtml/index.html.twig
src/Wallabag/ImportBundle/Resources/views/Shaarli/index.html.twig
tests/Wallabag/ImportBundle/Controller/ImportControllerTest.php
tests/Wallabag/ImportBundle/Controller/PocketHtmlControllerTest.php
tests/Wallabag/ImportBundle/Controller/ShaarliControllerTest.php
tests/Wallabag/ImportBundle/Import/PocketHtmlImportTest.php
tests/Wallabag/ImportBundle/Import/ShaarliImportTest.php
tests/Wallabag/ImportBundle/fixtures/ril_export.html
tests/Wallabag/ImportBundle/fixtures/shaarli-bookmarks.html
translations/messages.en.yml

| New feature?  | yes, idea from @nhoizey
| Tests pass?   | **no** 
~~Still one failing test.~~ 
Fix https://github.com/wallabag/wallabag/issues/6776

Add Shaarli and Pocket HTML imports

---

app/config/config.yml

Related to https://github.com/wallabag/wallabag/pull/6797
I revert the for_rest part and it seems to fix https://github.com/wallabag/wallabag/issues/6865
But I have to see with @yguedidi why 🙂

Fix API token generation

---

composer.lock
src/Wallabag/ApiBundle/Controller/EntryRestController.php
src/Wallabag/CoreBundle/Controller/ExportController.php
src/Wallabag/CoreBundle/Helper/EntriesExport.php
tests/Wallabag/ApiBundle/Controller/EntryRestControllerTest.php
tests/Wallabag/CoreBundle/Controller/ExportControllerTest.php

Following https://github.com/wallabag/wallabag/pull/6768

Remove remaining MOBI stuff

---

CHANGELOG.md
app/config/wallabag.yml

Prepare wallabag 2.6.5

---

CHANGELOG.md
app/config/wallabag.yml
composer.lock

Be ready for the next release 🍺

Prepare 2.6.6 release

---

package.json
yarn.lock

Remove unused font `ptsans-npm-webfont`

---

app/Resources/static/themes/_global/index.js
app/config/tests/parameters_test.sqlite.yml
src/Wallabag/AnnotationBundle/Repository/AnnotationRepository.php
src/Wallabag/ApiBundle/Controller/UserRestController.php
src/Wallabag/CoreBundle/Command/InstallCommand.php
src/Wallabag/CoreBundle/Event/Subscriber/TablePrefixSubscriber.php
src/Wallabag/CoreBundle/Repository/EntryRepository.php
src/Wallabag/ImportBundle/Import/AbstractImport.php

Fix some typos

---

app/config/parameters_addons.yml
translations/messages.cs.yml
translations/messages.de.yml
translations/messages.el.yml
translations/messages.en.yml
translations/messages.es.yml
translations/messages.fa.yml
translations/messages.fr.yml
translations/messages.gl.yml
translations/messages.hr.yml
translations/messages.hu.yml
translations/messages.it.yml
translations/messages.ja.yml
translations/messages.nb.yml
translations/messages.nl.yml
translations/messages.oc.yml
translations/messages.pl.yml
translations/messages.pt.yml
translations/messages.ro.yml
translations/messages.ru.yml
translations/messages.th.yml
translations/messages.tr.yml
translations/messages.uk.yml

Updated text iTunes to App Store.

---

.github/dependabot.yml

Until we release official support for Symfony 5+

Avoid deps for Symfony/*

---

CHANGELOG.md
app/config/wallabag.yml
composer.lock
phpstan-baseline.neon
src/Wallabag/CoreBundle/Controller/ConfigController.php
src/Wallabag/CoreBundle/Form/Type/UserInformationType.php
src/Wallabag/CoreBundle/Resources/views/Config/index.html.twig
tests/Wallabag/CoreBundle/Controller/ConfigControllerTest.php

Latest security release fix
https://github.com/wallabag/wallabag/milestone/84
- run linter to fix CS
- run phpstan to remove one occurence of an error
- cleanup the twig file to avoid error (and fix indentation)

Prepare 2.6.7 release

---

translations/CraueConfigBundle.pl.yml

Hi, I'm contributor in hacktoberfest event. When you approve these changes could you please add hacktoberfest-accepted label to this PR?
Thanks :)

Corrected PL translations

---

.github/workflows/continuous-integration.yml

Test against php 8.3

---

src/Wallabag/CoreBundle/Command/InstallCommand.php
src/Wallabag/CoreBundle/Event/Subscriber/SQLiteCascadeDeleteSubscriber.php
src/Wallabag/ImportBundle/Command/ImportCommand.php

Fix Doctrine deprecation notices

---

docker/php/Dockerfile

Fix docker setup

---

app/config/services.yml

Make database dependent commands lazy

---

CHANGELOG.md
app/config/wallabag.yml
composer.lock

Latest release of 2023 with some bug fix and site configs up to date (huge thanks to @HolgerAusB)

Prepare 2.6.8 release

---

CHANGELOG.md
app/config/wallabag.yml
composer.lock
src/Wallabag/CoreBundle/Controller/ConfigController.php
src/Wallabag/CoreBundle/Controller/EntryController.php
src/Wallabag/CoreBundle/Controller/TagController.php
src/Wallabag/CoreBundle/Helper/Redirect.php
src/Wallabag/CoreBundle/Resources/views/Entry/_card_actions.html.twig
src/Wallabag/CoreBundle/Resources/views/Entry/_card_list.html.twig
src/Wallabag/CoreBundle/Resources/views/Entry/_tags.html.twig
src/Wallabag/CoreBundle/Resources/views/Entry/entries.html.twig
src/Wallabag/CoreBundle/Resources/views/Entry/entry.html.twig
src/Wallabag/CoreBundle/Resources/views/Tag/tags.html.twig
tests/Wallabag/CoreBundle/Controller/EntryControllerTest.php
tests/Wallabag/CoreBundle/Controller/TagControllerTest.php
tests/Wallabag/CoreBundle/Helper/RedirectTest.php

As #7140 is the only remaining PR not forward ported to master, I'm trying a proper merge of 2.6 in master so that all fix commits become part of master starting from 2.6.8 :)
There were no complex conflicts to resolve, proof is that the diff is similar to the one of #7140

Merge 2.6 in master

---

app/config/config.yml
app/config/services.yml
src/Wallabag/CoreBundle/Helper/DownloadImages.php
tests/Wallabag/CoreBundle/Helper/DownloadImagesTest.php

first step toward removing Guzzle

Make DownloadImages use HttpClient

---

src/Wallabag/CoreBundle/Controller/EntryController.php

Fix same domain pagination

---

src/Wallabag/CoreBundle/Guzzle/AuthenticatorSubscriber.php

see the first commit that is empty has [failing tests](https://github.com/wallabag/wallabag/actions/runs/7951883836) on master..

Make retries an instance property in AuthenticatorSubscriber

---

app/config/config.yml
app/config/services.yml
src/Wallabag/CoreBundle/Import/PocketImport.php
tests/Wallabag/CoreBundle/Import/PocketImportTest.php

second step toward removing Guzzle

Make PocketImport use HttpClient

---

app/config/config.yml
app/config/services_test.yml
phpstan.neon
phpunit.xml.dist
src/Controller/Api/EntryRestController.php
tests/Command/ReloadEntryCommandTest.php
tests/Controller/Api/DeveloperControllerTest.php
tests/Controller/Api/WallabagApiTestCase.php
tests/Controller/ConfigControllerTest.php
tests/Controller/ExportControllerTest.php
tests/WallabagTestCase.php
tests/bootstrap.php

From [4m04s](https://github.com/wallabag/wallabag/actions/runs/8018668664) on latest master CI run to now [2m51s](https://github.com/wallabag/wallabag/actions/runs/8027285194): ~ -1m10s

Run tests in no debug mode

---

src/Wallabag/ImportBundle/Resources/views/Elcurator/index.html.twig
translations/messages.en.yml
translations/messages.fr.yml

See https://matrix.to/#/!HkmhZSUCplHZKWIAbG:gitter.im/$vT1P0qpPmZUsL9Zb0bVhq0ngF-9SaQM7UBoB2E4fWfE?via=gitter.im&via=matrix.org&via=tchncs.de

Use a proper "how to" for elCurator

---

app/config/security.yml
src/Controller/UserController.php
src/Security/Voter/AdminVoter.php
src/Security/Voter/UserVoter.php
templates/User/edit.html.twig
templates/User/index.html.twig
templates/layout.html.twig
tests/Security/Voter/AdminVoterTest.php
tests/Security/Voter/UserVoterTest.php

extracted from #7242, added tests and updated on latest master

Use IsGranted in UserController

---

app/config/security.yml
src/Controller/IgnoreOriginInstanceRuleController.php
src/Security/Voter/AdminVoter.php
src/Security/Voter/IgnoreOriginInstanceRuleVoter.php
templates/IgnoreOriginInstanceRule/edit.html.twig
templates/IgnoreOriginInstanceRule/index.html.twig
templates/layout.html.twig
tests/Security/Voter/AdminVoterTest.php
tests/Security/Voter/IgnoreOriginInstanceRuleVoterTest.php

Use IsGranted in IgnoreOriginInstanceRuleController

---

CHANGELOG.md
app/config/wallabag.yml
composer.lock

Prepare 2.6.9

---

app/config/services.yml
migrations/Version20161024212538.php
migrations/Version20161214094402.php
migrations/Version20170606155640.php
migrations/Version20240310150000.php
src/Doctrine/WallabagMigration.php
src/Entity/Api/AccessToken.php
src/Entity/Api/AuthCode.php
src/Entity/Api/RefreshToken.php
src/Entity/Config.php
src/Entity/Entry.php
src/Entity/IgnoreOriginUserRule.php
src/Entity/InternalSetting.php
src/Entity/SiteCredential.php
src/Entity/Tag.php
src/Event/Subscriber/SchemaAdapterSubscriber.php
tests/bootstrap.php

Through the different migrations, the database schema became not in sync with the Doctrine metadata, in the 3 supported DBMS (MySQL, PostgreSQL and SQLite).
Goal of this PR is to fix that by providing a (big) migration fixing the database schema and some changes to Doctrine metadata.
Also, to avoid the issue in the future, the command `doctrine:schema:validate` will now be run when running tests and on the CI.
This PR also adds some helper functions for foreign key names and indexes names, as their name depend on the table name, and it can be impacted by the table prefix.
Finally, I decided to rely only on Doctrine generated names instead of custom ones for consistency.
Note about the first commit: it makes some migrations NOOP instead of skipping them so they are actually executed by …

Fix schema validation

---

src/Controller/SiteCredentialController.php
src/Security/Voter/MainVoter.php
src/Security/Voter/SiteCredentialVoter.php
templates/SiteCredential/edit.html.twig
templates/SiteCredential/index.html.twig
templates/layout.html.twig
tests/Security/Voter/MainVoterTest.php
tests/Security/Voter/SiteCredentialVoterTest.php

Use IsGranted in SiteCredentialController

---

.github/dependabot.yml

And bother @yguedidi instead ✨

Don't bother @tcitworld anymore

---

app/config/routing.yml

| BC breaks?    |  no
| Tests pass?   | yes?
Fixes #7462
Apologies @j0k3r I had accidentally commented this part of the template out

Enable Swagger JSON output in routing.yml

---

composer.json
composer.lock
phpunit.xml.dist
src/Mailer/UserMailer.php

- lock `shipmonk/composer-dependency-analyser` because I don't know how to workaround the error
- update parameter PHPDoc for `UserMailer` following `TwigSwiftMailer` update
- migrate PHPUnit config using `--migrate-configuration`

Update all deps

---

composer.json
composer.lock
tests/Wallabag/CoreBundle/Controller/EntryControllerTest.php
tests/Wallabag/ImportBundle/Controller/FirefoxControllerTest.php
tests/Wallabag/ImportBundle/fixtures/firefox-bookmarks.json

Just update site config to latest.
The downgrade of `lcobucci/jwt` is related to https://github.com/wallabag/wallabag/issues/7531

Update site config & tests

---

composer.lock

Update site config

---

CHANGELOG.md
app/config/wallabag.yml

Prepare 2.6.10

---

composer-dependency-analyser.php
composer.json
composer.lock

So it'll get updated regularly by dependabot.

Add `graby-site-config` as direct deps

---

.github/ISSUE_TEMPLATE/config.yml
README.md
src/Wallabag/CoreBundle/Resources/views/Static/quickstart.html.twig
translations/messages.cs.yml
translations/messages.de.yml
translations/messages.el.yml
translations/messages.en.yml
translations/messages.es.yml
translations/messages.fa.yml
translations/messages.fr.yml
translations/messages.gl.yml
translations/messages.hr.yml
translations/messages.hu.yml
translations/messages.it.yml
translations/messages.ja.yml
translations/messages.ko.yml
translations/messages.nb.yml
translations/messages.nl.yml
translations/messages.oc.yml
translations/messages.pl.yml
translations/messages.pt.yml
translations/messages.ru.yml
translations/messages.th.yml
translations/messages.tr.yml
translations/messages.uk.yml
translations/messages.zh.yml

Replaced gitter with matrix

---

app/config/wallabag.yml
composer.json
composer.lock
migrations/Version20241112193044.php
src/Controller/ExportController.php
src/Helper/EntriesExport.php
templates/Entry/entries.html.twig
templates/Entry/entry.html.twig
tests/Controller/ExportControllerTest.php

Add Markdown export

---

templates/Import/index.html.twig
tests/Controller/Import/ImportControllerTest.php

Fix https://github.com/wallabag/wallabag/issues/7761

Improved import page

---

composer.lock

Update Symfony components after 5.4.47 release

---

.github/CONTRIBUTING.md
GNUmakefile

Improve a bit the developer experience when using Docker compose locally

Better Makefile

---

.github/workflows/continuous-integration.yml

Add php 8.4 for our CI

---

src/ExpressionLanguage/AuthenticatorProvider.php
src/Import/HtmlImport.php
src/Import/PocketHtmlImport.php
src/SiteConfig/Authenticator/LoginFormAuthenticator.php

Use DomCrawler component

---

src/Wallabag/CoreBundle/Resources/views/Entry/_card_actions.html.twig
src/Wallabag/CoreBundle/Resources/views/Entry/_card_list.html.twig
src/Wallabag/CoreBundle/Resources/views/Entry/entries.html.twig
tests/Wallabag/CoreBundle/Controller/EntryControllerTest.php

Fix https://github.com/wallabag/wallabag/issues/7821

Fix redirection after action in search results

---

src/Wallabag/CoreBundle/Resources/views/Entry/_title.html.twig

Fix title tag filter

---

app/config/config.yml
app/config/services.yml
app/config/services_test.yml
fixtures/IgnoreOriginInstanceRuleFixtures.php
fixtures/InternalSettingFixtures.php
fixtures/SiteCredentialFixtures.php
migrations/Version20160410190541.php
migrations/Version20160812120952.php
migrations/Version20160911214952.php
migrations/Version20161031132655.php
migrations/Version20161117071626.php
migrations/Version20161122144743.php
migrations/Version20170327194233.php
migrations/Version20170420134133.php
migrations/Version20170602075214.php
migrations/Version20170606155640.php
migrations/Version20171120163128.php
migrations/Version20171125164500.php
migrations/Version20190129120000.php
migrations/Version20190826204730.php
migrations/Version20230728093912.php
migrations/Version20240310150000.php
migrations/Version20240521152037.php
src/Doctrine/MigrationFactoryDecorator.php
src/Doctrine/WallabagMigration.php

ContainerAwareInterface is deprecated

Stop using ContainerAwareInterface

---

composer.lock

Update composer.lock with latest composer version

---

.github/workflows/coding-standards.yml

Validate the sync between the composer.json and the composer.lock

Add composer validate to CI

---

src/Wallabag/AnnotationBundle/Repository/AnnotationRepository.php
src/Wallabag/CoreBundle/Repository/EntryRepository.php
src/Wallabag/CoreBundle/Twig/WallabagExtension.php
tests/Wallabag/CoreBundle/Twig/WallabagExtensionTest.php

The query were badly made and return all annotations for the current user instead of the total of entries with annotation(s).
Fix https://github.com/wallabag/wallabag/issues/7987

Fix entries counter for annotated entries in the menu

---

app/AppKernel.php
app/config/config.yml
package.json
yarn.lock

This removes so many JS dependencies

Remove Webpack dev server

---

app/AppKernel.php
app/config/parameters.yml.dist
app/config/services.yml
docker/php/config/parameters.yml
docker/php/env.example

To later have a single environment variable to configure Redis

Introduce a REDIS_URL

---

app/AppKernel.php
app/config/config.yml

To later have a single environment variable to configure RabbitMQ

Introduce a RABBITMQ_URL

---

assets/scss/_dark_theme.scss

Fix focus card in dark mode

---

assets/index.js
templates/Import/check_queue.html.twig
templates/bundles/FOSUserBundle/Security/login.html.twig
templates/layout.html.twig

Fix toast since Materialize upgrade

---

assets/index.js
assets/js/tools.js

Looks better to me without animations.
Also, this a preparation to remove jQuery own usages that I have almost ready locally :)

Remove jQuery animations

---

assets/index.js

Fixes the Floating Action Button

Fix Floating Action Button

---

app/config/security.yml
phpstan-baseline.neon
src/Controller/AnnotationController.php
src/Security/Voter/AnnotationVoter.php
src/Security/Voter/EntryVoter.php
tests/Controller/AnnotationControllerTest.php
tests/Security/Voter/AnnotationVoterTest.php
tests/Security/Voter/EntryVoterTest.php

Add IsGranted to AnnotationController

---

src/Controller/ExportController.php
src/Security/Voter/EntryVoter.php
src/Security/Voter/MainVoter.php
templates/Entry/entries.html.twig
templates/Entry/entry.html.twig
tests/Security/Voter/EntryVoterTest.php
tests/Security/Voter/MainVoterTest.php

Add IsGranted to ExportController

---

src/Controller/Api/AnnotationRestController.php

Add IsGranted to AnnotationRestController

---

src/Controller/Api/SearchRestController.php

Add IsGranted to SearchRestController

---

templates/Config/index.html.twig

Fix display thumbnails checkbox

---

app/config/security.yml
src/Controller/FeedController.php

Add IsGranted to FeedController

---

phpstan-baseline.neon
src/Controller/ConfigController.php
src/Security/Voter/IgnoreOriginUserRuleVoter.php
src/Security/Voter/MainVoter.php
src/Security/Voter/TaggingRuleVoter.php
templates/Config/index.html.twig
templates/Static/quickstart.html.twig
templates/layout.html.twig
tests/Security/Voter/IgnoreOriginUserRuleVoterTest.php
tests/Security/Voter/MainVoterTest.php
tests/Security/Voter/TaggingRuleVoterTest.php

For this one I initially wanted to split it in multiple controller to provide more detailed security attributes, but being a single page with multiple forms, it was a pain to do, so I went for the simple way, for now, with a general EDIT_CONFIG attribute.

Add IsGranted to ConfigController

---

src/Controller/StaticController.php

Add IsGranted to StaticController

---

src/Controller/TagController.php
src/Repository/TagRepository.php
src/Security/Voter/EntryVoter.php
src/Security/Voter/MainVoter.php
src/Security/Voter/TagVoter.php
templates/Entry/_tags.html.twig
templates/Entry/entries.html.twig
templates/Entry/entry.html.twig
templates/Tag/tags.html.twig
templates/layout.html.twig
tests/Security/Voter/EntryVoterTest.php
tests/Security/Voter/MainVoterTest.php
tests/Security/Voter/TagVoterTest.php

Add IsGranted to TagController

---

assets/index.js
assets/js/tools.js
assets/scss/_nav.scss
templates/Entry/entries.html.twig
templates/layout.html.twig

Better reviewed commit by commit

Back-end hide/show of random, export and filters

---

src/Repository/AnnotationRepository.php
src/Repository/EntryRepository.php
src/Twig/WallabagExtension.php
templates/Entry/_card_actions.html.twig
templates/Entry/_card_list.html.twig
templates/Entry/_title.html.twig
templates/Entry/entries.html.twig
tests/Controller/EntryControllerTest.php
tests/Twig/WallabagExtensionTest.php

Update from 2.6

---

app/config/config.yml
src/Entity/Annotation.php
src/Entity/Api/AccessToken.php
src/Entity/Api/AuthCode.php
src/Entity/Api/Client.php
src/Entity/Api/RefreshToken.php
src/Entity/Config.php
src/Entity/Entry.php
src/Entity/IgnoreOriginInstanceRule.php
src/Entity/IgnoreOriginUserRule.php
src/Entity/InternalSetting.php
src/Entity/SiteCredential.php
src/Entity/Tag.php
src/Entity/TaggingRule.php
src/Entity/User.php
src/Helper/EntityTimestampsTrait.php

Prepare the Doctrine ORM upgrade to 3.x
Used Rector locally

Migrate to Doctrine attributes

---

GNUmakefile
phpstan-baseline.neon
phpstan.neon
src/Controller/Api/EntryRestController.php
src/Controller/FeedController.php
src/Controller/Import/PocketController.php
src/Entity/Entry.php
src/Entity/Tag.php
src/Entity/User.php
src/Event/Subscriber/DownloadImagesSubscriber.php
src/Form/DataTransformer/StringToListTransformer.php
src/Helper/ContentProxy.php
src/Helper/DownloadImages.php
src/Helper/Redirect.php
src/Helper/RuleBasedTagger.php
src/Import/PinboardImport.php
src/Mailer/AuthCodeMailer.php
src/Tools/Utils.php
tests/Controller/Api/WallabagRestControllerTest.php
tests/Controller/ExportControllerTest.php
tests/Controller/SecurityControllerTest.php
tests/Helper/ContentProxyTest.php
tests/Tools/UtilsTest.php

PHPStan level 4

---

CHANGELOG.md
app/config/wallabag.yml

| CHANGELOG.md  | yes
fix #8034

Prepare 2.6.12 release

---

phpstan.neon
src/Command/Import/ImportCommand.php
src/Controller/Api/EntryRestController.php
src/Controller/Api/SearchRestController.php
src/Controller/ConfigController.php
src/Controller/EntryController.php
src/Controller/ExportController.php
src/Entity/Config.php
src/Entity/Entry.php
src/Event/Listener/CreateConfigListener.php
src/Helper/DownloadImages.php
src/Helper/EntriesExport.php
src/Repository/ConfigRepository.php
src/Repository/EntryRepository.php
src/Repository/SiteCredentialRepository.php
tests/Controller/Api/DeveloperControllerTest.php
tests/Controller/Api/UserRestControllerTest.php
tests/Controller/Api/WallabagApiTestCase.php
tests/Controller/Api/WallabagRestControllerTest.php
tests/Controller/EntryControllerTest.php
tests/Controller/FeedControllerTest.php
tests/Mailer/AuthCodeMailerTest.php

Easy one before the harder level 6 that will require adding proper types everywhere :)

PHPStan level 5

---

templates/Entry/share.html.twig

Show display name on shared entries instead of username

---

CHANGELOG.md
app/config/wallabag.yml
composer.json
composer.lock

Prepare 2.6.13 release

---

CHANGELOG.md
app/config/config.yml
app/config/services.yml
app/config/services_rabbit.yml
app/config/services_redis.yml
composer-dependency-analyser.php
composer.json
composer.lock
src/Command/Import/ImportCommand.php
src/Consumer/RabbitMQConsumerTotalProxy.php
src/Controller/Import/ImportController.php
src/Controller/Import/PocketCsvController.php
src/Import/PocketCsvImport.php
templates/Import/PocketCsv/index.html.twig
tests/Controller/Import/ImportControllerTest.php
tests/Controller/Import/PocketCsvControllerTest.php
tests/Import/PocketCsvImportTest.php
tests/fixtures/Import/pocket.csv
tests/fixtures/Import/ril_export.html
tests/fixtures/Import/shaarli-bookmarks.html
translations/messages.en.yml
translations/messages.fr.yml

merge-2.6-in-master

---

templates/Static/about.html.twig
templates/Static/quickstart.html.twig

Fix about and quickstart pages

---

docker/php/Dockerfile

Fix docker base image

---

composer.lock

So that siteconfig are up to date.

Bump deps (mostly for siteconfig)
